### ISSUE TITLE
WezTerm crashes when close RDP and login to RDP again

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#267] opened 2020-09-12 19:57 UTC
Windows 10.

Repro steps:
1. Login to RDP (remote desktop)
2. Open WezTerm
3. close RDP
4. Login to RDP
5. focus wezterm. See the crash.

![image](https://user-images.githubusercontent.com/287744/93003900-50ec8a00-f4f7-11ea-9427-2bfacd192913.png)

Let me know if there is a particular way to get logs.

**Comment by wez** [comment] 2020-09-13 05:13
Sounds like a duplicate of https://github.com/wez/wezterm/issues/265 which has a lot of debug info in there.
I'm going to close this issue on favor of that one

**Closed by wez** 2020-09-13 05:13 UTC
Labels: bug, duplicate
