### ISSUE TITLE
Screwed up display when using a font line

### ISSUE THREAD

**Issue by jankatins** [wez/wezterm#314] opened 2020-10-30 10:11 UTC
## Describe the bug

I had a font line in my config: `font = wezterm.font_with_fallback({"JetBrains Mono Semi Light", "Noto Color Emoji"}),` and when I put that in wezterm looks like it has a big line height but still "normal" fonts.  It worked before and it still works on my linux machine. On Mac it's now crashing with both the nightly and the released release (installed via brew).

## Environment (please complete the following information):

 - OS: Mac
 - Version: wezterm 20200909-002054-4c9af461

## To Reproduce

Add the line and it's screwed, sometimes even crashes. Removing that line and it's fine.

## Configuration

```
-- https://wezfurlong.org/wezterm/config/
local wezterm = require 'wezterm';

return {
-- THIS LINE
  font = wezterm.font_with_fallback({"JetBrains Mono Semi Light", "Noto Color Emoji"}),
  font_size = 11.0,
  dpi = 96.0,
  font_antialias = "Subpixel", -- None, Greyscale, Subpixel
  font_antialias = "Greyscale", -- None, Greyscale, Subpixel
  font_hinting = "Full",  -- None, Vertical, VerticalSubpixel, Full

  -- this disables ligatures
  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},


  -- Use a adjusted tango theme -> in colors subfolder
  color_scheme = "TangoDarkAdjusted",
  --color_scheme = "Builtin Tango Dark",

  -- don't ask the macOS IME/text services to compose input
  use_ime = false,

  keys = {
  	-- from https://github.com/wez/wezterm/issues/253
    -- Make Option-Left equivalent to Alt-b which many line editors interpret as backward-word
    {key="LeftArrow", mods="OPT", action=wezterm.action{SendString="\x1bb"}},
    -- Make Option-Right equivalent to Alt-f; forward-word
    {key="RightArrow", mods="OPT", action=wezterm.action{SendString="\x1bf"}},
  },
}
```

## Expected behavior

Good display :-)

## Screenshots

![image](https://user-images.githubusercontent.com/890156/97692414-08396200-1aa0-11eb-8993-b18995b0aa70.png)

**Comment by wez** [comment] 2020-10-30 15:44
I can reproduce it with the current release (the version in your report).
I can't reproduce this with the nightly builds; this sounds exactly like #263 for which fixes have landed in master.
Are you sure that you're seeing this with the nightlies on your mac?

I use:

```
brew rm wezterm
brew install --HEAD wezterm
```

to ensure that I pick up nightly builds on my mac.

**Comment by jankatins** [comment] 2020-10-30 21:23
Your above commands worked. I was pretty sure that I had the latest HEAD installed, but seems I didn't have it. Sorry for the noise and thanks for the fast help!

**Closed** 2020-10-30 21:23 UTC
Labels: bug
