### ISSUE TITLE
Vim: part of the screen is not refreshed on certain actions, or is laggy compared to other terminal emulators

### ISSUE THREAD

**Issue by reportaman** [wez/wezterm#559] opened 2021-03-20 00:15 UTC
## Describe the bug

At times part of vim screen is not redrawn, for instance when resizing WezTerm window with mouse (I have only tried holding and dragging from SE corner). Doesn't happen all the time, but still concerning.

And perhaps related: In a long file, pressing and holding ``<PageDown>`` key results in intermittent lag. In a 1500+ line file I often see 1-2 times the screen Vim window will momentarily appear blank & then populate again to continue to end of file. This doesn't happen with other GPU based terminal emulators like Alacritty.

> Sidenote: Also while using a theme with background (which I have since stopped using), I had seen that at times while scrolling (pressing holding``<Up>``/``<Down>`` key) would show screen area to the right of line with no background color (it showed terminal's background color). This is a sidenote because I have not tested this again on latest version unlike above two points.

## Environment (please complete the following information):

 - OS: macOS BigSur 11.2.3
 - Version: wezterm 20210314-114017-04b7cedd-14-g7def5f07
 - The active keyboard layout name: Unicode Hex Input
 
<img width="670" alt="Screen Shot 2021-03-19 at 5 09 04 PM" src="https://user-images.githubusercontent.com/71736629/111852863-e701d280-88d5-11eb-8883-59290860359c.png">

## Configuration

Complete ``wezterm.lua``:
```
local wezterm = require 'wezterm';

-- A helper function for my fallback fonts
function font_with_fallback(name, params)
    local names = {name, "Noto Color Emoji"}
    return wezterm.font_with_fallback(names, params)
end

return {
    --font = wezterm.font("JetBrainsMonoNerdR"),
    font = font_with_fallback("OperatorMonoNerdR"),
    font_size = 21.0,
    font_rules = {
        {
            italic = true,
            font = wezterm.font("OperatorMonoNerdI"),
        },
        {
            italic = true,
            intensity = "Bold",
            font = wezterm.font("OperatorMonoNerdMI"),
        },
        {
            intensity = "Bold",
            font = wezterm.font("OperatorMonoNerdM"),
        },
    },
    term = "wezterm", -- with xterm-256color opening my 1500 line vimrc file has a noticeable lag compared to terminfo wezterm
    color_scheme = "Pandora",
    window_background_opacity = 0.85,
}
```

## Expected behavior
Be smooth in scroll, and accurate in screen drawing.

**Comment by wez** [comment] 2021-03-20 00:37
your comment in your config about `term`; is that accurate, or did you see it regardless of the term setting?

**Comment by reportaman** [comment] 2021-03-20 01:09
@wez That’s a good question. When I encountered the noticeable delay I mention in the comment of my config file, I switched over to “wezterm”. After that I didn’t notice that delay, though I did notice the same intermittent lag pressing and holding PageDown. I don’t remember if I saw part of vim screen not being drawn before or after moving to “wezterm”, it happened today is what I remember (on latest commit). Lastly for the sidenote about background, I had seen that more than a month ago & had moved over to Alacritty for that period, but got back to WezTerm for the missing tab feature... Given the time between, I don’t know whether it was “xterm-256color” or “wezterm” then.

**Comment by wez** [comment] 2021-03-20 02:06
I believe that you're experiencing this; I've got several people reporting latency, but I'm having a hard time reproducing the effect that you (or the others) described on the systems that I use (which are all reasonably strong systems).

Over in https://github.com/wez/wezterm/issues/506 which sounds potentially similar, we found that there was a font resolving problem.  Could you run `wezterm` from a terminal and see if any errors are logged when you trigger the laggy behavior?
Running as `WEZTERM_LOG=trace wezterm >/tmp/wezterm.txt` may also show some useful additional information.

**Comment by reportaman** [comment] 2021-03-20 08:58
@wez Dear Mr. Wez, I think I found something that could be it! WezTerm memory grows to **``4.7 GigaBytes``** while scrolling my humble 1500 line vimrc file with ``<PageDown>`` held down. Repeating the same thing that just keeps the memory of other similar GPU-accelerated terminals under **``290 MegaBytes``** (Alacritty), **``245 MegaBytes``** (iTerm2),  **``296 MegaBytes``** (Kitty).

<img width="961" alt="Screen Shot 2021-03-20 at 12 53 41 AM" src="https://user-images.githubusercontent.com/71736629/111863427-c018c000-8918-11eb-8c1a-eb37b88bd04b.png">

Here's the sequence of events & observed memory behavior at each step:

1. Open WezTerm. (within few seconds memory grows to and stays around 320MB). This is at par with memory footprint of other terminals listed above
2. Open Vim. (memory jumps by 50 something MB)
3. Open ``~/.vimrc``. (memory jumps to 1.45GB -- doesn't happen in other terminals, could explain why I see noticeable lag at times while opening file).
4. Press and hold ``<PageDown>`` to go to end of file, and ``<PageUp>`` to come all the way up. (At the points where I see the lag that I mentioned above, at exactly those points memory bumps up by another GB or so each time -- finally stabilizing at either 4.5+ or 3.8GB (latter happens more often). None of this effect happens with any other terminals mentioned above either.)

Root-causing & fixing this might resolve all the issues... The log created is 335MB, not sure how to share :D

**Comment by wez** [comment] 2021-03-20 18:34
Interesting.  regarding the big log, if you filter it using `grep wezterm_font` is it more managable?  Also, `grep ERROR` in that log and attach it here too!

**Comment by wez** [comment] 2021-03-20 18:37
FWIW, I have an entry-level M1 macbook air which feels smooth as butter in each test I've tried.  I suspect that you might have something fancier in your fonts and vim configuration and file contents that triggers this situation for you.

If you run through the [Session Recording](https://github.com/wez/wezterm/blob/main/.github/ISSUE_TEMPLATE/bug_report.md#session-recording) portion of the bug reporting template, that will capture exactly the output from your repro scenario and make it a bit easier for me to replay that output and trigger it locally, without having to replicate your vim setup.

**Comment by reportaman** [comment] 2021-03-21 02:43
@wez Yes, I have attached the result of ``:vim /ERROR\|Error\|wezterm_font/ %`` its only 243 lines: [wt_grep.txt](https://github.com/wez/wezterm/files/6176741/wt_grep.txt)

**Comment by reportaman** [comment] 2021-03-21 02:46
Also, let me check the session recording that you talk about. Btw, the same problem happens with JetBrainsMonoNerd font too. I replaced all the Operator Mono font with those. Also, given the problem occurs even with ``--noplugin``, and it does not happen with same font+vim setup+steps on other terminals, I don't think there is anything extra fancy.

**Comment by reportaman** [comment] 2021-03-21 03:08
@wez It seems like there is some problem in your script. The tar is empty, these are the lines printed in the parent terminal:

```
20210321030247
 2021-03-21T03:02:47.735Z INFO  wezterm_mux_server_impl::local > setting up /Users/reportaman/.local/share/wezterm/gui-sock-2181
 2021-03-21T03:02:47.881Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Apple M1 4.1 Metal - 71.0.7 is_context_loss_possible=false wezterm version: 20210314-114017-04b7cedd-16-ge5ae1d47
 2021-03-21T03:02:57.044Z ERROR mux::localpane                 > unknown DeviceControlMode::Enter EnterDeviceControlMode(params: [], intermediates: [], byte: 'z' 0x7a, ignored_extra_intermediates=false)
 2021-03-21T03:02:57.044Z ERROR mux::localpane                 > unhandled DeviceControlMode::Data 7a z
 2021-03-21T03:02:57.044Z WARN  wezterm_term::terminalstate    > unknown unspecified CSI: "%0m"
tar: 20210321030247.typescript: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
Transcript recorded in 20210321030247.tgz
```

**Comment by wez** [comment] 2021-03-21 03:15
Ah, it's because the current directory changes inside the terminal; I just pushed a simple fix in 1e6754b6

**Comment by reportaman** [comment] 2021-03-21 03:55
@wez I have sent you an attachment for another file that is available in public domain: [enwiki8](http://cs.fit.edu/~mmahoney/compression/enwik8.zip). In this case the memory bumps up to 2.7GB each time unlike for my ``.vimrc`` for which it does to 3.8GB. Hopefully this could be sufficient, or I'll have to clean my vimrc from non-public domain information.

**Comment by wez** [comment] 2021-03-21 06:21
Looks like all of that memory utilization was from loading all the fallback fonts into memory!  I've made some changes to avoid that; peak memory utilization for me when replaying your session recording is ~70MB.

**Comment by reportaman** [comment] 2021-03-22 06:49
@wez The memory issue is gone, though the stutter remains. Its subtle, so bare with me (I used to work as commercial GUI developer)... I have GIF's comparing same actions in iTerm2 & WezTerm. I also think I have a solution proposal & perhaps you might already have it as an option (idk), but first let's see the GIFs:

1. Opening first file in Vim: In this example, look at one GIF at a time & keep your eyes sort of focussed near the lower left quadrant. As you will see the screen redraw in WezTerm is slow & partial redraw is visible. Whereas in iTerm2, I never see partial screen redraws while opening files.

WezTerm
![wezterm_firstfile_50fps](https://user-images.githubusercontent.com/71736629/111949234-93da7c00-8a9d-11eb-8af2-1059251b6792.gif)

iTerm2
![iterm2_firstfile](https://user-images.githubusercontent.com/71736629/111949259-9b9a2080-8a9d-11eb-9be9-57d1bc3d8233.gif)

2. Scrolling past a line that has special symbols that were never encountered before in scroll: In this example too, look at one GIF at a time & this time keep your eyes on the current line number to see if it has a stutter/slowdown at some point. As you will notice, for there is a slight stutter when line 729 is about to be loaded. This GIF is 20fps (due to 10MB size restriction of GitHub), so the effect is not that clearly visible... 

WezTerm
![wezterm_scroll](https://user-images.githubusercontent.com/71736629/111949723-7659e200-8a9e-11eb-8f04-7d0ca1bb7e23.gif)

iTerm2
![iterm2_scroll](https://user-images.githubusercontent.com/71736629/111949736-7a85ff80-8a9e-11eb-824e-f572e6fd4cd2.gif)

**_Proposal:_** Give users an option to manually specify mapping of unicode code points to font file, and disable WezTerm's on-the-fly font search. Kitty terminal provides such an option. I think it will resolve both issues. I repeated the experiment 1) with airline/powerline disabled & the partial screen draw/ screen draw lag goes away. Check the GIF below:

WezTerm after disabling powerline:
![wezterm_fileopen_nopowerline](https://user-images.githubusercontent.com/71736629/111950771-f896d600-8a9f-11eb-8956-3d750e91b4c1.gif)

**Comment by wez** [comment] 2021-03-22 07:24
I think what you're seeing now sounds like https://github.com/wez/wezterm/issues/508 wherein the issue is that the glyph lookup is blocking the render thread.

Regarding symbol_map: if you add the font containing the symbols to the fallback list in your wezterm config, you can avoid the slower full system fallback lookup.  This comment has an example: https://github.com/wez/wezterm/issues/506#issuecomment-799508014

**Comment by reportaman** [comment] 2021-03-22 07:29
@wez Thanks, I am already using that (as you can see in the GIFs). The problem with this approach is that one doesn't know if & when full system fallback lookup kickstarts. Two possibilities are: add a config option to always load a information window when that happens (so I as a user know what glyphs kickstarted this and can edit the fallback list to avoid system lookup again), or add the symbol_map & show tofu...

**Comment by reportaman** [comment] 2021-03-22 08:26
Also, you might consider reverting this https://github.com/wez/wezterm/commit/9e6abce96338febdf726d37e7ff1fe3c04df43a6 as the theorized case there is not the cause here, and perhaps sounds like 1ms extra delay? (why slow things if it is not broken)

**Comment by reportaman** [comment] 2021-03-30 03:50
@wez Good news! I haven't encountered the font-related slowness effects discussed here. Though each time I do see the memory go up to 350-400MB. IMO that could still be because of fallback fonts. It will be nice to see a report which unicode glyphs are causing fallback fonts to be loaded, so user can actively maintain their ``wezterm.lua`` to keep memory down to ~80MB like in your case.

**Closed** 2021-04-03 17:47 UTC
Labels: bug, fixed-in-nightly

**Comment by reportaman** [comment] 2021-04-11 07:02
@wez I still see memory usage above 400MB with Vim. Is there a way to figure out what all fonts are being used for what all glyphs so I can avoid kickstarting loading fallback fonts, and maintain ``wezterm.lua``?

**Comment by wez** [comment] 2021-04-11 21:44
With the commit I just pushed, you can do:

```
; WEZTERM_LOG=wezterm_font=trace wezterm -n 2> /tmp/font.txt
; grep 'fallback font' /tmp/font.txt
2021-04-11T21:41:09.653Z TRACE wezterm_font > Looking for \u{d604}\u{c7ac}\u{be0c}\u{b79c}\u{ce58} in fallback fonts
2021-04-11T21:41:12.132Z TRACE wezterm_font > Looking for \u{f4e9} in fallback fonts
```

**Comment by reportaman** [comment] 2021-04-12 06:20
@wez Thanks! I added the fonts to fallback list, and now the grep returns no hits... but the memory size is still 375+MB

Here's the list of open files and ports, I wonder if/what is the way to go about this kind of debug...

```
cwd
/
txt
/Applications/WezTerm.app/Contents/MacOS/wezterm-gui
txt
/Library/Preferences/Logging/.plist-cache.KMtZrIBn
txt
/usr/lib/dyld
txt
/usr/share/icu/icudt66l.dat
txt
/private/var/db/timezone/tz/2021a.1.0/icutz/icutz44l.dat
txt
/private/var/db/analyticsd/events.whitelist
txt
/private/var/folders/40/g1hxt47j5sn3wg34689bfpnr0000gn/0/com.apple.LaunchServices.dv/com.apple.LaunchServices-2543-v2.csstore
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAqua.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantDark.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantDark.car
txt
/Users/reportaman/Library/Fonts/Operator Mono Book Nerd Font Complete diff.otf
txt
/usr/lib/libobjc-trampolines.dylib
txt
/System/Library/Fonts/SFNS.ttf
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Aqua.car
txt
/System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/MacOS/AppleMetalOpenGLRenderer
txt
/System/Library/Extensions/AGXMetal13_3.bundle/Contents/MacOS/AGXMetal13_3
txt
/private/var/folders/40/g1hxt47j5sn3wg34689bfpnr0000gn/C/com.github.wez.wezterm/com.apple.metal/16777235_322/functions.data
txt
/Users/reportaman/Library/Fonts/Operator Mono Medium Nerd Font Complete diff.otf
txt
/Users/reportaman/Library/Fonts/Operator Mono Book Italic Nerd Font Complete diff.otf
txt
/System/Library/Fonts/Helvetica.ttc
txt
/Library/Application Support/CrashReporter/SubmitDiagInfo.domains
txt
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantLightGraphite.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLightGraphiteAX.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLight.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Graphite.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantLight.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLightGraphite.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/AquaAX.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/GraphiteAX.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLightAX.car
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkGraphite.car
txt
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
txt
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
txt
/System/Library/Fonts/Supplemental/Arial Unicode.ttf
0
/dev/null
1
/dev/null
2
/dev/null
3
/Users/reportaman/.local/share/wezterm/gui-sock-1367
4
count=0, state=0xa
5
->0x4fbd3aa079672105
6
->0x4fbd3aa0796721cd
7
/dev/ptmx
8
->0x4fbd3aa070d501c5
9
/dev/ptmx
10
/dev/ptmx
11
/private/var/folders/40/g1hxt47j5sn3wg34689bfpnr0000gn/C/com.github.wez.wezterm/com.apple.metal/16777235_322/functions.list
12
/private/var/folders/40/g1hxt47j5sn3wg34689bfpnr0000gn/C/com.github.wez.wezterm/com.apple.metal/16777235_322/functions.data
13
/System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/Resources/default.metallib
14
/Library/Application Support/CrashReporter/SubmitDiagInfo.domains
15
/Users/reportaman/Library/Saved Application State/com.github.wez.wezterm.savedState/window_2.data
16
/Users/reportaman/Library/Saved Application State/com.github.wez.wezterm.savedState/data.data
17
/Users/reportaman/Library/Saved Application State/com.github.wez.wezterm.savedState/windows.plist
18
19
->0x4fbd3aa07966e0f5
```
