### ISSUE TITLE
Error running Wezterm flatpak 

### ISSUE THREAD

**Issue by RomanAverin** [wez/wezterm#3826] opened 2023-06-05 16:34 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Fedora 38, Gnome 44.1, Mutter 44.1, Nvidia prop driver 530

### WezTerm version

20230408-112425

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After starting the window is not displayed, there is an error in the logs

### To Reproduce

Run flatpak version

### Configuration

no config

### Logs

```
июн 05 19:28:16 fedora-pc-local org.wezfurlong.wezterm.desktop[91525]: [destroyed object]: error 7: failed to import supplied dmabufs: Unsupported buffer format 875713345
июн 05 19:28:16 fedora-pc-local org.wezfurlong.wezterm.desktop[91525]: 19:28:16.638  ERROR  wezterm_gui > running message loop: error during event_q.read_events protocol_error=Some(ProtocolError { code: 7, object_id: 0, object_interface: "<unknown>", message: "" }): Protocol error (os error 71); terminating

```

**Comment by wez** [comment] 2023-06-05 20:26
Likely a duplicate of https://github.com/wez/wezterm/issues/3244

**Closed** 2023-06-06 16:46 UTC
Labels: bug
