### ISSUE TITLE
Show tab name momentarily during switching ... ala Windows & Linux Wokspaces

### ISSUE THREAD

**Issue by thisismygitrepo** [wez/wezterm#4859] opened 2024-01-26 00:30 UTC
In Windows & Linux workspaces, there is no permanent writing on the screen to indicate that this is `workspace 2`, however, that writing shows up momentarily while switching workspaces.

In `wezterm`, I hide all bars that permanently takes up space, however, when I switch tabs, I have zero clue from wezterm which tab I'm switching from or to. Can we please have an ephemeral text showing that, or something like Windows Terminal solution where you get a temprary dropdown menue showing you the context of switching process.

Concretly, ctrl+tab (ctrl is held) beings down a dropdown menu showing all tabs with current tab highlighted and repeated press of tab cycle through them and the switching occurs when ctrl press is lifted.

Thanks.

**Comment by wez** [comment] 2024-01-27 23:46
Closing as a duplicate of https://github.com/wez/wezterm/issues/3647

**Closed by wez** 2024-01-27 23:46 UTC
Labels: enhancement
