### ISSUE TITLE
CTRL-A is sent to terminal on key-up rather than key-down when use_ime=true on X11

### ISSUE THREAD

**Issue by ayang** [wez/wezterm#2951] opened 2023-01-13 02:34 UTC
**Is your feature request related to a problem? Please describe.**
When I press Ctrl+A, it should gose to the begin of line on bash, but It occurs on I release the keys. This behavior is differrent from other terminals like gnome terminal. In gnome terminal, it gose to the line of begin immediately when the keys Contrl and A both down.
This behavior always lead to the character 'a' is typed in when I release Contrl key before A is released.

You can reproduce it by click the following keys quickly:
1. keydown Ctrl
2. keydown a
3. keyup Ctrl
4. keyup a

**Describe the solution you'd like**
Detect keydown event to determine a hotkey (or named shortcut).

Thank you for the beautiful software!!!

**Comment by wez** [comment] 2023-01-13 02:47
wezterm's keyboard handling is all based on key-down events, so what you're describing doesn't sound right; I'm not at my linux box at the moment, but on my mac this definitely responds on key-down events.

Please run: `wezterm --config debug_key_events=true` and then press the keys from your description above, and share the debug output. 

See: https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html

You may wish to try setting `use_ime = false` in case the IME is affecting input processing.

**Comment by ayang** [comment] 2023-01-13 03:11
I found it is caused by fcitx5 on ubuntu. This is the logs below. But I tested in gnome terminal, kitty, and terminology, they are not 
influenced by fcitx at all.

### open fcitx

11:06:02.548  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(A), modifiers: NONE, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:06:02.548  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('a'), modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:06:02.549  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('a') mods=NONE
11:06:02.549  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "a", Char('a') NONE
11:06:02.549  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:06:02.549  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Control mods=NONE
11:06:02.596  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('a'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:06:02.596  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('a') mods=NONE


### quit fcitx

11:04:42.450  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
11:04:42.450  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('a'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(A), modifiers: CTRL, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
11:04:42.450  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('a') mods=CTRL
11:04:42.450  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1}", Char('a') CTRL
11:04:42.546  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Control, modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:04:42.546  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Control mods=CTRL
11:04:42.569  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('a'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
11:04:42.569  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('a') mods=NONE

**Comment by ayang** [comment] 2023-01-13 03:16
wezterm --config use_ime=false is a solution.

**Comment by ayang** [comment] 2023-01-13 03:32
Can I set a hot key to disable and enable ime in config file? I think it is a better solution.

**Comment by wez** [comment] 2023-01-13 16:03
Take a look at:
https://wezfurlong.org/wezterm/config/lua/window/set_config_overrides.html

**Comment by ayang** [comment] 2023-01-14 03:41
Thank you. I found it is good if no ime, all works is speed up. Including typing and hotkey.

**Comment by wez** [comment] 2023-01-14 04:14
I'm going to close this: it's not a bug in wezterm, but a quirk of the IME when enabled. I don't think changing the default value for `use_ime` is warranted; I think having the IME available is more generally useful for more people by default, but if enough people raise this, I'll reconsider.

**Closed by wez** 2023-01-14 04:14 UTC
Labels: X11, keyboard
