### ISSUE TITLE
Black image when using a gif image

### ISSUE THREAD

**Issue by Lesnock** [wez/wezterm#4131] opened 2023-08-11 01:41 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230806-225328-bf172634

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I set the background configuration to use a specific GIF, only a black image is shown (only happens to this specifically image).

Image is at the "To Reproduce" section.

Here is how the terminal is shown:

![image](https://github.com/wez/wezterm/assets/19783675/170856f5-de22-4fd1-a4b4-34d2e09e8545)

### To Reproduce

Use my configuration with this image:

![programmer](https://github.com/wez/wezterm/assets/19783675/5d3c8800-fb00-45d0-b9dd-7eb82f057baf)

### Configuration

```lua
local wezterm = require 'wezterm'
local config = {}

-- Appearance
config.color_scheme = 'Catppuccin Macchiato'
config.font = wezterm.font 'JetBrainsMono Nerd Font Mono'
config.font_size = 16
config.line_height = 1.2
config.window_background_opacity = 0.97
config.enable_tab_bar = false

config.background = {
    {
        source = { File = 'C:/Users/caiol/Desktop/programmer.gif' }
    }
}

config.window_padding = {
    left = 20,
    right = 20,
    top = 20,
    bottom = 20,
}

-- Start
config.default_domain = 'WSL:Ubuntu-22.04'
config.initial_rows = 16

return config
```

### Expected Behavior

Should show the animated GIF.

### Anything else?

I'm using Windows 10 (build: 19045.3324).
My video card is an AMD Radeon R7 200 series.

**Comment by Lesnock** [comment] 2023-08-11 01:47
I tried to use GIMP to just open and export the image and it worked...
So I don't know what was causing this bug, but I found this workaround.
Be free to investigate or close this ticket.
Thank you!

**Comment by wez** [comment] 2023-08-27 17:41
I can't reproduce this on my linux system with the image that was attached to this issue.
If wezterm can't render an image, there should be a message about why in the logs.
I'm going to close this because it sounds like it is working for you now as well.

**Closed by wez** 2023-08-27 17:41 UTC
Labels: bug
