### ISSUE TITLE
wayland window resize issue

### ISSUE THREAD

**Issue by mckellygit** [wez/wezterm#1280] opened 2021-10-28 15:53 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20211027-125648-539d72a9

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

if you resize the window on the right-side larger and then you resize the same window on the left-side larger - it does not seem correct.
As soon as you resize the left-side, the right-side reverts to where it was before the previous right-side resize.
If you do this in reverse, resizing the left-side first and then the right-side it seems correct.
This is only when wayland is enabled, not with X11.
I have an old mutter 3.24.4 so perhaps its just with that, but did want to report this in case it is a real issue.

### To Reproduce

enable wayland
resize window on right-side larger
resize same window on left-side larger - and see right-side shrink

### Configuration

Not sure it matters, except for wayland ?

### Expected Behavior

To have right-side not shrink back.

### Anything else?

Thank you again for wezterm.

**Comment by wez** [comment] 2022-07-09 16:55
I can't reproduce this in current mutter/fedora 36, so let's close this!

**Closed by wez** 2022-07-09 16:55 UTC
Labels: bug, Wayland
