### ISSUE TITLE
Windows Defender detects C:\Program Files\WezTerm\strip-ansi-escapes.exe as malware

### ISSUE THREAD

**Issue by carterols** [wez/wezterm#5198] opened 2024-03-20 21:00 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

This is on a work computer and it is safer to just uninstall wezterm, so I did not update Wezterm.

Windows detects C:\Program Files\WezTerm\strip-ansi-escapes.exe as containing a Trojan virus.
<img width="311" alt="image" src="https://github.com/wez/wezterm/assets/38794079/34fbbb9f-7c27-4515-b9ca-a1d51186631c">

### To Reproduce

Download the executable and run windows defender on it... My company's Windows Defender might be configured differently, so you may or may not find a threat. This could be a false positive.

### Configuration

no config

### Expected Behavior

I didn't expect WezTerm to contain a Trojan Virus. This could be a false positive though

**Comment by valerian** [comment] 2024-03-21 13:56
I have the same issue, on a regular default windows defender

**Comment by dbs** [comment] 2024-04-09 05:22
SentinelOne also considers strip-ansi-escapes a threat (using the Windows stable installer build as of five minutes ago): 
![image](https://github.com/wez/wezterm/assets/317113/c0b615bf-0cc0-41ca-80f3-2b7ecd4fd62d)

What are you trying to do to us, Wez? :)

**Comment by NotYourAlejandro** [comment] 2024-04-10 22:21
A check on VirusTotal shows a very concerning result: https://www.virustotal.com/gui/file/ac6b05ae682c120778791eb942895db8fe1e513787c718df6996a3895d82c1c3

**Comment by carterols** [comment] 2024-04-10 23:07
Is @wez the only contributor to this project? Can someone figure out if this was malicious or an accident? Kinda concerning...

**Comment by NotYourAlejandro** [comment] 2024-04-10 23:10
Apparently this issue is a duplicate of https://github.com/wez/wezterm/issues/5074. The tag on that issue states it's fixed in the nightly build.

**Comment by wez** [comment] 2024-04-11 05:02
Duplicate of #5074

**Closed by wez** 2024-04-11 05:02 UTC
Labels: bug
