### ISSUE TITLE
Strange cursor shape for inactive windows/panes

### ISSUE THREAD

**Issue by chtenb** [wez/wezterm#4231] opened 2023-09-01 08:23 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230828-220414-99c96139

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The cursor shape is off for inactive windows/panes

No config:
![image](https://github.com/wez/wezterm/assets/1030961/dcaaa0c7-7c92-4cf3-a904-308f303d48d0)

My config (slightly more pronounced:
![image](https://github.com/wez/wezterm/assets/1030961/18d5c645-a573-4cfa-981c-6475bcb4f1c5)

This is obviously a very minor issue, but it might point to a regression since I didn't see this in the past, with older versions.

### Configuration

no config

### Logs

Debug Overlay
wezterm version: 20230828-220414-99c96139 x86_64-pc-windows-msvc
Window Environment: Windows
WebGPU: name=Intel(R) Iris(R) Xe Graphics, device_type=IntegratedGpu, backend=Vulkan, driver=Intel Corporation, driver_info=Intel driver, vendor=32902, device=39497

**Comment by wez** [comment] 2023-09-01 12:56
Confirmed. This is related to 2c95b98447ac88e0327b84c725efc7b837bdbd75

**Comment by nvllsvm** [comment] 2023-09-02 21:01
The inactive cursor colors also do not respect `force_reverse_video_cursor = true` and show as the default green.

**Comment by futile** [comment] 2023-12-27 12:53
Hi, I wanted to maybe take a stab at this, to clear the way for a new release. But I'm not super familiar with wezterm/terminal emulators, so I wanted to make sure I get the problem correctly :)

First: It only happens on Windows, correct?

Then, I guess it should look more like this (screenshot from wezterm on my Linux system)? 
![image](https://github.com/wez/wezterm/assets/1130337/2cc9e084-edab-443c-b66f-6422373f5008)

A bit cut off, but with a consistent thickness, i.e., not thicker on the left/thinner on the right like in your screenshots.

And then the problem @nvllsvm mentioned (re/ `force_reverse_video_cursor = true`) is probably/might be related to the same commit, but might need a different fix?

I just added `force_reverse_video_cursor = true` to my config, but couldn't see a difference. Is the problem visible by adding `force_reverse_video_cursor = true` to an empty config on Windows, or else how can it be reproduced?

Thank you! :)

**Comment by wez** [comment] 2023-12-28 14:14
@futile the issue is not specific to windows, it is due to the change of how the graphics are rasterized in 2c95b98447ac88e0327b84c725efc7b837bdbd75

It's a rendering artifact; the way to resolve this is to tweak the logic for this case:
https://github.com/wez/wezterm/blob/2c95b98447ac88e0327b84c725efc7b837bdbd75/wezterm-gui/src/customglyph.rs#L3846-L3869

**Comment by futile** [comment] 2023-12-30 15:30
Took a stab at it in #4733.

I ended up adjusting the maximum width used for rendering the glyph (which is what `BlockCoord::One` resolves to) to account for the stroke width. So I didn't just adjust the part you linked, because it felt like `BlockCoord::One` meant the right thing, which makes me feel like I might have gone into the wrong direction here.

Honestly I'm not super happy with it, and don't think I fully understood the problem/all the parts involved. Specifically my attempt is to reduces the width in pixels by `(stroke_width / 2.).floor()`, which happens to look correct, for this issue at least. But I don't really know why the `floor()` works/makes it correct, so I don't think it's the final solution yet.

**Comment by joouha** [comment] 2024-01-08 15:28
I think might be a duplicate of https://github.com/wez/wezterm/issues/3759

**Closed** 2024-01-21 19:01 UTC
Labels: bug
