### ISSUE TITLE
color_scheme: rose-pine-moon `selected_bg` is the same color as `background` - impossible to see what is selected

### ISSUE THREAD

**Issue by mayboroda** [wez/wezterm#6118] opened 2024-09-10 21:47 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I use `color_scheme = "rose-pine-moon"` or any other rose-pine color scheme I can't see selection area during copy-mode, because background color and selection_bg color is identical, at lease [here](https://github.com/wez/wezterm/blob/30345b36d8a00fed347e4df5dadd83915a7693fb/docs/colorschemes/data.json#L31189)

### To Reproduce

- Install latest nightly build
- set `color_scheme = "rose-pine-moon",` in wezterm.lua
- try to select something in copy-mode or use your mouse

### Configuration
```lua
config = {
    color_scheme = "rose-pine-moon",
}
```

### Expected Behavior

According to [rose-pine color scheme for nvim](https://github.com/rose-pine/neovim/blob/8b1fd252255a7f2c41b4192a787ab62660b29f72/lua/rose-pine/palette.lua#L39C3-L39C29) selection color must be `#44415a`

**Comment by mayboroda** [comment] 2024-09-11 20:53
UPD:
You can easily fix the issue with your own config for `colors`
```lua
config ={
...
    color_scheme = "rose-pine-moon",
    colors = {
        selection_bg = "#44415a",
    },
}
```

**Comment by Risinggoblin** [comment] 2024-09-14 21:51
Glad you were able to fix this. Also btw, wezterm uses rose-pine-dawn (and many other themes) directly from the iterm themes repo. So this would be an issue for that repo https://github.com/mbadolato/iTerm2-Color-Schemes (unless you have checked for this issue on iterm and this doesn't get reproduced there)

I suggest you check for this on iterm and close this issue if this gets recreated there?

**Comment by wez** [comment] 2024-09-15 13:39
Once it is fixed upstream, it will get picked up here when I next sync the color schemes. I do that every so often in `main`, and always before I prepare to tag a release.

I'm going to close this because I'm not going to remember to look for this issue when I next run a sync, and I may as well close it out while I'm here.

**Closed by wez** 2024-09-15 13:39 UTC
Labels: bug
