### ISSUE TITLE
Nushell prompt issue

### ISSUE THREAD

**Issue by thomascft** [wez/wezterm#2096] opened 2022-06-09 05:12 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Upon opening WezTerm with NuShell as my login shell, two lines appear as if `\n` was hit once. If I open a new tab it appears normally with only one prompt line. I'm using the base config for NuShell and the only setting I have set on WezTerm is the font. Both have the date and path, but the first has the date centered.

### To Reproduce

Open Wezterm with NuShell set as user shell.

### Configuration

local wezterm = require("wezterm")

return {
        font = wezterm.font("Victor Mono Nerd Font")
}`

### Expected Behavior

Single line rather than two.

### Logs

00:01:43.166 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-2896
00:01:43.382 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) HD Graphics 4600 (HSW GT2) 4.6 (Compatibility Profile) Mesa 22.1.1 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2dd
00:11:59.090 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) HD Graphics 4600 (HSW GT2) 4.6 (Compatibility Profile) Mesa 22.1.1 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2dd

**Comment by thomascft** [comment] 2022-06-09 05:15
Actually the prompts are spaced about 4 lines apart when I open it not one.

**Comment by wez** [comment] 2022-06-09 05:28
Did you take a look at: https://github.com/wez/wezterm/issues/1999 ?

**Comment by thomascft** [comment] 2022-06-09 06:50
Yeah, it happens without any interaction. I open WezTerm with a hot key or rofi, and it looks like this 
'''
/home/thomas   12:34



/home/thomas               12:34
'''
And when I open a new tab it only opens a single line like normal.

**Comment by thomascft** [comment] 2022-06-09 16:24
This happens on my two laptops, one is AMD and the other Intel. Both arch based with stock Nushell

**Comment by wez** [comment] 2022-06-09 17:06
Oh, it looks like your WM is resizing the window from its default size immediately after launch and the extra prompt is nushell adjusting to the resize.

**Comment by thomascft** [comment] 2022-06-09 17:09
Oh... How should I fix that?

**Comment by wez** [comment] 2022-06-10 14:03
This is the underlying issue in nushell: https://github.com/nushell/nushell/issues/4906
You can see the same effect just by resizing nushell when it is running in any terminal.

**Comment by wez** [comment] 2022-06-16 20:38
Closing this, as the issue is in nushell

**Closed by wez** 2022-06-16 20:38 UTC
Labels: bug
