### ISSUE TITLE
font_size > 13 causes initial windows to be extremely wide

### ISSUE THREAD

**Issue by brandonchinn178** [wez/wezterm#3015] opened 2023-01-27 00:39 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230125-180646-f15bb186

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When opening a new Wezterm window on an external monitor, it opens with 162 or 172 columns for font sizes over 13. The issue is exacerbated because my external monitor's resolution is scaled to 1600x900; when using "Default for Display", at least the window fits on the screen (still at 172 columns instead of the expected default of 80 columns).

### Configuration

return { font_size = 16 }

**Comment by wez** [comment] 2023-01-27 01:11
Can you look through this issue:
* https://github.com/wez/wezterm/issues/2958

and collect the same sort of information that I asked for over there, but share it here in this issue?

The git hash of the version you are running is the commit that theoretically resolves that particular issue, and the behavior you described sounds sort of similar to that one.

**Comment by brandonchinn178** [comment] 2023-01-27 01:40
🤦 sorry I don't know why I didnt search existing issues first (pretty sure I did for the other issues though).

I'll take a look when I'm back at my laptop

**Comment by brandonchinn178** [comment] 2023-01-27 17:46
<details>
<summary><code>wezterm.gui.screens()</code></summary>

```
{
    "active": {
        "height": 900,
        "max_fps": 60,
        "name": "DELL U2715H",
        "scale": 1,
        "width": 1600,
        "x": 0,
        "y": 0,
    },
    "by_name": {
        "Built-in Retina Display": {
            "height": 1600,
            "max_fps": 60,
            "name": "Built-in Retina Display",
            "scale": 1,
            "width": 2560,
            "x": 3200,
            "y": 200,
        },
        "DELL U2715H": {
            "height": 900,
            "max_fps": 60,
            "name": "DELL U2715H",
            "scale": 1,
            "width": 1600,
            "x": 0,
            "y": 0,
        },
    },
    "main": {
        "height": 900,
        "max_fps": 60,
        "name": "DELL U2715H",
        "scale": 1,
        "width": 1600,
        "x": 0,
        "y": 0,
    },
    "origin_x": 0,
    "origin_y": 0,
    "virtual_height": 1800,
    "virtual_width": 5760,
}
```
</details>


[wezterm.log](https://github.com/wez/wezterm/files/10521590/wezterm.log)

Is that helpful?

**Comment by wez** [comment] 2023-02-06 01:29
Duplicate of https://github.com/wez/wezterm/issues/2958

**Closed by wez** 2023-02-06 01:29 UTC
Labels: bug
