### ISSUE TITLE
Wezterm need a ROCKET

### ISSUE THREAD

**Issue by zonta00001** [wez/wezterm#4312] opened 2023-09-18 19:26 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME 44

### WezTerm version

20230806-225328-bf172634

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

wezterm is a wonderfull terminal,  to use o any platform,
but it seems to be slow for rendering output datas and even for input data, i had use all advice a got from others issues, like checking my rendering options available by runing wezterm.gui.enumerate_gpus()  and changing my front_end to OpenGL or WebGpu, but the condition is same,
i hope that will change in the future,and Wez will put a Fuc***g rocket on it ,
for now im looking for other alternative to this terminal :-(, like kitty who's work perfect out of the box , because this is it. concerning performance it always good to have the maximum at startup, without need to customize that by complicated process. some of users are not  much powerfull user, that have enough experience to check inside source code and try to figure it out what is the concerning issue,
they just hope to get a nice tools, who will help them to build they dreams.
thanks. 
Please fix that.

### To Reproduce

the fact report of the facts speaks for themselves
[read the last comment by ttys3-net](https://www.reddit.com/r/linux/comments/v86m6o/why_doesnt_wezterm_get_any_attention_compared_to/?rdt=43527)
List of issue report
    #546
    #790  
    #1872
    #2916
    #3042
    #3214 
    #4052

### Configuration

```lua
local wezterm = require 'wezterm'
local config = {}
-------------------------------------
if wezterm.config_builder then
  config = wezterm.config_builder()
end

----------------------- Setup
config.term = 'wezterm' 					--Terminfo 
config.color_scheme = 'matrix'				--Themes (Colorless	 ✔️
config.window_decorations = "INTEGRATED_BUTTONS|RESIZE"		--Window Decoration
config.integrated_title_button_style = "Gnome"				--Window Decoration
config.front_end = "WebGpu"					--Rendering Engine
config.animation_fps=200					--Rendering speed

----------------------- Fonts
--config.font_dirs = { 'wez_font', '~/.local/share/fonts' }
--config.font_locator = 'ConfigDirsOnly'
config.font = wezterm.font_with_fallback {
  {
-- 	family = 'Roboto',
 	family = 'JetBrains Mono',
--    family = 'VictorMono Nerd Font',
  --  family = 'Agave Nerd Font',
    weight = 'ExtraLight',
  },
  'OpenSymbol',
  'Standard Symbols PS',
  'Symbols Nerd Font',
}
--config.dpi=96
config.freetype_load_target = 'Light'
config.freetype_render_target ='Light' --'HorizontalLcd'
config.freetype_load_flags='FORCE_AUTOHINT'
config.font_size = 17
config.unicode_version = 14

----------------------Boolean
config.log_unknown_escape_sequences = false
config.warn_about_missing_glyphs = false
config.log_unknown_escape_sequences = false
config.adjust_window_size_when_changing_font_size = false
config.hide_tab_bar_if_only_one_tab = true
config.quit_when_all_windows_are_closed = false

------------------------- key assignement
local act = wezterm.action
--config.leader = { key = 'CTRL', mods = 'SHIFT' }
config.keys = {
--Menus
  { key = 'F1',   action = act.ActivateCommandPalette },
  { key = 'F2',   action = act.ShowLauncher },
  { key = 'F4',   action = act.PaneSelect },
  { key = 'F12',  action = wezterm.action.ShowDebugOverlay },
--Srollback buffer, scroll by semantic prompt
  { key = 'UpArrow',   mods = 'SHIFT', action = act.ScrollToPrompt(-1) },
  { key = 'DownArrow', mods = 'SHIFT', action = act.ScrollToPrompt(1) },
--Copy Paste operation
  { key = 'v', mods = 'CTRL', action = act.PasteFrom 'Clipboard' },
  { key = 'v', mods = 'CTRL', action = act.PasteFrom 'PrimarySelection' },
--Pane navigation
  { key = 'LeftArrow', mods = 'ALT', action = act.ActivatePaneDirection 'Left',},
  { key = 'RightArrow', mods = 'ALT', action = act.ActivatePaneDirection 'Right',},
  { key = 'UpArrow', mods = 'ALT', action = act.ActivatePaneDirection 'Up', },
  { key = 'DownArrow', mods = 'ALT', action = act.ActivatePaneDirection 'Down',},
--Pane spliting 
  { key = 'm', mods = 'ALT', action = wezterm.action.SplitHorizontal { domain = 'CurrentPaneDomain' },},
  { key = 'n', mods = 'ALT', action = wezterm.action.SplitVertical { domain = 'CurrentPaneDomain' },},
--Pane resize
  { key = 'LeftArrow', mods = 'SHIFT|CTRL', action = act.AdjustPaneSize { 'Left', 1 }, },
  { key = 'RightArrow', mods = 'SHIFT|CTRL', action = act.AdjustPaneSize { 'Right', 1 }, },
  { key = 'UpArrow', mods = 'SHIFT|CTRL', action = act.AdjustPaneSize { 'Up', 1 } },
  { key = 'DownArrow', mods = 'SHIFT|CTRL', action = act.AdjustPaneSize { 'Down', 1 }, },
--Tab navigation
  { key = '[', mods = 'ALT', action = act.ActivateTabRelative(-1) },
  { key = ']', mods = 'ALT', action = act.ActivateTabRelative(1) },
  { key = '\\', mods = 'ALT', action = act.ShowTabNavigator },  
--Tab spawning
  { key = 't', mods = 'ALT', action = act.SpawnTab 'DefaultDomain' },
--Window navigation
  { key = ',', mods = 'ALT', action = act.ActivateWindowRelative(-1) },
  { key = '.', mods = 'ALT', action = act.ActivateWindowRelative(1) },
	----------------------------- Miscelanous Key for testing
--  { key = 'k', mods = 'ALT',  action = wezterm.action_callback( function(window, pane)wezterm.log_info (pane:get_cursor_position(), pane:get_semantic_zones("Output"))  end) },
--  { key = 'F1',  action = wezterm.action.SendString 'welcome'},
}

---------------------- mouse assignement
config.mouse_bindings = {
  {
    event = { Down = { streak = 3, button = 'Left' } },
    action = wezterm.action.SelectTextAtMouseCursor 'SemanticZone',
    mods = 'NONE',
  },
}

-----------------------------------
--wezterm.on('window-config-reloaded', function(window, pane)
--  window:toast_notification('wezterm', 'configuration reloaded!', nil, 4000)
--end)

-----------------------------------
return config
```

### Expected Behavior

more speed in all stream, output and input!.

### Logs

```
Debug Overlay
wezterm version: 20230806-225328-bf172634 x86_64-unknown-linux-gnu
Window Environment: Wayland
WebGPU: name=Intel(R) HD Graphics 4600 (HSW GT2), device_type=IntegratedGpu, backend=Vulkan, driver=Intel open-source Mesa driver, driver_info=Mesa 23.1.0-devel (git-ca4ec49 2023-03-29 jammy-oibaf-ppa), vendor=32902, device=1046
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
> wezterm.gui.enumerate_gpus()
[
    {
        backend: Vulkan,
        device: 1046,
        device_type: IntegratedGpu,
        driver: Intel open-source Mesa driver,
        driver_info: Mesa 23.1.0-devel (git-ca4ec49 2023-03-29 jammy-oibaf-ppa),
        name: Intel(R) HD Graphics 4600 (HSW GT2),
        vendor: 32902,
    },
    {
        backend: Vulkan,
        device: 0,
        device_type: Cpu,
        driver: llvmpipe,
        driver_info: Mesa 23.1.0-devel (git-ca4ec49 2023-03-29 jammy-oibaf-ppa) (LLVM 15.0.6),
        name: llvmpipe (LLVM 15.0.6, 256 bits),
        vendor: 65541,
    },
    {
        backend: Gl,
        device: 0,
        device_type: Cpu,
        name: llvmpipe (LLVM 15.0.6, 256 bits),
        vendor: 65541,
    },
]
>
```

### Anything else?

nop

**Comment by wez** [comment] 2023-09-18 22:52
There are performance issues on wayland, but I don't have time to work on wayland support, so they are lingering.

I'm going to close this issue as a duplicate of the others that you referenced in the main description, because this report adds no additional useful information that can help to resolve any of those issues.

In addition: your tone and attitude are neither respectful nor productive, so I am not inclined to spend any further time in conversation with you.

**Closed by wez** 2023-09-18 22:52 UTC
Labels: bug

**Comment by pallaswept** [comment] 2023-09-23 22:57
> sorry! that was not my intention.

Nor was it your effect. You were perfectly respectful and productive.
