### ISSUE TITLE
[Feature request] tabs in titlebar support

### ISSUE THREAD

**Issue by hosxy** [wez/wezterm#1596] opened 2022-01-28 07:43 UTC
Could you please add a new tabs layout like windows terminal ,it's tabs in titlebar not under titlebar.
There is a windows terminal's screenshot:
![图片](https://user-images.githubusercontent.com/17108640/151505944-202ba8c9-8041-4ef0-a6ce-7f2240941cf5.png)

Firefox and Chrome also have similar layout.
It will save vertical space , maybe this is a good news for laptop.

**Comment by wez** [comment] 2022-01-28 16:08
Duplicate of #1180 

Note that you can set `window_decorations = "RESIZE"` in your config to disable the title bar and get most of the way there.
See: https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html

**Closed by wez** 2022-01-28 16:08 UTC
Labels: enhancement

**Comment by hosxy** [comment] 2022-01-31 03:20
> Duplicate of #1180
> 
> Note that you can set `window_decorations = "RESIZE"` in your config to disable the title bar and get most of the way there. See: https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html

Dose it have any way to add `close` `max` `min` button?

**Comment by wez** [comment] 2022-01-31 14:37
Not yet; that's why #1180 is still open
