### ISSUE TITLE
Alt+ Enter can't make wezterm fullscreen after it exit from full screen by create new tab (ctrl + shift + t)

### ISSUE THREAD

**Issue by netherstar** [wez/wezterm#2941] opened 2023-01-11 05:02 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230109-162248-c19b6505

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Alt+ Enter can't make wezterm fullscreen after it exit from full screen by create new tab (ctrl + shift + t).

1. Open wezterm
2.  press Alt + Enter to go to full screen
3.  press Ctrl + Shift + T to open new tab -> wezterm lost fullscreen
4. press Alt + Enter -> not go to full screen. (it should now go to full screen)

https://user-images.githubusercontent.com/12563466/211721734-7326d8aa-9b0d-4b88-9ea8-94d33844ad72.mp4

### Configuration

With this setting:
```
  enable_tab_bar = true,
  hide_tab_bar_if_only_one_tab = true,

```

### Expected Behavior

it should go to full screen or better behavior: when create new tab in full screen it remain full screen state just like when 
```hide_tab_bar_if_only_one_tab = false``` is set

**Comment by wez** [comment] 2023-04-08 18:27
Possibly the same root cause as https://github.com/wez/wezterm/issues/3439, which I believe is now fixed.
Please try the next nightly build, available within 30-60 minutes from now.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Closed** 2023-04-08 22:02 UTC
Labels: bug, Windows, fixed-in-nightly
