### ISSUE TITLE
Windows: sixel does not work on wezterm but works on wezterm ssh.

### ISSUE THREAD

**Issue by Kreijstal** [wez/wezterm#6032] opened 2024-08-25 14:29 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

Windows 10

### WezTerm version

WezTerm-windows-20240812-215703-30345b36 nightly

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Sixel does not work if you use wezterm and then use ssh to get in.

### To Reproduce

use anything that can generate sixel, try it from ./wezterm ssh, then try it from normal wezterm then ssh

### Configuration

no config

### Expected Behavior

Should always work. Unless configured otherwise.

### Anything else?

No

**Comment by wez** [comment] 2024-09-15 14:44
Duplicate of #1236

**Closed by wez** 2024-09-15 14:44 UTC
Labels: bug, Windows
