### ISSUE TITLE
resolution change in mac not refreshing the wezterm

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#268] opened 2020-09-13 23:00 UTC
Connected to airplay and uses the tv's resolution but wezterm doesn't seem to be updating to the new ressolution.

![Screen Shot 2020-09-13 at 3 58 44 PM](https://user-images.githubusercontent.com/287744/93030730-1871ac80-f5da-11ea-9944-0afb20979564.png)

`ctrl+l` to redraw also doesn't help here.

**Comment by wez** [comment] 2020-09-14 00:02
CMD-+ then CMD-- will likely workaround this.
This is a duplicate of https://github.com/wez/wezterm/issues/161; closing this one in favor of that one

**Closed by wez** 2020-09-14 00:02 UTC
Labels: bug, duplicate
