### ISSUE TITLE
neovim interprets `*` different than kitty itself when using kitty kbd protocol

### ISSUE THREAD

**Issue by craigmac** [wez/wezterm#3092] opened 2023-02-11 00:43 UTC
Issue explained here: https://github.com/kylechui/nvim-surround/issues/200

With kitty protocol turned on, neovim HEAD build interprets `*` as `<S-*>` while when using kitty itself  it reports `*` while using the kitty protocol.

**Comment by wez** [comment] 2023-02-11 15:30
Potentially a duplicate of https://github.com/wez/wezterm/issues/2546

**Comment by craigmac** [comment] 2023-02-11 16:58
Looks like it, yes!

**Comment by wez** [comment] 2023-02-11 17:08
OK, I'll close this in favor of that!

**Closed by wez** 2023-02-11 17:08 UTC
Labels: keyboard
