### ISSUE TITLE
Error converting Lua value returned by script to Config struct

### ISSUE THREAD

**Issue by bangedorrunt** [wez/wezterm#2479] opened 2022-09-04 00:13 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220903-135850-a29d8ed4

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, I tried both stable and nightly versions

### Describe the bug

<img width="957" alt="Screen Shot 2022-09-04 at 9 59 13 am" src="https://user-images.githubusercontent.com/1514823/188291101-4d051551-c097-4b4b-b9b2-0206f969bdd1.png">

### To Reproduce

I can reliably reproduce this bug by having two themes inside one folder. Here is my current folder structure 
```
wezterm/
  |_ justfile
  |_ wezterm.lua
  |_ themer/
       |_ rose-pine.lua
       |_ rose-pine-dawn.lua
  |_ fnl/
      |_ wezterm.fnl
      |_ themer/
          |_ rose-pine.fnl
          |_ rose-pine-dawn.fnl
```

Whenever I want to change the theme, run
```
just compile
```
and the error happened

**However, if I remove one of theme files, no error occured**

### Configuration

The error possibly caused by line 2. But it should not be a problem here, as I mentioned above, if there was only either one of file in `themer` folder, no error occured.
<img width="828" alt="Screen Shot 2022-09-04 at 10 01 27 am" src="https://user-images.githubusercontent.com/1514823/188291237-418a0db8-82f8-40fb-9f39-37c8a8323a41.png">
<img width="857" alt="Screen Shot 2022-09-04 at 10 04 15 am" src="https://user-images.githubusercontent.com/1514823/188291309-b37ac3c3-5d7e-488a-90d3-1a7ae53905c5.png">

### Expected Behavior

Wezterm should load the config without any error

**Comment by wez** [comment] 2022-09-04 00:35
It sounds like this is an issue with the config build/generation system you're using, and that it is generating an invalid config.
Can you share the actual `wezterm.lua` file that is being produced?

**Comment by wez** [comment] 2022-09-04 00:43
Can you also share the two files in the themer directory?

**Comment by wez** [comment] 2022-09-04 00:47
Just the generated lua files please!

**Comment by wez** [comment] 2022-09-04 01:11
I can't reproduce the error with those files.
However, there are issues with the config.
Here's the local file structure on my system:

```
; find /tmp/2479
/tmp/2479
/tmp/2479/wezterm
/tmp/2479/wezterm/wezterm.lua
/tmp/2479/wezterm/themer
/tmp/2479/wezterm/themer/rose-pine-dawn.lua
/tmp/2479/wezterm/themer/rose-pine.lua
```

Starting wezterm on that:

```
; env -u WEZTERM_CONFIG_FILE -u WEZTERM_CONFIG_DIR XDG_CONFIG_HOME=/tmp/2479 wezterm
18:04:46.329  WARN   mux::domain > Directory "~" is not readable and will not be used for the command we are spawning: No such file or directory (os error 2)
18:04:46.329  ERROR  wezterm_gui > Unable to spawn /usr/local/bin/zsh because it doesn't exist on the filesystem or is not executable (ENOENT: No such file or directory); terminating
```

The warning is because `~` is not valid. You should use [wezterm.home_dir](https://wezfurlong.org/wezterm/config/lua/wezterm/home_dir.html) to refer to the home directory.
I'd also recommend using [wezterm.target_triple](https://wezfurlong.org/wezterm/config/lua/wezterm/target_triple.html) to determine if you are running on windows.

The error is because `default_prog` isn't valid for my system; if I comment it out, wezterm will start up without any other major issues (just one around resolving fonts, but it's not a blocker).

**Closed as completed** 2022-09-04 01:19 UTC
Labels: bug
