### ISSUE TITLE
Sixel image protocol doesn't work on Windows

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [wez/wezterm#5758] opened 2024-06-26 15:52 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240623-130118-4daab4dc

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When running a Windows version of _WezTerm_, _Sixel_ image protocol doesn't work.

### To Reproduce

1. Connect a Windows version of WezTerm to a Linux box, over SSH or WSL.
2. Install `img2sixel` to be able to display images in your terminal: `apt-get install img2sixel` on Debian/Ubuntu.
3. Alternatively, get a sixel file you can display via `cat`.
4. Run `cat image.six`. The image will **not** get displayed.
5. Run `img2sixel image.png`. The image will **not** get displayed.

### Configuration

no config

**Comment by 0x6675636b796f75676974687562** [comment] 2024-06-26 15:55
Reference rendering: **XTerm**

![image](https://github.com/wez/wezterm/assets/73111822/1c7cc3a4-e02d-418e-9b26-e9f690eababe)

**Comment by 0x6675636b796f75676974687562** [comment] 2024-06-26 15:58
Correct rendering: **Wezterm** on Linux (via X11):

![image](https://github.com/wez/wezterm/assets/73111822/799d6988-2d2c-41fe-a482-6a1e7e82571c)

**Comment by 0x6675636b796f75676974687562** [comment] 2024-06-26 16:00
No rendering: **WezTerm** on Windows

![image](https://github.com/wez/wezterm/assets/73111822/b9a25494-a0e9-48c3-b6ba-ee29ae70310f)

**Comment by AnonymouX47** [comment] 2024-06-26 20:39
Duplicate of #1236

**Closed** 2024-07-13 21:26 UTC
Labels: bug
