### ISSUE TITLE
Color issue when starting WezTerm in Windows RDP session

### ISSUE THREAD

**Issue by kaddkaka** [wez/wezterm#1451] opened 2021-12-22 12:19 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20211221-224952-1c9b9f69

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Starting Wezterm directly on a machine with Windows 10 or from an RDP session to the same machine with windows 8 results in different colors.

### To Reproduce

Machine A: Windows 10 (OS Build 19042.1237)
Machine B: Windows 8 (OS Build 9600)

When I start wezterm from machine A itself, the colors look bright and fine (right part in picture).
If I start RDP session from machine B connecting to A, and then start wezterm within that session, the colors are much darker (and in this case more difficult to read). Are the number of colors for some reason reduced when starting wezterm like this?
![wezterm_rdp](https://user-images.githubusercontent.com/4508793/147091363-1139efdd-6947-43ca-9c60-f32d0fc020d4.png)
 

### Configuration

no config

### Expected Behavior

No color difference.

**Comment by wez** [comment] 2021-12-22 15:00
Duplicate of https://github.com/wez/wezterm/issues/1373

**Closed by wez** 2021-12-22 15:00 UTC
Labels: bug
