### ISSUE TITLE
Close pane closes wezterm

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#866] opened 2021-06-12 21:34 UTC
```lua
{ key = "x", mods = "LEADER",       action=wezterm.action{CloseCurrentPane={confirm=true}}},
```

The above code seems to behave differently on mac and linux/win. Works correctly on Linux/Win but on Mac it seems to close the entire wezterm. It then gets in to a weird state where I have to close wezterm by Activity Monitor or from the dock.

version: wezterm 20210610-074348-db9a65ae

**Comment by anongit** [comment] 2021-06-15 10:12
Can confirm, also on mac.
Removing zsh from `skip_close_confirmation_for_processes_named` restores confirmation and closes only the active pane. However with `confirm=false` it still closes the entire window keeping the process alive.

**Comment by wez** [comment] 2021-06-19 18:05
Duplicate of #890

**Closed by wez** 2021-06-19 18:05 UTC
Labels: bug
