### ISSUE TITLE
cli activate-pane-direction not take effect when using unix_domain multiplexing

### ISSUE THREAD

**Issue by xiantang** [wez/wezterm#2863] opened 2022-12-14 15:10 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

I use macos

### WezTerm version

wezterm 20221212-091509-91ea1095

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I want use `wezterm cli activate-pane-direction up` to move my cursor between window up,  and it does not take effect. 
when I input `wezterm cli activate-pane-direction --help ` it have correct result 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/34479567/207631807-7f38b46d-9393-4cdc-b482-37e07d4c222a.png">

see gif:
![Kapture 2022-12-14 at 22 50 55](https://user-images.githubusercontent.com/34479567/207628998-dd9c4fef-17b9-419e-a370-9eab36bd2bdf.gif)

### To Reproduce

1. install latest wezterm
2. cut two splits one's up, and another one is below
3. put the cursor in the below one, run `wezterm cli activate-pane-direction up`

### Configuration

```lua
local wezterm = require("wezterm")
local act = wezterm.action

local function isViProcess(pane)
	return pane:get_title():find("nvim") ~= nil
end

local function conditionalActivatePane(window, pane, pane_direction, vim_direction)
	if isViProcess(pane) then
		window:perform_action(
			-- This should match the keybinds you set in Neovim.
			act.SendKey({ key = vim_direction, mods = "CTRL" }),
			pane
		)
	else
		window:perform_action(act.ActivatePaneDirection(pane_direction), pane)
	end
end

wezterm.on("ActivatePaneDirection-right", function(window, pane)
	conditionalActivatePane(window, pane, "Right", "l")
end)
wezterm.on("ActivatePaneDirection-left", function(window, pane)
	conditionalActivatePane(window, pane, "Left", "h")
end)
wezterm.on("ActivatePaneDirection-up", function(window, pane)
	conditionalActivatePane(window, pane, "Up", "k")
end)
wezterm.on("ActivatePaneDirection-down", function(window, pane)
	conditionalActivatePane(window, pane, "Down", "j")
end)

return {
	unix_domains = {
		{
			name = "unix",
		},
	},

	default_gui_startup_args = { "connect", "unix" },
	color_scheme = "tender (base16)",
	keys = {
		{ key = "h", mods = "CTRL", action = act.EmitEvent("ActivatePaneDirection-left") },
		{ key = "j", mods = "CTRL", action = act.EmitEvent("ActivatePaneDirection-down") },
		{ key = "k", mods = "CTRL", action = act.EmitEvent("ActivatePaneDirection-up") },
		{ key = "l", mods = "CTRL", action = act.EmitEvent("ActivatePaneDirection-right") },
		{
			key = "s",
			mods = "CTRL",
			action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }),
		},
		{
			key = "v",
			mods = "CTRL",
			action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }),
		},
	},
	font = wezterm.font("JetBrains Mono"),
	-- change font size
	font_size = 14.0,
}
```

### Expected Behavior

can move cursor correctly, when I type  `wezterm cli activate-pane-direction up`, it will go upper split.

### Logs

23:03:17.151  WARN   env_bootstrap > setlocale(en_SG.UTF-8) failed, fall back to en_US.UTF-8
23:03:17.235  ERROR  wezterm_gui::termwindow > new_window has no tabs... yet?

seems not related.

### Anything else?

Thank you. I love wezterm help me a lot.

**Comment by xiantang** [comment] 2022-12-14 15:11
add on: 
![image](https://user-images.githubusercontent.com/34479567/207628998-dd9c4fef-17b9-419e-a370-9eab36bd2bdf.gif)

**Comment by wez** [comment] 2022-12-14 15:48
What does `wezterm cli list` show?

Can you try commenting out the `unix_domains` portion of your config?

**Comment by xiantang** [comment] 2022-12-14 15:54
23:31 ➜  ~ wezterm cli list
WINID TABID PANEID WORKSPACE SIZE  TITLE   CWD
   47    49    159 default   87x48 wezterm file:///Users/xxxxx
   47    49    162 default   87x48 ~       file:///Users/xxxxx

**Comment by xiantang** [comment] 2022-12-14 15:54
> What does `wezterm cli list` show?
> 
> Can you try commenting out the `unix_domains` and `default_gui_startup_args` portions of your config?

let me try

**Comment by xiantang** [comment] 2022-12-14 15:57
worked! after I comment `unix_domains and default_gui_startup_args`
![Kapture 2022-12-14 at 23 57 06](https://user-images.githubusercontent.com/34479567/207644749-75fde5b7-92eb-42f9-af3f-dd559d9c05fb.gif)

**Comment by xiantang** [comment] 2022-12-14 15:58
![Kapture 2022-12-14 at 23 57 57](https://user-images.githubusercontent.com/34479567/207644923-f9ef387d-1b70-4e5f-84e0-31e13fabfd05.gif)

**Comment by xiantang** [comment] 2022-12-14 15:59
but when I enabled unix_domains and default_gui_startup_args the issue come out again

**Comment by wez** [comment] 2022-12-14 16:05
I think the issue is that the focus/activation change request needs to fan out through multiple layers of multiplexer when you use a unix domain.

I generally recommend against using a unix_domain on something like a laptop or other client system, as the performance is not as good as using the integrated multiplexer in the the GUI process itself.

**Comment by mcwhitfield** [comment] 2022-12-23 17:24
FWIW I have the same issue in an SSH domain. Same behavior -- `wezterm cli list` output is as expected, `activate-pane-direction` exits successfully with no effect.

**Comment by lkhphuc** [comment] 2023-03-24 17:56
Just want to confirm that issue still persist on latest nightly `﻿﻿﻿wezterm 20230324-070322-1116c14c` and stable `wezterm 20230320-124340-559cb7b0`,  with both unix and ssh domain.

**Comment by wez** [comment] 2023-03-24 20:20
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by lkhphuc** [comment] 2023-03-25 11:06
Thank so much for your fast work. Can confirm it fixed on nightly for me.

**Closed** 2023-03-25 11:37 UTC
Labels: bug, fixed-in-nightly, multiplexer
