### ISSUE TITLE
Custom cli command possibility

### ISSUE THREAD

**Issue by VPavliashvili** [wez/wezterm#2361] opened 2022-08-06 01:59 UTC
**Is your feature request related to a problem? Please describe.**
Not really.
What I want to achieve is to be able create and execute custom cli commands, as already known, there are several built in [cli commands](https://wezfurlong.org/wezterm/cli/cli/index.html?search=workspace%20switch), what I want is to be able make my own commands like them with lua config

**Describe the solution you'd like**
I am not sure how would it be solved.

**Describe alternatives you've considered**
Alternative solution would be something like [on](https://wezfurlong.org/wezterm/config/lua/wezterm/on.html?highlight=custom#custom-events) custom even, where instead of cli command I will be able to run lua code with keybinding

**Additional context**
example use case would be something like this
`wezterm cli sayhello` and under the hood lua script will run from config where related logic will be executed and sayhello will be printed in console
I searched in wezterm docs and google for quite some time but was not able to find something helpful

**Comment by wez** [comment] 2022-08-06 02:22
Sounds like a duplicate of #2251 
See my comment in: https://github.com/wez/wezterm/issues/2251#issuecomment-1182414112

**Comment by VPavliashvili** [comment] 2022-08-06 07:23
Agree. Closing the issue as duplicate

**Comment by VPavliashvili** [comment] 2022-08-06 07:24
Duplicate of #2251

**Closed** 2022-08-06 07:25 UTC
Labels: enhancement
