### ISSUE TITLE
Scoop update fails because of tag mismatch

### ISSUE THREAD

**Issue by rashil2000** [wez/wezterm#1369] opened 2021-12-06 06:15 UTC
I apologize for intentionally ignoring the issue templates, because this is neither a bug nor a feature request.

For wezterm, Scoop fetches the latest version number using this regex from the releases page - `WezTerm-windows-([\w-]+)`. In the last release, there is a mismatch between the tag ("a66c61ee9") and release file name ("a66c61ee"), so Scoop fails to update the URL accordingly.

I'd like to request you to change the file name accordingly.

**Comment by rashil2000** [comment] 2021-12-06 06:16
Relevant PR here - https://github.com/ScoopInstaller/Extras/pull/7473

**Comment by AyoungDukie** [comment] 2021-12-06 11:36
This also impacts build scripts for other platforms; anything that utilizes the release version to dynamically build the download links will have this problem. Are these auto-built names? It seems like the tag is being truncated even on the Github release page:
![image](https://user-images.githubusercontent.com/5449443/144839356-72b6c1ac-3173-4e97-a131-0e88fda4dfe3.png)

**Comment by rashil2000** [comment] 2021-12-06 12:02
Yes, I was talking about this suffix itself, in the screenshot. This gets picked up by the regex. Ideally the suffix should have the same amount of truncation as the commit shorthash.

**Comment by wez** [comment] 2021-12-06 15:11
Duplicate of https://github.com/wez/wezterm/issues/1365

**Closed by wez** 2021-12-06 15:11 UTC
