### ISSUE TITLE
De-selection does not work under some circumstances

### ISSUE THREAD

**Issue by zhou13** [wez/wezterm#910] opened 2021-06-28 23:38 UTC
## Describe the bug

Canceling selection does not work under some circumstances.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: `20210628-091813-e05ddb17`
 - The active keyboard layout name: ENG

## To Reproduce

Steps to reproduce the behavior.

### Method 1
1. triple-click any line to select it;
2. move the cursor to another line and click.

If you act fast so that the gap between 1 and 2 is small enough, the line selected in 1 won't be deselected.

### Method 2
1. press down the cursor and move the cursor to drag an area
2. move the cursor to another line and click.

If you act fast so that the gap between 1 and 2 is small enough, wezterm will always select the area of 2 rather than deselected.

## Configuration

```
return {
    colors = {
        foreground = "#F8F8F2",
        background = "#282A36",
        selection_bg = "#44475a",
        selection_fg = "#ffffff",
        ansi = {"#282A36", "#ff5555", "#50fa7b", "#f1fa8c", "#bd93f9", "#ff79c6", "#8be9fd", "#bfbfbf"},
        brights = {"#4d4d4d", "#ff6e67", "#5af78e", "#f4f99d", "#caa9fa", "#ff92d0", "#9aedfe", "#e6e6e6"},
    },
    check_for_updates = false,
    exit_behavior = "Close",
    font = wezterm.font_with_fallback({
        "Fantasque Sans Mono",
    }),
    font_size = font_size,
    force_reverse_video_cursor = true,
    freetype_interpreter_version = 35,
    freetype_render_target = "HorizontalLcd",
    hide_tab_bar_if_only_one_tab = true,
    scrollback_lines = 35000,
    term = "xterm-256color",
}
```

## Expected behavior
wezterm should deselect the area in 1.

**Comment by wez** [comment] 2021-06-29 00:31
How fast is fast enough for this to trigger?

**Comment by zhou13** [comment] 2021-06-29 00:51
According to my feeling it is about 100-300ms.

**Comment by wez** [comment] 2021-07-17 16:29
is this still an issue for you?  I think we identified some other mouse binding issues that I think were probably the cause of what you were seeing here; the interaction delay is small enough that I think you were driving up the "streak" count for click counting and not triggering the event you thought you were.
I'm going to speculatively close this, but please reopen if there is something still to be run down.

**Closed by wez** 2021-07-17 16:29 UTC
Labels: bug

**Comment by unrelentingtech** [comment] 2021-09-08 19:22
I just wanted to report something along those lines. I think the issue is that streaks are only interrupted by time or button change, but they really, really should be interrupted by significant movement.
