### ISSUE TITLE
wayland+webgpu default vertical scroll is unusably sensitive

### ISSUE THREAD

**Issue by colemickens** [wez/wezterm#3549] opened 2023-04-17 20:38 UTC
**Is your feature request related to a problem? Please describe.**

I don't seem to have this problem with other terminal emulators, just wezterm. Under wayland (not sure about X, don't have it here), the touchpad scroll is unbelievably sensitive. Bordering on "unusable".

Quick googling hasn't revealed a config option for this, but I'd imagine there is one if I search harder. Regardless, it feels like the default is too high, or is being miscalculated, etc.

**Describe the solution you'd like**

The scrolling to scroll a "reasonable" amount like under Chrome, Firefox, Alacritty.

**Describe alternatives you've considered**

**Additional context**

**Comment by wez** [comment] 2023-04-17 20:48
Duplicate of https://github.com/wez/wezterm/issues/3142

**Closed by wez** 2023-04-17 20:48 UTC
Labels: enhancement
