### ISSUE TITLE
can`t startup on arch linux hyprland

### ISSUE THREAD

**Issue by matianhe3** [wez/wezterm#5228] opened 2024-03-28 02:05 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm 20240325-093507-e5ac32f2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Can`t startup.

### Configuration

no config.

### Logs

export WEZTERM_LOG=debug
❯ wezterm
10:03:19.253  DEBUG  config > Reloaded configuration! generation=1
10:03:19.254  DEBUG  sctk   > Bound new global [49] wl_output v4
10:03:19.254  DEBUG  sctk   > Bound new global [48] zxdg_output_manager_v1 v3
10:03:19.254  DEBUG  sctk   > Bound new global [14] wl_seat v7
10:03:19.254  DEBUG  window::os::x_and_wayland > Using wayland connection!
10:03:19.258  DEBUG  config                    > Reloaded configuration! generation=2
10:03:19.269  DEBUG  wezterm_font::ftwrap      > set_char_size computing 13 dpi=96 (pixel height=17.333333333333332)
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Argb8888
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Xrgb8888
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Xbgr8888
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Abgr8888
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Bgr888
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Rgbx4444
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Rgba4444
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Rgbx5551
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Rgba5551
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Rgb565
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Xbgr2101010
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Abgr2101010
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Xbgr16161616f
10:03:19.273  DEBUG  sctk                      > supported wl_shm format Abgr16161616f
10:03:19.274  DEBUG  sctk                      > supported wl_shm format Xbgr16161616
10:03:19.274  DEBUG  sctk                      > supported wl_shm format Abgr16161616
10:03:19.274  DEBUG  wezterm_gui::frontend     > workspace is default, fixup windows
10:03:19.285  DEBUG  wezterm_font::ftwrap      > set_char_size computing 13 dpi=96 (pixel height=17.333333333333332)
10:03:19.288  DEBUG  window::os::wayland::window > Config: self.window_state=None, states: (empty) (empty)
10:03:19.288  DEBUG  window::os::wayland::window > dispatch_pending_event self.window_state=(empty), pending:(empty)
10:03:19.288  DEBUG  wezterm_gui::termwindow     > Resized { dimensions: Dimensions { pixel_width: 960, pixel_height: 1042, dpi: 96 }, window_state: (empty), live_resizing: false }
10:03:19.288  DEBUG  wezterm_term::screen        > resize screen to 94x44 dpi=96
10:03:19.288  DEBUG  wezterm_term::screen        > resize screen to 94x44 dpi=96
10:03:19.292  DEBUG  wezterm_font::ftwrap        > set_char_size computing 12 dpi=96 (pixel height=16)
10:03:19.293  DEBUG  wezterm_gui::termwindow     > NeedRepaint
10:03:19.293  DEBUG  window::os::wayland::window > Had configured an event
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Intensity(Bold)))
10:03:19.317  DEBUG  wezterm_term::terminalstate            > Intensity(Bold)
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Inverse(true)))
10:03:19.317  DEBUG  wezterm_term::terminalstate            > Inverse(true)
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform Print('%')
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Inverse(false)))
10:03:19.317  DEBUG  wezterm_term::terminalstate            > Inverse(false)
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Intensity(Bold)))
10:03:19.317  DEBUG  wezterm_term::terminalstate            > Intensity(Bold)
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
10:03:19.317  DEBUG  wezterm_term::terminalstate            > Reset
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform PrintString("                                                                                             ")
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform Control(CarriageReturn)
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform Print(' ')
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform Control(CarriageReturn)
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(FinalTermSemanticPrompt(FreshLineAndStartPrompt { aid: Some("352748"), cl: Some(MultipleLine) }))
10:03:19.317  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(ITermProprietary(SetUserVar { name: "WEZTERM_PROG", value: "" }))
10:03:19.322  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(ITermProprietary(SetUserVar { name: "WEZTERM_USER", value: "m" }))
10:03:19.322  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(ITermProprietary(SetUserVar { name: "WEZTERM_IN_TMUX", value: "0" }))
10:03:19.327  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(ITermProprietary(SetUserVar { name: "WEZTERM_HOST", value: "carch" }))
10:03:19.332  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(CurrentWorkingDirectory("file://carch/home/m/"))
10:03:19.332  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(StringTerminator))
10:03:19.332  DEBUG  wezterm_gui::termwindow                > OpenGL initialized! OpenGL: Mesa Intel(R) HD Graphics 630 (KBL GT2) 4.6 (Compatibility Profile) Mesa 24.0.3-arch1.2 wezterm version: 20240325-093507-e5ac32f2
10:03:19.333  DEBUG  wezterm_gui::frontend                  > workspace is default, fixup windows
10:03:19.333  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.333  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.333  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.333  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.333  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.333  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.333  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.334  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.334  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.334  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.334  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.334  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.334  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
10:03:19.335  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })

**Comment by dylantompkins** [comment] 2024-03-28 05:49
I am having the same problem. I am also using Hyprland, but I am on NixOS

**Comment by dylantompkins** [comment] 2024-03-28 05:51
this is a duplicate of #5197

**Comment by rubiin** [comment] 2024-04-06 14:39
I just switched to hyprland and wezterm seems to be broken as well. as working fine on kde wayland session though I assume kde wayland session uses xwayland

**Comment by shripadk** [comment] 2024-05-22 06:58
Broken for me as well!

**Closed** 2024-06-25 14:11 UTC
Labels: bug
