### ISSUE TITLE
Tab/window/pane not automatically closed after failed command and Ctrl-D/exit

### ISSUE THREAD

**Issue by koterpillar** [wez/wezterm#721] opened 2021-04-23 04:59 UTC
## Describe the bug

When a command exits with nonzero status and then the shell is closed with Ctrl-D, the pane stays open with "Process Completed".

## Environment (please complete the following information):

 - OS: macOS
 - Version: `wezterm 20210405-110924-a5bb5be8`
 - The active keyboard layout name: Australian English

## To Reproduce

* Open WezTerm.
* Run `false` in the shell.
* Run `exit` in the shell or press Ctrl-D.

## Configuration

Happens with default configuration.

## Expected behavior

The last command - `exit` - did not fail, so the terminal pane should be closed.

## Actual behavior

Tab is not closed, with `[Process completed]` displayed instead.

**Comment by wez** [comment] 2021-04-23 06:10
Probably related to the issue discussed and fixed in https://github.com/wez/wezterm/pull/720

**Comment by wez** [comment] 2021-04-24 05:39
I read your problem description more clearly, and what you've described is the expected behavior.
The shell will return the status of the last command if you `exit` (with no explicit status) or `CTRL-D`.

Since you explicitly ran `false` and then exited the shell in that way, the shell exits with a non-zero exit status.

The default `exit_behavior = "CloseOnCleanExit"` configuration will see that as an unsuccessful termination of the shell and thus hold the pane open.

If you prefer, you can set `exit_behavior = "Close"` to have wezterm ignore the exit status and immediately close the pane.

More info here in the docs: https://wezfurlong.org/wezterm/config/lua/config/exit_behavior.html

**Comment by koterpillar** [comment] 2021-04-24 10:59
What is the expected behavior of "close on clean exit" versus just "close"? That is, what is a _useful_ situation where "close" would have closed the window, but "close on clean exit" keeps it open?

Here is my idea of how it should work:

* `exec long_running_process` when the process succeeds - the window is closed.
* `exec long_running_process` when the process fails - the window stays open.
* `exit` or Ctrl-D - the window is closed.

However, I just read [`man 1p exit`](https://man7.org/linux/man-pages/man1/exit.1p.html) and it says:

> The exit status [if argument to exit is not specified] shall be the value shall be the exit value of the last command executed.

So while I see `exit` as explicit user request to be done with this shell (and therefore close the tab) - it would be hard to tell `false; exit` from `exec false` on a terminal level, feel free to close.

**Comment by wez** [comment] 2021-04-24 16:45
Yep, that's exactly it.  It's a bit frustrating that interactive shells preserve that last command status for `exit`/EOF.  I wonder if there might be a shell option for that, but regardless: this isn't something that the terminal can guess and get right, and we do provide the `exit_behavior` option for you to have some control over this imperfect situation.

**Closed by wez** 2021-04-24 16:45 UTC
Labels: bug
