### ISSUE TITLE
Resizing window displays wrong background color for areas without cells

### ISSUE THREAD

**Issue by JeanMertz** [wez/wezterm#589] opened 2021-03-30 08:40 UTC
On macOS, when resizing the terminal window using the mouse, the background colour of cells at the edges of the screen aren't rendered as expected when a cell isn't fully in-view yet.

I assume this has something to do with cells not rendering until they are fully in-view, and instead the default window background is shown in those locations, but I can't be sure.

https://user-images.githubusercontent.com/383250/112959785-14574780-9144-11eb-850e-acb667e6619f.mov

 - OS: macOS
 - Version: wezterm 20210314-114017-04b7cedd-116-g1af47804

**Comment by wez** [comment] 2021-04-03 03:07
I thought this might be related to #605, but this appears to be different somehow.  I cannot reproduce this particular issue.  What's interesting is that that wezterm has code that fills the entire window with the background color, which is black.

That grey color looks like the default NSWindow fill, but for that to show it would mean that either the view isn't being sized to the window contents (which "can't" be happening, because it is always sized to the window size), or that the background color is somehow transparent.

I think there's something environmental that hasn't been captured in your report; could you share the config that's being used?  And please also share which version of macOS is in use.

You may wish to try the nightly once https://github.com/wez/wezterm/commit/5509c0af69c16ed98e799c983ed9634b01548a43 is built out (when you see a green checkmark next to the title of the commit, the nightly build contains that commit) just to see if it was somehow related to that issue.

**Comment by wez** [comment] 2021-04-16 02:08
Closing in favor of https://github.com/wez/wezterm/issues/653

**Closed by wez** 2021-04-16 02:08 UTC
Labels: bug
