### ISSUE TITLE
Totally mangled output

### ISSUE THREAD

**Issue by DavSanchez** [wez/wezterm#6134] opened 2024-09-14 04:00 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

Amethyst

### WezTerm version

wezterm 20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Wezterm started showing blots of color where characters should be, even in the tab titles (in b/w):

![image](https://github.com/user-attachments/assets/fa432561-0f1e-4782-a87b-f51ab2e98a4f)

Note the tab windows above.

For comparison, this is what should be output, from another terminal:

![image](https://github.com/user-attachments/assets/f28e2e07-1ab2-4663-8c3f-0d08d8d8825f)

### Configuration

This is the whole config, haven't touched it in months but this started happening today.

```lua
-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm';

return {
  font_size = 14,
  window_background_opacity = 0.8,
  hide_tab_bar_if_only_one_tab = true,
  color_scheme = 'Catppuccin Mocha',
  -- term = "wezterm",
  -- font = wezterm.font 'JetBrainsMono Nerd Font',
  window_decorations = "RESIZE",
}
```

### Expected Behavior

Should show the terminal window as normal.

### Logs

Tried to enable it but given the fonts seem borked I don't see anything. Logs in `$HOME/.local/share/wezterm` do not show any significant thing I'd say, but I'll copy the latest:

```log
04:40:34.828  WARN   wezterm_client::client > While connecting to Socket("/Users/david/.local/share/wezterm/sock"): connecting to /Users/david/.local/share/wezterm/sock.  Will try spawning the server.
04:40:34.829  WARN   wezterm_client::client > Running: "/nix/store/0lfmgd8ci4kkafhw2qkp11ygxyr9kil2-wezterm-20240203-110809-5046fc22/bin/wezterm-mux-server" "--daemonize"
04:42:50.826  INFO   wezterm_gui::termwindow > QuitApplication over here (window)
04:42:54.678  INFO   wezterm_gui::termwindow > QuitApplication over here (window)
```

### Anything else?

Not sure what could have changed in my environment to cause this. Perhaps there was a font change at some point but I don't even have a font configured in Wezterm 🤷‍♂️. Any way to troubleshoot this?

**Comment by bew** [comment] 2024-09-14 05:56
AFAIK this is due to some miscommunication with the GPU.
Can you share the start of logs?

**Comment by wez** [comment] 2024-09-15 13:12
Sounds like a texture issue with the GPU. What hardware are you running on?
Try varying the https://wezfurlong.org/wezterm/config/lua/config/front_end.html

**Comment by DavSanchez** [comment] 2024-09-15 15:20
Hi! Sorry for the delay.

For the start of logs I assume you mean when starting `wezterm` from another terminal, as the logs I shared earlier correspond to an entire file already.

When running the command `wezterm` from another terminal, I get the following message:

```console
$ wezterm
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
```

As for the hardware I'm running, this is a MacBook Pro M1 Max. I'll try modifying the front-end to see what I get.

**Comment by wez** [comment] 2024-09-15 15:38
Possibly a duplicate of or related to https://github.com/wez/wezterm/issues/6005

**Comment by DavSanchez** [comment] 2024-09-15 16:02
Indeed I installed Western through Nixpkgs (Home Manager), so seems to be the same issue.

**Comment by wez** [comment] 2024-09-15 16:04
Duplicate of #6005

**Closed by wez** 2024-09-15 16:04 UTC
Labels: bug
