### ISSUE TITLE
multiplexer: hyperlinks don't work for wrapped lines

### ISSUE THREAD

**Issue by suo** [wez/wezterm#3987] opened 2023-07-14 05:53 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230712-141508-4924fd51

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Multi-line implicit hyperlinks do not work (only the part of the URL on the first line is treated as a link). This was reported in https://github.com/wez/wezterm/issues/408 and it looks like a fix was made (closing the issue) but then backed out. Unfortunately, that issue is locked and I can't reopen it, so I'm making a duplicate.

### Configuration

no config

**Comment by wez** [comment] 2023-07-14 14:48
Please provide more information on how to trigger this; pointing to a closed issue from 2 years ago doesn't help me reproduce what you are seeing today.

**Comment by suo** [comment] 2023-07-14 19:07
Sure, sorry about that. If I have a link that is wrapped by the terminal to be on multiple lines, e.g.
```
url="https://console.developers.google.com/apis/api/phot
oslibrary.html"
```

Then only the first line (`https://console.developers.google.com/apis/api/phot`) will be treated as hyperlink. Ideally, the terminal would know that the full URL spans across multiple lines and clicking will go to the full URL (`https://console.developers.google.com/apis/api/photoslibrary.html`)

**Comment by wez** [comment] 2023-07-14 19:40
It works for me when the terminal wraps it; see the underline in the screenshot here; that's from hovering over the link:

![image](https://github.com/wez/wezterm/assets/117777/73f59cb3-f4cd-4fbb-9244-537c1f8715be)

if you output two separate lines then we won't match it; hyperlink rules are applied to individual logical (pre-wrapped) lines only.

The logical line aspect was what was fixed in #408; prior to that we only considered the post-wrapped physical lines.

**Comment by suo** [comment] 2023-07-14 22:30
Ah, it seems that things only don't work if you are using the multiplexing feature:
<img width="534" alt="image" src="https://github.com/wez/wezterm/assets/1617424/f867316a-9eb8-49d4-a1ee-ca53f3021436">

When I open a regular terminal window, the multi-line behavior matches yours.

**Comment by wez** [comment] 2023-07-16 22:09
Duplicate of https://github.com/wez/wezterm/issues/3459

**Closed by wez** 2023-07-16 22:09 UTC
Labels: bug, multiplexer
