### ISSUE TITLE
is windows acrylic background effect possible?

### ISSUE THREAD

**Issue by kunchenguid** [wez/wezterm#2478] opened 2022-09-03 07:53 UTC
**Is your feature request related to a problem? Please describe.**
On windows, is it possible to configure wezterm such that it would make the background support the acrylic blur effect?

(not the most beautiful screenshot in the world but just to illustrate "acrylic blur")
![image](https://user-images.githubusercontent.com/3233006/188261524-0c774715-4070-4a8b-aa7b-76fbd549091e.png)

**Describe the solution you'd like**
Have a configuration property available to turn on acrylic effect. 

**Describe alternatives you've considered**
Currently I do know we can set opacity. So the effect could also be supported by having a "blur" config that takes a 0-1 float number?

**Comment by wez** [comment] 2022-09-03 16:20
Duplicate of https://github.com/wez/wezterm/issues/1614

**Closed by wez** 2022-09-03 16:20 UTC
Labels: enhancement
