### ISSUE TITLE
Copying using OSC 52 is Broken

### ISSUE THREAD

**Issue by elcurious** [wez/wezterm#3848] opened 2023-06-11 08:32 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Gnome Mutter

### WezTerm version

wezterm 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Text is not properly copied into the system clipboard using OSC 52. Specifically, the first copy using OSC 52 succeeds and adds the text to the clipboard, but then subsequent copies do not actually add the copied text into the clipboard. Instead, the clipboard still contains the text from the first copy.

Interestingly, if we add a large delay (~30 seconds) between copies, then the second copy succeeds. This suggests that some buffer might not be getting flushed properly. 

### To Reproduce

1- Run `date -u ; printf '\e]52;c;%s\a' $(base64 <<<"$(date -u)")`
2- Paste using `ctrl+shift+v`.
3- Observe that the correct date is pasted.
4- Discard the pasted text using `ctrl + c`.
5- Repeat steps 1 and 2.
6- Observe that the old date from the first copy is pasted.

![image](https://github.com/wez/wezterm/assets/136172567/e273f846-842b-4465-82f4-4684e847f9f0)

### Configuration

No config.

### Expected Behavior

A new copy to system clipboard overwrites the old clipboard content.

### Logs

```
Debug Overlay
wezterm version: 20230408-112425-69ae8472 x86_64-unknown-linux-gnu
Window Environment: Wayland
OpenGL version: virgl (Mesa Intel(R) UHD Graphics (CML GT2)) 4.3 (Compatibility Profile) Mesa 23.1.2
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
```

**Comment by pescobar** [comment] 2023-06-30 14:05
I am also experiencing a similar issue.

I always work in tmux session in remote machines with the tmux copy-paste mode enabled and from time to time osc52 copy stops working and it doesn't work again until I close/reopen wezterm

```
Debug Overlay
wezterm version: 20230408-112425-69ae8472 x86_64-unknown-linux-gnu
Window Environment: X11 Mutter (Muffin)
OpenGL version: Mesa Intel(R) Iris(R) Pro Graphics 6200 (BDW GT3) 4.6 (Compatibility Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
Enter lua statements or expressions and hit Enter.
```

**Comment by wez** [comment] 2023-07-09 22:36
Likely a duplicate of this Wayland specific issue:
* https://github.com/wez/wezterm/issues/3843

which was fixed in main the other day by:
* https://github.com/wez/wezterm/pull/3929

Please try the latest nightly build to confirm!

@pescobar please file a separate issue; you are using X11 while the OP is running Wayland, which is different enough to track separately.

**Comment by pescobar** [comment] 2023-07-11 09:14
@wez I am using the stable release and, while creating a new issue, I have noticed you suggest to first try the latest nightly build so I am going to upgrade to latest nightly first and I will create the issue if the issue happens again.

Thanks for you work on this great software.

**Comment by elcurious** [comment] 2023-07-15 19:14
I tested this using the [20230712-072601-f4abf8fd release](https://github.com/wez/wezterm/releases/tag/20230712-072601-f4abf8fd), and the problem doesn't occur anymore.

Thank you!

**Closed** 2023-07-15 19:15 UTC
Labels: bug, fixed-in-nightly
