### ISSUE TITLE
Skip close confirmation when pane(s) are idle

### ISSUE THREAD

**Issue by supermarin** [wez/wezterm#562] opened 2021-03-20 17:56 UTC
## Describe the bug

"Really kill this tab and all contained panes?" appears on every tab close, even though if there's nothing active in the tab.
A better UX would be to match some other terminals and only warn the user if $(jobs | wc -l) > 0.

## Environment (please complete the following information):

 - macos big sur
 - Version: master

## To Reproduce

Steps to reproduce the behavior.

1. Open a new tab
2. close a tab with CMD+W

## Configuration
```
local wezterm = require 'wezterm';

return {
  color_scheme = "Dracula+",
  font_size = 14.0,
  font = wezterm.font("SF Mono"),
  line_height = 1.25,
  window_padding = {
    left = 10,
    right = 10,
    top = 10,
    bottom = 10,
  },
  window_close_confirmation = "NeverPrompt",
};

```

## Screenshots
<img width="802" alt="Screen Shot 2021-03-20 at 1 56 02 PM" src="https://user-images.githubusercontent.com/627285/111880818-03f4df00-8984-11eb-9ac2-1ab9533d067e.png">

**Comment by wez** [comment] 2021-03-20 18:31
This is working as intended, but I do want to improve this.

An important thing to note is that the only thing that the terminal knows for certain about what's running in a pane is the process id that it spawned, and potentially what the process group leader process is.  And that is only for panes that are running on the local machine (eg: not via a multiplexer).

There's no way for wezterm to literally run the unix shell specific `jobs` command, partly because it isn't portable across shells and partly because it would have to inject that command into the pty input stream to do so, and then try to guess something about the output stream.

What I think is a reasonable heuristic for improving this is:

* If we can determine the process group leader, and if we can resolve the executable name of the process group leader, then:
* see if the executable name matches known shells and multiplexers (eg: `bash`, `zsh`, `fish`, `tmux`) (this would be a configurable list)
* if it does, assume that the session is "idle" and doesn't contain valuable state and that the pane can be closed without prompting

This will be prone a false positive if for example you have a backgrounded child process.  There may be a further heuristic that could be employed to guess at whether there are any child processes, but the deeper we go on this, the more operating system specific and the more chances of making an incorrect guess occur.

**Comment by wez** [comment] 2021-03-20 18:32
If you wish, you can disable the prompt on pane closing by redefining that key binding to use `confirm=false`:

https://wezfurlong.org/wezterm/config/lua/keyassignment/CloseCurrentPane.html

**Comment by supermarin** [comment] 2021-03-21 15:53
Thanks, was looking into that yesterday thinking `window_close_confirmation = "NeverPrompt",` was the right one.

**Closed** 2021-03-25 23:22 UTC
Labels: enhancement, fixed-in-nightly

**Comment by ImportTaste** [comment] 2021-06-02 04:28
@wez Will a way to skip the close confirmation be added for Windows?

**Comment by wez** [comment] 2021-06-02 04:31
@ImportTaste could you open a new enchancement issue to track that?

**Comment by marcelarie** [comment] 2022-09-02 11:16
> If you wish, you can disable the prompt on pane closing by redefining that key binding to use `confirm=false`:
> 
> [wezfurlong.org/wezterm/config/lua/keyassignment/CloseCurrentPane.html](https://wezfurlong.org/wezterm/config/lua/keyassignment/CloseCurrentPane.html)

This worked for me, thanks!!
