### ISSUE TITLE
`CTRL-X` requires two presses

### ISSUE THREAD

**Issue by barreyra** [wez/wezterm#2798] opened 2022-11-27 07:51 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221122-154621-68c754b1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The first `CTRL-X` keypress is not passed along to the terminal and I must press it twice within some short time span.

### Configuration

I've disabled the default `ActivateCopyMode` binding, but even disabling all keyboard shortcuts does not work:

```lua
return {
  disable_default_key_bindings = true,
  keys = {},
  -- more non-keyboard related stuff
}
```

### Logs

I see hitting the key combination onceonly registers the up key event:

> 08:21:08.788  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: true, handled: Handled(false) }
> 08:21:08.847  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: false, handled: Handled(false) }
> 08:21:08.847  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('x'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
> 08:21:08.847  INFO   wezterm_gui::termwindow::keyevent > send to pane UP key=Char('x') mods=CTRL

In contrast, this is the result of hitting it twice:

> 08:22:06.109  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: true, handled: Handled(false) }
> 08:22:06.150  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: false, handled: Handled(false) }
> 08:22:06.150  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('x'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
> 08:22:06.151  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('x') mods=CTRL
> 08:22:18.166  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: true, handled: Handled(false) }
> 08:22:18.166  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('x'), modifiers: CTRL, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
> 08:22:18.166  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('x') mods=CTRL
> 08:22:18.166  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{18}", Char('x') CTRL
> 08:22:18.240  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: false, handled: Handled(false) }
> 08:22:18.240  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('x'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
> 08:22:18.240  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('x') mods=CTRL
> 08:22:18.306  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: true, handled: Handled(false) }
> 08:22:18.377  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: false, handled: Handled(false) }
> 08:22:18.377  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('x'), modifiers: CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('x'), modifiers: CTRL, phys_code: Some(X), raw_code: 7, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
> 08:22:18.377  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('x') mods=CTRL

**Comment by gegoune** [comment] 2022-11-27 07:54
Duplicated #2630.

**Comment by barreyra** [comment] 2022-11-27 08:03
Setting `use_ime = false` does fix the issue for me. Since I don't strictly need IME, I'll keep it as a workaround for now.

**Comment by wez** [comment] 2022-11-28 04:19
Duplicate of #2630

**Closed by wez** 2022-11-28 04:19 UTC
Labels: bug
