### ISSUE TITLE
Sometime init windows size wrong

### ISSUE THREAD

**Issue by Kurt-Shiwz** [wez/wezterm#4285] opened 2023-09-13 10:34 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

First, the focus of my mouse is on the internal screen of my Mac. Sometimes when I open wezterm, the window opens on the Dell monitor but the size of the window is incorrect. When I exit the wezterm. app and reopen it, it opens normally on the internal screen.

### Configuration

confing:
```
    initial_rows = 40,
    initial_cols = 120,
```

**Comment by wez** [comment] 2023-09-13 16:09
Likely a duplicate of:
* https://github.com/wez/wezterm/issues/1983
* https://github.com/wez/wezterm/issues/3396
* https://github.com/wez/wezterm/issues/3575

**Comment by snobb** [comment] 2023-10-17 20:16
I've done a simple workaround of this issue by adding the code below into the conifg:
```-- maximise window on start
wezterm.on('gui-startup', function()
    local tab, pane, window = wezterm.mux.spawn_window(cmd or {})
    window:gui_window():maximize()
end)
```
Unfortunately that does not solve the window size after unlocking the screen or moving the terminal window between the screens (Mac Retina and Acer, which is bigger but with smaller resolution).

**Comment by wez** [comment] 2024-02-08 12:12
Please try the latest nightly build and let me know if this is still an issue!

**Closed** 2024-02-22 13:08 UTC
Labels: bug, macOS, waiting-on-op
