### ISSUE TITLE
feat: Allow scrolling inactive panes

### ISSUE THREAD

**Issue by davidosomething** [wez/wezterm#3398] opened 2023-03-29 13:32 UTC
**Describe the solution you'd like**

A config option to enable this behavior:
- When there are multiple panes with scrollback, using the mousewheel (or trackpad gesture) over an inactive pane should scroll the inactive pane
- possibly without activating it (maybe another option to activate_pane_on_scroll)

**Additional context**

- konsole activates the pane on scroll and begins scrolling
- iterm scrolls pane without activating

**Comment by wez** [comment] 2023-03-31 04:04
Duplicate of https://github.com/wez/wezterm/issues/3040

**Closed by wez** 2023-03-31 04:04 UTC
Labels: enhancement
