### ISSUE TITLE
Shifted keys register as unshifted on programmable keyboards

### ISSUE THREAD

**Issue by JeffDess** [wez/wezterm#4615] opened 2023-11-25 03:10 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11, Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mostly KDE Plasma (X11) and Hyprland (Wayland)

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

With ZMK keyboard over bluetooth and IME enabled, typing a key such as right parenthesis (shift + 0) read as 0. I observed that the keys are all sent with the same timestamp (modifier press, key press, key release, modifier release). I first thought if was due to IME, so I reported it to fcitx. They reproduced it and gave more insight about the issue.

### To Reproduce

In X11, with fcitx5t running, this should do it:
```
sleep 5; for((i=0;i<30;i++)); do xdotool keydown --delay 0 Shift_L keydown --delay 0 9 keyup --delay 0 Shift_L keyup --delay 0 9; done
```

The same exact same issue is happening on Wayland, but this method has not been tested to reproduce outside X11.

### Configuration

```
{
   use_ime = true 
}
```

### Expected Behavior

To quote fcitx:
> Basically I think the point would be, the xcb key event, either from X server or input method, it already carries the state mask, and that is the always correct. Use key code + key mask from x server may cause event be handled with wrong mask. The fix should be in wezterm's process_key_event_impl.

### Anything else?

For more background and details, see [fcitx5 # 893](https://github.com/fcitx/fcitx5/issues/893)

**Comment by JeffDess** [comment] 2023-11-29 04:13
Regarding this bug on Wayland, fcitx released an option that resolves the issue (in `fcitx5-git` package) . This can be acheived by opening "Wayland Input Method Frontend" in fcitx config and unchecking the option "Forward key event instead of committing text if it is not handled".

 This is a workaround for Wayland only, X11 still have the issue.

**Comment by ohle** [comment] 2024-01-23 08:22
I'm seeing the same issue using a SplitKB Kyria (no bluetooth; QMK firmware).

It very much seems like a race condition; quitting and restarting Wezterm can sometimes fix it.

**Comment by wez** [comment] 2024-01-24 01:18
Please try the latest nightly; there have been some changes with handling the modifier masks on x11 that may help here

**Comment by ohle** [comment] 2024-01-24 08:46
That doesn't seem to help either, unfortunately.

**Comment by wez** [comment] 2024-01-24 15:13
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by ohle** [comment] 2024-01-25 09:39
Using `wezterm-nightly 20240124-220416-642bfbb6` from `https://apt.fury.io/wez` I cannot reproduce the issue anymore.

Looks good, thanks!

**Comment by JeffDess** [comment] 2024-01-27 03:28
Using `wezterm 20240126-122653-178f35a4`, I cannot reproduce on X11 either. I am able reproduce on Wayland tough, fortunately the fcitx workaround is still working. Thanks a lot!

**Comment by wez** [comment] 2024-01-27 14:56
From discussion on the related ibus issue, the behavior on wayland is not something that wezterm can work around:
https://github.com/ibus/ibus/issues/2600#issuecomment-1908406340

**Comment by JeffDess** [comment] 2024-01-27 17:38
Got it, looks good to me then!

Maybe it's worth documenting the Wayland solution in the [relevant doc](https://wezfurlong.org/wezterm/config/lua/config/use_ime.html)? This bug might be niche, but a small note/hint in that page may be helpful to users having the issue?

Thanks again for your work, it is much appreciated.

**Comment by wez** [comment] 2024-01-27 20:31
There are currently many open issues for wayland; I'm not going to write them up in the docs with their various workarounds (if any) as it doesn't scale, and the docs will be cluttered with the remnants of past issues forever afterwards.

**Comment by wez** [comment] 2024-01-27 20:33
Closing this, as these changes are now in the latest release

**Closed by wez** 2024-01-27 20:33 UTC
Labels: bug, X11, Wayland, fixed-in-nightly, keyboard
