### ISSUE TITLE
cycle between pan

### ISSUE THREAD

**Issue by hemedani** [wez/wezterm#1375] opened 2021-12-07 19:02 UTC
**Is your feature request related to a problem? Please describe.**
It's very hard to determine what pane is active and how can get the right-left-top-bottom pan, even when set a key to that

**Describe the solution you'd like**
I want something like `ActivateTabRelative` for pane and get the next pane clockwise.

**Comment by wez** [comment] 2021-12-08 15:47
I think this is a duplicate of https://github.com/wez/wezterm/issues/976

**Closed by wez** 2021-12-08 15:47 UTC
Labels: enhancement
