### ISSUE TITLE
Support opening search with empty string

### ISSUE THREAD

**Issue by brandonchinn178** [wez/wezterm#3038] opened 2023-01-31 18:14 UTC
**Is your feature request related to a problem? Please describe.**
I would like CMD+F to always open an empty search bar. The default search action is `CurrentSelectionOrEmptyString`, which seems to have the behavior that it'll reuse the last search when opening the search again. The other search parameters also has this behavior, even when specifying the empty string (e.g. `Search{ CaseSensitiveString = '' }`), possibly due to this:
https://github.com/wez/wezterm/blob/0dc7d92b6ca1974fb81c1437883b75641e8cd2e8/wezterm-gui/src/termwindow/mod.rs#L2539

**Describe the solution you'd like**
Remove the `!pattern.is_empty()` check, or, to avoid a breaking change, add `Search{ CaseSensitiveString = nil }` that always opens an empty search buffer in the given mode

**Describe alternatives you've considered**

**Additional context**

**Comment by wez** [comment] 2023-01-31 20:12
Duplicate of https://github.com/wez/wezterm/issues/1988

**Closed by wez** 2023-01-31 20:12 UTC
Labels: enhancement

**Comment by brandonchinn178** [comment] 2023-01-31 20:14
... I promise I did a search this time. Not sure why I didn't find it
