### ISSUE TITLE
keep cursor height while increasing line height

### ISSUE THREAD

**Issue by effinsky** [wez/wezterm#3482] opened 2023-04-09 20:31 UTC
In Iterm2, which I'm currently using but cannot do so if I move away from MacOS, I really like how when you increase line height, you keep the same neat cursor shape. In Wezterm, however, it seems to stretch vertically. Is there a way to avoid this behavior?

For reference, the cursor at 1.0 and at 1.8 (for exaggerated effect and to make a point).
<img width="404" alt="Screenshot 2023-04-09 at 22 30 14" src="https://user-images.githubusercontent.com/54535543/230795089-730741c9-b752-431b-846c-c03223a2c97f.png">
<img width="431" alt="Screenshot 2023-04-09 at 22 30 29" src="https://user-images.githubusercontent.com/54535543/230795090-5540652a-d346-437d-94a1-153b76a90607.png">

Alacritty is the same in this regard and they claim it's their intended behavior. I find this a rather odd choice and I wonder if it's possible, or could be possible, to avoid while using WT.

**Comment by wez** [comment] 2023-04-09 20:34
It is the intended behavior.  The line height controls the height of the cell, and the cell height defines the height of the cursor.

Closing this as a duplicate of https://github.com/wez/wezterm/issues/2882

**Closed by wez** 2023-04-09 20:34 UTC
Labels: enhancement

**Comment by effinsky** [comment] 2023-04-09 21:10
ok so I'm not the only one who thinks this is weird. is it not possible to decouple the height of the cursor from cell height?
