### ISSUE TITLE
Crashes on Ubuntu when right clicking on a tab

### ISSUE THREAD

**Issue by ltearno** [wez/wezterm#602] opened 2021-04-01 04:26 UTC
To reproduce on Ubuntu 20.04 :

- launch WezTerm
- with the mouse click on the '+' to open a new tab
- right-click on the new tab, this will show the activation menu
- right-click again on the same spot (on the tab header)
- => the application crashes.

Here is the RUST_BACKTRACE=full trace :

```
2021-04-01T04:22:19.129Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-137953
 2021-04-01T04:22:19.233Z INFO  wezterm_gui::termwindow        > OpenGL initialized! GeForce GTX 1060 6GB/PCIe/SSE2 OpenGL ES 3.2 NVIDIA 460.39 is_context_loss_possible=false wezterm version: 20210314-114017-04b7cedd
thread 'main' panicked at 'already borrowed: BorrowMutError', mux/src/lib.rs:364:44
stack backtrace:
   0:     0x563b19734e70 - <unknown>
   1:     0x563b1975c3ac - <unknown>
   2:     0x563b1972b7a2 - <unknown>
   3:     0x563b197374c5 - <unknown>
   4:     0x563b1973701a - <unknown>
   5:     0x563b19737c86 - <unknown>
   6:     0x563b197377a7 - <unknown>
   7:     0x563b1973532c - <unknown>
   8:     0x563b19737709 - <unknown>
   9:     0x563b1975a051 - <unknown>
  10:     0x563b19759e73 - <unknown>
  11:     0x563b18db94d5 - <unknown>
  12:     0x563b1877214e - <unknown>
  13:     0x563b1876d649 - <unknown>
  14:     0x563b187658ca - <unknown>
  15:     0x563b19550b83 - <unknown>
  16:     0x563b19541f6b - <unknown>
  17:     0x563b19541491 - <unknown>
  18:     0x563b187b386b - <unknown>
  19:     0x563b187b08d7 - <unknown>
  20:     0x563b187d2b03 - <unknown>
  21:     0x563b187728c9 - <unknown>
  22:     0x563b19738177 - <unknown>
  23:     0x563b187b48f2 - <unknown>
  24:     0x7f1dd102c0b3 - __libc_start_main
  25:     0x563b186b516e - <unknown>
  26:                0x0 - <unknown>
```

**Comment by wez** [comment] 2021-04-01 04:29
This sounds like a duplicate of https://github.com/wez/wezterm/issues/542 which is fixed in the nightly builds; could you give the nightly a try to confirm?

**Comment by wez** [comment] 2021-04-03 03:25
(Speculatively closing as a duplicate to help make it easier for me to see what's open: if the nightly build doesn't work for you, please let me know!)

**Closed by wez** 2021-04-03 03:25 UTC
