### ISSUE TITLE
Hyperlink on files ending with .js doesnt work

### ISSUE THREAD

**Issue by dagadbm** [wez/wezterm#2917] opened 2023-01-03 16:47 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The hyperlinks dont work for every type of url.

The url on the left side wezterm correctly underlines it and I can click on it.
The url on the right side wezterm doesnt recognize it as a url.

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/16737095/210401933-d9a9c326-9bc8-4555-bf68-ebe79d758e46.png">

Im probably missing something very simple but I just cant get it to accept that url.

Shouldnt this be supported out of the box ? Kitty for example understands that this is a url

### Configuration

local wezterm = require 'wezterm'
local mux = wezterm.mux

wezterm.on('gui-startup', function(cmd)
  local tab, pane, window = mux.spawn_window(cmd or {})
  window:gui_window():maximize()
  window:gui_window():toggle_fullscreen()
end)

return {
  -- https://wezfurlong.org/wezterm/config/mouse.html
  -- http://localhost:3000/isolated/exercise/01.js
  font = wezterm.font 'JetBrainsMono Nerd Font Mono',
  font_size = 13,
  line_height = 1.2,
  color_scheme = 'OneDark (base16)',
  bypass_mouse_reporting_modifiers = 'CMD',
  enable_tab_bar = false,
  hide_tab_bar_if_only_one_tab = true,
  max_fps = 60,
  native_macos_fullscreen_mode = true,
  enable_kitty_keyboard = false,
  enable_scroll_bar = false,
  exit_behavior = 'CloseOnCleanExit',
  window_padding = {
    left = 0,
    right = 0,
    top = 0,
    bottom = 0,
  },
}

**Comment by wez** [comment] 2023-01-11 17:47
Duplicate of https://github.com/wez/wezterm/issues/928

**Closed by wez** 2023-01-11 17:47 UTC
Labels: bug
