### ISSUE TITLE
Sometimes stuck at startup

### ISSUE THREAD

**Issue by aj3423** [wez/wezterm#4926] opened 2024-02-01 10:18 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Fedora KDE Plasma 5.27.10

### WezTerm version

20240129_220340_47f647ca

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When Wezterm is being launched, there is a 10% chance that it only shows a taskbar item, no terminal window appears on the screen, as in the screenshot:

![image](https://github.com/wez/wezterm/assets/4710875/2c62e898-b7be-4f15-a158-65cfa96d298b)

I tried to right click the item and maximize it, but still no window appears, I can only right click and close it. 

I tried to launch it in different ways, using `wezterm start --always-new-process`
1. when using global hotkey: bug happens
2. when type this command in terminal: bug happens
3. when lauched from KDE's krunner: bug never happens, it's always launched successfully. 

I tried kitty and konsole, they always launch fine.

How to trace this problem?

### To Reproduce

1. open an wezterm terminal (or any other terminal like konsole or kitty)
2. type `wezterm start --always-new-process`
3. close it if it's launched successfully

Repeat step 1-3

### Configuration

return {}

### Expected Behavior

always launch success

### Logs

I cleared all previous log, and trigger the bug again, but there is no new log file generated in dir `/run/user/0/wezterm`(the $XDG_RUNTIMME_DIR/wezterm) or `~/.local/share/wezterm`
But there are lots of "gui-sock-xxx" files there:
![image](https://github.com/wez/wezterm/assets/4710875/1f8a4d50-80e8-4659-b5a8-a690af87fd6b)

**Comment by wez** [comment] 2024-02-01 15:57
is this a duplicate of:
* https://github.com/wez/wezterm/issues/3986

**Comment by aj3423** [comment] 2024-02-06 13:51
> is this a duplicate of:
> 
> * [launching wezterm in gnome sometimes don't get focused upon launch #3986](https://github.com/wez/wezterm/issues/3986)

I don't know if they are caused by same reason, but in that link, the window exists on screen, it's just not focused,  but in my case there is no Wezterm window at all.

**Comment by poperigby** [comment] 2024-02-16 19:57
I'm having the exact same issue, but I'm on version 20240212_074107_22f9f8d2.

For me, it also doesn't show the correct icon, but the default Wayland icon. Unsure if that's related.

I've gotten it to happen when launching from another terminal, and captured the output:
<details>
<summary>Debug output</summary>
<p>

```
11:47:45.025  DEBUG  config > Reloaded configuration! generation=1
11:47:45.029  DEBUG  sctk   > Bound new global [47] wl_output v4
11:47:45.029  DEBUG  sctk   > Bound new global [32] zxdg_output_manager_v1 v3
11:47:45.029  DEBUG  sctk   > Bound new global [12] wl_seat v7
11:47:45.029  DEBUG  window::os::x_and_wayland > Using wayland connection!
11:47:45.065  DEBUG  config                    > Reloaded configuration! generation=2
11:47:45.073  DEBUG  wezterm_font::ftwrap      > set_char_size computing 11 dpi=96 (pixel height=14.666666666666666)
11:47:45.076  DEBUG  sctk                      > supported wl_shm format Argb8888
11:47:45.076  DEBUG  sctk                      > supported wl_shm format Xrgb8888
11:47:45.076  DEBUG  sctk                      > supported wl_shm format Argb2101010
11:47:45.076  DEBUG  sctk                      > supported wl_shm format Xrgb2101010
11:47:45.076  DEBUG  sctk                      > supported wl_shm format Abgr2101010
11:47:45.076  DEBUG  sctk                      > supported wl_shm format Xbgr2101010
11:47:45.076  DEBUG  sctk                      > supported wl_shm format Abgr16161616
11:47:45.076  DEBUG  sctk                      > supported wl_shm format Xbgr16161616
11:47:45.076  DEBUG  wezterm_gui::frontend     > workspace is default, fixup windows
11:47:45.078  DEBUG  wezterm_font::ftwrap      > set_char_size computing 11 dpi=96 (pixel height=14.666666666666666)
11:47:45.082  DEBUG  wezterm_font::ftwrap      > set_char_size computing 12 dpi=96 (pixel height=16)
11:47:45.089  DEBUG  window::os::wayland::window > Config: self.window_state=None, states: (empty) (empty)
11:47:45.090  DEBUG  window::os::wayland::window > dispatch_pending_event self.window_state=(empty), pending:(empty)
11:47:45.090  DEBUG  window::os::wayland::window > Had configured an event
11:47:45.121  DEBUG  wezterm_gui::termwindow     > OpenGL initialized! OpenGL: Mesa Intel(R) Xe Graphics (TGL GT2) 4.6 (Compatibility Profile) Mesa 23.3.5 wezterm version: 20240212_074107_22f9f8d2
11:47:45.121  DEBUG  wezterm_gui::frontend       > workspace is default, fixup windows
11:47:45.122  DEBUG  wezterm_gui::termwindow     > NeedRepaint
11:47:45.122  DEBUG  wezterm_font::shaper::harfbuzz > cluster_resolver: ClusterResolver {
    map: {
        0: ClusterInfo {
            start: 0,
            byte_len: 1,
            cell_width: 1,
            incomplete: false,
        },
    },
    presentation_width: None,
    start_by_cell_idx: {},
}
11:47:45.122  DEBUG  wezterm_font::shaper::harfbuzz > hb info.cluster 0 -> Info { cluster: 0, len: 1, codepoint: 4, x_advance: 256, y_advance: 0, x_offset: 0, y_offset: 0 }
11:47:45.122  DEBUG  wezterm_font::shaper::harfbuzz > font_idx=0 info_clusters: [
    [
        Info {
            cluster: 0,
            len: 1,
            codepoint: 4,
            x_advance: 256,
            y_advance: 0,
            x_offset: 0,
            y_offset: 0,
        },
    ],
]
11:47:45.122  DEBUG  wezterm_font::ftwrap           > set_char_size computing 12 dpi=96 (pixel height=16)
11:47:45.123  DEBUG  wezterm_gui::termwindow::render::paint > paint_impl before call_draw elapsed=1.193418ms
11:47:45.123  DEBUG  wezterm_gui::termwindow::render::paint > paint_impl elapsed=1.353223ms, fps=0
11:47:45.124  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.124  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.124  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.125  DEBUG  wezterm_gui::termwindow                > FocusChanged(true)
11:47:45.125  DEBUG  window::os::wayland::window            > Config: self.window_state=None, states: (empty) ACTIVATED
11:47:45.125  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.125  DEBUG  window::os::wayland::window            > dispatch_pending_event self.window_state=(empty), pending:(empty)
11:47:45.125  DEBUG  wezterm_gui::termwindow                > Resized { dimensions: Dimensions { pixel_width: 1440, pixel_height: 1026, dpi: 192 }, window_state: (empty), live_resizing: false }
11:47:45.128  DEBUG  wezterm_font::ftwrap                   > set_char_size computing 11 dpi=192 (pixel height=29.333333333333332)
11:47:45.133  DEBUG  wezterm_font::ftwrap                   > set_char_size computing 12 dpi=192 (pixel height=32)
11:47:45.133  DEBUG  wezterm_term::screen                   > resize screen to 80x24 dpi=192
11:47:45.133  DEBUG  wezterm_term::screen                   > resize screen to 80x24 dpi=192
11:47:45.133  DEBUG  window::os::wayland::window            > Had configured an event
11:47:45.133  DEBUG  wezterm_gui::termwindow                > AdviseDeadKeyStatus(None)
11:47:45.133  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.133  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.133  DEBUG  wezterm_gui::termwindow                > Resized { dimensions: Dimensions { pixel_width: 1360, pixel_height: 1002, dpi: 192 }, window_state: (empty), live_resizing: false }
11:47:45.133  DEBUG  wezterm_gui::termwindow                > SetInnerSizeCompleted
11:47:45.133  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.133  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.133  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.133  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.134  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.134  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.134  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.134  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.135  DEBUG  wezterm_gui::termwindow                > FocusChanged(false)
11:47:45.135  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.135  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.135  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.135  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.137  DEBUG  window::os::wayland::window            > Config: self.window_state=None, states: (empty) (empty)
11:47:45.137  DEBUG  wezterm_gui::termwindow                > AdviseDeadKeyStatus(None)
11:47:45.137  DEBUG  window::os::wayland::window            > dispatch_pending_event self.window_state=(empty), pending:(empty)
11:47:45.137  DEBUG  window::os::wayland::window            > Had configured an event
11:47:45.137  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.137  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.137  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.159  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Mode(SetDecPrivateMode(Code(BracketedPaste))))
11:47:45.159  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(CurrentWorkingDirectory("file://allan/var/home/cassidy"))
11:47:45.159  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.159  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.160  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.160  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.160  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.160  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.160  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.160  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.160  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.198  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(SetIconNameAndWindowTitle("/v/h/cassidy"))
11:47:45.198  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(0))))
11:47:45.198  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(0))
11:47:45.198  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.198  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.198  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.198  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.198  DEBUG  wezterm_term::terminalstate::performer > perform Control(CarriageReturn)
11:47:45.198  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.198  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.198  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.199  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.199  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.199  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.199  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.199  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.199  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.199  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.237  DEBUG  wezterm_term::terminalstate::performer > perform OperatingSystemCommand(SetIconNameAndWindowTitle("/v/h/cassidy"))
11:47:45.237  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(0))))
11:47:45.237  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(0))
11:47:45.237  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.238  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.237  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.238  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.238  DEBUG  wezterm_term::terminalstate::performer > perform Control(CarriageReturn)
11:47:45.238  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.238  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.239  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.239  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.239  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.239  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.239  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.239  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.239  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.239  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.239  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.239  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.239  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.239  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(6))))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(6))
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform PrintString("/var/home/")
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Intensity(Bold)))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Intensity(Bold)
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(14))))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(14))
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform PrintString("cassidy")
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.240  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(6))))
11:47:45.240  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(6))
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Foreground(PaletteIndex(10))))
11:47:45.241  DEBUG  wezterm_term::terminalstate            > Foreground(PaletteIndex(10))
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform PrintString(" ❯")
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.241  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.241  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.241  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform Esc(Code(AsciiCharacterSetG0))
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Sgr(Reset))
11:47:45.241  DEBUG  wezterm_term::terminalstate            > Reset
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform Print(' ')
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Edit(EraseInLine(EraseToEndOfLine)))
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform Control(CarriageReturn)
11:47:45.241  DEBUG  wezterm_term::terminalstate::performer > perform CSI(Cursor(Right(20)))
11:47:45.241  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.241  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.241  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.241  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.241  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.241  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.241  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:45.241  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:46.125  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:46.125  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })
11:47:46.125  DEBUG  wezterm_gui::termwindow                > Notification(Any { .. })

```
</p>
</details>

System information:

- Operating System: Fedora Linux 39
- KDE Plasma Version: 5.27.10
- KDE Frameworks Version: 5.113.0
- Qt Version: 5.15.12
- Kernel Version: 6.7.4-200.fc39.x86_64 (64-bit)
- Graphics Platform: Wayland
- Processors: 8 × 11th Gen Intel® Core™ i5-1135G7 @ 2.40GHz
- Memory: 15.4 GiB of RAM
- Graphics Processor: Mesa Intel® Xe Graphics
- Manufacturer: Framework
- Product Name: Laptop
- System Version: A3

Video of the issue: 

https://github.com/wez/wezterm/assets/20866468/c3232062-f253-4e21-a53f-630106b37c10

**Comment by aj3423** [comment] 2024-02-16 20:15
I run `dnf update` every day, I noticed it didn't happen in the last 3 days, and I can't reproduce it anymore.
@poperigby Maybe try update both system and Wezterm?

**Comment by poperigby** [comment] 2024-02-16 22:09
My system is fully up-to-date, and it's still happening :neutral_face:.

**Comment by poperigby** [comment] 2024-02-16 22:45
It doesn't happen on my desktop, which is using the same version on the same OS.

**Comment by lokesh-krishna** [comment] 2024-03-20 03:54
I'm on Arch with Hyprland 0.37. Didn't have this issue on 0.35 but since updating to 0.37, WezTerm won't launch and setting `enable_wayland = false` fixes it.

**Comment by aj3423** [comment] 2024-03-21 12:01
This hasn't happened for a month, seems fixed

**Closed** 2024-03-21 12:01 UTC
Labels: bug, Wayland
