### ISSUE TITLE
Error `Failed to create window: The OpenGL implementation is too old to work with glium` on Windows 11 in VirtualBox

### ISSUE THREAD

**Issue by sheepla** [wez/wezterm#1813] opened 2022-04-03 06:20 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20220319-142410-0fcdea07

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I typed `wezterm.exe` on Windows 11 (Ver: `21H2`, OS Build: `22000.593`) but couldn't start with the following error:

`Failed to create window: The OpenGL implementation is too old to work with glium`

### Configuration

no config

### Logs

`set WEZTERM_LOG=window=trace,info` then run `wezterm.exe`

```
 2022-04-03T05:58:55.414Z INFO  wezterm_mux_server_impl::local > setting up C:\Users\User\.local/share/wezterm\gui-sock-1216
 2022-04-03T05:58:55.418Z INFO  wezterm_client::discovery::windows > published gui path as gui-sock-1216
 2022-04-03T05:58:55.555Z TRACE window                             > FocusChanged(true)
 2022-04-03T05:58:55.558Z TRACE window::os::windows::window        > WindowOps::invalidate calling InvalidateRect
 2022-04-03T05:58:55.559Z WARN  window::os::windows::window        > EGL init failed Config says to avoid EGL, fall back to WGL
 2022-04-03T05:58:55.562Z TRACE window::os::windows::wgl           > loaded Library@0x7ffad1b10000 from "C:\\Windows\\SYSTEM32\\opengl32.dll"
 2022-04-03T05:58:55.676Z TRACE window::os::windows::wgl           > opengl extensions: ""
 2022-04-03T05:58:55.678Z TRACE window::os::windows::wgl           > dropping WglWrapper and libloading Library@0x7ffad1b10000 from "C:\\Windows\\SYSTEM32\\opengl32.dll"
 2022-04-03T05:58:55.742Z ERROR wezterm_gui::frontend              > Failed to create window: The OpenGL implementation is too old to work with glium
```

**Comment by wez** [comment] 2022-04-03 12:44
Strange!  Can you try setting `prefer_egl = true` in your config?  (or alternatively, run: `wezterm.exe --config "prefer_egl=true"`)

**Comment by sheepla** [comment] 2022-04-04 10:35
Successfully launched!

```
wezterm.exe --config "prefer_egl=true"
 2022-04-04T10:31:20.022Z INFO  wezterm_mux_server_impl::local > setting up C:\Users\User\.local/share/wezterm\gui-sock-3664
 2022-04-04T10:31:20.169Z INFO  wezterm_gui::termwindow        > OpenGL initialized! ANGLE (Microsoft Basic Render Driver Direct3D11 vs_5_0 ps_5_0) OpenGL ES 3.0.0 (ANGLE 2.1.1 git hash: 07ea804e6201) is_context_loss_possible=true wezterm version: 20220319-142410-0fcdea07
```

![image](https://user-images.githubusercontent.com/62412884/161526306-bf070dba-668f-42e6-912a-26af6b6d3557.png)

**Comment by wez** [comment] 2022-04-04 14:11
I've pushed commits to update to a newer version of glium and to try to get it to include more information about what it didn't like when it tries to start up.

It will take about an hour before that change is available in the nightly build; would you mind trying that version with `prefer_egl=false` to see if it starts successfully?  If not, please include the error message that you see this time.

Could you also share some information about the graphics hardware and drivers that are present in that system?

**Comment by sheepla** [comment] 2022-04-05 11:33
I tried the nightly version in with ` prefer_egl=false`, but I encountered the same error and couldn't start it.
If `prefer_egl=true`, it can be started as well.


```
wezterm.exe --version
wezterm 20220404-203930-526cc26b
```

```
wezterm.exe --config "prefer_egl=false"
 2022-04-05T11:02:54.683Z INFO  wezterm_mux_server_impl::local > setting up C:\Users\User\.local/share/wezterm\gui-sock-3772
 2022-04-05T11:02:54.766Z WARN  window::os::windows::window    > EGL init failed Config says to avoid EGL, fall back to WGL
 2022-04-05T11:02:54.832Z ERROR wezterm_gui::frontend          > Failed to create window: The OpenGL implementation is too old to work with glium (The OpenGL implementation is too old to work with glium)
```

I'm running Windows on Virtualbox maybe it's related...
What specific information do you need to investigate a bug? I will provide it.

**Comment by wez** [comment] 2022-04-05 14:06
> I'm running Windows on Virtualbox maybe it's related...
> What specific information do you need to investigate a bug? I will provide it.

Ah, that's the useful information.  VirtualBox's opengl implementation is too old to run wezterm, so the recommended solution would be to set `prefer_egl=true`; that causes it to use the bundled ANGLE EGL implementation, which uses Direct3D instead of OpenGL.

**Comment by sheepla** [comment] 2022-04-05 21:14
Oh, I understand, I didn't know Virtualbox's OpenGL implementation was too old. I should have told them that at the beginning. Thank you very much.
I will set `prefer_egl=true` and use it more.

**Comment by wez** [comment] 2022-04-06 04:16
Since this is expected behavior, I'm closing this issue!

**Closed by wez** 2022-04-06 04:16 UTC
Labels: bug
