### ISSUE TITLE
Can't find default configuration

### ISSUE THREAD

**Issue by hornyjailfish** [wez/wezterm#2065] opened 2022-06-02 10:22 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

there are no `werterm.lua` neither in `$HOME` `$HOME/.config/wezterm/` `%WEZTERM_EXECUTABLE_DIR%` `$WEZTERM_CONFIG_FILE`
just cant find it

### Configuration

there is it?

### Expected Behavior

default configuration must be in a file to observe and edit

**Comment by wez** [comment] 2022-06-02 12:44
Duplicate of https://github.com/wez/wezterm/issues/548

**Closed by wez** 2022-06-02 12:44 UTC
Labels: bug
