### ISSUE TITLE
After a short usage period, text selection and scrollable output are unavailable on mouse input

### ISSUE THREAD

**Issue by M0Rf30** [wez/wezterm#3513] opened 2023-04-13 08:57 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

**Compositor**: mutter on GNOME 44
**OS**: Arch Linux

### WezTerm version

20230411-221643-c8b8e811

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After a short usage period, text selection and scrollable output are unavailable.
If I close and restart wezterm, everything goes fine

### To Reproduce

Fire up wezterm
Do some tasks
After a while (some seconds) I can't select text / I can't scroll the terminal lines up and/or down with mouse cursor

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

config.tab_bar_at_bottom = true

-- For example, changing the color scheme:
config.color_scheme = 'Chalk'
config.font = wezterm.font 'JetBrains Mono NL Light'
config.font_size = 16

-- status
config.status_update_interval = 1000

-- tab bar
config.enable_tab_bar = true
config.hide_tab_bar_if_only_one_tab = false
config.hide_mouse_cursor_when_typing = false
config.use_fancy_tab_bar = true
config.tab_max_width = 25
config.show_tab_index_in_tab_bar = false
config.switch_to_last_active_tab_when_closing_tab = true

-- window
config.window_padding = {
      left = 1,
      right = 1,
      top = 1,
      bottom = 1
}

config.automatically_reload_config = true

-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

I should be able to select text and scroll up and down with mouse cursor

**Comment by wez** [comment] 2023-04-16 14:21
Are you saying that mouse input stops working but keyboard input still works, or that no input works at all?

**Comment by M0Rf30** [comment] 2023-04-16 15:56
Mouse input stops to works, but seems that with latest commits (wezterm 20230415-235902-6ec11393), doesn't happen anymore. I would like to give you more details, tell me if I can be helpful from this point of view

**Comment by wez** [comment] 2023-04-16 16:07
I'm assuming that this was the same root cause as https://github.com/wez/wezterm/issues/3126
I'm going to close this out since it sounds like it is working for you now!

**Closed by wez** 2023-04-16 16:07 UTC
Labels: bug, Wayland
