### ISSUE TITLE
passthrough does not work with disabledefaultassignment

### ISSUE THREAD

**Issue by hboetes** [wez/wezterm#3845] opened 2023-06-10 14:19 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

sway

### WezTerm version

20230530-062729-95e44f21

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Using `undo` in emacs , which is bound to ctrl+shift+- (ctrl-_) and wezterm does not work after unsetting the key binding.

The docs suggest that setting `DisableDefaultAssignment` will pass through the key binding to the application running in the terminal:

> DisableDefaultAssignment
> Has no special meaning of its own; this action will undo the registration of a default assignment if that key/mouse/modifier combination is one of the default assignments and cause the key press to be propagated through to the tab for processing.

For double checks, the key bind is really gone. 
```
%  wezterm show-keys --lua |grep 'Decrease'
    { key = '-', mods = 'CTRL', action = act.DecreaseFontSize },
    { key = '-', mods = 'SUPER', action = act.DecreaseFontSize },
```

But I can't `undo` in Emacs. What am I missing here?

### Configuration

```lua
[snip] 
  {
      key = '-',
      mods = 'SHIFT|CTRL',
      action = wezterm.action.DisableDefaultAssignment,
   },
   {
      key = '_',
      mods = 'SHIFT|CTRL',
      action = wezterm.action.DisableDefaultAssignment,
   },
   {
      key = '_',
      mods = 'CTRL',
      action = wezterm.action.DisableDefaultAssignment,
   },
[snip]
```

### Logs

```
Debug Overlay
wezterm version: 20230530-062729-95e44f21 x86_64-unknown-linux-gnu
Window Environment: Wayland
WebGPU: name=AMD Radeon Graphics (RADV RENOIR), device_type=IntegratedGpu, backend=Vulkan, driver=radv, driver_info=Mesa 23.1.1, vendor=4098, device=5688
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
16:19:14.344 ERROR wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)
>
```

**Comment by wez** [comment] 2023-07-10 16:10
Potentially a duplicate of #3610 
Please try the latest nightly to see if this is now working.

**Closed** 2023-07-24 17:07 UTC
Labels: bug, waiting-on-op
