### ISSUE TITLE
OSC 52 does not work on the first opened tab

### ISSUE THREAD

**Issue by ikey4u** [wez/wezterm#1662] opened 2022-02-24 08:03 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220218-071628-85a8434e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The wezterm I used is built from source, and the commit (85a8434ecb646556ced7d53dd18bebcdb9c9db3b) is the HEAD when I file this issue. 

OSC 52 copy does not work on the first opened tab, but if you open another tab, it does work.

### To Reproduce

1. Using ` cargo run  --bin wezterm -- start ` to start wezterm
2. When wezterm is started, in the initialized tab, copy the OSC 52 command ([source](https://github.com/wez/wezterm/issues/764)) below and run.
```
printf '\033]52;c;%s\a' Ki5zcWwKKi50YWdzKgoqLmdlbXRhZ3MqCioudG1wKgoqLm1pbi5qcwoqLm1pbi5jc3MKKi5wbGlzdAoqLnBkZgoqLmEKY29tcGlsZV9jb21tYW5kcy5qc29uCnRhZ3MK
```
The output is not copied to the clipboard.
3. Click the `+` icon in the tab bar to create the second tab window, and run the above OSC 52 command again. The output is copied to the clipboard.

### Configuration

`$ cat ~/.config/wezterm/wezterm.lua`

```
local wezterm = require 'wezterm';
return {
    font = wezterm.font("MesloLGS NF" , { weight="Bold" }),
    font_size = 14.0,
    color_scheme = "Dracula",
    use_ime = true,
}
```

### Expected Behavior

OSC 52 works in the initialized tab window.

**Comment by seqizz** [comment] 2022-03-16 18:50
I was thinking why it stopped working lately, didn't even think to test it on a new tab :grimacing:

**Comment by wez** [comment] 2022-03-29 01:52
I can't reproduce this on macOS with `20220319-142410-0fcdea07`; is this still an issue for you in the most recent release?

**Comment by seqizz** [comment] 2022-03-29 05:53
I'm on commit a0b8d2196a260726eca28b32fecaeb87420851ec, which looks recent-ish. I'll report back with latest one.

**Comment by seqizz** [comment] 2022-03-29 20:34
I tried with no configuration and still had the same result. Also ran with `WEZTERM_LOG=trace`, and while getting the similar line:

```
DEBUG wezterm_term::terminalstate::performer > perform OperatingSystemCommand(SetSelection(CLIPBOARD, "*.sql\n*.tags*\n*.gemtags*\n*.tmp*\n*.min.js\n*.min.css\n*.plist\n*.pdf\n*.a\ncompile_commands.json\ntags\n"))
```
on both trials, the first-tab one didn't actually put anything to clipboard. Not sure how to continue :thinking:

**Comment by ikey4u** [comment] 2022-03-30 02:18
I've tried with the latest build (20220319-142410-0fcdea07), this problem seems disappeared (tested with macOS Monterey). However, I am not sure whether it is fully solved, it may does not work, occasionally (just like what is described in issue #1790 ).  I am using wezterm in my daily work, and will come back to report

**Comment by seqizz** [comment] 2022-03-30 09:54
Saw 1a71a0b21616467509a762425a522d822c23f7e7 which should increase the logging :eyes: 

I've switched to 6015957cd2b8e29816ba4475c80733a5f52001dc and tried, indeed now it works without issues. So, thanks :smile: 

> It only fails if the configuration file has an error (e.g. a literal empty file which can't be parsed) but I am not sure why + I don't think that's a valid bug case.

**Comment by seqizz** [comment] 2022-03-30 20:37
Tried again, it says:
```
2022-03-30T20:35:46.638Z ERROR wezterm_term::terminalstate::performer > failed to set clipboard in response to OSC 52: Error {
    context: "RemoteClipboard::set_contents send failed",
    source: "Closed(..)",
}
```

**Comment by wez** [comment] 2022-03-31 14:54
I'm going to close this: I think it was a slightly different issue that has subsequently been resolved.
However, https://github.com/wez/wezterm/issues/1790 is open for another OSC 52 issue.

**Closed by wez** 2022-03-31 14:54 UTC
Labels: bug
