### ISSUE TITLE
Space key doesn't work after update (RU layout)

### ISSUE THREAD

**Issue by welqd** [wez/wezterm#4910] opened 2024-01-30 18:37 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3-wm (4.23)
ArchLinux (6.7.2-arch1-1)

### WezTerm version

wezterm 20240128-202157-1e552d76

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I have two layouts configured  (setxkbmap -layout us,ru -option 'grp:win_space_toggle') after changing layout to RU the space key stops working. 
When layout changes back to US - the space key is working as usual.
But, if I have only RU layout - the space key is working too.

Version 20230712-072601-f4abf8fd didn't have this issue.

### To Reproduce

1. Set layout: **setxkbmap -layout us,ru -option 'grp:win_space_toggle'**  
2. Press mod+space to change layout to RU
3. Try to press Space inside terminal

### Configuration

no config

### Expected Behavior

The Space key does its thing

### US layout (with 2 layouts configured)
20:55:34.276  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char(' '), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }

20:55:34.276  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char(' ') mods=NONE

### RU layout (with 2 layouts configured)
20:56:59.432  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }

### Only RU layout configured (setxkbmap -layout ru)
21:35:19.872  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }
21:35:19.872  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char(' '), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
21:35:19.872  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char(' ') mods=NONE
21:35:19.872  INFO   wezterm_term::terminalstate::keyboard > key_down: sending " ", Char(' ') NONE
21:35:20.035  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char(' '), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
21:35:20.035  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char(' ') mods=NONE

### Anything else?

Thank you for the brilliant terminal :)

**Comment by ProspectPyxis** [comment] 2024-01-31 02:51
Confirming this issue and adding that this seems to happen on non-qwerty English layouts as well - tested with colemak-DH.

**Comment by wez** [comment] 2024-01-31 14:44
I can't reproduce this under mutter; I think it's own keyboard stuff is getting in the way.

Please run:

```
WEZTERM_LOG=window::os::x11::keyboard=trace,info wezterm -n --config debug_key_events=true
```

to collect some more detailed tracing around the X11 keyboard events; please try to limit the keypresses to just the ones where the problem is observed, as the output is very verbose!

**Comment by ProspectPyxis** [comment] 2024-01-31 15:11
Trying to hit space twice results in this log:
```
22:03:52.458  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }
22:03:52.458  TRACE  window::os::x11::keyboard         > feed XK_space -> result Accepted
22:03:52.458  TRACE  window::os::x11::keyboard         > feed XK_ISO_Next_Group -> result Ignored
22:03:52.458  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_ISO_Next_Group. kc -> None fallback_feed=Nothing(" ", XK_space)
22:03:52.458  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
22:03:52.906  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
22:03:55.474  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }
22:03:55.474  TRACE  window::os::x11::keyboard         > feed XK_space -> result Accepted
22:03:55.474  TRACE  window::os::x11::keyboard         > feed XK_ISO_Next_Group -> result Ignored
22:03:55.474  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_ISO_Next_Group. kc -> None fallback_feed=Nothing(" ", XK_space)
22:03:55.474  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
22:03:55.858  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
```

**Comment by wez** [comment] 2024-01-31 15:13
I also need the debug key events bits as well!

**Comment by wez** [comment] 2024-01-31 15:13
or is that in there? there aren't as many log lines as I was expecting

**Comment by ProspectPyxis** [comment] 2024-01-31 15:16
Those are the only lines that appear when I press and release space over and over. Nothing related to key bits show up at all.

**Comment by ProspectPyxis** [comment] 2024-01-31 15:19
Maybe the problem is the `grp:win_space_toggle` option? OP seems to have used this option too, and so did I - and the `XK_ISO_Next_Group` mentions in the log seems suspicious to me.

**Comment by wez** [comment] 2024-01-31 15:19
@ProspectPyxis and for the sake of clarity for me, when you press space twice in that configuration, are you expecting to see two spaces emitted, or is space some kind of dead key? I don't understand the configuration you are using so it is difficult to figure out what should be happening.

Could you run that same logging setup and test with an older version of wezterm and share what you see there?

**Comment by wez** [comment] 2024-01-31 15:41
Please run `xev -event keyboard` and press space twice, and share the `xev` output here; let's see what the underlying raw state is.
I think something about that configuration is setting an unexpected bit in the key modifier state

**Comment by ProspectPyxis** [comment] 2024-01-31 15:48
Made a mistake with my previous comment.

After a bit of testing, starting from version `20240127-113634-bbcac864` onwards, with the keyboard setup as in the OP, using any layout other than the first listed results in the space key not emitting a space and acting as a dead key.

This is what the logs look like with the command you gave on version `20230712-072601-f4abf8fd`. Space works as expected and emits a space in the terminal here:

```
22:36:45.667  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }
22:36:45.667  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: " ", 32. kc -> Some(Char(' ')) fallback_feed=Nothing(" ", 32)
22:36:45.667  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char(' '), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
22:36:45.668  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char(' ') mods=NONE
22:36:45.668  INFO   wezterm_term::terminalstate::keyboard > key_down: sending " ", Char(' ') NONE
22:36:45.803  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char(' '), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
22:36:45.803  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char(' ') mods=NONE
22:36:46.075  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }
22:36:46.075  TRACE  window::os::x11::keyboard             > process_key_event: RawKeyEvent FeedResult::Nothing: " ", 32. kc -> Some(Char(' ')) fallback_feed=Nothing(" ", 32)
22:36:46.075  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char(' '), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
22:36:46.076  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char(' ') mods=NONE
22:36:46.076  INFO   wezterm_term::terminalstate::keyboard > key_down: sending " ", Char(' ') NONE
22:36:46.243  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char(' '), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
22:36:46.243  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char(' ') mods=NONE
```

Meanwhile, the logs on version `20240127-113634-bbcac864`, which are identical to the previous logs I posted (which were on version `20240128-202157-1e552d76`) and seems to be the release which introduced this regression:
```
22:40:05.947  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }
22:40:05.947  TRACE  window::os::x11::keyboard         > feed XK_space -> result Accepted
22:40:05.947  TRACE  window::os::x11::keyboard         > feed XK_ISO_Next_Group -> result Ignored
22:40:05.948  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_ISO_Next_Group. kc -> None fallback_feed=Nothing(" ", XK_space)
22:40:05.948  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
22:40:06.203  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
22:40:08.508  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }
22:40:08.508  TRACE  window::os::x11::keyboard         > feed XK_space -> result Accepted
22:40:08.508  TRACE  window::os::x11::keyboard         > feed XK_ISO_Next_Group -> result Ignored
22:40:08.508  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_ISO_Next_Group. kc -> None fallback_feed=Nothing(" ", XK_space)
22:40:08.508  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
22:40:08.812  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
```

And here are the xev logs as requested:
```
KeyPress event, serial 28, synthetic NO, window 0x5a00001,
    root 0x242, subw 0x0, time 51909756, (407,485), root:(1370,490),
    state 0x2000, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XmbLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x5a00001,
    root 0x242, subw 0x0, time 51910069, (407,485), root:(1370,490),
    state 0x2000, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x5a00001,
    root 0x242, subw 0x0, time 51910692, (407,485), root:(1370,490),
    state 0x2000, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XmbLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x5a00001,
    root 0x242, subw 0x0, time 51910989, (407,485), root:(1370,490),
    state 0x2000, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False
```

**Comment by welqd** [comment] 2024-01-31 16:26
In case, information from my side:
1. wezterm 20230712-072601-f4abf8fd - everything works
Single press on space
```raw
19:18:18.372  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }
19:18:18.372  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: " ", 32. kc -> Some(Char(' ')) fallback_feed=Nothing(" ", 32)
19:18:18.372  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char(' '), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
19:18:18.372  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char(' ') mods=NONE
19:18:18.372  INFO   wezterm_term::terminalstate::keyboard > key_down: sending " ", Char(' ') NONE
19:18:18.490  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char(' '), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
19:18:18.490  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char(' ') mods=NONE
```

2. wezterm 20240128-202157-1e552d76  - space isn't working
Single press on space
```raw
19:23:29.098  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Space), modifiers: NONE, leds: (empty), phys_code: Some(Space), raw_code: 65, repeat_count: 1, key_is_down: true, handled: Handled(false) }
19:23:29.098  TRACE  window::os::x11::keyboard         > feed XK_space -> result Accepted
19:23:29.098  TRACE  window::os::x11::keyboard         > feed XK_ISO_Next_Group -> result Ignored
19:23:29.098  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_ISO_Next_Group. kc -> None fallback_feed=Nothing(" ", XK_space)
19:23:29.098  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
19:23:29.188  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Next_Group and XK_ISO_Next_Group -> None
19:23:31.585  TRACE  window::os::x11::keyboard         > update_state with StateFromXcbStateNotify { depressed_mods: 0, latched_mods: 0, locked_mods: 0, depressed_layout: 0, latched_layout: 0, locked_layout: 1 }
19:23:31.585  TRACE  window::os::x11::keyboard         > update_state with StateFromXcbStateNotify { depressed_mods: 0, latched_mods: 0, locked_mods: 0, depressed_layout: 0, latched_layout: 0, locked_layout: 1 }
```

3. xev -event keyboard
Space pressed twice

```raw
KeyPress event, serial 28, synthetic NO, window 0x2a00001,
    root 0x553, subw 0x0, time 578035, (223,651), root:(3111,664),
    state 0x0, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XmbLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2a00001,
    root 0x553, subw 0x0, time 578154, (223,651), root:(3111,664),
    state 0x0, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x2a00001,
    root 0x553, subw 0x0, time 579101, (223,651), root:(3111,664),
    state 0x0, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XmbLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2a00001,
    root 0x553, subw 0x0, time 579219, (223,651), root:(3111,664),
    state 0x0, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False
```

**Comment by wez** [comment] 2024-02-01 16:25
I've pushed a couple of commits that improve some diagnostics slightly, and that may have a solution to this.
I'm not sure if the approach I've taken is correct for all situations, but I think it may resolve the specific situation you are experiencing.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.

Please take a few moments to try out the changes and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download an `.AppImage` file that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by ProspectPyxis** [comment] 2024-02-03 06:48
Confirming that the bug has been fixed in nightly for me as well. Thank you!

**Closed** 2024-02-03 19:24 UTC
Labels: bug, X11, fixed-in-nightly, keyboard

**Comment by Flakebi** [comment] 2024-02-25 12:50
Hi, this slightly broke the de-neo layout for me.
With this change, pressing some of the modifier keys (which are on the `<` and `\` key on a us layout) inserts characters (`<` or `\`) but they shouldn’t as it’s only modifier keys.
Reverting b8d93ed fixes the problem.

Running `WEZTERM_LOG=window::os::x11::keyboard=trace,info wezterm -n --config debug_key_events=true`

<details>
<summary>Log from main (95581d869)</summary>

```
13:45:37.196  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: RawCode(94), modifiers: NONE, leds: (empty), phys_code: None, raw_code: 94, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:45:37.196  TRACE  window::os::x11::keyboard         > Compose::feed(fallback) XK_less -> result=Accepted status=Nothing
13:45:37.196  TRACE  window::os::x11::keyboard         > Compose::feed(selected) XK_ISO_Level5_Shift -> result=Accepted status=Nothing
13:45:37.196  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_ISO_Level5_Shift. kc -> None fallback_feed=Nothing("<", XK_less)
13:45:37.196  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent using fallback sym XK_less because layout did not expand to anything
13:45:37.196  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('<'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: RawCode(94), modifiers: NONE, leds: (empty), phys_code: None, raw_code: 94, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:45:37.196  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char('<') mods=NONE
13:45:37.196  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "<", Char('<') NONE
13:45:37.196  ERROR  window::os::wayland::window           > set_cursor: Cursor not found
13:45:37.292  TRACE  window::os::x11::keyboard             > keysym_to_keycode for XK_ISO_Level5_Lock and XK_ISO_Level5_Lock -> None
13:45:37.404  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: RawCode(94), modifiers: NONE, leds: (empty), phys_code: None, raw_code: 94, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:45:37.404  TRACE  window::os::x11::keyboard             > Compose::feed(fallback) XK_less -> result=Accepted status=Nothing
13:45:37.404  TRACE  window::os::x11::keyboard             > Compose::feed(selected) XK_ISO_Level5_Shift -> result=Accepted status=Nothing
13:45:37.404  TRACE  window::os::x11::keyboard             > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_ISO_Level5_Shift. kc -> None fallback_feed=Nothing("<", XK_less)
13:45:37.404  TRACE  window::os::x11::keyboard             > process_key_event: RawKeyEvent using fallback sym XK_less because layout did not expand to anything
13:45:37.404  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('<'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: RawCode(94), modifiers: NONE, leds: (empty), phys_code: None, raw_code: 94, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:45:37.404  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('<') mods=NONE
13:45:37.404  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "<", Char('<') NONE
13:45:37.404  ERROR  window::os::wayland::window           > set_cursor: Cursor not found
13:45:37.516  TRACE  window::os::x11::keyboard             > keysym_to_keycode for XK_ISO_Level5_Lock and XK_ISO_Level5_Lock -> None
13:45:38.828  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(LeftWindows), modifiers: NONE, leds: (empty), phys_code: Some(LeftWindows), raw_code: 133, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:45:38.828  TRACE  window::os::x11::keyboard             > Compose::feed(fallback) XK_Super_L -> result=Ignored status=Nothing
13:45:38.828  TRACE  window::os::x11::keyboard             > Compose::feed(selected) XK_Super_L -> result=Ignored status=Nothing
13:45:38.828  TRACE  window::os::x11::keyboard             > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_Super_L. kc -> None fallback_feed=Nothing("", XK_Super_L)
13:45:38.828  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Super, modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftWindows), modifiers: NONE, leds: (empty), phys_code: Some(LeftWindows), raw_code: 133, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:45:38.828  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Super mods=NONE
```

</details>

<details>
<summary>Log from main with b8d93ed reverted</summary>

```
13:45:09.227  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: RawCode(94), modifiers: NONE, leds: (empty), phys_code: None, raw_code: 94, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:45:09.227  TRACE  window::os::x11::keyboard         > Compose::feed(fallback) XK_less -> result=Accepted status=Nothing
13:45:09.227  TRACE  window::os::x11::keyboard         > Compose::feed(selected) XK_ISO_Level5_Shift -> result=Accepted status=Nothing
13:45:09.227  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_ISO_Level5_Shift. kc -> None fallback_feed=Nothing("<", XK_less)
13:45:09.227  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Level5_Shift and XK_ISO_Level5_Shift -> None
13:45:09.323  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Level5_Lock and XK_ISO_Level5_Lock -> None
13:45:09.419  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: RawCode(94), modifiers: NONE, leds: (empty), phys_code: None, raw_code: 94, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:45:09.419  TRACE  window::os::x11::keyboard         > Compose::feed(fallback) XK_less -> result=Accepted status=Nothing
13:45:09.419  TRACE  window::os::x11::keyboard         > Compose::feed(selected) XK_ISO_Level5_Shift -> result=Accepted status=Nothing
13:45:09.419  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_ISO_Level5_Shift. kc -> None fallback_feed=Nothing("<", XK_less)
13:45:09.419  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Level5_Shift and XK_ISO_Level5_Shift -> None
13:45:09.491  TRACE  window::os::x11::keyboard         > keysym_to_keycode for XK_ISO_Level5_Lock and XK_ISO_Level5_Lock -> None
13:45:11.267  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, leds: (empty), phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:45:11.268  TRACE  window::os::x11::keyboard         > Compose::feed(fallback) XK_Control_L -> result=Ignored status=Nothing
13:45:11.268  TRACE  window::os::x11::keyboard         > Compose::feed(selected) XK_Control_L -> result=Ignored status=Nothing
13:45:11.268  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", XK_Control_L. kc -> None fallback_feed=Nothing("", XK_Control_L)
13:45:11.268  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: LeftControl, modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: NONE, leds: (empty), phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:45:11.268  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=LeftControl mods=NONE
13:45:11.379  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(Semicolon), modifiers: CTRL, leds: (empty), phys_code: Some(Semicolon), raw_code: 47, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:45:11.380  TRACE  window::os::x11::keyboard         > Compose::feed(fallback) XK_semicolon -> result=Accepted status=Nothing
13:45:11.380  TRACE  window::os::x11::keyboard         > Compose::feed(selected) XK_d -> result=Accepted status=Nothing
13:45:11.380  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "\u{4}", XK_d. kc -> None fallback_feed=Nothing(";", XK_semicolon)
13:45:11.380  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('d'), modifiers: CTRL, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(Semicolon), modifiers: CTRL, leds: (empty), phys_code: Some(Semicolon), raw_code: 47, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:45:11.380  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Char('d') mods=CTRL
13:45:11.380  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{4}", Char('d') CTRL
13:45:11.380  ERROR  window::os::wayland::window           > set_cursor: Cursor not found
```

</details>
