### ISSUE TITLE
Unable to scroll in `less` and `most`

### ISSUE THREAD

**Issue by MuhammedZakir** [wez/wezterm#429] opened 2021-01-17 19:12 UTC
I am unable to scroll in `less` and `most`, but I am able to do it in Vim. Is this is a bug, or is this not implemented?

P.S. I am using wezterm (`20201101-103216-403d002d-235-gbd614b5e`) on Manjaro (X11).

**Comment by wez** [comment] 2021-01-17 19:52
What do you mean by scroll?  Please describe clearly what action you are taking, what you expect to happen, and what actually happened!

**Comment by wez** [comment] 2021-01-18 05:41
Someone also brought up scrolling over here: https://matrix.to/#/!RibfHDCcaAAcGCkNEM:gitter.im/$YuhdRuRpNhLLI7ZGDD-_ncP29M5Xf3IQvwyVe-h_puE?via=gitter.im&via=matrix.org

It looks like there's been a regression in the logic that maps the wheel to the cursor keys when the alt screen is active

**Comment by wez** [comment] 2021-01-18 05:52
I've pushed a commit that should show up in the nightly builds in the next hour or two

**Comment by MuhammedZakir** [comment] 2021-01-18 13:06
> Someone also brought up scrolling over here: https://matrix.to/#/!RibfHDCcaAAcGCkNEM:gitter.im/$YuhdRuRpNhLLI7ZGDD-_ncP29M5Xf3IQvwyVe-h_puE?via=gitter.im&via=matrix.org
> 
> It looks like there's been a regression in the logic that maps the wheel to the cursor keys when the alt screen is active

When I couldn't scroll, I checked wezterm doc to see if I need to enable any option for it work. Then I found this - "SGR style mouse reporting (_works in vim and tmux_)", in Features page. So I tested scrolling in Vim to see if it's working, and for me, scrolling in Vim was working. Probably because I have this in my config:

```
 if has('mouse_sgr')
  set ttymouse=sgr
endif
set mouse=vi
```

This made me confused over whether this works only if this "SGR" is supported. That's why, I asked whether scrolling in others is currently implemented/supported or not. I admit that I don't know anything about this.

**Comment by MuhammedZakir** [comment] 2021-01-18 13:09
> I've pushed a commit that should show up in the nightly builds in the next hour or two

It's working now. But when compared to other terminals (e.g. Konsole, Yakuake), scrolling is slow. Is there anything I should do to increase scrolling speed?

**Comment by bew** [comment] 2021-01-18 14:16
>  I just found out scrolling in Vim is only working in wezterm nightly. It is not working in normal release.

I'm surprised you say that, I'm using neovim with the config `set mouse=nv`, and mouse scrolling and selection has always been working in wezterm normal releases

**Comment by MuhammedZakir** [comment] 2021-01-18 14:37
> > I just found out scrolling in Vim is only working in wezterm nightly. It is not working in normal release.
> 
> I'm surprised you say that, I'm using neovim with the config `set mouse=nv`, and mouse scrolling and selection has always been working in wezterm normal releases

That's weird. Are you using latest release? Because I was using nightly release, I had to install `wezterm-bin` AUR package for testing. So I am not sure why we are getting different results. Maybe I did something wrong? I will test this again and report back soon.

**Comment by wez** [comment] 2021-01-18 17:43
Re: questions about scroll speed, I've opened https://github.com/wez/wezterm/issues/432 to track that as an enhancement request.

Let's close this since the original issue is resolved!

**Closed by wez** 2021-01-18 17:43 UTC
