### ISSUE TITLE
[BUG] - Windows maximize button not working

### ISSUE THREAD

**Issue by mrjackwills** [wez/wezterm#3591] opened 2023-04-22 14:26 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

 20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am running wezterm on Windows, after updating to the latest version, I am now unable to use the window decoration maximize button to increase the size of the wezterm Window.I am instead greeted with the Windows window snapping options. The Minimize and Close button work as expected. This issue only started after I updated to the "20230408-112425-69ae8472" version. Please see the attached video.

### Configuration

```lua
local wezterm = require 'wezterm';

return {
	default_prog = {"wsl", "~"},
	font_size = 10.0,
	font = wezterm.font("Ubuntu Mono"),
	color_scheme = "Nancy (terminal.sexy)",
	keys = {
		-- This will create a new split and run your default program inside it
		{
			key="a", mods="CTRL",
			action=wezterm.action.SplitHorizontal{domain="CurrentPaneDomain"}}
			,
	}
}
```

The issue also occurs if no wezterm.lua is set

### Logs

Debug Overlay
wezterm version: 20230408-112425-69ae8472 x86_64-pc-windows-msvc
Window Environment: Windows
OpenGL version: NVIDIA GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 4.5.0 NVIDIA 531.68
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>

### Anything else?

https://user-images.githubusercontent.com/32690432/233790530-f02e060a-d1c6-4dfd-a87c-75bdf71197d9.mp4

**Comment by wez** [comment] 2023-04-22 16:25
Duplicate of https://github.com/wez/wezterm/issues/3499

**Closed by wez** 2023-04-22 16:25 UTC
Labels: bug

**Comment by mrjackwills** [comment] 2023-04-22 16:41
> Duplicate of #3499

Sorry, don't know how I missed that
