### ISSUE TITLE
Window Maximize

### ISSUE THREAD

**Issue by gwww** [wez/wezterm#675] opened 2021-04-10 17:56 UTC
**Is your feature request related to a problem? Please describe.**
When starting `wezterm` I would like to have the initial window be maximized (not full screen). The window will be resized as large as possible, without obscuring the dock/menu (this sentence taken from Hammerspoon `window:maximize` help).

**Describe the solution you'd like**
Be able to maximize a window. I would use it on the initial `wezterm` window.

**Describe alternatives you've considered**
Using Hammerspoon, but it's not a nice as the app doing this for itself.

**Additional context**
I'm on MacOS.

**Comment by wez** [comment] 2021-04-10 18:10
Duplicate of #284

**Closed by wez** 2021-04-10 18:10 UTC
Labels: enhancement
