### ISSUE TITLE
Duplicate / phantom key presses

### ISSUE THREAD

**Issue by ndom91** [wez/wezterm#4836] opened 2024-01-22 12:31 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

Latest `wezterm-git` from the AUR from this morning: `20240121-180215-76028ca1`

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After stopping typing, some keypresses get duplicated about 1-2ms after the last keypress like a ghost / phantom keypress. I've done some debugging, but can't for the life of me figure out where its coming from. It occurs maybe 1 to 2 times every 60s or so during active typing/using of the terminal. It also doesn't seem to be limited to any application, it occurs at the shell prompt just as often as it does in vim :thinking: 

I could only get this to occur in Wezterm, not any other application on the system.

My config is relatively straight forward, see below.

Any additional debugging ideas would also be greatly appreciated! :pray: 

### Configuration

```lua
local wezterm = require 'wezterm'

local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.default_prog = { '/bin/tmux', 'new-session' }

config.debug_key_events = true

config.color_scheme = 'Rosé Pine (base16)'
config.window_background_opacity = 0.92

config.font = wezterm.font_with_fallback {
  { family = 'Operator Mono Light', harfbuzz_features = { 'liga=1' } },
  'Fira Code',
  'Ubuntu Mono',
}
config.font_size = 10.0

config.hide_tab_bar_if_only_one_tab = true

config.window_padding = {
  left = 0,
  right = 0,
  top = 0,
  bottom = 0,
}

config.keys = {
  {
    key = 'R',
    mods = 'CTRL|SHIFT',
    action = wezterm.action.ReloadConfiguration,
  },
  {
    key = 'S',
    mods = 'SHIFT|CTRL',
    action = wezterm.action.QuickSelect,
  },
}

return config
```

### Logs

I've enabled `debug_key_events` and got the following output. The last keypress in each section is the "phantom" one, in the first section the `"f"` (I typed 'asdf' but got 'asdff') and in the last two sections the `"k"`.

```typescript
// Typing "asdf" at the shell prompt, getting "asdff" in return
13:35:48.623  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(A), modifiers: NONE, leds: (empty), phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:35:48.623  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('a'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, leds: (empty), phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:35:48.623  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('a') mods=NONE
13:35:48.623  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "a", Char('a') NONE
13:35:48.695  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(S), modifiers: NONE, leds: (empty), phys_code: Some(S), raw_code: 39, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:35:48.695  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('s'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(S), modifiers: NONE, leds: (empty), phys_code: Some(S), raw_code: 39, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:35:48.695  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('s') mods=NONE
13:35:48.695  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "s", Char('s') NONE
13:35:48.759  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(D), modifiers: NONE, leds: (empty), phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:35:48.759  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('d'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(D), modifiers: NONE, leds: (empty), phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:35:48.759  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('d') mods=NONE
13:35:48.759  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "d", Char('d') NONE
13:35:48.783  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('a'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(A), modifiers: NONE, leds: (empty), phys_code: Some(A), raw_code: 38, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:35:48.783  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('a') mods=NONE
13:35:48.831  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(F), modifiers: NONE, leds: (empty), phys_code: Some(F), raw_code: 41, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:35:48.831  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('f'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(F), modifiers: NONE, leds: (empty), phys_code: Some(F), raw_code: 41, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:35:48.831  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('f') mods=NONE
13:35:48.831  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "f", Char('f') NONE
13:35:48.903  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('s'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(S), modifiers: NONE, leds: (empty), phys_code: Some(S), raw_code: 39, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:35:48.903  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('s') mods=NONE
13:35:48.903  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('d'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(D), modifiers: NONE, leds: (empty), phys_code: Some(D), raw_code: 40, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:35:48.903  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('d') mods=NONE
13:35:49.433  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('f'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(F), modifiers: NONE, leds: (empty), phys_code: Some(F), raw_code: 41, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:35:49.433  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('f') mods=NONE
13:35:49.433  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "f", Char('f') NONE
13:35:49.436  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('f'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(F), modifiers: NONE, leds: (empty), phys_code: Some(F), raw_code: 41, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:35:49.436  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('f') mods=NONE

---

13:24:13.779  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('d') mods=NONE
13:24:13.835  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('f'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(F), modifiers: NONE, leds: (empty), phys_code: Some(F), raw_code: 41, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:24:13.835  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('f') mods=NONE
13:24:13.851  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('j'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(J), modifiers: NONE, leds: (empty), phys_code: Some(J), raw_code: 44, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:24:13.851  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('j') mods=NONE
13:24:14.508  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(K), modifiers: NONE, leds: (empty), phys_code: Some(K), raw_code: 45, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:24:14.508  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('k'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(K), modifiers: NONE, leds: (empty), phys_code: Some(K), raw_code: 45, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:24:14.508  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('k') mods=NONE
13:24:14.508  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "k", Char('k') NONE
13:24:15.109  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('k'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(K), modifiers: NONE, leds: (empty), phys_code: Some(K), raw_code: 45, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:24:15.109  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('k') mods=NONE
13:24:15.109  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "k", Char('k') NONE
13:24:15.110  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('k'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(K), modifiers: NONE, leds: (empty), phys_code: Some(K), raw_code: 45, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:24:15.110  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('k') mods=NONE

---

13:25:41.035  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('k') mods=NONE
13:25:41.035  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "k", Char('k') NONE
13:25:41.075  INFO   wezterm_gui::termwindow::keyevent     > key_event RawKeyEvent { key: Physical(L), modifiers: NONE, leds: (empty), phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }
13:25:41.075  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('l'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(L), modifiers: NONE, leds: (empty), phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:25:41.075  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('l') mods=NONE
13:25:41.075  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "l", Char('l') NONE
13:25:41.091  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('j'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(J), modifiers: NONE, leds: (empty), phys_code: Some(J), raw_code: 44, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:25:41.091  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('j') mods=NONE
13:25:41.139  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('k'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(K), modifiers: NONE, leds: (empty), phys_code: Some(K), raw_code: 45, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:25:41.139  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('k') mods=NONE
13:25:41.676  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('l'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(L), modifiers: NONE, leds: (empty), phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: true, handled: Handled(false) }) }
13:25:41.676  INFO   wezterm_gui::termwindow::keyevent     > send to pane DOWN key=Char('l') mods=NONE
13:25:41.676  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "l", Char('l') NONE
13:25:41.678  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: Char('l'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(L), modifiers: NONE, leds: (empty), phys_code: Some(L), raw_code: 46, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
13:25:41.678  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=Char('l') mods=NONE
```

**Comment by johnae** [comment] 2024-03-07 11:56
I think this is a dupe of https://github.com/wez/wezterm/issues/4504

**Closed** 2024-06-22 10:04 UTC
Labels: bug, Wayland
