### ISSUE TITLE
Confirmation window when pressed "close" button

### ISSUE THREAD

**Issue by sapi01** [wez/wezterm#393] opened 2020-12-22 22:21 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my system goes to sleep, for some reason (probably I turned on power saving? IDK) it closes few applications and one of them is WezTerm. And I have to open a new WezTerm application and redo all my ssh/irc/vim/etc... AGAIN and AGAIN. I noticed, iTerm2 Does have that Confirmation window when pressed "close" button or when my system "trying" to close the application. And it is SUPER useful because, I can press "cancel" and abort application from closing.

**Describe the solution you'd like**
When I manually press "close" button OR when my system "tries" to close the application(in our case WizTerm), It needs to prompt a Confirmation window like "Do you want to close WizTerm? cancel / close". This feature is super useful

**Additional context**
Example, like iTerm2 will ask for a Confirmation when Im in the middle of an ssh session or something when I "accidentally"  pressed Close button or when I put my system to sleep and my OS sneak in and "tries" to close the application

**Comment by wez** [comment] 2020-12-22 23:08
Duplicate of #280

**Closed by wez** 2020-12-22 23:08 UTC
Labels: enhancement
