### ISSUE TITLE
imgcat: returns blank image

### ISSUE THREAD

**Issue by statespace** [wez/wezterm#3701] opened 2023-05-08 08:24 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Side-by-side comparison with iterm2:

<img width="1209" alt="Screenshot 2023-05-08 at 11 08 47" src="https://user-images.githubusercontent.com/8366324/236772809-c5782426-3311-415d-8baf-25c843314049.png">

Using `wezterm imgcat` or `imgcat` (one that was installed via iterm2) - same result.

### Configuration

local wezterm = require("wezterm")
local config = {}

if wezterm.config_builder then
        config = wezterm.config_builder()
end

config.color_scheme = "Monokai Pro (Gogh)"
config.font_size = 14

return config

### Logs

❯ cat ~/.local/share/wezterm/wezterm-gui-log-40732.txt
10:56:25.456  ERROR  wezterm_gui::glyphcache > Error decoding image: inconsistent 600x400 -> 720000
10:56:25.478  WARN   wezterm_gui::glyphcache > decoder thread terminated

**Comment by wez** [comment] 2023-05-08 14:21
Duplicate of https://github.com/wez/wezterm/issues/3529

**Closed by wez** 2023-05-08 14:21 UTC
Labels: bug
