### ISSUE TITLE
Windows Scroll / Typing Performance has significant delay in maximized mode

### ISSUE THREAD

**Issue by markhagemann** [wez/wezterm#805] opened 2021-05-18 02:33 UTC
## Describe the bug

When running WezTerm (nightly and latest release), if the terminal isn't maximized, the performance is almost identical to Windows Terminal Preview (I can't fault it). 

If WezTerm is maximized, the typing and scroll delay is significantly worse. This is shown most clearly in vim / neovim (even with plugins disabled). 

I have experimented with `front_end` and `prefer_egl` and found the same results. 

## Environment (please complete the following information):

 - OS: Windows with WSL2
 - Version: wezterm 20210517-072856-bf032062
 - The active keyboard layout name: English (United States)

## To Reproduce

- Load up a large file in vim without WezTerm being on maximized, scroll up and down and note the performance.
- Maximize WezTerm and compare scrolling performance from before

## Configuration

```
local wezterm = require 'wezterm';

return {
    colors = {
		background = "#202734",
		foreground = "#CBCCC6",
		cursor_fg = "#fff",
		cursor_bg = "#42546e",
		cursor_border = "#42546e",
    },
    default_prog = {"wsl.exe", "~", "--exec", "tmux", "-l"},
    font = wezterm.font("CaskaydiaCove Nerd Font"),
    font_size = 12,
    hide_tab_bar_if_only_one_tab = true,
    initial_cols = 160,
    initial_rows = 40,
    window_close_confirmation = "NeverPrompt",
    window_padding = {
		left = 10,
		right = 5,

		top = 5,
		bottom = 5,
    }
}
```

## Expected behavior
Minimal difference between maximized mode and standard mode. 

## Session Recording
[wezterm windows recording.zip](https://github.com/wez/wezterm/files/6532975/wezterm.windows.recording.zip)

**Comment by wez** [comment] 2021-05-22 06:15
What are the window dimensions when maximized?

**Comment by markhagemann** [comment] 2021-05-24 14:06
1920 x 1150 (50px for the windows taskbar) (max res on laptop is 1920 x 1200 - Dell Precision 5550)

**Comment by wez** [comment] 2021-06-13 16:09
Even though #817 is newer than this, it has the same root cause; the render cost is `O(window area)`, so I'm closing this issue in favor of that one.

**Closed by wez** 2021-06-13 16:09 UTC
Labels: bug
