### ISSUE TITLE
Shift the baseline up

### ISSUE THREAD

**Issue by anuvyklack** [wez/wezterm#2963] opened 2023-01-15 22:37 UTC
Is there any possibility to shift baseline up?

**kitty**
In kitty all symbols are vertically in the center (almost) of the cell. It is clearly visible if you look on digits and icons.

![Screenshot from 2023-01-16 01-16-11](https://user-images.githubusercontent.com/13056013/212570235-cb2cb437-6331-468f-9543-4d54a275d334.png)

**wezterm**
In wezterm all symbols are shifted down to the down border of the row.

![Screenshot from 2023-01-16 01-16-39](https://user-images.githubusercontent.com/13056013/212570246-fcebb893-512e-4149-9275-3c9b39e55d07.png)

**Comment by wez** [comment] 2023-01-15 22:51
Sounds like a duplicate of https://github.com/wez/wezterm/issues/2818

**Closed** 2023-01-15 22:54 UTC
Labels: enhancement
