### ISSUE TITLE
Closing windows or clearing terminal buffer doesn't release memory

### ISSUE THREAD

**Issue by rolfb** [wez/wezterm#2004] opened 2022-05-18 09:19 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220517-184546-9b5c8878

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

First off, very happy with this terminal client. Thank you so much!

Noticed some high memory consumption and did some quick experiments, and memory didn't seem to come down as expected when closing windows and tabs.

### To Reproduce

Open a new window, run `yes` for a short time while watching the memory consumption. Clear the buffer with [CMD+K], `clear` command doesn't seem to remove the scrollback?

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  initial_cols = 150,
  initial_rows = 40,
  color_scheme = "Molokai",
  font = wezterm.font("JetBrainsMono Nerd Font Mono"),
  font_size = 15,
  exit_behavior = "Close",
  send_composed_key_when_left_alt_is_pressed = true,
  scrollback_lines = 3500,
  audible_bell = "Disabled",
  remember_window_positions = true,
  use_dead_keys = false,
}
```

### Expected Behavior

- Memory usage to drop after closing window
- Memory usage to drop after doing clear

**Comment by wez** [comment] 2022-05-18 14:45
The `clear` command will only emit the escape sequence that clears the scrollback if your OS terminfo for `xterm-256color` (the default `$TERM` in wezterm) defines it, and I've yet to see it defined by default on the systems that I use.

The current scrollback data structure is a VecDeque which works by allocating a linked list of arrays of an implementation defined internal size.  Clearing the scrollback will tell the VecDeque to resize its reported structure, but it may retain notional excess memory if the scrollback straddles multiple segments which may be why you don't notice a significant change in the memory usage.

In addition, monitoring memory usage by coarse methods like eg: `top` isn't a great way to attribute where the memory is in use, especially because modern allocators employ caching to speed up subsequent allocations.

That said: yes, the scrollback data structure in wezterm is relatively heavyweight today.  I have a local branch that I've been working on to improve this.

I'm going to close this issue as a duplicate of https://github.com/wez/wezterm/issues/1626

**Closed by wez** 2022-05-18 14:45 UTC
Labels: bug
