### ISSUE TITLE
Wayland colours are seemingly broken

### ISSUE THREAD

**Issue by Suyashtnt** [wez/wezterm#2755] opened 2022-11-18 14:32 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm (thats all it says, git commit is 35e3e30d7ad8f8667ac9df1168575f6854cc0530)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

when using `enable_wayland = true`, the colours are incredibly broken using any theme.

### To Reproduce

1. set `enable_wayland` to true in config
2. open up wezterm
3. witness this

### Configuration

```lua
local wezterm = require "wezterm"

return {
	color_scheme = "Catppuccin Mocha",
	font = wezterm.font_with_fallback {
		'JetBrainsMono Nerd Font Mono', -- Comic code breaks the font
		'Noto Color Emoji',
	},
	font_size = 13,
	line_height = 1.6,
	font_antialias = "Subpixel",
        harfbuzz_features = {
          "cv06=1",
          "cv14=1",
          "cv32=1",
          "ss04=1",
          "ss07=1",
          "ss09=1",
        },
	enable_wayland = true,
	cursor_blink_ease_in = "EaseIn",
	cursor_blink_ease_out = "EaseOut",
	animation_fps = 120,
	cursor_blink_rate = 800,
	cursor_thickness = 1.0,
	default_cursor_style = "BlinkingBar",
	initial_rows = 17,
	initial_cols = 70,
	window_padding = {
		left = 12,
		right = 12,
		top = 12,
		bottom = 12,
	},
	window_frame = {
		inactive_titlebar_bg = '#171723',
		active_titlebar_bg = '#171723',
		inactive_titlebar_fg = '#9399b2',
		active_titlebar_fg = '#cdd6f4',
		font = wezterm.font { family = 'Inter', weight = 'Bold' },
	},
	colors = {
		tab_bar = {
			active_tab = {
				bg_color = '#1e1e2e',
				fg_color = '#cdd6f4',
				intensity = 'Bold',
			},
			inactive_tab = {
				bg_color = '#313244',
				fg_color = '#9399b2',
			},
                        inactive_tab_hover = {
                                bg_color = '#11111b',
                                fg_color = '#cdd6f4',
                        },
			new_tab = {
				bg_color = '#181825',
				fg_color = '#cdd6f4',
			},
			new_tab_hover = {
                                bg_color = '#1e1e2e',
                                fg_color = '#cdd6f4',
                        },
		},
	},
}
```

### Expected Behavior

The colours to appear properly

### Logs

Debug Overlay
wezterm version:
OpenGL version: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 4.6.0 NVIDIA 520.56.06
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
16:29:29.313 WARN wezterm_dynamic::error > `font_antialias` is not a valid Config field. Did you mean one of `font_dirs`, `font_rules`, `font`, `font_rasterizer`, `font_locator`, `font_size`, `font_shaper`? There are too many alternatives to list here; consult the documentation!
16:29:29.340 WARN wezterm_dynamic::error > `font_antialias` is not a valid Config field. Did you mean one of `font_dirs`, `font_rules`, `font`, `font_rasterizer`, `font_locator`, `font_size`, `font_shaper`? There are too many alternatives to list here; consult the documentation!
16:31:56.435 WARN wezterm_dynamic::error > `font_antialias` is not a valid Config field. Did you mean one of `font_dirs`, `font_rules`, `font`, `font_rasterizer`, `font_locator`, `font_size`, `font_shaper`? There are too many alternatives to list here; consult the documentation!

### Anything else?

![image](https://user-images.githubusercontent.com/45307955/202728075-8e8c4506-5e2b-4b1e-9f53-4eb5b4db7ff6.png)

**Comment by wez** [comment] 2022-11-18 17:01
Duplicate of https://github.com/wez/wezterm/issues/1701

**Closed** 2022-11-18 17:04 UTC
Labels: bug
