### ISSUE TITLE
Splitting multiplexed panes results in incorrect position and size

### ISSUE THREAD

**Issue by BetaRavener** [wez/wezterm#3386] opened 2023-03-27 14:27 UTC
### What Operating System(s) are you seeing this problem on?

Windows, Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Windows app native.
X11 was tested by running under WSL with VcXsrv and X410 as X11 server.

### WezTerm version

20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Splitting pane while connected to SSH-domain results in the new pane having unexpected position and size:

https://user-images.githubusercontent.com/1514221/227945138-e40d181e-1c75-42ab-bebd-9e7c5856b12d.mp4

Resizing the whole window resets the state of the panes after which they appear as expected.

### To Reproduce

1. `wezterm connect <ssh-domain>
2. Do `SplitVertical`.
3. Close the new (right) pane.
4. Repeat 2 & 3. The pane will spawn further and further right. Sometimes the new pane spawns with the previous position / size.

### Configuration

```
local wezterm = require 'wezterm'
local act = wezterm.action

return {
  color_scheme = 'MaterialDark',

  -- Scrollbar Settings
  enable_scroll_bar = true,
  -- Make it easy to still see scrollbar head when there's lot of output
  min_scroll_bar_height = "1.5cell",
  -- Customize padding, mainly setting scrollbar width
  window_padding = {
    left = '0px',
    right = '6px',
    top = '5px',
    bottom = '0px',
  },

  keys = {
    -- Pane Zoom
    {
      key = 'X',
      mods = 'CTRL|SHIFT',
      action = act.TogglePaneZoomState,
    },

    -- Split H*O*rizontally (adding a vertical line)
    {
      key = 'O',
      mods = 'CTRL|SHIFT',
      action = act.SplitVertical,
    },

    -- Split V*E*rtically (adding a horizontal line)
    {
      key = 'E',
      mods = 'CTRL|SHIFT',
      action = act.SplitHorizontal,
    },

    -- Close Pane
    {
      key = 'w',
      mods = 'CTRL|SHIFT',
      action = act.CloseCurrentPane { confirm = false },
    },
  },

  ssh_domains = {
    {
      name = 'ubuntu-wsl',
      remote_address = '192.168.2.3',
      username = 'test',
    },
  },

}
```

### Expected Behavior

The pane should be normally split in two equal halves, both within the window's surface.

**Comment by wez** [comment] 2023-03-28 02:09
FWIW, I can't reproduce this with a mac as the client and separate linux box as the server.

**Comment by BetaRavener** [comment] 2023-03-28 14:52
That's interesting because I just did that. I've updated all machines to `wezterm 20230326-111934-3666303c` and just to eliminate WSL factor, ran Linux Mint in VirtualBox - this surely behaves like standard Linux box. I've also dumbed down prompt to simple "$" if that makes any difference and used basic bash here. Client is running on MacOS 12.2.1.


https://user-images.githubusercontent.com/1514221/228278341-6eb40e2a-3dad-45fd-a2e1-184130ce3b33.mp4

**Comment by wez** [comment] 2023-03-28 15:52
I was able to reproduce this on my linux box with that latest config, and I've pushed a fix for what I was seeing.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by BetaRavener** [comment] 2023-03-28 16:28
Amazing that you were able to locate and fix it so fast.
Build from source Win and Linux version and tested in the WSL scenario.
For sane usage WezTerm now behaves as expected, but I managed to still break it by stressing it out:

https://user-images.githubusercontent.com/1514221/228306804-c8bcb209-c66e-4f83-980d-76eda0f578e7.mp4

**Comment by wez** [comment] 2023-03-30 23:38
I couldn't reproduce that most recent issue, but I made a small change that may help a little

**Closed** 2023-04-07 15:13 UTC
Labels: bug, fixed-in-nightly, multiplexer
