### ISSUE TITLE
`vim-airline` causes 100% cpu usage on one thread

### ISSUE THREAD

**Issue by szbergeron** [wez/wezterm#2165] opened 2022-06-23 13:15 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220622-113325-21f1e632

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If the `vim-airline` plugin is enabled (whether with others or on its own), wezterm-gui runs full throttle in one thread (100% cpu usage for one core).

I am unable to reproduce the issue in kitty or alacritty.

The issue is new within the past few weeks, I can try to bisect more granularly shortly.

### To Reproduce

1. add the `vim-airline` plugin using a plugin manager of your choice to your vimrc
2. start vim or neovim (repro on both), an anonymous buffer is enough to display the issue
3. check cpu usage in htop

### Configuration

local wezterm = require 'wezterm';

return {
    font = wezterm.font("FiraCode Nerd Font Mono"),

    color_scheme = "Aurora",

    enable_wayland = true,

    default_prog = {"/usr/bin/fish"},

    -- enable_scroll_bar = true,

    warn_about_missing_glyphs = false,

    hide_tab_bar_if_only_one_tab = true,

    window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0,
    },

    animation_fps = 1,

    cursor_blink_rate = 0,

    window_decorations = "RESIZE"
}

### Expected Behavior

CPU usage settles to near-idle after N seconds

### Logs

Unsupported modifier, resource creation failed.
XXX: resource creation failed
09:15:10.244  INFO   wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) UHD Graphics (CML GT2) 4.6 (Compatibility Profile) Mesa 22.1.2 is_context_loss_possible=false wezterm version: 20220622-113325-21f1e632
Unsupported modifier, resource creation failed.
XXX: resource creation failed
Unsupported modifier, resource creation failed.
XXX: resource creation failed
09:15:13.480  WARN   wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)

**Comment by wez** [comment] 2022-06-23 13:25
If you set `warn_about_missing_glyphs = true` do you see a continuous stream of warnings about them?
If so, then 427e4a0a84abf6ef36a4255de710fdf70a9b848f is likely the cause.
Can you confirm that?

**Comment by wez** [comment] 2022-06-23 13:38
I think 21e6fcedd will fix this!

**Comment by szbergeron** [comment] 2022-06-23 13:41
I mucked around and broke my clone and am having a new issue building it to test 🙃
![image](https://user-images.githubusercontent.com/7364398/175313360-c8732521-123b-44d7-bbed-3fbef51a3bea.png)

**Comment by szbergeron** [comment] 2022-06-23 13:56
(installing and adding Unifont as a fallback works around this for me on prior versions)

**Comment by wez** [comment] 2022-06-23 15:35
I've reproduced the behavior on the older rev and confirmed that it is now resolved in `main`

**Closed by wez** 2022-06-23 15:35 UTC
Labels: bug
