### ISSUE TITLE
Correctly render NFD forms of Korean characters

### ISSUE THREAD

**Issue by achimnol** [wez/wezterm#1474] opened 2021-12-30 03:33 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20211208-214421-4dd014b1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Unicode has two representative normalization forms: NFC and NFD. (see also: [Unicode equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence))
While Windows uses NFC, macOS uses NFD.
There is no difference for most Western languages but this makes big differences when representing Korean characters.
It is difficult for text rendering codes to handle them correctly, even web browsers sometimes do it wrong.

An NFD text example:
```
-rw-r--r--@ 1 joongi  staff     60624 Aug 23  2020 2020년 경주  가 족여 행 저  산.pdf
-rw-r--r--@ 1 joongi  staff     11841 Aug 23  2020 2020년 경주  가 족여 행 저  산.xlsx
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
```

An NFC text example:
```
-rw-r--r--@ 1 joongi  staff     60624 Aug 23  2020 2020년 경주 가족여행 정산.pdf
-rw-r--r--@ 1 joongi  staff     11841 Aug 23  2020 2020년 경주 가족여행 정산.xlsx
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
```

Both NFD/NFC texts should be displayed in the same way, and only the macOS default Terminal app achieves it. iTerm2 and wezterm both fails in different ways.

macOS Terminal (the correct result):
![image](https://user-images.githubusercontent.com/555156/147719346-1ca18db5-fb4d-4cd6-9de2-019dc1be8f02.png)

iTerm2:
![image](https://user-images.githubusercontent.com/555156/147719329-05f4397f-f330-4282-9433-15764c6064a7.png)

wezterm:
![image](https://user-images.githubusercontent.com/555156/147719323-2c5fe095-91eb-41a4-8776-b55f851e6c2e.png)

There are two ways to solve this rendering issue:
 * Convert all Unicode texts to NFC before rendering.
   - Pros: no need to write complicated rendering logic
   - Cons: copy-and-pasting the terminal output would include implicit NFC conversion
   - I'd welcome to have a configuration option, which defaults to off.
 * Calculate the width of NFD-composed glyphs correctly.
   - In particular, Korean characters are composed of two or three [jamos](https://en.wikipedia.org/wiki/Hangul_Jamo_(Unicode_block)), in NFD a character may take up two or three memory spaces while the rendered result should be two blocks.

Currently wezterm renders NFD Korean characters using 3 blocks and depending on whether the character has jongseong (an optional jamo at the end) the whole character is rendered on the right two blocks with an empty first block or left two blocks with a potentially reused graphic memory from other parts of the screen.

### To Reproduce

Please see the description.

### Configuration

```lua
local wezterm = require 'wezterm';

return {
    use_ime = true,
    color_scheme = "Rapture",
    font = wezterm.font_with_fallback({
        "JetBrains Mono",
        "Menlo",
        "NanumBarunGothic",
        "AppleGothic",
    }),
    custom_block_glyphs = true,
    send_composed_key_when_left_alt_is_pressed = false,
    send_composed_key_when_right_alt_is_pressed = true,
    use_dead_keys = false,
    keys = {
      {key="LeftArrow", mods="SUPER", action=wezterm.action{ActivateTabRelative=-1}},
      {key="RightArrow", mods="SUPER", action=wezterm.action{ActivateTabRelative=1}},
      {key="Tab", mods="CTRL|SHIFT", action=wezterm.action{ActivateTabRelative=-1}},
      {key="Tab", mods="CTRL", action=wezterm.action{ActivateTabRelative=1}},
      {key="UpArrow", mods="SUPER", action=wezterm.action{SendString="\x1b[5~"}},   -- PageUp
      {key="DownArrow", mods="SUPER", action=wezterm.action{SendString="\x1b[6~"}}, -- PageDown
      {key="F1", mods="SHIFT", action=wezterm.action{SendString="\x1bOP"}},
      {key="F2", mods="SHIFT", action=wezterm.action{SendString="\x1bOQ"}},
      {key="F3", mods="SHIFT", action=wezterm.action{SendString="\x1bOR"}},
      {key="F4", mods="SHIFT", action=wezterm.action{SendString="\x1bOS"}},
      {key="F5", mods="SHIFT", action=wezterm.action{SendString="\x1b[15~"}},
      {key="F6", mods="SHIFT", action=wezterm.action{SendString="\x1b[17~"}},
      {key="F7", mods="SHIFT", action=wezterm.action{SendString="\x1b[18~"}},
      {key="F8", mods="SHIFT", action=wezterm.action{SendString="\x1b[19~"}},
      {key="F9", mods="SHIFT", action=wezterm.action{SendString="\x1b[20~"}},
      {key="F10", mods="SHIFT", action=wezterm.action{SendString="\x1b[21~"}},
      {key="F11", mods="SHIFT", action=wezterm.action{SendString="\x1b[23~"}},
      {key="F12", mods="SHIFT", action=wezterm.action{SendString="\x1b[24~"}},
    },
    -- debug_key_events = true,
}
```

### Expected Behavior

The NFD text should be also rendered like this NFC text:
![image](https://user-images.githubusercontent.com/555156/147719581-5258bf81-6e23-425a-bafe-123ab75c1911.png)

**Comment by wez** [comment] 2021-12-30 04:49
I had difficulty copying the NFD example because Chrome also doesn't handle this correctly, but what I did was copy
the NFC text and use this little script:

```bash
#!/bin/bash

echo NFC:
cat ~/issue-1474.txt

echo NFD:
iconv  -f utf-8 -t utf-8-mac < ~/issue-1474.txt
```

I confirmed that Terminal.app handles this correctly, and that wezterm wasn't doing the right thing.

I pushed c68b55ba4fb94d321744870498e8e595078bcb58 which targets the width calculation.
Here's how it looks with this change:

![image](https://user-images.githubusercontent.com/117777/147722293-32fe4b3a-fa17-4eff-b065-31483d75e04e.png)

FWIW, I think this is essentially a duplicate of https://github.com/wez/wezterm/issues/1469 but this issue has a great example of the practical impact of the issue whereas the other is a good technical example of where the problem originates.

**Comment by achimnol** [comment] 2021-12-30 06:34
I confirm the nightly build fixes the issue.
However, there is another slightly different issue: NFC characters are rendered with "NanumBarunGothic" (the 3rd font in my config) while NFD characters are rendered with "Apple Gothic" (the ultimate fallback font).
This is not a big deal and I believe it's more the font-side problem, but it may be good to know.

**Comment by achimnol** [comment] 2021-12-30 06:48
Changing my font setting to:
```lua
    font = wezterm.font_with_fallback({
        "JetBrains Mono",
        "Menlo",
        "Apple SD 산돌고딕 Neo",
        "AppleGothic",
    }),
```
resolves the inconsistency of font choices for NFC and NFD. Both of them are rendered with the 3rd font, which is the Apple's new Korean system font since OS X Mountain Lion.

**Comment by wez** [comment] 2021-12-30 16:41
I think we can call this good!  Thanks for the report: it was very clear!

**Closed by wez** 2021-12-30 16:41 UTC
Labels: bug, fixed-in-nightly

**Comment by aca** [comment] 2022-01-04 06:25
@achimnol Hi, I have trouble with Korean input on macOS and you seem to be familiar with this kind of issue.
I can't complete Korean character after 된소리. It seems like there's an issue with keys after shift.
Can you help me with this?

![image](https://user-images.githubusercontent.com/50316549/148017708-9d2a2935-e0e8-4df6-a7f5-dd7603062a57.png)

**Comment by y-mx-b** [comment] 2022-04-21 01:26
> @achimnol Hi, I have trouble with Korean input on macOS and you seem to be familiar with this kind of issue. I can't complete Korean character after 된소리. It seems like there's an issue with keys after shift. Can you help me with this?
> 
> ![image](https://user-images.githubusercontent.com/50316549/148017708-9d2a2935-e0e8-4df6-a7f5-dd7603062a57.png)

I've just started setting up Wezterm and I've come across an issue where I am unable to type Korean properly in general, not just after 된소리. 

<img width="375" alt="Screen Shot 2022-04-20 at 9 24 48 PM" src="https://user-images.githubusercontent.com/48655352/164353127-eed86db8-47be-47a7-8231-ac429088390b.png">

It should be typed as 가나다라 but it ends up separating each individual character into its own cell. Does anyone have any clue why this is?
