### ISSUE TITLE
Cant use wezterm on wayland / hyprland

### ISSUE THREAD

**Issue by bryant-the-coder** [wez/wezterm#4903] opened 2024-01-30 04:53 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

cant run command in terminal

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

![image](https://github.com/wez/wezterm/assets/92417638/868334f8-1e30-470a-990d-d97330c7f79b)
![image](https://github.com/wez/wezterm/assets/92417638/a5a42fe4-a874-4668-838e-4eba4e886190)

### To Reproduce

I just downloaded wezterm from the AUR using `yay -S wezterm`. I cant open it

### Configuration

no config

### Expected Behavior

Wezterm run normally

### Logs

12:43:47.489  ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating
12:52:11.287  ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating
12:47:36.751  ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating

**Comment by wez** [comment] 2024-01-30 05:12
Sounds like you have a mixture of flatpak (or a leftover alias from when you had the flatpak) and some other version installed, which may make things more confusing.

That said: there are a number of open issues about hyprland and this is likely a duplicate of one of those:
https://github.com/wez/wezterm/issues?q=is%3Aissue+is%3Aopen+hyprland++

**Comment by bryant-the-coder** [comment] 2024-01-30 05:40
even after i remove the alias. i still get the same error

```
wezterm
interface 'wl_surface' has no event 2
13:39:17.169  ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=None: Resource temporarily unavailable (os error 11); terminating
warning: queue 0x55a7b77501e0 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1@4278190085 still attached
  zwp_primary_selection_offer_v1@4278190084 still attached
  zwp_primary_selection_offer_v1@4278190083 still attached
  zwp_primary_selection_offer_v1@4278190082 still attached
  wl_data_offer@4278190081 still attached
  wl_data_offer@4278190080 still attached
  wl_callback@34 still attached
  xdg_wm_base@22 still attached
  wl_surface@21 still attached
  wl_data_device@18 still attached
  wl_pointer@16 still attached
  zwp_text_input_v3@15 still attached
  wl_keyboard@14 still attached
  zwp_primary_selection_device_v1@13 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@12 still attached
  wl_output@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
```

**Comment by bryant-the-coder** [comment] 2024-01-30 06:12
ok i install `wezterm-git` and it worked. turns out the package in aur is outdated.

**Closed** 2024-01-30 13:26 UTC
Labels: bug, Wayland
