### ISSUE TITLE
Preserve tab history on exit/restore on launch

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#3091] opened 2023-02-10 10:11 UTC
**Is your feature request related to a problem? Please describe.**
iTerm has this cool feature where it __automatically__ __saves__ all the tabs' data when you quit the app and __restores__ it when you reopen the app.
It can't restore the state of the shell, but still having the same tabs with the same content is rather helpful in not breaking the workflow on restarts

**Describe the solution you'd like**
Have an option to automatically save all tab data on close and restore it on next startup when I quit the app

**Describe alternatives you've considered**
Not sure what thse would be. As far as I understand it could be possible to save the position by hooking into quit/startup events, but not the history itself

**Additional context**
Searched through the issues/discussions and there are some that are tangentially related, but not the same, they mostly cover only the composition/layout, but not the content, sorry if I missed something
  - https://github.com/wez/wezterm/issues/256
  - https://github.com/wez/wezterm/issues/1949
  - https://github.com/wez/wezterm/discussions/1665 and https://github.com/wez/wezterm/issues/1531

**Comment by wez** [comment] 2023-02-10 17:39
I consider this to be a duplicate of #256

**Closed by wez** 2023-02-10 17:39 UTC
Labels: enhancement
