### ISSUE TITLE
lua binding to `cli move-pane-to-new-tab`

### ISSUE THREAD

**Issue by psydvl** [wez/wezterm#2747] opened 2022-11-15 09:38 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to move tab to new window with keybinding, and now I can do this only with [`wezterm cli move-pane-to-new-tab`](https://wezfurlong.org/wezterm/cli/cli/move-pane-to-new-tab.html#wezterm-cli-move-pane-to-new-tab)
Which is a little ugly to use in lua config.

**Describe the solution you'd like**
Just linkage existed function will be great to action or mux_pane method.

**Additional context**
PS: Also, I hope, this function can be extended with little multiplexing to something like _attach-pane-to-new-tab_ when you just have the same pane in two different tabs or even windows.
Without additional multiplexing setting

**Comment by wez** [comment] 2022-11-15 15:16
Duplicate of https://github.com/wez/wezterm/issues/549

**Closed by wez** 2022-11-15 15:16 UTC
Labels: enhancement
