### ISSUE TITLE
Black box when using gif's in windows 11

### ISSUE THREAD

**Issue by TechAssistance** [wez/wezterm#4657] opened 2023-12-10 16:21 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

unknown

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Similar to [this report](https://github.com/wez/wezterm/issues/4131) where we get a black screen when using gif images. Sometimes saving the file again can make things work. But if you save another file in the same directory that the image is in, I had it actually break wezterm. And sometimes it seems that the .gif files just dont work at all. Not sure what's up. 

![Screenshot 2023-12-10 091705](https://github.com/wez/wezterm/assets/76240748/21126b77-6879-44d6-b8b5-d000c75e472b)

But when switching to a PNG file it works

![Screenshot 2023-12-10 091813](https://github.com/wez/wezterm/assets/76240748/9cebb8a1-069b-489f-95c5-5efa80ec715b)

When checking logs I can see this is produced consistently upon every wezterm launch.
`ERROR  wezterm_gui::glyphcache > Unable to move file data to blob manager: Io error in BlobLease: Access is denied. (os error 5)`

Here are the file details as well: 

![Screenshot 2023-12-10 091603](https://github.com/wez/wezterm/assets/76240748/a2e0b0ae-b7cb-42b2-a70a-8b092600e366)

Here are also files I have tested with and get the issue on: 

 

![giphy](https://github.com/wez/wezterm/assets/76240748/2cc10f65-d60d-40a4-96b0-fc8c500b893e)
![main](https://github.com/wez/wezterm/assets/76240748/1b0c8e0f-7e6f-4d54-b873-65fe7d3aaa45)
![rah](https://github.com/wez/wezterm/assets/76240748/32db8179-3f54-41c1-9a4e-3204e556694b)

Not really sure what is up here. 

### To Reproduce

Save gif on widows system from web (in my case using brave), then add the gif to your config file using the `config.background ` method. 

ex:
`config.background = {
    {
        source = { File = {path = 'C:/Users/someuserboi/Pictures/Backgrounds/rah.png', speed = 0.2}}
    }
}`

### Configuration

local wezterm = require 'wezterm'
local mux = wezterm.mux
local act = wezterm.action

local config = {}
local keys = {}
local mouse_bindings = {}
local launch_menu = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

--- Default config settings
config.color_scheme = 'Dracula'
config.font = wezterm.font('Hack Nerd Font')
config.font_size = 10
config.launch_menu = launch_menu
config.default_cursor_style = 'BlinkingBar'
config.disable_default_key_bindings = true
config.keys = keys
config.mouse_bindings = mouse_bindings

mouse_bindings = {
  {
    event = { Down = { streak = 3, button = 'Left' } },
    action = wezterm.action.SelectTextAtMouseCursor 'SemanticZone',
    mods = 'NONE',
  },
}

config.background = {
    {
        source = { File = {path = 'C:/Users/someuserboi/Pictures/Backgrounds/giphy.gif', speed = 0.2}}
    }
}

config.default_domain = 'WSL:Ubuntu-22.04'

return config

### Expected Behavior

Expect gif to render into wezterm and animate at the set speed

### Logs

09:16:43.024  ERROR  wezterm_gui::glyphcache > Unable to move file data to blob manager: Io error in BlobLease: Access is denied. (os error 5)

### Anything else?

No other context. Apart from this things have been easy to use and understand thus far.

**Comment by TechAssistance** [comment] 2023-12-10 18:55
And sure enough after re-launching etc it don't work anymore. Seems super buggy.

**Comment by gamephreak13** [comment] 2024-04-19 15:05
Same issue here. I tried the GIMP export work around and that didn't work.

## Running
Windows 10 22H2

## Config
**Note:** I have the correct path in my config | removed for privacy
```lua
-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This will hold the configuration.
local config = wezterm.config_builder()

-- This is where you actually apply your config choices

-- Background Image
config.window_background_image = "path\to\animation.gif"

-- and finally, return the configuration to wezterm
return config
```

## Screenshot
**Note:** I blured out the bar and initial line from console

![image](https://github.com/wez/wezterm/assets/31524849/2dfa7da5-c926-47bd-b584-3d64b60b11e5)

**Comment by wez** [comment] 2024-07-14 15:08
Sounds like a similar root cause to https://github.com/wez/wezterm/issues/5422 which is now fixed in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Closed** 2024-07-15 13:13 UTC
Labels: bug, fixed-in-nightly
