### ISSUE TITLE
Active pane not swtiched on wezterm window focus

### ISSUE THREAD

**Issue by wilriker** [wez/wezterm#996] opened 2021-08-02 10:28 UTC
## Describe the bug
wezterm will not move the internal focus to the pane that was clicked when getting wezterm window back to focus. (after any other window was focussed)

## Environment (please complete the following information):

 - OS: Linux X11, herbstluftwm tiling-window-manager
 - Version: wezterm 20210502-154244-3f7122cb
 - The active keyboard layout name: GB (`caps:none`)

## To Reproduce

1. wezterm with two panes
1. activate one of them
1. focus any other window
1. click on wezterm to get focus but click the previously inactive pane
1. wezterm window gets focus but internal focus remains in previous active pane instead of switching to the pane that was clicked

## Configuration

Happens already in default config.

## Expected behavior
I expect to have the pane focussed that I clicked.

**Comment by wez** [comment] 2021-08-02 15:40
Duplicate of https://github.com/wez/wezterm/issues/941
Please try the nightly!

**Closed by wez** 2021-08-02 15:40 UTC
Labels: bug

**Comment by wilriker** [comment] 2021-08-02 19:42
Thanks, I can confirm it's fixed in nightly build.
