### ISSUE TITLE
Crash on laptop resume

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#131] opened 2020-01-24 18:41 UTC
## Describe the bug

A running `wezterm connect` crashed on resume.

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Frontend:  OpenGL
 - Version: 20200113-222147-724ad3a-51-gb2a4ec7

## To Reproduce

1. Run `wezterm`
2. Suspend/resume laptop

## Additional context

I captured the log output:
```
wl_registry@2: error 0: invalid global wl_output (30)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: the buffers have already been swapped', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: window::os::wayland::window::WaylandWindowInner::dispatch_pending_event
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
  17: async_task::raw::RawTask<F,R,S,T>::run
  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  19: window::spawn::SpawnQueue::run
  20: <window::os::wayland::connection::WaylandConnection as window::connection::ConnectionOps>::run_message_loop
  21: wezterm::run
  22: wezterm::main
  23: std::rt::lang_start::{{closure}}
  24: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  25: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  26: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  27: std::panicking::try
             at src/libstd/panicking.rs:265
  28: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  29: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  30: main
  31: __libc_start_main
  32: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 ERROR wezterm::mux          > read_pty EOF: tab_id 1
 ERROR wezterm::mux          > read_pty EOF: tab_id 2
 ERROR wezterm::mux          > read_pty EOF: tab_id 3
 ERROR wezterm::mux          > read_pty EOF: tab_id 4
 ERROR wezterm::mux          > read_pty EOF: tab_id 5
 ERROR wezterm::mux          > read_pty EOF: tab_id 0
```

**Comment by wez** [comment] 2020-01-25 01:06
I suspect that the panic is because of this unwrap:

https://github.com/wez/wezterm/blob/master/window/src/os/wayland/window.rs#L478

which I think is caused by this synthetic error return where we don't know for sure that the buffers were already swapped:

https://github.com/wez/wezterm/blob/8950c6cc2410d68c50eba997f7b359333b9a49e3/window/src/egl.rs#L355

The very first line in your post above:

```
wl_registry@2: error 0: invalid global wl_output (30)
```

`wl_output` refers to display devices in wayland; those are handled via smithay-client-toolkit.  My guess is that we render while those are being re-jiggered perhaps because your laptop switched from integrated graphics to the gpu and back and then we bubble up to the unwrap.

I'd suggest replacing that unwrap with a log::error! and see if we get any further next time you perform a similar suspend/resume.

This doesn't happen for me when I suspend my pixelbook, but it only has integrated graphics and not anything more fancy than that.

**Comment by jsgf** [comment] 2020-01-25 15:25
Laptop is a Lenovo X1 Yoga with only integrated graphics.

**Comment by wez** [comment] 2020-10-02 14:08
Closing this out; it's unresolved but the defaults in wezterm have since changed to avoid wayland and I haven't had any other similar reports.

**Closed by wez** 2020-10-02 14:08 UTC
Labels: Linux, Wayland, bug
