### ISSUE TITLE
Background black on wayland, other colors not correct either

### ISSUE THREAD

**Issue by wrbright** [wez/wezterm#3316] opened 2023-03-21 20:54 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Wayland version 1.21.0-2 KWin inside the Plasma desktop on arch linux with a Nvidia Graphics card

### WezTerm version

wezterm 20230321-091724-0b83c974

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

As shown in the following images, the colors on the terminal act very strange on wayland, but not with xwayland or in an x11 environment. Same behavior exists with ``wezterm -n`` or when moving my config file. When configured, any specified color is heavily darkened and setting opacity simply darkens the colors.  No errors are logged to the debug overlay.
### wayland (not configured)
![Screenshot_20230321_165238](https://user-images.githubusercontent.com/55282244/226738728-a6fe766b-8f8f-4b20-b264-32c5608f8761.png)

### xwayland (configured)
![Screenshot_20230321_180039](https://user-images.githubusercontent.com/55282244/226739875-84adc274-0494-406a-9bc9-1fffe203fda5.png)

### To Reproduce

Start wezterm in a wayland session

### Configuration

no config

### Expected Behavior

Wezterm colors are the same as on x11 or xwayland

### Logs

Debug Overlay
wezterm version: 20230321-091724-0b83c974 x86_64-unknown-linux-gnu
Window Environment: Wayland
OpenGL version: NVIDIA GeForce RTX 2070 Super with Max-Q Design/PCIe/SSE2 4.6.0 NVIDIA 525.89.02
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>

### Anything else?

This behavior occurs on the aurs version which seems to be, at the time of writing, one version behind. This behavior also exists after following the build from source instructions. I have not attempted the stabel version on the Arch repos.

I cannot confirm this has ever worked correctly, as I installed wezterm yesterday while using x11 temporarily 

One last thing, entirely unrelated, but I absolutely love this Terminal Emulator. Fantastic work, the code-base is very clean too. Apologies for the praise in an issue but you've done something great here. Thank you for this tool

**Comment by wez** [comment] 2023-03-21 21:01
Thanks for the kind words!

Unfortunately, nvidia and wayland have patchy support from the respective vendor(s).  There are several open issues with nvidia + proprietary drivers + wayland.  There's not really anything wezterm can do about it.

My suggestions are:

* Run X11, or XWayland.
* Try using the [WebGpu frontend](https://wezfurlong.org/wezterm/config/lua/config/front_end.html?h=#webgpu) to see if it works differently (users report mixed results)
* What I did: moved to an AMD card for my Linux box and my life is free of a number of headaches. Note that I also run X11. I think Wayland is getting better and better, but it's still not ready for me to be productive.

See also:
* https://github.com/wez/wezterm/issues/1701 (your issue is likely a duplicate of that issue)

**Comment by wez** [comment] 2023-03-21 21:46
Thanks for confirming! Let's close this in favor of #1701

**Closed by wez** 2023-03-21 21:46 UTC
Labels: bug
