### ISSUE TITLE
Crashing upon entering tmux CC mode

### ISSUE THREAD

**Issue by salehqt** [wez/wezterm#6133] opened 2024-09-13 16:03 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Cinnamon default

### WezTerm version

20240812-215703-30345b36

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

I downloaded https://github.com/wez/wezterm/releases/download/nightly/wezterm-nightly-fedora40.rpm today.

### Describe the bug

Crash as soon as I type `tmux -CC` and enter

### To Reproduce

Scenario 1:
1. SSH into a devserver
2. Run tmux -CC

Scenario 2:
1. Run tmux -CC on local machine

### Configuration

no config

### Expected Behavior

See the tmux windows

### Logs

[wezterm-gui-log-33180.txt](https://github.com/user-attachments/files/16996485/wezterm-gui-log-33180.txt)

From the terminal:
```
12:01:14.772  INFO   mux::localpane > tmux -CC mode requested
12:01:14.772  INFO   mux::tmux      > tmux: Guarded(Guarded { error: false, timestamp: 1726243274, number: 23106, flags: 0, output: "" }) in state WaitForInitialGuard
12:01:14.772  INFO   mux::tmux      > tmux: WindowAdd { window: 9 } in state Idle
12:01:14.772  INFO   mux::tmux      > Tmux create window id 1
12:01:14.772  INFO   mux::tmux      > tmux: SessionsChanged in state Idle
12:01:14.772  INFO   mux::tmux      > tmux: SessionChanged { session: 1, name: "1" } in state Idle
12:01:14.772  INFO   mux::tmux      > tmux session changed:1
12:01:14.772  INFO   mux::tmux      > tmux: Output { pane: 9, text: "\u{1b}]0;devvm24708.atn0 ~\u{7}" } in state Idle
12:01:14.772  ERROR  mux::tmux      > Tmux pane 9 havn't been attached
12:01:14.773  INFO   mux::tmux      > tmux: Output { pane: 9, text: "\u{1b}[?2004h[salh@devvm24708.atn0 ~]$ " } in state Idle
12:01:14.773  ERROR  mux::tmux      > Tmux pane 9 havn't been attached
12:01:14.773  INFO   mux::tmux      > sending cmd "list-panes -aF '#{session_id} #{window_id} #{pane_id} #{pane_index} #{cursor_x} #{cursor_y} #{pane_width} #{pane_height} #{pane_left} #{pane_top}'\n"
12:01:14.914  INFO   mux::tmux      > tmux: Guarded(Guarded { error: false, timestamp: 1726243274, number: 23113, flags: 1, output: "$0 @8 %8 0 32 87 182 88 0 0\n$0 @3 %3 0 83 43 148 44 0 0\n$0 @4 %4 0 58 43 148 44 0 0\n$0 @5 %5 0 89 43 148 44 0 0\n$1 @9 %9 0 26 0 80 25 0 0\n" }) in state WaitingForResponse
12:01:14.917  ERROR  env_bootstrap  > panic at /__w/wezterm/wezterm/vendor/async-task-4.7.1/src/runnable.rs:451:17 - local task polled by a thread that didn't spawn it
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: __libc_start_call_main
  17: __libc_start_main@@GLIBC_2.34
  18: <unknown>

thread 'main' panicked at /__w/wezterm/wezterm/vendor/async-task-4.7.1/src/runnable.rs:451:17:
local task polled by a thread that didn't spawn it
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
12:01:14.917  ERROR  env_bootstrap  > panic at /__w/wezterm/wezterm/vendor/async-task-4.7.1/src/runnable.rs:437:17 - local task dropped by a thread that didn't spawn it
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: __libc_start_call_main
  18: __libc_start_main@@GLIBC_2.34
  19: <unknown>

thread 'main' panicked at /__w/wezterm/wezterm/vendor/async-task-4.7.1/src/runnable.rs:437:17:
local task dropped by a thread that didn't spawn it
stack backtrace:
   0:     0x55a5957b0335 - <unknown>
   1:     0x55a5957df7bb - <unknown>
   2:     0x55a5957aaedf - <unknown>
   3:     0x55a5957b1bd1 - <unknown>
   4:     0x55a5957b18ac - <unknown>
   5:     0x55a593ca2d54 - <unknown>
   6:     0x55a5957b246f - <unknown>
   7:     0x55a5957b2063 - <unknown>
   8:     0x55a5957b07f9 - <unknown>
   9:     0x55a5957b1d24 - <unknown>
  10:     0x55a59386eff3 - <unknown>
  11:     0x55a5946d0794 - <unknown>
  12:     0x55a59475e5d7 - <unknown>
  13:     0x55a59474c5a3 - <unknown>
  14:     0x55a59498f56d - <unknown>
  15:     0x55a5948ef5b5 - <unknown>
  16:     0x55a593b35d09 - <unknown>
  17:     0x55a593b38d84 - <unknown>
  18:     0x55a593b90e53 - <unknown>
  19:     0x55a593c3ff19 - <unknown>
  20:     0x55a5957a15b0 - <unknown>
  21:     0x55a593b41985 - <unknown>
  22:     0x7f45b3439088 - __libc_start_call_main
  23:     0x7f45b343914b - __libc_start_main@@GLIBC_2.34
  24:     0x55a59386f905 - <unknown>
  25:                0x0 - <unknown>
12:01:14.921  ERROR  env_bootstrap  > panic at /__w/wezterm/wezterm/vendor/async-task-4.7.1/src/utils.rs:17:5 - aborting the process
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: __libc_start_call_main
  19: __libc_start_main@@GLIBC_2.34
  20: <unknown>

thread 'main' panicked at /__w/wezterm/wezterm/vendor/async-task-4.7.1/src/utils.rs:17:5:
aborting the process
stack backtrace:
   0:     0x55a5957b0335 - <unknown>
   1:     0x55a5957df7bb - <unknown>
   2:     0x55a5957aaedf - <unknown>
   3:     0x55a5957b1bd1 - <unknown>
   4:     0x55a5957b18ac - <unknown>
   5:     0x55a593ca2d54 - <unknown>
   6:     0x55a5957b246f - <unknown>
   7:     0x55a5957b2063 - <unknown>
   8:     0x55a5957b07f9 - <unknown>
   9:     0x55a5957b1d24 - <unknown>
  10:     0x55a59386eff3 - <unknown>
  11:     0x55a59566340a - <unknown>
  12:     0x55a595663457 - <unknown>
  13:     0x55a59475e7ae - <unknown>
  14:     0x55a59474c5a3 - <unknown>
  15:     0x55a59498f56d - <unknown>
  16:     0x55a5948ef5b5 - <unknown>
  17:     0x55a593b35d09 - <unknown>
  18:     0x55a593b38d84 - <unknown>
  19:     0x55a593b90e53 - <unknown>
  20:     0x55a593c3ff19 - <unknown>
  21:     0x55a5957a15b0 - <unknown>
  22:     0x55a593b41985 - <unknown>
  23:     0x7f45b3439088 - __libc_start_call_main
  24:     0x7f45b343914b - __libc_start_main@@GLIBC_2.34
  25:     0x55a59386f905 - <unknown>
  26:                0x0 - <unknown>
12:01:14.923  ERROR  env_bootstrap  > panic at /__w/wezterm/wezterm/vendor/async-task-4.7.1/src/utils.rs:12:13 - aborting the process
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: __libc_start_call_main
  19: __libc_start_main@@GLIBC_2.34
  20: <unknown>

thread 'main' panicked at /__w/wezterm/wezterm/vendor/async-task-4.7.1/src/utils.rs:12:13:
aborting the process
stack backtrace:
   0:     0x55a5957b0335 - <unknown>
   1:     0x55a5957df7bb - <unknown>
   2:     0x55a5957aaedf - <unknown>
   3:     0x55a5957b1bd1 - <unknown>
   4:     0x55a5957b18ac - <unknown>
   5:     0x55a593ca2d54 - <unknown>
   6:     0x55a5957b246f - <unknown>
   7:     0x55a5957b2063 - <unknown>
   8:     0x55a5957b07f9 - <unknown>
   9:     0x55a5957b1d24 - <unknown>
  10:     0x55a59386eff3 - <unknown>
  11:     0x55a59566343d - <unknown>
  12:     0x55a595663457 - <unknown>
  13:     0x55a59475e7ae - <unknown>
  14:     0x55a59474c5a3 - <unknown>
  15:     0x55a59498f56d - <unknown>
  16:     0x55a5948ef5b5 - <unknown>
  17:     0x55a593b35d09 - <unknown>
  18:     0x55a593b38d84 - <unknown>
  19:     0x55a593b90e53 - <unknown>
  20:     0x55a593c3ff19 - <unknown>
  21:     0x55a5957a15b0 - <unknown>
  22:     0x55a593b41985 - <unknown>
  23:     0x7f45b3439088 - __libc_start_call_main
  24:     0x7f45b343914b - __libc_start_main@@GLIBC_2.34
  25:     0x55a59386f905 - <unknown>
  26:                0x0 - <unknown>
12:01:14.924  ERROR  env_bootstrap  > panic at library/core/src/panicking.rs:229:5 - panic in a destructor during cleanup
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: __libc_start_call_main
  21: __libc_start_main@@GLIBC_2.34
  22: <unknown>

thread 'main' panicked at library/core/src/panicking.rs:229:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
Aborted (core dumped)
```

**Comment by loops** [comment] 2024-09-13 16:20
Hi salehqt,

Unfortunately Tmux is still not expected to work.  You can see this panic report submitted by someone else 
here: https://github.com/wez/wezterm/issues/3223   Where Wez mentions that the implementation is
still incomplete and references:  https://github.com/wez/wezterm/issues/336

You can close this issue for now.  Since it's already known and being tracked.

**Comment by wez** [comment] 2024-09-15 13:13
Duplicate of #3223

**Closed by wez** 2024-09-15 13:13 UTC
Labels: bug
