### ISSUE TITLE
Fcitx support?

### ISSUE THREAD

**Issue by MiraculousMoon** [wez/wezterm#361] opened 2020-12-07 15:42 UTC
**Is your feature request related to a problem? Please describe.**
Can it support fcitx so I can input Chinese on it?

**Describe the solution you'd like**
I don't know how to implement it now... But alacritty can do it, so I think it can be done on wezterm?

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by wez** [comment] 2020-12-07 17:08
Duplicate of #250

**Closed by wez** 2020-12-07 17:08 UTC
Labels: enhancement
