### ISSUE TITLE
hang when hovering over splits on macOS

### ISSUE THREAD

**Issue by sapi01** [wez/wezterm#391] opened 2020-12-22 05:40 UTC
## Describe the bug
I noticed that, when I vertical split the tab and get the cursor out-of-focus(click somewhere) and return back to WizTerm, I noticed it becomes totally unresponsive. I noticed this specifically with vertical split.

## Environment (please complete the following information):

 - OS: macOS(version: 11.1 Big Sur)
 - Version: wezterm 20201101-103216-403d002d

## To Reproduce

Open a new tab, press `CTRL + SHIFT + ALT + %" to vertical split, move the cursor out-of-focus(click somewhere on the screen, other than WezTerm) and now click-back(focus) the cursor to WizTerm, it becomes unresponsive. I have to close the WizTerm application and re-open to use the terminal emulator. 
I have included a screen recording: https://streamable.com/72vpub

## Configuration

```lua
local wezterm = require 'wezterm';

return {
        default_cursor_style = "SteadyBar",
        send_composed_key_when_left_alt_is_pressed=false,
        send_composed_key_when_right_alt_is_pressed=true,
        leader = { key="a", mods="CTRL", timeout_milliseconds=1000 },
        keys = {
                {key="RightArrow", mods="CMD", action=wezterm.action{SendString="\x05"}},
                {key="LeftArrow", mods="CMD", action=wezterm.action{SendString="\x01"}},
                {key="{", mods="SHIFT|ALT", action=wezterm.action{MoveTabRelative=-1}},
                {key="}", mods="SHIFT|ALT", action=wezterm.action{MoveTabRelative=1}},
        }

}
```

## Expected behavior
It should not freeze when I do vertical split and work on somewhere(other than terminal-emulator) and comeback to WizTerm. 

## Session Recording
https://bayfiles.com/Z6vd0418pf

I also noticed some "ERROR" popping up: 
![image](https://user-images.githubusercontent.com/117777/102856337-2144fc00-43db-11eb-802e-e7ee9b299bf8.png)

**Comment by wez** [comment] 2020-12-22 06:28
The NSCursor selector error was fixed in 5b8b41adbb3782516c21bdaf3e090cb8da559511
That could bubble up as an exception and lead to things being unresponsive.  The cause is mousing over a split, rather than selecting or re-focusing.

I'd suggest updating to a nightly build which has that fixed, however, while I was testing this locally I noticed that key assignments that include Option weren't working in the nightly builds due to some recent refactoring.  3d37b4a95644102fad845fde31a5ab683f9aacda fixes that, so I'd suggest grabbing a nightly in an hour or two.

**Comment by sapi01** [comment] 2020-12-22 13:49
@wez Ok, I just grabbed the nightly from installation section of your website, the hang issue when hovering over splits is Fixed, but all my fonts and ligatures that I had out-of-box before(previous WizTerm that I shared with you) are for some reason gone. The fonts looks like crap now, can you please help me fix this?

SCREENSHOT: https://pasteboard.co/JG6NmJS.png

**Comment by wez** [comment] 2020-12-22 17:48
You may want to set `font_antialias = "Greyscale"` to get a bolder appearance.

On macOS, the default dpi was reduced to 72 to bring the font point size setting into alignment with other macOS apps, so you may wish to set `font_size = 13` if you want to bring the font size back up to the apparent size from the prior release.  (default is `10` and technically speaking you want to set it to `10.0 * 96.0 / 72.0` to get precisely the prior size, which is `13.333333`).

Ligatures haven't changed; can you tell me more about what isn't working for you there?

**Comment by sapi01** [comment] 2020-12-22 18:34
![Screenshot 2020-12-22 at 1 25 13 PM](https://user-images.githubusercontent.com/71412187/102920820-61e35a80-4459-11eb-9ead-1185803ec2b1.png)

Im looking for exact match of the "font sharpness"(I can notice the pix of some letters example, "NORMAL" in the neovim's bottom and "w" in ".wizterm.lua" inside neovim).

Im also trying to get the exact color palette like bit sharper and concentrated green, orange, red and colors. You can easily notice the color diff with those two terminals. My target to get to the one on the left(underneath one), you can also notice the BG of the one underneath is bit more darker and sharp. 

These are the few things Im trying to make it work in nightly.

**Comment by wez** [comment] 2020-12-26 23:47
I'm going to close this out as the hang is resolved.  In the element/gitter channel you mentioned that you were going to try changing some options around rendering; we can continue that part of the conversation over there.

**Closed by wez** 2020-12-26 23:47 UTC
Labels: bug, macOS
