### ISSUE TITLE
Changing window size decreases dpi on linux hdpi monitor when overriding the dpi in the config

### ISSUE THREAD

**Issue by blue-devil** [wez/wezterm#2914] opened 2023-01-03 11:43 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

XFCE4

### WezTerm version

wezterm 20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

My host machine is macOS(Retina 5K). I have a ArchLinux XFCE4 vm running and I also use wezterm on my linux machine. Here is my config file:
```
$ cat .wezterm.lua 
local wezterm = require 'wezterm';

return {
  font = wezterm.font("Fira Code"),
  color_scheme = "Builtin Solarized Dark",
  dpi = 144.0,
  window_background_opacity = 0.90,
}
```

When I launch wezterm (from any where) its scaling is OK. But when I change the size of the wezterm window it decreases like I did not set `dpi` value. Here is a picture

![wez-ss](https://user-images.githubusercontent.com/10853207/210351359-e24cc39c-a426-48fb-99a4-e093c8e012c8.png)

Look at the picture the big in size is the one when I first run wezterm. The smaller one is the one which I resized window.

### To Reproduce

While using an HDPI screen Install Archlinux with XFCE4. Install latest wezterm. Set the wezterm config to the values I have shared above. Then change window size.

### Configuration

```
$ cat .wezterm.lua 
local wezterm = require 'wezterm';

return {
  font = wezterm.font("Fira Code"),
  color_scheme = "Builtin Solarized Dark",
  dpi = 144.0,
  window_background_opacity = 0.90,
}
```

### Expected Behavior

After setting `dpi` value to 144, the window and fonts should stay as the same size when I change size of window.

### Logs

$ WEZTERM_LOG=wezterm_gui::termwindow=trace,wezterm_gui::termwindow::render=info,info wezterm > wez.log
12:28:38.564  TRACE  wezterm_gui::termwindow > using render_metrics RenderMetrics {
    descender: -7.0,
    descender_row: 24,
    descender_plus_two: 26,
    underline_height: 1,
    strike_row: 12,
    cell_size: 14x29,
}
12:28:38.570  TRACE  wezterm_gui::termwindow > Initial geometry was TerminalSize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384, dpi: 144 } but dpi-adjusted geometry is TerminalSize { rows: 24, cols: 80, pixel_width: 1120, pixel_height: 696, dpi: 144 }; update the kernel pixel geometry for the ptys!
12:28:38.570  TRACE  wezterm_gui::termwindow > TermWindow::new_window called with mux_window_id 0 TerminalSize { rows: 24, cols: 80, pixel_width: 1120, pixel_height: 696, dpi: 144 } Dimensions { pixel_width: 1148, pixel_height: 774, dpi: 144 }
12:28:38.571  TRACE  wezterm_gui::termwindow > RequestedWindowGeometry { width: Pixels(1148.0), height: Pixels(774.0), x: None, y: None, origin: ScreenCoordinateSystem }
12:28:38.584  DEBUG  wezterm_gui::termwindow > FocusChanged(true)
12:28:38.584  TRACE  wezterm_gui::termwindow > Setting focus to true
12:28:38.658  DEBUG  wezterm_gui::termwindow > KeyEvent(KeyEvent { key: Char('\r'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: NONE, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: false, handled: Handled(false) }) })
12:28:38.658  TRACE  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\r'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(Return), modifiers: NONE, phys_code: Some(Return), raw_code: 36, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
12:28:38.669  DEBUG  wezterm_gui::termwindow           > NeedRepaint
12:28:38.669  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.707  DEBUG  wezterm_gui::termwindow           > OpenGL initialized! virgl (AMD Radeon Pro 5500 XT OpenGL Engine (Compat)) 4.0 (Compatibility Profile) Mesa 22.3.1 wezterm version: 20221119-145034-49b9839f
12:28:38.707  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.708  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.709  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.709  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.709  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.709  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.709  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.712  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.712  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.712  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.713  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.713  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.724  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.724  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.724  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.724  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.724  DEBUG  wezterm_gui::termwindow           > NeedRepaint
12:28:38.808  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.808  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.808  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:38.825  DEBUG  wezterm_gui::termwindow           > NeedRepaint
12:28:39.585  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:39.585  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:39.585  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.461  DEBUG  wezterm_gui::termwindow           > RawKeyEvent(RawKeyEvent { key: Physical(LeftAlt), modifiers: NONE, phys_code: Some(LeftAlt), raw_code: 64, repeat_count: 1, key_is_down: true, handled: Handled(false) })
12:28:40.461  TRACE  wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftAlt), modifiers: NONE, phys_code: Some(LeftAlt), raw_code: 64, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
12:28:40.461  DEBUG  wezterm_gui::termwindow           > KeyEvent(KeyEvent { key: Alt, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftAlt), modifiers: NONE, phys_code: Some(LeftAlt), raw_code: 64, repeat_count: 1, key_is_down: true, handled: Handled(false) }) })
12:28:40.461  TRACE  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Alt, modifiers: NONE, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftAlt), modifiers: NONE, phys_code: Some(LeftAlt), raw_code: 64, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
12:28:40.469  DEBUG  wezterm_gui::termwindow           > RawKeyEvent(RawKeyEvent { key: Physical(LeftControl), modifiers: ALT, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) })
12:28:40.469  TRACE  wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(LeftControl), modifiers: ALT, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
12:28:40.469  DEBUG  wezterm_gui::termwindow           > KeyEvent(KeyEvent { key: Control, modifiers: ALT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: ALT, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) })
12:28:40.469  TRACE  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: ALT, repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: ALT, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
12:28:40.469  DEBUG  wezterm_gui::termwindow           > FocusChanged(false)
12:28:40.469  TRACE  wezterm_gui::termwindow           > Setting focus to false
12:28:40.469  DEBUG  wezterm_gui::termwindow           > MouseLeave
12:28:40.471  DEBUG  wezterm_gui::termwindow           > Resized { dimensions: Dimensions { pixel_width: 2552, pixel_height: 1347, dpi: 96 }, window_state: (empty), live_resizing: true }
12:28:40.471  TRACE  wezterm_gui::termwindow::resize   > resize event, live=true current cells: RowsAndCols { rows: 24, cols: 80 }, current dims: Dimensions { pixel_width: 1148, pixel_height: 774, dpi: 144 }, new dims: Dimensions { pixel_width: 2552, pixel_height: 1347, dpi: 96 } window_state:(empty)
12:28:40.471  TRACE  wezterm_gui::termwindow::resize   > dpi_changed=true, font_scale_changed=false scale_changed=true simple_dpi_change=false
12:28:40.479  TRACE  wezterm_gui::termwindow::resize   > scaling_changed, follow with applying dimensions. scale_changed_cells=None
12:28:40.479  TRACE  wezterm_gui::termwindow::resize   > apply_dimensions Dimensions { pixel_width: 2552, pixel_height: 1347, dpi: 96 } scale_changed_cells None. window_state (empty)
12:28:40.484  TRACE  wezterm_gui::termwindow::resize   > apply_dimensions computed size TerminalSize { rows: 64, cols: 253, pixel_width: 2530, pixel_height: 1280, dpi: 96 }, dims Dimensions { pixel_width: 2552, pixel_height: 1347, dpi: 96 }
12:28:40.485  DEBUG  wezterm_gui::termwindow           > FocusChanged(true)
12:28:40.485  TRACE  wezterm_gui::termwindow           > Setting focus to true
12:28:40.485  DEBUG  wezterm_gui::termwindow           > NeedRepaint
12:28:40.495  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.495  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.510  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.512  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:40.526  DEBUG  wezterm_gui::termwindow           > NeedRepaint
12:28:41.001  DEBUG  wezterm_gui::termwindow           > KeyEvent(KeyEvent { key: Control, modifiers: ALT | CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: ALT | CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) })
12:28:41.001  TRACE  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Control, modifiers: ALT | CTRL, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftControl), modifiers: ALT | CTRL, phys_code: Some(LeftControl), raw_code: 37, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
12:28:41.016  DEBUG  wezterm_gui::termwindow           > KeyEvent(KeyEvent { key: Alt, modifiers: ALT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftAlt), modifiers: ALT, phys_code: Some(LeftAlt), raw_code: 64, repeat_count: 1, key_is_down: false, handled: Handled(false) }) })
12:28:41.016  TRACE  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Alt, modifiers: ALT, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(LeftAlt), modifiers: ALT, phys_code: Some(LeftAlt), raw_code: 64, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
12:28:41.470  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:41.470  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:41.470  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:41.768  DEBUG  wezterm_gui::termwindow           > FocusChanged(false)
12:28:41.769  TRACE  wezterm_gui::termwindow           > Setting focus to false
12:28:41.769  DEBUG  wezterm_gui::termwindow           > NeedRepaint
12:28:41.770  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:41.770  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:41.770  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:41.770  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:42.769  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:42.769  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })
12:28:42.769  DEBUG  wezterm_gui::termwindow           > Notification(Any { .. })

**Comment by niclashoyer** [comment] 2023-01-18 21:31
I can confirm this on Ubuntu 22.10 using wayland

**Comment by niclashoyer** [comment] 2023-01-18 22:19
I added a fix for this in #2978, but I don't know if this was the right place to override the dpi from the configuration. At least it is working for me now 👍🏽

**Closed** 2023-01-19 03:07 UTC
Labels: bug

**Comment by wez** [comment] 2023-01-19 03:12
Thanks to @niclashoyer, this should be fixed now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by blue-devil** [comment] 2023-01-19 07:04
@wez  and @niclashoyer you are great thank you guys!
I have check nightly build on my machine and it work like a charm.
I hope you will update the latest tag soon!

**Comment by niclashoyer** [comment] 2023-01-19 11:07
@wez @blue-devil maybe we could also talk about why we changed our config in the first place? For me the dpi recognition is not sufficient on GNOME. My screen says it is 96dpi, but it actually is smaller (FHD on 14"). With an external monitor the scaling is ok, but as soon as I switch to the internal display of my notebook I need to set the font scale using gnome tweaks to at least 1.2.

So I manually set the dpi to 120 to circumvent this. I don't know how we could read the font scaling setting from GNOME to use in wezterm. Most programs like firefox seem to recognize the setting, though.

On the other side I also like to know why my internal screen is reported as 96dpi, while it seems to be more like 150 dpi. This might be a hardware issue then?

**Comment by wez** [comment] 2023-01-19 15:01
@niclashoyer are you running under Wayland? There are no Wayland protocols to correctly report the true dpi or to communicate settings like text scaling.  GTK apps cheat: they just look at the GTK/Gnome settings, but other applications don't know how to do that, so they are disadvantaged.

Under X11, the situation is slightly better, but still less than ideal. There is a desktop-environment agnostic protocol called xsettings that publishes some of this sort of information; wezterm uses the documented values from that protocol to influence the detected dpi.  Ultimately, it is trusting what the system tells it about the dpi.

Why not simply read the gtk settings directly? I cannot and do not want to link wezterm to the GTK runtime, and we don't know if we really should read it by default.  For example, what if you have both gnome and kde environments installed, but prefer kde?

What I have in my config is this lua module, saved at: `~/.config/wezterm/wayland.lua`

```lua
local wezterm = require 'wezterm'
local mod = {}

local function gsettings(key)
  return wezterm.run_child_process({"gsettings", "get", "org.gnome.desktop.interface", key})
end

function mod.apply_xcursor(config)
  if wezterm.target_triple ~= "x86_64-unknown-linux-gnu" then
    -- skip this if we are not on linux
    return
  end
  local success, stdout, stderr = gsettings("cursor-theme")
  if success then
    config.xcursor_theme = stdout:gsub("'(.+)'\n", "%1")
  end

  local success, stdout, stderr = gsettings("cursor-size")
  if success then
    config.xcursor_size = tonumber(stdout)
  end

  config.enable_wayland = true

  if config.enable_wayland and os.getenv("WAYLAND_DISPLAY") then
    local success, stdout, stderr = gsettings("text-scaling-factor")
    if success then
      config.font_size = (config.font_size or 10.0) * tonumber(stdout)
    end
  end

end

return mod
```

which I use like this in my main config:

```lua
local wayland = require 'wayland'
local config = {}

wayland.apply_xcursor(config)

return config
```

I can choose to apply `wayland.apply_xcursor` conditionally in code if I wish.

I would like to have something that is better integrated and presents fewer headaches by default, but many wezterm users are power users and making opinionated default decisions usually results in bugs being filed against wezterm :-/

**Comment by niclashoyer** [comment] 2023-01-19 15:07
@wez I think a custom lua module is just fine for this, just like dark/light mode switching as explained in the docs
