### ISSUE TITLE
Terminal windows open with the incorrect number of rows and columns

### ISSUE THREAD

**Issue by mivok** [wez/wezterm#1039] opened 2021-08-18 01:58 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20210814-124438-54e29167 (and wezterm 20210816-234431-24d971c8)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

On a macbook, I opened wezterm and the terminal looked smaller than I expected. This is what I saw on a freshly opened terminal:

```
❯ echo $COLUMNS
159
❯ echo $LINES
50
❯ grep init ~/.config/wezterm/wezterm.lua
  initial_cols = 169,
  initial_rows = 49,
```

After some digging, I found that the initial_rows setting I had was just slightly too large for the screen, and so the window got resized, but in the process the number of columns got shrunk too, and weirdly, the number of rows _grew_ by one.

### To Reproduce

Open wezterm with the configuration below, making sure initial_rows is enough to overflow the screen size. I _think_ you need to be on a retina display to reproduce the problem also.

### Configuration

This is a stripped down config file where I was able to reproduce the issue:

```
local wezterm = require 'wezterm';

return {
  font = wezterm.font_with_fallback({
    "Hack Nerd Font", -- The main font I want to use
    "Menlo", -- This has the check mark and cross symbols
    "Apple Color Emoji" -- I prefer apple emoji to google emoji
  }, {weight="Medium"}),
  font_size = 14,
  initial_cols = 169,
  initial_rows = 49,
}
```

I was able to reproduce the issue without the font setting, but I did need to add font_size=14. I wasn't able to reproduce if I left out either of the font_size or initial_cols/rows settings. The initial_rows setting needs to be enough to be larger than your screen's height (pick 300 or something if 49 isn't enough).

### Expected Behavior

Terminal opens with the correct size.

### Logs

When I ran wezterm with `WEZTERM_LOG=window=trace,wezterm_gui::termwindow=trace,info wezterm --config-file=basic-config.lua 2>wezterm-debug.log` I got the following (among a bunch of other trace information):

```
 2021-08-18T01:57:22.973Z TRACE wezterm_gui::termwindow        > TermWindow::new_window called with mux_window_id 0 PtySize { rows: 49, cols: 169, pixel_width: 1352, pixel_height: 833 } Dimensions { pixel_width: 1352, pixel_height: 850, dpi: 72 }
 2021-08-18T01:57:23.009Z TRACE window                         > Resized { dimensions: Dimensions { pixel_width: 2704, pixel_height: 1694, dpi: 144 }, window_state: (empty) }
 2021-08-18T01:57:23.009Z TRACE wezterm_gui::termwindow::resize > resize event, current cells: RowsAndCols { rows: 49, cols: 169 }, new dims: Dimensions { pixel_width: 2704, pixel_height: 1694, dpi: 144 } window_state:(empty)
 2021-08-18T01:57:23.019Z TRACE wezterm_gui::termwindow::resize > apply_dimensions Dimensions { pixel_width: 2704, pixel_height: 1694, dpi: 144 } scale_changed_cells None. window_state (empty)
 2021-08-18T01:57:23.019Z TRACE wezterm_gui::termwindow::resize > apply_dimensions computed size PtySize { rows: 50, cols: 159, pixel_width: 2703, pixel_height: 1650 }, dims Dimensions { pixel_width: 2704, pixel_height: 1694, dpi: 144 }
```

### Anything else?

It looks like the terminal window gets resized if it's larger than the screen, which makes sense, but that when it does, the width of the window is determined incorrectly, even though the height of the window is what overflowed.

I was able to reproduce this on my Macbook Pro 13" (with init_rows=50) and on my work laptop (Macbook Pro 16"), but only when setting init_rows to a larger value (e.g. 300), because it has a larger screen. I was also only able to reproduce this on the laptop display, which is a retina display, and not an attached display, which was a regular monitor.

If I start wezterm with different column widths (e.g. with `wezterm --config-file=basic-config.lua --config=initial_cols=159`), and an init_rows/font_size setting that reproduces the bug, I see the following:

* initial_cols=169, actual=159
* initial_cols=180, actual=169
* initial_cols=150, actual=141
* initial_cols=80, actual=75

So it's not off by a constant amount.

**Comment by wez** [comment] 2021-09-10 04:12
I've been looking at this tonight, and I don't think it's a bug: what's happening is that macOS doesn't want the window to be taller than the screen, so it resizes the height to fit.  That resize happens after we've created the window, and it is indistinguishable from the user manually resizing the window to the new pixel size (albeit: at that time we now know that the display is retina), so we end up recomputing the cell matrix to fit the new pixel dimensions forced by macOS.

It the cell matrix didn't fit the new pixel dimensions then it would be a bug, but since that appears to be OK, this looks like it is working as intended.

**Comment by mivok** [comment] 2021-09-23 16:06
Hey, sorry, I meant to respond much sooner than now. I agree that macOS resizing the window is expected behavior, but the problem I had was that although only the height was out of bounds, the width of the window changed also.

I think there's an issue where, on retina displays, wezterm isn't correctly working out the number of rows/columns for a given resolution.

I noticed a couple of related issues since initially reporting this that might shed some light on what I'm seeing:

I have the following configuration set up which allows me to resize the window to a specific size with hotkeys:

```
-- Resize the window (called by event handlers)
function resize_window(window, pane, cols, rows)
  local overrides = window:get_config_overrides() or {}
  overrides.initial_cols = cols
  overrides.initial_rows = rows
  window:set_config_overrides(overrides)
  window:perform_action("ResetFontAndWindowSize", pane)
end

-- Resize window handlers
wezterm.on("resize-small", function(window, pane)
  resize_window(window, pane, 169, 49)
end)

wezterm.on("resize-large", function(window, pane)
  resize_window(window, pane, 201, 49)
end)

return {
  keys =  {
      key = "1",
      mods = "LEADER",
      action = wezterm.action {EmitEvent="resize-small"}
    }, {
      key = "2",
      mods = "LEADER",
      action = wezterm.action {EmitEvent="resize-large"}
    }
  }
}
```

If I run that on my external monitor (non-retina) it works fine, but if I run it on my retina display, it resizes to the wrong size, what appears to be roughly half the width and height.

Another weird issue I see is if I drag a terminal window between monitors, and keep the cursor near the edge, then the window resizes in a strange way, getting wider and wider. I tried to get a recording here (it only shows my main monitor, but my laptop monitor is to the left where I'm dragging the window to):

https://user-images.githubusercontent.com/60603/134543037-9bde7075-544f-4e5d-b4d4-29876468af46.mov

I mention these other issues because I'm guessing they have the same cause, and hopefully are easier to reproduce. If you want to see my full config, it's at https://github.com/mivok/dotfiles/blob/master/terminal/.config/wezterm/wezterm.lua

**Comment by wez** [comment] 2021-12-11 16:46
Using `ResetFontAndWindowSize` together with config overrides is a clever trick!
Is that the only time when the size is incorrect?

I noticed that the implementation of that action might use a mismatched dpi value and pushed a fix for that in bf34be3ab

**Comment by mivok** [comment] 2021-12-14 19:19
I just tested and I think it is only when ResetFontAndWindowSize is used, and when dragging windows between monitors with a different dpi, similar to the video above.

But, I just upgraded to the latest nightly and both issues appear to be fixed (using ResetFontAndWindowSize on the retina display, and the weird behavior when dragging across monitors)! Thank you.

**Comment by wez** [comment] 2021-12-15 00:23
Thanks for confirming!

**Closed by wez** 2021-12-15 00:23 UTC
Labels: bug, macOS
