### ISSUE TITLE
gnome: mutter: Wayland titlebar passes through clicks

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#139] opened 2020-01-28 17:17 UTC
## Describe the bug

On my Wayland system, clicking on the title bar has no effect; the click seems to go straight through it. For example, if there's another window underneath, it gets raised. If I right-click, the underlying window gets raised and it shows its right-button menu.

## Environment (please complete the following information):

 - OS: Linux Wayland
 - Frontend:  OpenGL
 - Version: 20200113-222147-724ad3a-135-gcf13661

## To Reproduce

1.Move wezterm's title-bar over another window
2.Try to interact with the title bar

## Configuration

default (wezterm -n)

## Expected behavior

Ability to move/close/maximize/minimize the window

## Additional context

System is Fedora 31 with Gnome3/Wayland

**Comment by wez** [comment] 2020-01-29 05:12
This doesn't happen for me on my Fedora 31 Gnome 3/Wayland system, so I wonder if there is something about your workflow/system config that leads to something getting in a confused state?  

For me the behavior that seems the most janky about the titlebar is that it doesn't immediately react to changes in the mouse focus when I click in another window (perhaps your focus-follows-mouse preference is a factor?) and that its width usually lags behind in a resize.

**Comment by jsgf** [comment] 2020-01-29 20:26
Yeah, the focus also goes to the windows behind when I hover the pointer over the titlebar. It's like its not being treated as part of the window.

Turning focus-follows-mouse off doesn't help - clicking on the titlebar still focuses the window underneath.

**Comment by jsgf** [comment] 2020-01-29 20:28
I can still repro it with `wezterm -n`, so it doesn't have anything to do with my wezterm config.

**Comment by wez** [comment] 2020-02-01 06:37
I rebooted and can now reproduce this, so I assume it must be due to a relatively recent change in gnome3/mutter.

**Comment by wez** [comment] 2020-02-01 06:43
if you haven't already found this, this will use x11 instead and perhaps save a little sanity:

```toml
enable_wayland = false
```

**Comment by wez** [comment] 2020-02-01 15:27
Here's the up-upstream issue in Mutter: https://gitlab.gnome.org/GNOME/mutter/issues/1024

**Comment by wez** [comment] 2020-02-21 05:13
I updated this evening and this appears to be fixed with this version of mutter:

```
$ rpm -q mutter
mutter-3.34.4-1.fc31.x86_64
```

`sudo dnf update` and reboot (or allow the software update GUI thingy to install and reboot)

**Closed by wez** 2020-02-21 05:13 UTC
Labels: bug
