### ISSUE TITLE
Backdoor!!!!!!!!!!!!

### ISSUE THREAD

**Issue by QianSong1** [wez/wezterm#5208] opened 2024-03-23 14:34 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

![image](https://github.com/wez/wezterm/assets/101644710/951ba438-6bd3-44f4-a46d-e66693c1a8ad)

### Configuration

NULL

**Comment by routerdieb** [comment] 2024-03-25 02:22
Is this Windows Defender or some other anti virus ?`
Chrome marked it as bad:
![Chrome Warning after Download](https://github.com/wez/wezterm/assets/11362030/aa36de74-005f-47a2-a395-26340c738d6a)
`
Windows 11 reports Trojan:Win32/Vigorf.A

----------------------------
=> Virus Total is clean for the zip: https://www.virustotal.com/gui/url/e1e46ae98591567f2be47d91e5ed375548f1df0a3846792b8d8e5fb1d666ebd4

Current Setup.exe looks like this:
https://www.virustotal.com/gui/file/35a6ec0eff7aa65e3987f14223bfb9df831eaab2964eb441ed6cad4356d252ff

I suggest sending the exe to some vendors, to figure out why the have been flagging this:
e.g. https://www.avg.com/en-us/false-positive-file-form

**Comment by danielfaust** [comment] 2024-05-17 10:41
Needs to be bumped to top. I encountered the same and submitted this to GitHub.

**Comment by akthe-at** [comment] 2024-05-17 13:50
> Needs to be bumped to top. I encountered the same and submitted this to GitHub.

This is a duplicate of #5074 related issues. Specifically read @wez  response [here](https://github.com/wez/wezterm/issues/5074#issuecomment-1974922875)

**Comment by wez** [comment] 2024-05-17 14:08
Duplicate of #5074

**Closed by wez** 2024-05-17 14:08 UTC
Labels: bug
