### ISSUE TITLE
Window opacity results in very bright (but translucent) background

### ISSUE THREAD

**Issue by d-miketa** [wez/wezterm#716] opened 2021-04-22 10:03 UTC
Setting `window_background_opacity = 0.8` turns the shell background bright and translucent, whereas I'd expect it to be dark and translucent.

This is on MacOS 11.2.1, nightly from 21/4/21, tested with both "Gruvbox Dark" and "Hardcore" colour schemes.

`window_background_opacity = 1.0`:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/320321/115695481-c2c46600-a359-11eb-8fc7-97f4ac0fa42f.png">

`window_background_opacity = 0.8`:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/320321/115695536-ceb02800-a359-11eb-8ea8-98c04e9b6a28.png">

Similar settings in Kitty:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/320321/115696151-4b430680-a35a-11eb-9c60-674ffa9883e4.png">

Possibly related to [#553](https://github.com/wez/wezterm/issues/553).

**Comment by wez** [comment] 2021-05-02 00:04
I suspect that this is another facet of https://github.com/wez/wezterm/issues/544

**Comment by wez** [comment] 2021-05-30 19:49
Duplicate of #544

**Closed by wez** 2021-05-30 19:49 UTC
Labels: bug, macOS

**Comment by wez** [comment] 2021-08-09 15:22
https://github.com/wez/wezterm/issues/1000 and https://github.com/wez/wezterm/issues/653 actually sound more related to this than the alpha blending issue
