### ISSUE TITLE
numpad is abnormal

### ISSUE THREAD

**Issue by pdm666** [wez/wezterm#2338] opened 2022-08-01 14:50 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220624-141144-bd1b7c5d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

when the first time using numpad can't input numbers before opening the app everytime,this is the direction key function and needs to click "NUMLOCK" on twice.
Excluding the keyboard reason when this condition can't occur in other apps.
OS：ubuntu 22

### Configuration

no config

**Comment by wez** [comment] 2022-08-07 13:37
Possibly a duplicate of https://github.com/wez/wezterm/issues/1869 but there's not enough information in this report to know whether you are also using mutter/gnome

**Closed** 2022-08-21 14:08 UTC
Labels: bug, Wayland, waiting-on-op
