### ISSUE TITLE
Random characters inserted without typing the keyboard

### ISSUE THREAD

**Issue by ydzhou** [wez/wezterm#1967] opened 2022-05-10 03:11 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220408-101518-b908e2dd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Sometimes few characters get inserted on the terminal while I am not doing any typing

Those characters look like containing my previously typed commands

One example
```
git add config.toml1+r6B42=1B5B5Agit
```

### To Reproduce

It is not consistently showing up but occurs few times a day.

### Configuration

```
local wezterm = require 'wezterm';

local termcolor_fg = "#2b2b2b"
local termcolor_cursor_bg = "#b0b0b0"

return {
    font = wezterm.font_with_fallback({
        "BlexMono Nerd Font",
        "WenQuanYi Micro Hei Mono"
    }),
    font_size = 14,

    enable_tab_bar = true,
    use_fancy_tab_bar = true,
    hide_tab_bar_if_only_one_tab = true,
    tab_bar_at_bottom = false,

    keys = {
        {key = "c", mods = "CMD", action = wezterm.action{CopyTo="Clipboard"}},
        {key = "v", mods = "CMD", action = wezterm.action{PasteFrom="Clipboard"}},
    },

    color_scheme = "nord",
}
```

### Expected Behavior

Nothing should happen since I am not typing at all. No random characters should be inserted into my terminal.

**Comment by wez** [comment] 2022-05-10 04:22
Sounds like a duplicate of:
* https://github.com/wez/wezterm/issues/1850
* https://github.com/wez/wezterm/issues/1950
which are fixed in the nightly build; please try the nightly!

**Comment by ydzhou** [comment] 2022-05-11 19:36
Yes, I think that is the issue. I tried the latest nightly build and have not yet run into this.

Thanks!

**Comment by wez** [comment] 2022-05-11 19:48
Duplicate of #1850

**Closed by wez** 2022-05-11 19:48 UTC
Labels: bug
