### ISSUE TITLE
IME doesn't work with the main branch on Wayland

### ISSUE THREAD

**Issue by yutkat** [wez/wezterm#2168] opened 2022-06-24 05:45 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20220623-130149-e633d897

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

With the current main branch, the IME on/off does not work.
```
wezterm --config-file /tmp/wezterm.lua
# 20220623-130149-e633d897
```

The previous version is working fine.
```
/usr/bin/wezterm --config-file /tmp/wezterm.lua
# 20220408-101518-b908e2dd
```

Also, it works fine with other applications. The only one that doesn't work is the latest version of wezterm.
And also, X11(i3) works fine.
If you can't find the cause, I'll investigate which commits are causing the problem.

### Configuration

```lua
return {
        use_ime = true,
}
```

### Expected Behavior

Can turn on/off IME as before.

### Anything else?

- wezterm: Expanded from wezterm-nightly.Ubuntu20.04.tar.xz
- Arch Linux
- WM: sway
- fcitx5 version: 5.0.17
- My on/off key: Ctrl-;

**Comment by Funami580** [comment] 2022-06-24 12:37
That's because `enable_wayland` now defaults to true. Just set `enable_wayland = false` in your config and it should work again.

**Comment by yutkat** [comment] 2022-06-24 12:40
I tried `enable_wayland` and it still didn't work.

**Comment by wez** [comment] 2022-06-24 12:57
https://github.com/wez/wezterm/issues/1772 is needed before IME will work with native wayland.
Set `enable_wayland = false` and restart wezterm to use XWayland and XIM for IME.

**Comment by yutkat** [comment] 2022-06-24 13:10
I don't fully understand, but I'll wait until #1772 is resolved. I'll use i3wm until then, no problem.
Thanks for the response.

**Comment by wez** [comment] 2022-06-24 13:28
Marking this as a duplicate of #1772

**Closed by wez** 2022-06-24 13:28 UTC
Labels: bug
