### ISSUE TITLE
Current head fatls with 'error: entered unreachable' condition

### ISSUE THREAD

**Issue by hzeller** [wez/wezterm#567] opened 2021-03-22 03:51 UTC
## Build Environment

 - OS: Linux Debian bullseye/sid
 - `Linux bohr 5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux`
 -  rustc 1.48.0 / cargo 1.46.0 (`rustup` does not exist)

Compiling and starting crashes immediately due to entering unreachable code ...
Unfortunately, I don't know enough about the rust environment to make any sense of it. Is that an issue with the tool-chain ?

It started recently, I `git bisect`-ed it to commit 20e3d4d982b547501a79b636df48028517a24a11 as the first failing

Stacktrace:
```
$ RUST_BACKTRACE=full target/release/wezterm
 2021-03-22T03:47:46.018Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-173727
thread 'main' panicked at 'internal error: entered unreachable code', /home/hzeller/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.28.0/src/buffer/alloc.rs:1292:17
stack backtrace:
   0:     0x55c71c81ab2c - std::backtrace_rs::backtrace::libunwind::trace::hbc0dbba8e4be7fe4
                               at /usr/src/rustc-1.48.0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55c71c81ab2c - std::backtrace_rs::backtrace::trace_unsynchronized::hd8cc0512eb4dd70a
                               at /usr/src/rustc-1.48.0/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55c71c81ab2c - std::sys_common::backtrace::_print_fmt::h766fae1718fafbdd
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:79
   3:     0x55c71c81ab2c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha84a0cc4b4a9ee84
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:58
   4:     0x55c71c85d56f - core::fmt::write::h600ac4150cc03aef
                               at /usr/src/rustc-1.48.0/library/core/src/fmt/mod.rs:1080
   5:     0x55c71c812f15 - std::io::Write::write_fmt::h204ba0c32f2b9a99
                               at /usr/src/rustc-1.48.0/library/std/src/io/mod.rs:1516
   6:     0x55c71c83603d - std::sys_common::backtrace::_print::h6e0f6c74c2c2ad8f
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:61
   7:     0x55c71c83603d - std::sys_common::backtrace::print::h44d505c625eab4ff
                               at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:48
   8:     0x55c71c83603d - std::panicking::default_hook::{{closure}}::h891d2ab61783cea8
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:208
   9:     0x55c71c835d43 - std::panicking::default_hook::h99e2d300f2614f89
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:227
  10:     0x55c71c836664 - std::panicking::rust_panic_with_hook::h1b36ee28aa35f9da
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:581
  11:     0x55c71b7c23d4 - std::panicking::begin_panic::{{closure}}::hb28383984bbf9ceb
  12:     0x55c71b7bf81c - std::sys_common::backtrace::__rust_end_short_backtrace::h8ab8c839e13c3d31
  13:     0x55c71b80eb4c - std::panicking::begin_panic::hecbf5b2ac91bfee5
  14:     0x55c71b8200d5 - glium::buffer::alloc::create_buffer::hbf16ca7c31904074
  15:     0x55c71b82016d - glium::buffer::alloc::Alloc::new::h575926d18b1f50ae
  16:     0x55c71b889572 - wezterm_gui::renderstate::RenderState::compute_vertices::hf60ea4bbd851c65b
  17:     0x55c71b8860bd - wezterm_gui::renderstate::RenderState::new::h7913951469316175
  18:     0x55c71b83d9d0 - <wezterm_gui::termwindow::TermWindow as window::WindowCallbacks>::created::h9825246558440b0f
  19:     0x55c71c64b027 - window::os::x11::window::XWindowInner::enable_opengl::h1c3b672ef2baca09
  20:     0x55c71c64dc43 - window::os::x11::window::XWindow::new_window::heba9a4d81a3da8e8
  21:     0x55c71c64f873 - window::os::x_and_wayland::Window::new_window::h09a6b8175cadaa16
  22:     0x55c71b8412a1 - wezterm_gui::termwindow::TermWindow::new_window::h21b5eaa940803506
  23:     0x55c71b7f4d8a - wezterm_gui::frontend::GuiFrontEnd::try_new::{{closure}}::h29d61af377a87795
  24:     0x55c71be9c902 - hashbrown::map::HashMap<K,V,S>::retain::hcd384b2897adec09
  25:     0x55c71bee9f37 - mux::Mux::notify::hd37f0ff1be8dcb1a
  26:     0x55c71bee9643 - <mux::MuxWindowBuilder as core::ops::drop::Drop>::drop::hd8a082efb21c003a
  27:     0x55c71b7e8d21 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::heb4b124db879a698
  28:     0x55c71b7e9a5f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf891581046318553
  29:     0x55c71b84a815 - <async_task::runnable::spawn_local::Checked<F> as core::future::future::Future>::poll::h4d828d18650c981b
  30:     0x55c71b78857b - async_task::raw::RawTask<F,T,S>::run::h44e36e2571ac9bcc
  31:     0x55c71c634af3 - window::spawn::SpawnQueue::run::h8daac0db7f8884ca
  32:     0x55c71c63ad19 - <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop::hef16d785dbd6a5df
  33:     0x55c71b88ea3b - wezterm_gui::run::heb2824eb2ac10673
  34:     0x55c71b88bc67 - wezterm_gui::main::hd29e88345babb393
  35:     0x55c71b7c08f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc9ae0fc0aa03120d
  36:     0x55c71b8652a9 - std::rt::lang_start::{{closure}}::h64ef6906d32d1f6e
  37:     0x55c71c836a14 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h473f4d9760584df9
                               at /usr/src/rustc-1.48.0/library/core/src/ops/function.rs:259
  38:     0x55c71c836a14 - std::panicking::try::do_call::h38b2d68e1990d627
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:381
  39:     0x55c71c836a14 - std::panicking::try::h6c98453927853dba
                               at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:345
  40:     0x55c71c836a14 - std::panic::catch_unwind::hf939d3206ba7e318
                               at /usr/src/rustc-1.48.0/library/std/src/panic.rs:382
  41:     0x55c71c836a14 - std::rt::lang_start_internal::h3c710f42dc1fbba8
                               at /usr/src/rustc-1.48.0/library/std/src/rt.rs:51
  42:     0x55c71b88fa42 - main
  43:     0x7f3d53310d0a - __libc_start_main
  44:     0x55c71b78247a - _start
  45:                0x0 - <unknown>
```

**Comment by wez** [comment] 2021-03-22 03:53
Duplicate of #566 (and I just pushed a fix!)

**Closed by wez** 2021-03-22 03:53 UTC
Labels: bug

**Comment by wez** [comment] 2021-03-22 03:57
The explanation for this is: it's a bug in the underlying `glium` crate that decides to use an immutable vertex buffer when the probed GL implementation doesn't support it.
I've switched back to using `dynamic` buffers instead, which should work everywhere, but may not be as fast.

**Comment by hzeller** [comment] 2021-03-22 04:17
And it is confirmed fixed. Thanks!

I suppose my aging laptop that uses A Mesa-based OpenGL (`Mesa Intel(R) HD Graphics 620`) was lacking that support...

**Comment by wez** [comment] 2021-03-22 04:26
I'm not so sure that hardware age is a factor; there's a lot of variance in egl and opengl capabilities and it seems like a good chunk of those are due to software.  I actually did run into this same panic while poking around on the `gamma` branch I'm using to work on #544.  That's proving to be something of adventure of its own!
