### ISSUE TITLE
100% CPU in HarfbuzzShaper::do_shape() when running certain commands

### ISSUE THREAD

**Issue by chenxiaolong** [wez/wezterm#2701] opened 2022-11-03 22:37 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

KDE Plasma 5.26 on Fedora 36

### WezTerm version

20221102-081609-a6fc9323

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

This seems to be a bit of an obscure performance issue. When I run an Android AOSP build, the command output seems to cause wezterm to shoot to 100% CPU, despite what appears to be minimal, rate limited output. When this happens, input latency takes a noticeable hit. If I leave things in this state for half an hour, typing a key may take a couple seconds to appear and switching tabs can take almost 30 seconds to respond. Once the command completes, wezterm becomes responsive again. 

While the build is running, these issues only appear with the associated wezterm instance. There is no noticeable impact to other applications on the same machine, including a separate `--always-new-process` wezterm instance.

I recorded the output that the AOSP build tool produces here: [aosp_build.output.txt](https://github.com/wez/wezterm/files/9933401/aosp_build.output.txt). It seems to my untrained eye that the output has the following characteristics:

* ASCII text only, but with escape sequences for things like colors and bold text.
* Not much data is put into the scrollback buffer. At most, several hundred lines.
* Repeatedly overwrites the bottom 11 lines of the terminal, but rate limited. Visually estimating, there's approximately 10 updates per second.

I built wezterm from commit a6fc9323e20906d6b7836697b5ba6b4be08b2d1d in release mode (but with debug symbols enabled via https://stackoverflow.com/a/38804737). Then, I recorded the wezterm process with `sudo perf record -p <pid> -g` while it was exhibiting the 100% CPU usage.

Running `perf report` shows the following: [image](https://user-images.githubusercontent.com/646253/199842758-e4cde1ca-02d5-4e51-9333-66a9d5df34a0.png). It seems that most of the time is being spent in `wezterm_font::shaper::harfbuzz::HarfbuzzShaper::do_shape`. Given the presence of harfbuzz in there, I tried with different fonts, but it doesn't seem to make a difference if I use my normal font (Fira Code) or Wezterm's default (Jetbrains Mono).

### To Reproduce

This happens 100% of the time when I run the AOSP build system. Unfortunately, running an AOSP build requires downloading 100GB of code and an additional couple hundred GB for build artifacts. Perhaps the recording of the command output from above may be helpful?

I have not encountered this issue with other command I regularly run. (or if it happens, it's not noticeable)

### Configuration

```
local options = {
    font_size = 9,
}

return options
```

### Expected Behavior

Ideally, wezterm wouldn't be using 100% CPU.

### Logs

```
Debug Overlay
wezterm version: 20221102-081609-a6fc9323
OpenGL version: NVIDIA GeForce RTX 3090/PCIe/SSE2 4.6.0 NVIDIA 520.56.06
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
18:09:50.371 WARN wezterm_term::terminalstate::performer > Unhandled OSC  12 7
18:10:01.098 WARN wezterm_term::terminalstate::performer > Unhandled OSC  12 7
18:10:11.625 WARN wezterm_term::terminalstate::performer > Unhandled OSC  12 7
18:17:31.794 WARN wezterm_term::terminalstate::performer > Unhandled OSC  12 7
18:25:06.497 WARN wezterm_term::terminalstate::performer > Unhandled OSC  12 7
18:25:11.923 WARN wezterm_term::terminalstate::performer > Unhandled OSC  12 7
18:25:15.189 WARN wezterm_term::terminalstate::performer > Unhandled OSC  12 7
18:25:21.721 WARN wezterm_term::terminalstate::performer > Unhandled OSC  12 7
```

### Anything else?

(included above)

EDIT: In case it makes a difference, the GPU is an Nvidia 3090. The display is 3840x2160 with no scaling and the wezterm window, including titlebars, is 1920x1080.

**Comment by wez** [comment] 2022-11-04 00:14
Thanks for the thorough report!

Please capture a terminal recording following the steps below; I'm curious whether you see the same 100% load when you use `wezterm replay` to replay that recording: if so, that should make it easier for me to reproduce and resolve.

* Launch wezterm.  If possible, please use the default terminal size of 80x24 cells as it helps to keep things smaller and easier to manage, but if you only see the issue at a large size, make sure that you size the terminal appropriately before you move to the next step.
* Inside that terminal run `wezterm record` to start a recording session.
* Run through your reproduction steps
* Then type `exit`
* You should see a message like:

```
*** Finished recording to /var/tmp/wezterm-recording-sF6B3u.cast.txt
```

* Attach the file that it produced to this issue.

The file is an asciicast (compatible with https://asciinema.org/) and can also be replayed using `wezterm replay`.

The terminal recording allows me to replicate what is being sent to the terminal without requiring me to install the same applications as you and replicate your configuration for everything.

**Comment by vimpostor** [comment] 2022-11-04 19:16
Yeah I have hit that problem sporadically as well. I don't even need to do crazy things like AOSP compilation to trigger it, I usually perceive increased latency already after doing things like system upgrades.
Since I always use tmux, I usually workaround it by closing and reopening wezterm and then reattaching to tmux.

I will see if I'll be able to debug the increased latency next time I trigger it.

**Comment by chenxiaolong** [comment] 2022-11-04 19:30
Thanks for the reply, @wez! I didn't know about `wezterm record`--that's pretty neat.

I've attached a recording for both the default 80x24 size as well as when the window is resized to 272x62 (1920x1080px). Both exhibit the issue when running `wezterm replay`, but not to the same degree. The 80x24 window results in 30-50% CPU usage continuously, while the 272x62 window results in 70-95% CPU usage. Running `perf record` against the wezterm pid shows `HarfbuzzShaper::do_shape()` at the top in both cases.

[wezterm-recording-l4tmte.cast.80x24.txt](https://github.com/wez/wezterm/files/9941436/wezterm-recording-l4tmte.cast.80x24.txt)
[wezterm-recording-bRxVXD.cast.272x62.txt](https://github.com/wez/wezterm/files/9941437/wezterm-recording-bRxVXD.cast.272x62.txt)

**Comment by chenxiaolong** [comment] 2022-11-14 21:35
Thanks! I tested with commit 831eda86b981cab771ee63be02cdcd927655f430 and it does seem to make a noticeable difference.

Running the same command you posted, the CPU time reported by `time` went from 22% (a6fc9323e20906d6b7836697b5ba6b4be08b2d1d) to 12% (831eda86b981cab771ee63be02cdcd927655f430). In htop, I'm seeing a peak of about 30% and it stays in that ballpark during the 39s~60s timestamps in the replay.

**Comment by chenxiaolong** [comment] 2022-11-14 21:42
Running wezterm with `perf record <command from wez's post>`, `HarfbuzzShaper::do_shape` is no longer near the top. This is what `perf report` shows now with the recording: [perf.data.tar.gz](https://github.com/wez/wezterm/files/10007329/perf.data.tar.gz)

([Screenshot](https://user-images.githubusercontent.com/646253/201771678-031763f1-5e8d-43f4-a48a-e1f6cda4ccab.png))

**Closed** 2023-03-31 04:17 UTC
Labels: bug
