### ISSUE TITLE
Fonts are not rendered correctly

### ISSUE THREAD

**Issue by Sparkenstein** [wez/wezterm#651] opened 2021-04-06 07:49 UTC
## The bug
The fonts are not being rendered correctly, especially the symbols in vim statusline and zsh prompt etc. I compared the output with other terminals, xfce4-terminal and alacritty, it looks fine there.
attaching the screenshot below:

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210404-112810-b63a949d

## To Reproduce
Try any patched nerd font with status-line in vim or simply try p10k.zsh if you are using ZSH, no need to change any configuration, the behavior is observed on default settings as well

## Configuration
PS: trimmed few unnecessary keybindings about window/panes management `table.insert(mykeys...)` etc let me know if you need full config

```lua
local wezterm = require 'wezterm';

local mykeys = {}
for i = 1, 9 do
    table.insert(mykeys, {
        key=tostring(i),
        mods="CTRL|SHIFT",
        action=wezterm.action{ActivateTab=i-1},
    })

    table.insert(mykeys, {
        key="F" .. tostring(i),
        action=wezterm.action{ActivateTab=i-1},
    })

end

return {
  -- Fonts
  font = wezterm.font("MesloLGS NF"),
  font_size = 15.0,
  line_height = 1.2,

  -- Colors
  bold_brightens_ansi_colors = true,
  inactive_pane_hsb = {
        hue = 1.0,
        saturation = 0.7,
        brightness = 0.6,
  },
  -- UI
  color_scheme = "Galaxy",

  -- Keybindings
  leader = { key = "m", mods="CTRL" },
  keys = mykeys,

}
```
## Screenshots
![issue](https://user-images.githubusercontent.com/24642451/113676900-9a423800-96da-11eb-8043-75ec43c4a512.png)

Note the left one is wezterm, right top is xfce4-terminal, right bottom is alacritty,

**Comment by Sparkenstein** [comment] 2021-04-06 07:52
Hmm, now that I have looked closely, even alacritty is not rendering it properly, there's small misalignment on second line on right prompt

**Comment by wez** [comment] 2021-04-07 15:12
Seems like the same underlying issue as #584 which has a draft PR: #588
Possibly also related to #614

**Comment by wez** [comment] 2021-04-10 02:51
Duplicate of #584

**Closed by wez** 2021-04-10 02:51 UTC
Labels: bug
