### ISSUE TITLE
`wezterm connect <SshDomain>` does not work after latest update

### ISSUE THREAD

**Issue by bwbuhse** [wez/wezterm#2194] opened 2022-06-27 15:53 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220626-204048-65e0bb1d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

~Yes, and I updated the version box above to show the version of the nightly that I tried~
~Edit: apparently not... I'll try right now, though.~
Edit 2: Yes, the same issue happens. 

### Describe the bug

I have an SshDomain that I use to connect to a remote machine. It has worked fine until today, when I ran `brew update; and brew upgrade`. Wezterm was updated to the version listed above. In the new version, if I try to use `wezterm connect` Mac shows a new window being opened in the app bar, but the window never actually appears anywhere. 

I tried updating to the same version on my remote machine (running Ubuntu) but that hasn't helped either. I can still SSH normally into the remote machine just fine.

### To Reproduce

1. Create an SshDomain
2. Update to 20220624-141144-bd1b7c5d
3. `wezterm connect <SshDomain>`

### Configuration

```
ssh_domains = {
  {
    name = "rd-benjaminb",
    remote_address = "rd-benjaminb",
    username = "benjaminb",
    default_prog = { "fish" },
  },
},
```

### Expected Behavior

Wezterm connects to the SshDomain

### Logs

```
10:53:09.934 WARN wezterm_term::terminalstate::performer > Unhandled OSC  1337 RemoteHost=benjaminb@USAU-BENJAMINB-M
10:53:09.995 WARN wezterm_term::terminalstate::performer > unhandled iterm2: CurrentDir("/Users/benjaminb")
10:53:09.995 WARN wezterm_term::terminalstate::performer > Unhandled OSC  1337 ShellIntegrationVersion=17 shell=fish
10:53:10.000 INFO wezterm_gui::termwindow > OpenGL initialized! Intel(R) Iris(TM) Plus Graphics OpenGL Engine 4.1 INTEL-18.5.8 is_context_loss_possible=false wezterm version: 20220624-141144-bd1b7c5d
10:53:10.091 WARN wezterm_term::terminalstate::performer > Unhandled OSC  1337 RemoteHost=benjaminb@USAU-BENJAMINB-M
10:53:10.091 WARN wezterm_term::terminalstate::performer > unhandled iterm2: CurrentDir("/Users/benjaminb")
>
```

### Anything else?

When I run the command I don't get any output at all.
```
~
❯ wezterm connect rd-benjaminb

```

**Comment by wez** [comment] 2022-06-27 17:35
I can't reproduce this.
Can you reduce your configuration to the minimum possible to reproduce it?
For instance, try removing `default_prog` to see if perhaps that is related.

I'm unsure how to reconcile the logs section of your report with the last bit you mentioned where you don't see any output; are those from different runs?

You could also try starting wezterm like this:

```
WEZTERM_LOG=wezterm_ssh=trace,info wezterm connect rd-benjaminb
```

to increase the logging verbosity around ssh to see if that provides any additional insight

**Comment by bwbuhse** [comment] 2022-06-27 17:56
Thanks, I’ll give the steps you mentioned a shot. As for the logs, that was the debug logs with Ctl+Shift+L or whatever the command was (after running the connect command). The no output I just meant from the command itself.

**Comment by wez** [comment] 2022-06-27 21:43
Doesn't look like it's getting to the ssh part for some reason.  Let's try more verbose logging overall:

```
WEZTERM_LOG=trace wezterm connect rd-benjaminb
```

**Comment by bwbuhse** [comment] 2022-06-27 22:02
The trace from that was long, so I've uploaded it to 0x0.st [here](https://0x0.st/oSvR.out). I can post the full trace if you want, but again, it's 362 lines.

**Comment by wez** [comment] 2022-06-27 23:05
The trace suggests that it got as far as prompting you for a password.
But I don't see any logs from the window module there, which is weird.

**Comment by JonathanxD** [comment] 2022-06-27 23:17
I'm facing the same problem, interestingly, `wezterm ssh jonathan@rpi` works as intended (open a new window and connect), only the `connect` does not (although yes, it does connect and asks for password, but no GUI whatsoever).

**Comment by bwbuhse** [comment] 2022-06-27 23:28
Interestingly, I *do* have an SSH key configured for the host I'm using. I'm not at my work laptop right now (where I have wezterm installed, I just re-installed Windows on my Desktop and don't have it yet) so I can't test `wezterm ssh, but if I just run `ssh rd-benjaminb` it was connecting fine without a password prompt.

**Comment by JonathanxD** [comment] 2022-06-27 23:31
@wez maybe this helps, the code seems to be stuck at this async routine: 

https://github.com/wez/wezterm/blob/main/wezterm-client/src/domain.rs#L627-L642

And the window is only spawned after the `attach` finishes, as long as I've seen (I didn't dived too much into the logic).

**Comment by wez** [comment] 2022-06-27 23:49
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Closed** 2022-07-09 22:01 UTC
Labels: bug, fixed-in-nightly
