### ISSUE TITLE
Promote pane to tab

### ISSUE THREAD

**Issue by EpocSquadron** [wez/wezterm#746] opened 2021-04-27 23:09 UTC
In tmux, you can promote a pane to a tab. Having foregone tmux in favor of wezterm's multiplexing, this is a feature I'd like to be able to restore to my workflow. It seems it would be natural to have this be another Action that acts on the current pane, like AdjustPaneSize and the like.

**Comment by wez** [comment] 2022-01-16 18:42
Duplicate of #1253

**Closed** 2022-01-20 23:35 UTC
Labels: enhancement
