### ISSUE TITLE
When wezterm launched "Minimize/maximize all windows" doesn't work.

### ISSUE THREAD

**Issue by shaddu38** [wez/wezterm#1099] opened 2021-09-02 08:14 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20210901-211314-3d227d27

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When wezterm launched "Minimize/maximize all windows"-function doesn't work.

### To Reproduce

OS: Windows 10
Launch any app (e.g. notepad), launch wezterm, press Win+D or button at right bottom corner and you see that windows minimization does not occur.

### Configuration

No config.

### Expected Behavior

"Minimize/maximize all windows" should work with lauched wezterm.

### Logs

10:53:20.050 INFO wezterm_mux_server_impl::local > setting up C:\Users\admin\.local/share/wezterm\gui-sock-3584
10:53:20.099 WARNING window::os::windows::window > EGL init failed Config says to avoid EGL, fall back to WGL
10:53:20.217 WARNING wezterm_term::terminalstate > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(9001))
10:53:20.226 INFO wezterm_gui::termwindow > OpenGL initialized! GeForceGTX 1060 6GB/PCIe/SSE2 4.5.0 NVIDIA 456.71 is_context_loss_possible=true wezterm version: 20210901-211314-3d227d27

### Anything else?

In version 20210502-154244-3f7122cb and previous "Minimize/maximize all windows" works fine.

**Comment by wez** [comment] 2021-09-26 22:21
Sorry it's taken a while to get to this. I can't reproduce what you described; for me, it is sometimes a bit slow to minimize everything when wezterm is open. I don't know why this is.  Even with wezterm closed, it is sometimes slow to minimize all, so I'm not really sure that this is attributable to wezterm :-/

**Comment by wez** [comment] 2022-01-08 15:08
Possibly fixed by https://github.com/wez/wezterm/commit/67b8c453cad275c7ea78fd505049e66016d17dba

**Comment by wez** [comment] 2022-01-08 17:37
I'm pretty confident that this is fixed

**Closed by wez** 2022-01-08 17:37 UTC
Labels: bug, Windows, fixed-in-nightly
