### ISSUE TITLE
Failed to start AppImage on Opensuse Tumbleweed 20220420

### ISSUE THREAD

**Issue by davidcortesortuno** [wez/wezterm#1905] opened 2022-04-22 09:30 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220421-183827-26500c67

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Today I updated Tumbleweed to the latest version and WezTerm no longer starts from the AppImage. In the last 5 months it was running fine from the stable AppImage. The nightly version also fails. I get the error

```
╰─❯ ./WezTerm.AppImage
11:23:18.223  WARN   wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
11:23:18.229  ERROR  wezterm_gui::frontend       > Failed to create window: with_egl_lib failed: with_egl_lib(libEGL.so.1) failed: egl GetDisplay: Failed but with error code: SUCCESS, with_egl_lib(libEGL.so) failed: egl GetDisplay: Failed but with error code: SUCCESS, with_egl_lib(libEGL.so.1) failed: egl GetDisplay: Failed but with error code: SUCCESS, with_egl_lib(libEGL.so) failed: egl GetDisplay: Failed but with error code: SUCCESS
```

### To Reproduce

Download AppImage
Make it executable
Run Wezterm

### Configuration

```
local wezterm = require 'wezterm';
return {
  font = wezterm.font("Fira Code"),
  font_size = 13.0,
  color_scheme = "Desert",

  keys = {
    -- This will create a new split and run your default program inside it
    {key="j", mods="CTRL|SHIFT",
      action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
    {key="l", mods="CTRL|SHIFT",
      action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},

    {key="RightArrow", mods="ALT",
      action=wezterm.action{ActivatePaneDirection="Right"}},

    {key="LeftArrow", mods="ALT",
      action=wezterm.action{ActivatePaneDirection="Left"}},

    {key="DownArrow", mods="ALT",
      action=wezterm.action{ActivatePaneDirection="Down"}},

    {key="UpArrow", mods="ALT",
      action=wezterm.action{ActivatePaneDirection="Up"}},
  }
}
```

### Expected Behavior

To open a window and run normally

### Logs

```
11:23:18.223  WARN   wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
11:23:18.229  ERROR  wezterm_gui::frontend       > Failed to create window: with_egl_lib failed: with_egl_lib(libEGL.so.1) failed: egl GetDisplay: Failed but with error code: SUCCESS, with_egl_lib(libEGL.so) failed: egl GetDisplay: Failed but with error code: SUCCESS, with_egl_lib(libEGL.so.1) failed: egl GetDisplay: Failed but with error code: SUCCESS, with_egl_lib(libEGL.so) failed: egl GetDisplay: Failed but with error code: SUCCESS
```

**Comment by wez** [comment] 2022-04-26 13:35
FWIW, thanks to @xpufx, SUSE RPMs are now available from https://wezfurlong.org/wezterm/install/linux.html#installing-on-fedora-and-rpm-based-systems

**Comment by davidcortesortuno** [comment] 2022-05-04 23:40
Today I installed the RPM package for Opensuse Tumbleweed and now Wezterm runs perfectly :) I'm not sure what would be the difference. I guess the RPM is using my system's packages instead of the internal AppImage libraries

**Comment by wez** [comment] 2022-05-06 14:42
Closing as a duplicate of https://github.com/wez/wezterm/issues/1956  (that one has more info about the appimage issue than this, and I can test on fedora!)

**Closed by wez** 2022-05-06 14:42 UTC
Labels: bug
