### ISSUE TITLE
Exiting full screen when switching between other apps and Wezterm in ubuntu 22.04

### ISSUE THREAD

**Issue by ProfKache** [wez/wezterm#4667] opened 2023-12-12 11:55 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

My issue is, when I enter fulls creen mode it works fine, but however when switching from Wezterm to other applications, then back to Wezterm, the full screen window disappears, it defaults to the normal configurations that I have provided to "**cols**" and "**rows**". I'm running ubuntu 22.04

### Configuration

local wezterm = require("wezterm")
local act = wezterm.action
local mux = wezterm.mux

-- Maximize the window right away
wezterm.on("gui-startup", function(cmd)
	local _, _, window = mux.spawn_window(cmd or {})
	window:gui_window():maximize()
end)

local config = {}

-- Use config builder object if possible
if wezterm.config_builder then
	config = wezterm.config_builder()
end

-- Settings
-- config.font = wezterm.font("JetBrains Mono")
config.color_scheme = "Tokyo Night Storm"
config.line_height = 1.25
config.font = wezterm.font_with_fallback({
	{ family = "Operator Mono Lig", scale = 1.5, weight = "Light" },
	-- { family = "FuraCode Nerd Font", scale = 1.4, weight = "Light" },
})

config.keys = {
	{
		key = "C",
		mods = "CTRL",
		action = act.CopyTo("ClipboardAndPrimarySelection"),
	},
}

-- config.window_background_image = "/home/profkache/Pictures/term_wallpapers/pxfuel.jpg"
config.window_background_opacity = 0.9
config.window_decorations = "RESIZE"
config.window_padding = {
	left = 0,
	right = 0,
	top = 0,
	bottom = 0,
}
config.scrollback_lines = 3500
config.tab_bar_at_bottom = true
config.hide_tab_bar_if_only_one_tab = true
config.adjust_window_size_when_changing_font_size = false

-- Open in full screen
config.initial_rows = 50
config.initial_cols = 200

return config

**Comment by wez** [comment] 2024-09-22 15:33
Duplicate of https://github.com/wez/wezterm/issues/5783

**Closed by wez** 2024-09-22 15:33 UTC
Labels: bug, Wayland
