### ISSUE TITLE
Sixel graphics on Wezterm on does not appear to work on Windows

### ISSUE THREAD

**Issue by RioNight** [wez/wezterm#4736] opened 2024-01-01 04:53 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20231228-084719-ff274374

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Running `chafa -f sixel image.png` does not output anything. It should display `image.png` in sixel graphics.

### To Reproduce

1. On Windows, download git, chafa, wezterm from the scoop package system (https://scoop.sh/).
2. Set git bash (from the git installation from scoop) to the wezterm shell (see the config below).
3. Run `chafa -f sixel image.png`

### Configuration
```lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.default_prog = { 'c:\\users\\<username>\\scoop\\apps\\git\\current\\bin\\bash.exe -i -l' }

-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

The image should be shown on the terminal with sixel graphics.

### Anything else?

`chafa -f symbols image.png` works.

The image in question is:
![image](https://github.com/wez/wezterm/assets/58403689/69637a32-f624-4457-bbce-6c80ccd4f64d)

The sixel text for the image above is:
[image.six.txt](https://github.com/wez/wezterm/files/13807199/image.six.txt)
This was captured with `chafa -f sixel image.png > image.six.txt`.
(`cat image.six.txt` should render the image in sixel graphics.)

**Comment by wez** [comment] 2024-01-06 15:02
Duplicate of https://github.com/wez/wezterm/issues/1236

**Closed by wez** 2024-01-06 15:02 UTC
Labels: bug
