### ISSUE TITLE
WezTerm windows are sometimes invisible when launched with the Flatpak

### ISSUE THREAD

**Issue by poperigby** [wez/wezterm#4222] opened 2023-08-29 18:31 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin 5.27.7

### WezTerm version

0230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Sometimes when I launch WezTerm (the one installed from Flathub), the window will be completely invisible. Clicking on the window in my task manager doesn't pull it up. This doesn't happen every time though.

I didn't install the nightly version of WezTerm, because there is no nightly version on Flathub as far as I can tell.

Screenshot of WezTerm window being invisible in task manager:
![Screenshot_20230829_112021](https://github.com/wez/wezterm/assets/20866468/054cf29d-9628-450b-a38d-03e3cf953270)

### To Reproduce

Launch WezTerm. It can be through the shell (e.g. `flatpak run org.wezfurlong.wezterm`), or through an application launcher entry.

### Configuration

```lua
-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This table will hold the configuration.
-- The config_builder provides clearer error
-- messages.
local config = wezterm.config_builder()

local settings = {
    enable_wayland = true,
    font = wezterm.font("FiraMono Nerd Font Mono"),
    font_rules = {
        {
            italic = true,
            font = wezterm.font("FiraMono Nerd Font Mono", { italic = false }),
        },
    },
    font_size = 11.0,
    enable_tab_bar = true,
    window_background_opacity = 0.9,
    window_close_confirmation = "NeverPrompt",
    skip_close_confirmation_for_processes_named = {
        "bash",
        "fish",
        "chezmoi",
    },
    harfbuzz_features = { "calt=0", "clig=0", "liga=0" },
    show_update_window = false,
    check_for_updates = false,
    window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0,
    },
    keys = {
        { key = "t", mods = "ALT", action = wezterm.action({ SpawnTab = "DefaultDomain" }) },
        { key = "w", mods = "ALT", action = wezterm.action({ CloseCurrentTab = { confirm = true } }) },
        { key = "1", mods = "ALT", action = wezterm.action({ ActivateTab = 0 }) },
        { key = "2", mods = "ALT", action = wezterm.action({ ActivateTab = 1 }) },
        { key = "3", mods = "ALT", action = wezterm.action({ ActivateTab = 2 }) },
        { key = "4", mods = "ALT", action = wezterm.action({ ActivateTab = 3 }) },
        { key = "5", mods = "ALT", action = wezterm.action({ ActivateTab = 4 }) },
        { key = "6", mods = "ALT", action = wezterm.action({ ActivateTab = 5 }) },
        { key = "7", mods = "ALT", action = wezterm.action({ ActivateTab = 6 }) },
        { key = "8", mods = "ALT", action = wezterm.action({ ActivateTab = 7 }) },
        { key = "9", mods = "ALT", action = wezterm.action({ ActivateTab = 8 }) },
    },
    color_scheme = "Gruvbox dark, soft (base16)",

}

-- Copy the settings from the settings table to the config table
for key, value in pairs(settings) do
    config[key] = value
end

return config
```

### Expected Behavior

The WezTerm window isn't invisible.

### Logs

I can't open the debug overlay, because the window is invisible.

**Comment by wez** [comment] 2023-08-29 19:10
My guess is that this is a duplicate of:
* https://github.com/wez/wezterm/issues/3619

**Comment by wez** [comment] 2023-08-29 19:12
Oh, I misread "doesn't" as "does".  Disregard my previous comment.
Does a non-flatpak package work consistently?
This may just be a weird wayland bug; I'd suggest setting `enable_wayland=false` in your config and see if that helps.

**Comment by poperigby** [comment] 2023-08-29 20:28
No worries.

>  Does a non-flatpak package work consistently?

Yes. The issue only seems to happen with the Flatpak version. I repeatedly opened the native version (about 20 times), and it was never invisible. If I open the Flatpak version that amount of times, it will happen about 3 times.

>  This may just be a weird wayland bug; I'd suggest setting `enable_wayland=false` in your config and see if that helps.

If I set that, WezTerm fails to launch at all with this error:

```
13:27:25.113  ERROR  wezterm_gui > XOpenDisplay failed to open a display. Check the $DISPLAY env var; terminating
```

I made sure the Flatpak had permission to use X11.

**Comment by wez** [comment] 2024-01-16 21:33
I have no plans to do anything to look into this or resolve it; I just can't afford the time. I recommend using native packages in any case.

**Comment by poperigby** [comment] 2024-01-16 21:45
Okay, I understand. Sorry to bother you.

**Comment by poperigby** [comment] 2024-02-15 03:20
So, I've switched over to the native package, and it actually does still happen, at least when `enable_wayland` is true.

**Comment by wez** [comment] 2024-02-15 22:22
OK, I think this is a straight duplicate of #3619 so I'm going to close this in favor of that

**Closed by wez** 2024-02-15 22:22 UTC
Labels: bug, Wayland
