### ISSUE TITLE
tab bar like safari

### ISSUE THREAD

**Issue by moonsung-ho** [wez/wezterm#4002] opened 2023-07-15 12:58 UTC
please make wezterm's tab bar like safari
<img width="67" alt="image" src="https://github.com/wez/wezterm/assets/64302779/b868ffc5-628f-42b7-bea6-0415fa1562d9">
like this integrated tab bar and title bar.

**Comment by wez** [comment] 2023-07-15 15:03
Duplicate of https://github.com/wez/wezterm/issues/1180

**Closed by wez** 2023-07-15 15:03 UTC
Labels: enhancement
