### ISSUE TITLE
Downarrow key sends "\r", Enter 

### ISSUE THREAD

**Issue by lchen-p** [wez/wezterm#3810] opened 2023-05-31 00:29 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 

### WezTerm version

wezterm 20230524-062011-1cd340bb

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I press downarrow key, it sends  "\r". So effectively I cannot use up/down arrow to go through previous commands, because the downarrow key will sends "\r", Enter, which triggers that command directly. I build wezterm from source. I am not sure what causes this and how to change this behavior. 

### To Reproduce

press downarrow key

### Configuration

no config

### Expected Behavior

Downarrow key doesn't send "\r", Enter. 

### For downarrow key:
```
17:12:20.684  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(DownArrow), modifiers: NONE, leds: (empty), phys_code: Some(DownArrow), raw_code: 104, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
17:12:20.684  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('\r'), modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(DownArrow), modifiers: NONE, leds: (empty), phys_code: Some(DownArrow), raw_code: 104, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
17:12:20.684  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=Enter mods=NONE
17:12:20.684  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\r", Enter NONE
17:12:20.822  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: DownArrow, modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(DownArrow), modifiers: NONE, leds: (empty), phys_code: Some(DownArrow), raw_code: 104, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
17:12:20.822  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=DownArrow mods=NONE
```

### When I try uparrow key, it behaves normal:
```
17:25:29.355  INFO   wezterm_gui::termwindow::keyevent > key_event RawKeyEvent { key: Physical(UpArrow), modifiers: NONE, leds: (empty), phys_code: Some(UpArrow), raw_code: 98, repeat_count: 1, key_is_down: true, handled: Handled(false) } 
17:25:29.355  INFO   wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: UpArrow, modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: true, raw: Some(RawKeyEvent { key: Physical(UpArrow), modifiers: NONE, leds: (empty), phys_code: Some(UpArrow), raw_code: 98, repeat_count: 1, key_is_down: true, handled: Handled(false) }) } 
17:25:29.355  INFO   wezterm_gui::termwindow::keyevent > send to pane DOWN key=UpArrow mods=NONE
17:25:29.355  INFO   wezterm_term::terminalstate::keyboard > key_down: sending "\u{1b}[A", UpArrow NONE
17:25:29.464  INFO   wezterm_gui::termwindow::keyevent     > key_event KeyEvent { key: UpArrow, modifiers: NONE, leds: (empty), repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Physical(UpArrow), modifiers: NONE, leds: (empty), phys_code: Some(UpArrow), raw_code: 98, repeat_count: 1, key_is_down: false, handled: Handled(false) }) } 
17:25:29.464  INFO   wezterm_gui::termwindow::keyevent     > send to pane UP key=UpArrow mods=NONE
```

### Anything else?

I do have a warning when wezterm starts, but I am not sure if it matters:

```
17:25:27.138  WARN   window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: invalid value: string "()", expected at least one field signature between `(` and `)`: invalid value: string "()", expected at least one field signature between `(` and `)`
libEGL warning: DRI2: failed to authenticate
```

**Comment by lchen-p** [comment] 2023-05-31 18:23
Thanks for the reply. I also just have a US-English layout, don't have IME or anything special configured, at least I cannot find it. 
```
> localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us
```
Strange thing is, I don't see this behavior from gnome terminal or st, or kitty. Any idea where I can further investigate?

**Comment by wez** [comment] 2023-05-31 19:04
Try setting `use_ime = false` in your config?

**Comment by lchen-p** [comment] 2023-05-31 19:38
I tried the `showkey -a` command, by first pressing **uparrow** key then **downarrow** key, then Ctrl-D to exit:

In gnome terminal, or kitty or st:

```
Press any keys - Ctrl-D will terminate this program

^[[A 	27 0033 0x1b
 	91 0133 0x5b
 	65 0101 0x41
^[[B 	27 0033 0x1b
 	91 0133 0x5b
 	66 0102 0x42
^D 	 4 0004 0x04
```

in wezterm:

showkey -a

```
Press any keys - Ctrl-D will terminate this program

^[[A     27 0033 0x1b
         91 0133 0x5b
         65 0101 0x41
^M       13 0015 0x0d
^D        4 0004 0x04
```

I am kinda stuck now

**Comment by wez** [comment] 2023-06-01 03:00
Try running `xev -event keyboard` then pressing just the down arrow key, and share the output.

Then, start wezterm like this: 

```console
$ WEZTERM_LOG=window::os::x11::keyboard=trace,info wezterm -n --config debug_key_events=true
```

and press the down arrow, and share the output.

**Comment by lchen-p** [comment] 2023-06-01 08:41
Thanks a lot for taking a look and trying to help @wez !

**Comment by wez** [comment] 2023-06-01 15:07
This line:

```
01:36:56.037  TRACE  window::os::x11::keyboard         > process_key_event: RawKeyEvent FeedResult::Nothing: "", 65364. kc -> None def_sym=65421
```

shows that we got the Down key (65364, which is the 0xff54 key from the xev output), but because it didn't have a defined string representation, we chose to fallback to the default symbol for that key which is 65421, the enter key.

That default symbol comes from the system default keymap/layout on your system.

Can you tell me more about how that is setup for you?

On my system that default keymap is the same as the keymap I use; both as US english.
The purpose of using the fallback in this case is to allow for matching/mapping for non-latin layouts. It was introduced in 21e19ca09123dafd2d2ba5e21ef58ee7cbf1b123

**Comment by lchen-p** [comment] 2023-06-01 20:21
I would like to tell you, but I don't know how to get more info about my default keymap. I run below 2 commands. Let me know if there is any other command I can run or any other place I can check.

```
> cat /etc/vconsole.conf
KEYMAP="us"
FONT="eurlatgr"
```

```
> localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us
```

**Comment by lchen-p** [comment] 2023-06-13 07:04
Hi @wez, do you know where I can check further about my setup?

**Comment by wez** [comment] 2023-06-13 14:24
Sorry, no; I haven't had time to look any deeper at this

**Comment by wez** [comment] 2023-07-10 20:26
Please try the nightly build; I think this may be a duplicate of #3610 which was recently fixed.

**Closed** 2023-07-12 19:00 UTC
Labels: bug, fixed-in-nightly, waiting-on-op, keyboard
