### ISSUE TITLE
Every key stroke makes a new empty line in Nushell 

### ISSUE THREAD

**Issue by Event-Horizon-Labs** [wez/wezterm#3168] opened 2023-02-27 02:59 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

When I use Nushell and type anything, aside of the key being showed in the console, a new line is added to the shell, like if I were pressing enter.

![image](https://user-images.githubusercontent.com/1145623/221462198-943ee2a9-8eb6-414c-98d0-891017bd8e85.png)

![image](https://user-images.githubusercontent.com/1145623/221462220-fe32dbee-c39d-486d-881e-b69be5f9ba85.png)

### WezTerm version

WezTerm-20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Open Wezterm using the cmd, then type nu, when I use Nushell and type anything, aside from the key being shown in the console, a new line is added to the shell, as if I were pressing the enter key. 

### To Reproduce

Just launch Nushell and type

### Configuration

return {
    color_scheme = "Galaxy",
    }

### Expected Behavior

It should just put the key I type

**Comment by wez** [comment] 2023-02-27 05:30
Is this a duplicate of https://github.com/wez/wezterm/issues/2779 ?

**Comment by Event-Horizon-Labs** [comment] 2023-02-27 16:53
Yes, it seems so, I didn't see that previous report.

**Comment by wez** [comment] 2023-03-02 01:56
Duplicate of #2779

**Closed by wez** 2023-03-02 01:56 UTC
Labels: bug
