### ISSUE TITLE
Debug overlay prompt does not type characters that require key combinations

### ISSUE THREAD

**Issue by kalocsaibotond** [wez/wezterm#5257] opened 2024-04-02 14:06 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I am using WezTerm on a hungarian keyboard and I used the debug overlay to debug my lua configuration. On foreign keyboards there are many characters that can be only typed with using key combinations (usually with shift or alt gr modifiers. When I attempt to type such characters, the debug overlay do not access them.

### To Reproduce

Just use the debug overlay, and try to type characters, that require key combinations on your keyboard.

### Configuration

The bug is also present on vanilla WezTerm, without any configuration.

### Expected Behavior

After pressing the key combinations, the corresponding characters ought to be typed into the prompt.

**Comment by wez** [comment] 2024-05-06 00:44
Duplicate of https://github.com/wez/wezterm/issues/3999 please use a more recent version of wezterm.

**Closed by wez** 2024-05-06 00:44 UTC
Labels: bug
