### ISSUE TITLE
Modifier key+any key sends QWERTY key, even in other keyboard layouts

### ISSUE THREAD

**Issue by ProspectPyxis** [wez/wezterm#3678] opened 2023-05-04 07:05 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

20230501-084619-d0e9a034

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Pressing a key combination such as ctrl-a in a non-QWERTY keyboard layout seems to send the corresponding QWERTY key regardless of layout. For example, while on Colemak-DH, pressing ctrl-c instead sends ctrl-x to the terminal (as X in QWERTY corresponds to C in Colemak-DH).

### To Reproduce

1. Switch to any non-QWERTY English keyboard layout, such as Colemak-DH in my case.
2. Attempt to press ctrl-c.
3. Terminal receives ctrl-x instead, as X in QWERTY corresponds to C in Colemak-DH.

Though untested, I'm assuming the effect is the same with other layouts.

### Configuration

No config.

### Expected Behavior

The terminal receives ctrl-c and handles it accordingly (SIGINT, etc.).

### Logs

```
14:04:15.802 WARN window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
```

### Anything else?

This could be intended behavior, though I'm reporting this as a bug anyways since this was not the behavior formerly. I don't know which version this started happening with, though.

**Comment by rogueeve575** [comment] 2023-05-04 08:57
I can also confirm this bug (on standard Colemak here), and that it is new behavior. I have been on the git version for some time without issues and was surprised just now when after updating a few days ago (but apparently, I hadn't actually reloaded the new version yet), a reload suddenly made my "CTRL|SHIFT|T" "new tab" key go fullscreen instead and some others behaving strangely too, e.g. <C-r> for reload config would freeze the terminal as if it were <C-s>. Eventually I realized that the "weird" behavior corresponded to the QWERTY positions of the keys, e.g. T in colemak is at where QWERTY puts F...my keyboard is actually labeled in Colemak though so it took a bit of head scratching before I figured that out; thinking it was something gone wrong with my config or something :P

This was also on 20230501 version. Downgrading to 20230408 (the current latest non-git version in the Arch repos) on the same config instantly fixed the issue, so this must have been a fairly recent regression.

Possibly of interest, I don't know, is that I previously ever since I started using Wezterm about 6mo ago, I have always had the same issue on MacOS (and only on Mac, not on any of my Linux machines), but was always able to work around it with "use_ime = false". So I tried setting that to both true and false on the affected Linux machine but it did not make any difference. I have not updated the MacOS box to 0501 to see if the regression occurs there too, but can confirm that this is suddenly a problem on Linux which will basically stop me from upgrading again until it's resolved.

I suppose I could add Lua code to my config (btw I really _love_ the Lua in Wezterm, please add more :P) to map all of the specified keys that I actually want to the equivalent positions in QWERTY, e.g. change CTRL|SHIFT|T to CTRL|SHIFT|F, CTRL|N to CTRL|J, etc before returning the key config to Wezterm...but that hardly seems like the best solution :P

**Comment by wez** [comment] 2023-05-04 15:45
I haven't had time to look into this yet, but I suspect it is a duplicate of:
* https://github.com/wez/wezterm/issues/3610

in particular, see:
https://github.com/wez/wezterm/issues/3610#issuecomment-1521188292

**Comment by sarphiv** [comment] 2023-05-07 12:30
I am also experiencing this issue. It reminds me a lot of #3470, but this time for modifier+key combinations instead.
The issue seems to have been introduced between fixing #3470 and now. 

I followed your comment to #3610, made a clean clone from main, ran wezterm and the issue was present. I then reverted commit 21e19ca, and ran wezterm again, the issue appeared to have been fixed. 

On a side note, the default font on main appears very slightly more "bold"/blurry now. I haven't kept up with the change log, so I just wanted to mention it in case it was unintended.

**Comment by seungjin** [comment] 2023-07-09 04:09
I have two laptops one with Fedora 38 Silverblue and Debian 12. I don't see this problem in Debain 12 but see the issue on F38 Silverblue. Seems there is some outside issue. 
LeftWM (window manager) + Colnmak keylayout.

**Comment by rogueeve575** [comment] 2023-07-09 05:46
Yes, Colemak here too and still having this issue, which has basically kept me from updating ever since May since it basically makes all shortcuts (new tab etc) unusable if you don't use qwerty. For Arch Linux, one workaround is to do "yay --getpkgbuild wezterm-git", then modify the PKGBUILD: change line 33 (of the 'source' array) to freeze the download at a commit before this glitch, and do a "makepkg -si" to install; e.g. I've been using:

```
source=(
  "wezterm::git+https://github.com/wez/wezterm.git#commit=94359d29728b828210e8df41ca982057b90aafbd"
  "harfbuzz::git+https://github.com/harfbuzz/harfbuzz.git"
```

...of course, that kinda sucks though being stuck 2 months behind, and eventually they'll probably be some awesome new feature I can't live without, but at least I can still install Wezterm. I use the terminal a _LOT_, and have a 1200+ line wezterm.lua (really more of a program than a config at this point) with a lot of really nice productivity tweaks keeping me pretty invested in Wezterm as that terminal, so at this point I would probably just go make a local patch, but I'm a C/C++ person and don't really understand Rust all that well so haven't got around to it.

### Workaround 2:

That said though, just in case it helps anyone, I believe it should be actually possible to work around this glitch as a user from the wezterm.lua, by putting some translation code between the shortcut keys you define in your config and what you actually tell Wezterm that you want as the shortcut. In other words the idea is that in Colemak for example we might want CTRL+SHIFT+T to be "new tab". But since this glitch means that Wezterm will revert to QWERTY for all shortcut keys we can tell Wezterm that we want CTRL+SHIFT+F to be "new tab" since qwerty's "F" is in the Colemak "T" position, so then when we press <C-S>T and Wezterm sees <C-S>F it behaves as expected.

..and as it happens, I have some translation code that does just that. I wrote this for a different program I've been working on, but don't see any reason why it wouldn't work in Wezterm too; I just stripped out the irrelevant parts that were specific to my program and got the below module. You could assign your key table to a local variable, then iterate over the table and pass each "key" field through the translator function. I think you'd want "layoutconv.charToHardware()" for this use case. And of course you might want to fetch the default keytable or else fully redefine it to ensure that any shortcuts that you left at defaults would work too.
```

-- layoutconv.lua
-- support for alternative keyboard layouts such as Colemak/Dvorak

-- this allows translating physical keypresses (sent based on their qwerty
-- positions in most keyboards) to the proper keysym for the user's layout

-- usage example:
--      local layoutconv = require('layoutconv')
--      layoutconv.setup("colemak")
--      local qwertyKey = layoutconv.charToHardware('R')        -- returns "S"
--  local colemakKey = layoutconv.charFromHardware('s')     -- returns "r"
local TEST = true               -- run a demo usage on startup?

local layouts = {
        qwerty           = "qwertyuiop{} asdfghjkl;' zxcvbnm,./ 1234567890-=",
        colemak          = "qwfpgjluy;{} arstdhneio' zxcvbkm,./ 1234567890-=",
        colemak_dh       = "qwfpbjluy;{} arstgmneio' xcdvzkh,./ 1234567890-=",
        colemak_caws     = "qwfpb{jluy;' arstg}mneio xcdvz/kh,. 123456=7890-",
        workman          = "qdrwbjfup;{} ahstgyneio' zxmvckl,./ 1234567890-=",
        dvorak           = "',.pyfgcrl/= aoeuidhtns- ;qjkxbmvwz 1234567890{}",
}

-- set this to match the layout sent by your hardware. the number values for
-- evdev keycodes are based on their qwerty positions, and most keyboards
-- (even many Colemak/Dvorak keyboards), send keycodes based on each key's
-- position in qwerty, even if the actual keycap may be labeled differently
layouts.hardware = layouts.qwerty
local map_keycode_fromHardware, map_keycode_toHardware
local map_char_fromHardware, map_char_toHardware

-- default layout if setup() is given an argument
layouts.default = layouts.colemak

-- symbol names (KEY_xxx) for non-letter keys
--local specials, specials_rev = nil, nil
local specials_toupper, specials_tolower
local specials_in = {
        [";:"] = "SEMICOLON",
        ["~`"] = "GRAVE",
        ["\\|"] = "BACKSLASH",
        [",<"] = "COMMA",
        [".>"] = "DOT",
        ["/?"] = "SLASH",
        ["'\""] = "APOSTROPHE",
        ["+="] = "EQUAL",
}

local function initSpecials()
        if not specials_toupper then
                -- break up the combined two-char codes into multiple entries. this is
                -- just to make the definition of the specials table easier to read.
                specials_toupper, specials_tolower = {}, {}
                for k, v in pairs(specials_in) do
                        local len = #k
                        if len == 2 then
                                local lower = k:sub(1, 1)
                                local upper = k:sub(-1)

                                specials_toupper[lower] = upper
                                specials_tolower[upper] = lower
                        else
                                error("unexpected special length " .. len .. " in '" .. k .. "'")
                        end
                end
        end
end

-- a string.upper() / lower() that also works with special symbols
local _upper, _lower = string.upper, string.lower
local function strupper(ch)
        return specials_toupper[ch] or _upper(ch)
end
local function strlower(ch)
        return specials_tolower[ch] or _lower(ch)
end

local function setup(layoutName)
        map_keycode_fromHardware, map_keycode_toHardware = {}, {}
        map_char_fromHardware, map_char_toHardware = {}, {}
        initSpecials()

        layoutName = layoutName or "default"
        local usermap = layouts[layoutName]
        local hardmap = layouts.hardware

        print("layoutconv: initializing layout '" .. layoutName .. "'")

        if not hardmap then error("hardmap not configured") end
        if not usermap then
                error("unknown layout '" .. tostring(layoutName) .. "'")
        end

        if usermap ~= hardmap then
                assert(#usermap == #hardmap, "hardmap & usermap must be the same length")

                local len = #usermap
                local insert = table.insert
                for i = 1, len do
                        local hardkey = hardmap:sub(i, i)
                        local userkey = usermap:sub(i, i)
                        if hardkey ~= userkey then
                                -- build conversion maps
                                map_char_fromHardware[hardkey] = userkey
                                map_char_toHardware[userkey] = hardkey

                                -- uppercase versions
                                local HARDKEY, USERKEY = strupper(hardkey), strupper(userkey)
                                if HARDKEY ~= hardkey then
                                        map_char_fromHardware[HARDKEY] = USERKEY
                                end
                                if USERKEY ~= userkey then
                                        map_char_toHardware[USERKEY] = HARDKEY
                                end
                        end
                end
        end
end

local function mapKey(key, tbl)
        return tbl[key] or key
end

local mapChar = mapKey
local function mapString(str, tbl)
        local out = ""
        for ch in string.gmatch(str, ".") do
                out = out .. mapChar(ch, tbl)
        end
        return out
end

local M = {
        setup = setup,

        -- the same, but these work on characters rather than keycodes,
        -- in other words, charToHardware("t") = "f".
        charToHardware = function(char)
                return mapChar(char, map_char_toHardware)
        end,
        charFromHardware = function(char)
                return mapChar(char, map_char_fromHardware)
        end,

        -- same as the char functions, but will work on multi-character strings.
        strToHardware = function(str)
                return mapString(str, map_char_toHardware)
        end,
        strFromHardware = function(str)
                return mapString(str, map_char_fromHardware)
        end,
}

if TEST then
        setup("colemak")
        local testString = "ARST;:"
        local test_c2q = M.strToHardware(testString)
        local test_q2c = M.strFromHardware(test_c2q)

        print();
        print("if you typed \"" .. testString .. "\" in Colemak on a qwerty kbd you'd get: "
                        .. "'" .. test_c2q .. "'")

        print()
        print("if you typed \"" .. test_c2q .. "\" in qwerty on a Colemak keyboard you'd get: "
                        .. "'" .. test_q2c .. "'")
        --print(M.charToHardware('R'))
        --print(M.charFromHardware('s'))
end

return M
```

..A little hacky to have to do this so still hoping for a proper fix, but I think it should work if anyone wants to try.

**Comment by wez** [comment] 2023-07-09 19:33
Duplicate of https://github.com/wez/wezterm/issues/3610 which now has a fix in `main`

**Closed by wez** 2023-07-09 19:33 UTC
Labels: bug, X11, keyboard

**Comment by seungjin** [comment] 2023-07-11 00:58
Updated the main (most recent one at the moment: d07ec3e8bb14cf784f9ca74ed69f5ab03d685650)
Problem solved.
