### ISSUE TITLE
INTEGRATED_BUTTONS window_decorations style does *not* disable a window title

### ISSUE THREAD

**Issue by develop7** [wez/wezterm#6221] opened 2024-10-03 11:32 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter 46.5

### WezTerm version

wezterm a2f2c07

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`window_decorations = "INTEGRATED_BUTTONS"` doesn't disable the window title:

### To Reproduce

1. follow https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html regarding `INTEGRATED_BUTTONS` style (see config below)

### Configuration

```lua
local wezterm = require 'wezterm'

return {
	default_prog = {"/usr/bin/nu"},
	font = wezterm.font_with_fallback {
		{ family = 'PragmataPro Mono', harfbuzz_features = { 'liga=0'} },
		{ family = 'JetBrains Mono' },
		'Droid Sans Mono',
		"Noto Color Emoji"
	},
	font_size = 14,
	freetype_load_target = 'Light',
	freetype_render_target = 'HorizontalLcd',
	-- use_cap_height_to_scale_fallback_fonts = true,
	color_scheme = 'Tokyo Night Storm',
	default_cursor_style = "BlinkingBlock",
	window_decorations = "INTEGRATED_BUTTONS|RESIZE",
	integrated_title_button_alignment = "Left",
}
```

### Expected Behavior

The window title should disappear, as the doc says

### Logs

```text
Debug Overlay
wezterm version: a2f2c07 x86_64-unknown-linux-gnu
Window Environment: X11 GNOME Shell
Lua Version: Lua 5.4
OpenGL: NVIDIA GeForce RTX 3080/PCIe/SSE2 4.6.0 NVIDIA 550.120
```

### Anything else?

![image](https://github.com/user-attachments/assets/fef4d6ea-f761-4810-8c4b-b5d0a227c305)

In fact, the only style that makes the title actually disappear for me is the `NONE`, without `RESIZE`: anything with `|RESIZE` enables window title back

**Comment by develop7** [comment] 2024-10-05 16:46
Affects Wayland too

please let me know how could I improve this report

**Comment by xieve** [comment] 2024-11-28 16:36
Duplicate of #3936

**Comment by develop7** [comment] 2024-11-28 19:13
Agreed

**Closed** 2024-11-28 19:13 UTC
Labels: bug
