### ISSUE TITLE
Shift+PgUp after switching between fullscreen and windowed breaks the screen

### ISSUE THREAD

**Issue by lesleyrs** [wez/wezterm#3409] opened 2023-03-31 04:55 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Using `PgUp` works as intended, but when using `Shift+PgUp` (I guess this is a bigger jump?) while scroll bar is enabled the screen glitches as it scrolls to somewhere it shouldn't. Happened both in helix-editor and vim.

### To Reproduce

To make this happen I had to enter an editor, then fullscreen -> windowed + optionally back to fullscreen and now you can `Shift+PgUp` to break the screen.

### Configuration

scroll bar setting in title, other stuff is most likely unrelated.

### Expected Behavior

Don't allow `Shift-PgUp` to scroll past boundaries, limit it.

### Anything else?

![image](https://user-images.githubusercontent.com/19632758/229024878-f411e301-9231-4e87-b869-e546b5b95342.png)

**Comment by lesleyrs** [comment] 2023-03-31 05:00
Oh huh, I just noticed this still happens after turning off the scroll bar, so it's not related.

**Comment by wez** [comment] 2023-03-31 05:24
Windows has a complicated set of terminal situations going on.

More information is needed: what shell environment are you using? cmd.exe/powershell.exe/git bash/WSL/mingw or something else?

What editor do you have open?  Is it native win32 or does it belong to the shell environment you are using?

Are you connecting to a remote host?

Please spend some time to figure out the minimal config file that reproduces the issue and share it, it can make all the difference to reproducing an issue, which is key to resolving it.

**Comment by lesleyrs** [comment] 2023-03-31 15:27
Ok I turned off all settings to just leave the empty config
```
 -- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- and finally, return the configuration to wezterm
return config
```
Which I don't think does anything to affect this, then I restarted the terminal. Happens on cmd, pwsh, WSL with a native editor (helix, vim) not a remote host.

---
After some more testing I found out why it breaks. It doesn't actually allow you to use `Shift-PgUp` at first when inside an editor, you have to exit `fullscreen` when inside of the editor and then it will break for the entire time the terminal is active. The desired behavior is never allowing `Shift-PgUp` to be used as long as the editor is active, regardless of how many times you enter or exit fullscreen. PgUp by itself doesn't create this problem and works as intended.

**Comment by wez** [comment] 2023-03-31 15:48
By default, Shift PageUp and PageDown are assigned to scroll the scrollback:

```lua
$ wezterm -n show-keys --lua | grep ScrollByPage
    { key = 'PageUp', mods = 'SHIFT', action = act.ScrollByPage(-1) },
    { key = 'PageDown', mods = 'SHIFT', action = act.ScrollByPage(1) },
```

Those key assignments take precedence; they are never routed to the terminal for processing and will not be used by an editor running inside the terminal.

When you switch in and out of full screen, because of quirks on Windows, that generates data that gets moved into the scrollback so that those key assignments will scroll the screen.

In a normal unixy situation, text ui editors will switch to the "Alternate Screen" which has no scrollback and for which this effect will not occur.

If you don't want these key assignments to operate on the scrollback, you can disable them in your config:

```lua
local act = wezterm.action
config.keys = {
   { key = 'PageUp', mods = 'SHIFT', action = act.DisableDefaultAssignment },
   { key = 'PageDown', mods = 'SHIFT', action = act.DisableDefaultAssignment },
}
```

See: https://wezfurlong.org/wezterm/config/lua/keyassignment/DisableDefaultAssignment.html

**Comment by lesleyrs** [comment] 2023-03-31 16:16
> When you switch in and out of full screen, because of quirks on Windows, that generates data that gets moved into the scrollback so that those key assignments will scroll the screen.
> 
> In a normal unixy situation, text ui editors will switch to the "Alternate Screen" which has no scrollback and for which this effect will not occur.

Ok that makes sense, but I don't want to disable the keys since I use them to scroll through history outside of the editor.

I can simply avoid the issue and it's fine, but windows terminal doesn't allow you to use their `ctrl+shift+PgUp` shortcut outside of the command line even after entering and leaving fullscreen. Not sure how they did this.

Correct me if I'm wrong but do wezterm key assignments work anywhere, and you can only disable them completely? So you can either use `Shift-PgUp` everywhere or nowhere?

If the above is true I wonder how some other shortcuts will interact with things on windows. I'll have to try wezterm more and see what happens.

**Comment by wez** [comment] 2023-03-31 18:55
https://wezfurlong.org/wezterm/config/keyboard-concepts.html has a flow chart that explains how keyboard processing works

**Closed** 2023-04-02 18:24 UTC
Labels: bug, Windows

**Comment by lesleyrs** [comment] 2023-04-02 19:26
I still think this would be worth fixing in some way, as everyone that uses windows will probably be confused when this happens and it serves no purpose.

Would it be possible to disable the scrollback keybind if you're in an alternate screen on windows?

**Comment by wez** [comment] 2023-04-02 20:46
From my perspective, there is nothing to fix here.  You are literally the only person to question this behavior in the past 5 years. Adding more complexity by default is not warranted.

**Comment by lesleyrs** [comment] 2023-04-02 21:09
> Adding more complexity by default is not warranted.

I don't agree that your screen being glitched for pressing a wrong key can be considered "by default".

Your only suggestion was to turn off scrollback, which I couldn't recommend anyone to do in any scenario.

I'll leave it at that though.
