### ISSUE TITLE
windows 10 nightly not starting

### ISSUE THREAD

**Issue by ahcm** [wez/wezterm#359] opened 2020-12-02 23:42 UTC
wezterm 20201101-103216-403d002d-81-gab54d1f8

thread 'main' panicked at 'only valid for opengl render mode', wezterm-gui\src\gui\renderstate.rs:293:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 2020-12-02T23:37:37.717Z ERROR window::os::windows::window > caught Any

thread 'main' panicked at 'only valid for opengl render mode', wezterm-gui\src\gui\renderstate.rs:293:18
stack backtrace:
   0:     0x7ff7d377cf39 - <unknown>
   1:     0x7ff7d379dedb - <unknown>
   2:     0x7ff7d3773238 - <unknown>
   3:     0x7ff7d377ff94 - <unknown>
   4:     0x7ff7d377fb78 - <unknown>
   5:     0x7ff7d3780880 - <unknown>
   6:     0x7ff7d2edc984 - <unknown>
   7:     0x7ff7d2ed839f - <unknown>
   8:     0x7ff7d2e6761d - <unknown>
   9:     0x7ff7d2eb5a58 - <unknown>
  10:     0x7ff7d2ea144b - <unknown>
  11:     0x7ff7d3067565 - <unknown>
  12:     0x7ff7d3069229 - <unknown>
  13:     0x7ff7d306c52d - <unknown>
  14:     0x7fffdaf7e858 - CallWindowProcW
  15:     0x7fffdaf7e3dc - DispatchMessageW
  16:     0x7fffdaf95c00 - LookupIconIdFromDirectoryEx
  17:     0x7fffdb98fbd4 - KiUserCallbackDispatcher
  18:     0x7fffd91c14c4 - NtUserSetWindowPos
  19:     0x7fffd6addb2d - BufferedPaintUnInit
  20:     0x7fffd6add34c - GetThemeTextMetrics
  21:     0x7fffd6add22d - GetThemeTextMetrics
  22:     0x7fffd6acf2b7 - IsCompositionActive
  23:     0x7fffdaf7e962 - CallWindowProcW
  24:     0x7fffdaf7de1b - SendMessageW
  25:     0x7fffdaf7d68a - SendMessageW
  26:     0x7fffd6adfe24 - SetWindowTheme
  27:     0x7ff7d3065459 - <unknown>
  28:     0x7ff7d2eacba8 - <unknown>
  29:     0x7ff7d2ef7d72 - <unknown>
  30:     0x7ff7d32367a2 - <unknown>
  31:     0x7ff7d2eee829 - <unknown>
  32:     0x7ff7d2ee5cc5 - <unknown>
  33:     0x7ff7d2f0146a - <unknown>
  34:     0x7ff7d2e3010a - <unknown>
  35:     0x7ff7d305c4e1 - <unknown>
  36:     0x7ff7d3071a50 - <unknown>
  37:     0x7ff7d2e63ce8 - <unknown>
  38:     0x7ff7d2e617d1 - <unknown>
  39:     0x7ff7d2ed8eb6 - <unknown>
  40:     0x7ff7d2f0546c - <unknown>
  41:     0x7ff7d3780b83 - <unknown>
  42:     0x7ff7d2e662f7 - <unknown>
  43:     0x7ff7d3a424fc - <unknown>
  44:     0x7fffdb137034 - BaseThreadInitThunk
  45:     0x7fffdb93cec1 - RtlUserThreadStart
 2020-12-02T23:41:12.400Z ERROR window::os::windows::window > caught Any

**Comment by wez** [comment] 2020-12-05 18:57
I'm pretty sure this is a duplicate of #358 and is fixed by the commit referenced above; I'm going to speculatively close this out too, but please re-open this if the problem persists even with an updated nightly build (the change should be available in an hour or so).

**Closed by wez** 2020-12-05 18:57 UTC
Labels: bug
