### ISSUE TITLE
ActiveLastTab not a valid action

### ISSUE THREAD

**Issue by jaredramirez** [wez/wezterm#693] opened 2021-04-13 23:02 UTC
## Describe the bug

Wezterm does not accept a key binding to the action `ActivateLastTab` action

## Environment (please complete the following information):

 - OS: macOS
 - Version: Latest version published to nixpkgs (when I run `wezterm -V` no version prints)
 - ENG

## To Reproduce

Launch wezterm with the below config

## Configuration

```
local wezterm = require 'wezterm';

return {
    ...
    keys = {
        ...
        { key="l", mods="CMD", action="ActivateLastTab" },
    }
}
```

## Expected behavior

Wezterm should accept this config & map CMD-l to `ActivateLastTab`

## Actual Behavior

Wezterm prints:
```
Error converting lua value returned by script
/Users/jaredramirez/.config/wezterm/wezterm.lua to Config struct: while
processing a struct of type `Config` with value:
{
    ...
    "keys": [
        ...
        {
            "action": "ActivateLastTab",
            "key": "l",
            "mods": "CMD",
        },
    ],
}
while processing a struct of type `Key` with value:
{
    "action": "ActivateLastTab",
    "key": "l",
    "mods": "CMD",
}
while processing an enum of type `KeyAssignment` and value "ActivateLastTab"
which has allowed variants `ActivateCopyMode`, `ActivatePaneDirection`,
`ActivateTab`, `ActivateTabRelative`, `AdjustPaneSize`, `ClearScrollback`,
`CloseCurrentPane`, `CloseCurrentTab`, `CompleteSelection`,
`CompleteSelectionOrOpenLinkAtMouseCursor`, `Copy`, `DecreaseFontSize`,
`DisableDefaultAssignment`, `EmitEvent`, `ExtendSelectionToMouseCursor`,
`Hide`, `HideApplication`, `IncreaseFontSize`, `MoveTab`, `MoveTabRelative`,
`Nop`, `OpenLinkAtMouseCursor`, `Paste`, `PastePrimarySelection`,
`QuitApplication`, `ReloadConfiguration`, `ResetFontSize`, `ScrollByPage`,
`ScrollToPrompt`, `Search`, `SelectTextAtMouseCursor`, `SendString`, `Show`,
`ShowLauncher`, `ShowTabNavigator`, `SpawnCommandInNewTab`,
`SpawnCommandInNewWindow`, `SpawnTab`, `SpawnWindow`, `SplitHorizontal`,
`SplitVertical`, `ToggleFullScreen`, `TogglePaneZoomState`
unknown variant `ActivateLastTab`, expected one of `SpawnTab`, `SpawnWindow`,
`ToggleFullScreen`, `Copy`, `Paste`, `PastePrimarySelection`,
`ActivateTabRelative`, `IncreaseFontSize`, `DecreaseFontSize`,
`ResetFontSize`, `ActivateTab`, `SendString`, `Nop`,
`DisableDefaultAssignment`, `Hide`, `Show`, `CloseCurrentTab`,
`ReloadConfiguration`, `MoveTabRelative`, `MoveTab`, `ScrollByPage`,
`ScrollToPrompt`, `ShowTabNavigator`, `HideApplication`, `QuitApplication`,
`SpawnCommandInNewTab`, `SpawnCommandInNewWindow`, `SplitHorizontal`,
`SplitVertical`, `ShowLauncher`, `ClearScrollback`, `Search`,
`ActivateCopyMode`, `SelectTextAtMouseCursor`, `ExtendSelectionToMouseCursor`,
`OpenLinkAtMouseCursor`, `CompleteSelection`,
`CompleteSelectionOrOpenLinkAtMouseCursor`, `AdjustPaneSize`,
`ActivatePaneDirection`, `TogglePaneZoomState`, `CloseCurrentPane`,
`EmitEvent`
```

And indeed `ActiveLastTab` is not in the list of acceptable values!

## Additional context

This is something that should be possible based on the docs here: https://wezfurlong.org/wezterm/config/lua/keyassignment/ActivateLastTab.html

**Comment by cxiao** [comment] 2021-04-13 23:40
The documentation for that action says it was only added in the 20210404-112810-b63a949d release (i.e. the April 4, 2021 release), I think the version on nixpkgs is probably older than that?

**Comment by wez** [comment] 2021-04-13 23:44
Yeah, the nix package is currently older than this feature.

@pinpox @SuperSandro2000 have a PR to update it, but it's currently waiting on me cutting another new release.

It would be great to make the version number work in nix so that it is easier to debug.  There's a special file included in the source tarball produced by CI that is intended to make that work, but if you are building from the git repo, it may be the case that git needs to be present in the context that the build runs so that the version number is correctly detected.

**Comment by bew** [comment] 2021-04-13 23:44
@cxiao did you install it recently? wezterm in nixpkgs has been updated recently (https://github.com/NixOS/nixpkgs/pull/118712) to a revision at least around 2021-04-07

**Comment by pinpox** [comment] 2021-04-14 11:45
I'm using a custom package until there is a new release in `nixpkgs`, which uses the raw linux binary instead of building from source. Printing the version number works fine as far as I can tell:
```
➜ wezterm -V
wezterm 20210405-110924-a5bb5be8-86-g776aedf9
```

@SuperSandro2000 should we maybe change the package in `nixpkgs` to use the binary or is source always preferred?

In case someone wants to use the latest nightly binary with nixOS [here is my package](https://github.com/pinpox/nixos/blob/main/packages/wezterm-bin/default.nix)

**Comment by wez** [comment] 2021-04-14 15:13
@pinpox: building for the system is preferable as some users have reported that the appimage runs slower than the purpose-built native package

@pinpox / @SuperSandro2000:

Does `fetchFromGitHub` in a nix file do a regular git clone, or does it download the github generated source tarball?
If the latter, can you tell it to either do a git clone, or to download the source tarball that wezterm's CI generates?

https://github.com/wez/wezterm/blob/main/ci/source-archive.sh#L2 is the logic that builds that tarball; it includes the submodules and a special marker file that wezterm's build can pick up and read the version number from.

That source tarball is a published artifact on the release page.  The current version is:

https://github.com/wez/wezterm/releases/download/20210405-110924-a5bb5be8/wezterm-20210405-110924-a5bb5be8-src.tar.gz

(as referenced from the https://wezfurlong.org/wezterm/install/source.html instructions)

If you need to construct that URL in code, it is has the form:

```
'https://github.com/wez/wezterm/releases/download/' + RELEASE + '/wezterm-' + RELEASE + '-src.tar.gz'
```

**Comment by SuperSandro2000** [comment] 2021-04-14 16:20
> Does fetchFromGitHub in a nix file do a regular git clone, or does it download the github generated source tarball?

It downloads the tarball if the path and options allow it. If not I think a git clone and checkout is done and then the .git directory is removed to make the tarball reproducible.

> to download the source tarball that wezterm's CI generates?

We usually prefer git clones/downloads to make patches easier. We can also very easily write the version number into a file or append it to the build command.

```nix
postPatch = ''
  echo ${version} > .tag
'';
```

This [line](https://github.com/wez/wezterm/blob/main/ci/source-archive.sh#L43) is most likely not reproducible. I think we are using ``tar --sort=name --mtime='@1' --owner=0 --group=0 --numeric-owner -c`` for that.

**Comment by wez** [comment] 2021-04-14 16:34
having `postPatch` write out the `.tag` file seems reasonable to me!

**Comment by wez** [comment] 2021-04-14 22:00
@jaredramirez I think if you update nix now you should get a version with that feature, and one that tells you its version!

**Comment by SuperSandro2000** [comment] 2021-04-15 01:50
> @jaredramirez I think if you update nix now you should get a version with that feature, and one that tells you its version!

You can look at https://nixpk.gs/pr-tracker.html?pr=119437 to know when it hits the different unstables.

**Comment by wez** [comment] 2021-04-16 01:18
(I'm closing this out as it isn't something directly relating to wezterm, but is rather a nix packaging concern, and that is addressed, albeit pending an updated package release)

**Closed by wez** 2021-04-16 01:18 UTC
Labels: bug
