### ISSUE TITLE
Error when creating split windows

### ISSUE THREAD

**Issue by pbhide** [wez/wezterm#903] opened 2021-06-25 18:44 UTC
## Describe the bug
I am new to this project.. want to try it out. Trying out the multiplexer. But when I reconnect to it I cannot split current pane. Get this error -
`
2021-06-25T18:32:03.816Z ERROR wezterm_client::client  > going to run wezterm cli proxy
 2021-06-25T18:32:04.014Z INFO  wezterm_gui::termwindow > OpenGL initialized! Intel Iris Pro OpenGL Engine 4.1 INTEL-14.7.8 is_context_loss_possible=false wezterm version: 20210502-154244-3f7122cb
 2021-06-25T18:32:04.375Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Intel Iris Pro OpenGL Engine 4.1 INTEL-14.7.8 is_context_loss_possible=false wezterm version: 20210502-154244-3f7122cb
 2021-06-25T18:32:09.140Z ERROR wezterm_gui::termwindow::spawn > Failed to spawn: unexpected response Ok(ErrorResponse(ErrorResponse { reason: "Error: pane_id 4 invalid" }))
`

## Environment (please complete the following information):

 - OS: MacOS
 - Version: wezterm 20210502-154244-3f7122cb

 - The active keyboard layout name (eg: ENG, DEU and so on)

## To Reproduce
Create a ssh_domain (pointing to a centos server).
wezterm conntect myserver
create panes, split vertically, horizontally
Quit (close all panes Yes). Ideally I would like to quit and keep the panes so I can attach to it later, is it possible?
Connect again using wezterm connect myserver
Now I cannot split the panes anymore get the error.

## Configuration
  ssh_domains = {
    {
      -- This name identifies the domain
      name = "sw-dev6",
      -- The address to connect to
      remote_address = "myserver",
      -- The username to use on the remote host
      username = "xyz",
    }
  }

## Expected behavior
I expected to see old tabs including the splits
OR
Be able to split them again

**Comment by wez** [comment] 2021-06-25 20:52
Duplicate of #781

**Closed by wez** 2021-06-25 20:52 UTC
Labels: bug, fixed-in-nightly
