### ISSUE TITLE
wezterm unable to start after update and reboot

### ISSUE THREAD

**Issue by stankovictab** [wez/wezterm#5431] opened 2024-05-16 22:24 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

KWin on Wayland

### WezTerm version

20240515_054355_332b9b8b

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

wezterm doesn't create a window and crashes instantly with a libEGL.so error. 
I'm on Nobara 39 under KDE. 
This has been happening ever since I updated the system. 
I've seen other issues similar to this one and haven't found anything that can help me there. 
The issue is present even when running wezterm without a config file. 
The system is up to date, I tried rebooting, and the wezterm binary is from dnf, not flatpak. 

### Configuration

no config

### Expected Behavior

The wezterm window appears. 

### Logs

00:19:28.533  ERROR  wezterm_gui::frontend > Failed to create window: with_egl_lib failed: with_egl_lib(libEGL.so.1) failed: EGL CreateWindowSurface: BAD_MATCH 0x55846e75fc10
EGL CreateWindowSurface: BAD_MATCH 0x55846e75fce0
EGL CreateWindowSurface: BAD_MATCH 0x55846e760290
EGL CreateWindowSurface: BAD_MATCH 0x55846e760500
EGL CreateWindowSurface: BAD_MATCH 0x55846e760360
EGL CreateWindowSurface: BAD_MATCH 0x55846e7605d0
EGL CreateWindowSurface: BAD_MATCH 0x55846e760430
EGL CreateWindowSurface: BAD_MATCH 0x55846e7606a0
EGL CreateWindowSurface: BAD_MATCH 0x55846e760910
EGL CreateWindowSurface: BAD_MATCH 0x55846e7609e0
EGL CreateWindowSurface: BAD_MATCH 0x55846e760f90
EGL CreateWindowSurface: BAD_MATCH 0x55846e761200
EGL CreateWindowSurface: BAD_MATCH 0x55846e761060
EGL CreateWindowSurface: BAD_MATCH 0x55846e7612d0
EGL CreateWindowSurface: BAD_MATCH 0x55846e761130
EGL CreateWindowSurface: BAD_MATCH 0x55846e7613a0
, with_egl_lib(libEGL.so) failed: EGL CreateWindowSurface: BAD_MATCH 0x55846e6d97a0
EGL CreateWindowSurface: BAD_MATCH 0x55846e6d9870
EGL CreateWindowSurface: BAD_MATCH 0x55846e6d9e20
EGL CreateWindowSurface: BAD_MATCH 0x55846e6da090
EGL CreateWindowSurface: BAD_MATCH 0x55846e6d9ef0
EGL CreateWindowSurface: BAD_MATCH 0x55846e6da160
EGL CreateWindowSurface: BAD_MATCH 0x55846e6d9fc0
EGL CreateWindowSurface: BAD_MATCH 0x55846e6da230
EGL CreateWindowSurface: BAD_MATCH 0x55846e6da4a0
EGL CreateWindowSurface: BAD_MATCH 0x55846e6da570
EGL CreateWindowSurface: BAD_MATCH 0x55846e6dab20
EGL CreateWindowSurface: BAD_MATCH 0x55846e6dad90
EGL CreateWindowSurface: BAD_MATCH 0x55846e6dabf0
EGL CreateWindowSurface: BAD_MATCH 0x55846e6dae60
EGL CreateWindowSurface: BAD_MATCH 0x55846e6dacc0
EGL CreateWindowSurface: BAD_MATCH 0x55846e6daf30
, with_egl_lib(libEGL.so.1) failed: EGL CreateWindowSurface: BAD_MATCH 0x55846e47ea40
EGL CreateWindowSurface: BAD_MATCH 0x55846e4e0390
EGL CreateWindowSurface: BAD_MATCH 0x55846e4e0460
EGL CreateWindowSurface: BAD_MATCH 0x55846e4e06d0
EGL CreateWindowSurface: BAD_MATCH 0x55846e4e07a0
EGL CreateWindowSurface: BAD_MATCH 0x55846e61a650
EGL CreateWindowSurface: BAD_MATCH 0x55846e61a8c0
EGL CreateWindowSurface: BAD_MATCH 0x55846e749700
EGL CreateWindowSurface: BAD_MATCH 0x55846e5eb630
EGL CreateWindowSurface: BAD_MATCH 0x55846e5eb8a0
EGL CreateWindowSurface: BAD_MATCH 0x55846e5eb970
EGL CreateWindowSurface: BAD_MATCH 0x55846e5eba40
, with_egl_lib(libEGL.so) failed: EGL CreateWindowSurface: BAD_MATCH 0x55846e744eb0
EGL CreateWindowSurface: BAD_MATCH 0x55846e744f80
EGL CreateWindowSurface: BAD_MATCH 0x55846e745050
EGL CreateWindowSurface: BAD_MATCH 0x55846e7452c0
EGL CreateWindowSurface: BAD_MATCH 0x55846e745390
EGL CreateWindowSurface: BAD_MATCH 0x55846e745460
EGL CreateWindowSurface: BAD_MATCH 0x55846e7456d0
EGL CreateWindowSurface: BAD_MATCH 0x55846e5e07e0
EGL CreateWindowSurface: BAD_MATCH 0x55846e7459b0
EGL CreateWindowSurface: BAD_MATCH 0x55846e60fb50
EGL CreateWindowSurface: BAD_MATCH 0x55846e60fc20
EGL CreateWindowSurface: BAD_MATCH 0x55846e60fcf0

**Comment by stankovictab** [comment] 2024-05-16 22:29
My bad, didn't realise there already was this exact issue still open from last week. 
https://github.com/wez/wezterm/issues/5382

**Comment by wez** [comment] 2024-07-13 23:17
Duplicate of #5382

**Closed by wez** 2024-07-13 23:17 UTC
Labels: bug, Wayland
