### ISSUE TITLE
spawning new window doesn't work.

### ISSUE THREAD

**Issue by tmccombs** [wez/wezterm#5255] opened 2024-04-02 08:39 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland

### WezTerm version

wezterm 20240325-093507-e5ac32f2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If I try to create a new wezterm window, nothing happens. This is the case whether I use a hotkey like Ctrl+Shift+N, or run `wezterm` from the terminal, or `wezterm start`, or even `wezterm start --always-new-process`.

Possibly related, and really, really weird. If I try to launch wezterm from a launcher, when I first start Hyprland, nothing happens.  But if I start another terminal application, like kitty, foot, or even xterm, then launching wezterm works fine (for the first window, then I can't make more windows). It doesn't matter what application the terminal is running. And then even stranger, if I close the wezterm and the other terminal, I clan't start wezterm again, until another terminal is open.

### To Reproduce

In Hyprland with wayland open a wezterm terminal. 

Then run `wezterm` again to try and open a new window, or use `Ctrl+shift+n`.

### Configuration

This is reproducible even with the `-n` option.

### Expected Behavior

I should be able to create a new window.

### Logs

02:27:23.704  ERROR  wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)

**Comment by tmccombs** [comment] 2024-04-02 08:40
This seems wayland related. If I change the config to `use_wayland=false`, this doesn't happen

**Comment by woojiq** [comment] 2024-04-19 20:27
Duplicate of https://github.com/wez/wezterm/issues/5103

**Comment by wez** [comment] 2024-05-05 14:07
Duplicate of #5103

**Closed by wez** 2024-05-05 14:07 UTC
Labels: bug
