### ISSUE TITLE
Failed to set cursor on Wayland

### ISSUE THREAD

**Issue by alexherbo2** [wez/wezterm#532] opened 2021-03-12 12:02 UTC
## Describe the bug

Failed to set cursor on Wayland.
Cannot type anything, either in the previous or newly created window.

## Environment

 - OS: Linux Wayland
 - Version: `20210203-095643-70a364eb-190-g21f3f90e`
 - Keyboard layout: QWERTY (US)

## To reproduce

Open WezTerm, then a new window with <kbd>Control</kbd> + <kbd>Shift</kbd> + <kbd>n</kbd>.

## Configuration

``` lua
return {
  enable_wayland = true
}
```

## Additional context

No bug without `enable_wayland` configuration.

**Comment by wez** [comment] 2021-03-13 06:52
I couldn't reproduce this, but I did have a panic when running under wayland that I just fixed in https://github.com/wez/wezterm/commit/48a3674c9a2c2e39cfa61593a726262bf83ad43d

I just pushed that commit; give it a little bit of time to show up in the nightly and try that build?

**Comment by wez** [comment] 2021-03-20 18:58
some logs from that system:

```
2021-03-19T19:00:24.260Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:24.260Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:24.260Z DEBUG window::os::wayland::window                   > Config: self.full_screen=None, states:false [TiledLeft, TiledRight, TiledTop, TiledBottom]
 2021-03-19T19:00:24.260Z DEBUG window::os::wayland::window                   > Config: self.full_screen=None, states:false [Activated, TiledLeft, TiledRight, TiledTop, TiledBottom]
 2021-03-19T19:00:24.283Z DEBUG wezterm_gui::termwindow::render               > paint_pane_opengl elapsed=23.258078ms
 2021-03-19T19:00:25.342Z TRACE wezterm_gui::termwindow::keyevent             > key_event KeyEvent { key: Super, modifiers: NONE, raw_key: None, raw_modifiers: NONE, raw_code: Some(125), repeat_count: 1, key_is_down: true }
 2021-03-19T19:00:25.342Z TRACE wezterm_gui::termwindow                       > Setting focus to false
 2021-03-19T19:00:25.342Z TRACE wezterm_gui::termwindow                       > Setting focus to true
 2021-03-19T19:00:25.366Z DEBUG wezterm_gui::termwindow::render               > paint_pane_opengl elapsed=23.890056ms
 2021-03-19T19:00:25.377Z DEBUG wezterm_gui::termwindow::render               > paint_pane_opengl elapsed=10.132451ms
 2021-03-19T19:00:25.378Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:25.378Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:25.378Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:25.378Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:25.378Z DEBUG window::os::wayland::window                   > Config: self.full_screen=None, states:false [TiledLeft, TiledRight, TiledTop, TiledBottom]
 2021-03-19T19:00:25.378Z DEBUG window::os::wayland::window                   > Config: self.full_screen=None, states:false [Activated, TiledLeft, TiledRight, TiledTop, TiledBottom]
 2021-03-19T19:00:25.398Z DEBUG wezterm_gui::termwindow::render               > paint_pane_opengl elapsed=19.677148ms
 2021-03-19T19:00:26.613Z DEBUG wezterm_gui::termwindow::render               > paint_pane_opengl elapsed=15.56098ms
 2021-03-19T19:00:26.614Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:26.614Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:26.614Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:26.614Z ERROR smithay_client_toolkit::window::concept_frame > Failed to set cursor
 2021-03-19T19:00:26.614Z DEBUG window::os::wayland::window                   > Config: self.full_screen=None, states:false [TiledLeft, TiledRight, TiledTop, TiledBottom]
 2021-03-19T19:00:26.614Z DEBUG window::os::wayland::window                   > Config: self.full_screen=None, states:false [Activated, TiledLeft, TiledRight, TiledTop, TiledBottom]
 2021-03-19T19:00:26.638Z DEBUG wezterm_gui::termwindow::render               > paint_pane_opengl elapsed=23.706106ms
```

**Comment by wez** [comment] 2021-08-01 20:53
I think this might be resolved in `main`, but if not, it should give slightly better error messages.
CursorNotFound errors likely point to an issue with XCURSOR_PATH; the logic used at the time of writing comes from this indirect dependency:
https://github.com/esposm03/xcursor-rs/blob/0e16996452978717a98aacf38e20b35e5cac4b91/src/lib.rs#L131

**Closed** 2021-08-01 20:58 UTC
Labels: Wayland, bug
