### ISSUE TITLE
Window not using all space with Yabai on macos

### ISSUE THREAD

**Issue by andreicorpo** [wez/wezterm#1289] opened 2021-11-01 12:31 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20211027-125648-539d72a9

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

It seems like the window does not take the full space when using Yabai on macos. There is a gap at the bottom of the window.

### Configuration

```lua
local wezterm = require("wezterm")

return {
	color_scheme = "Batman",
	font = wezterm.font("JetBrainsMono Nerd Font"),
  term = "wezterm",
	font_rules = {
		{
			italic = true,
			font = wezterm.font("JetBrainsMono Nerd Font Mono", { italic = true }),
		},
		{
			italic = true,
			intensity = "Bold",
			font = wezterm.font("JetBrainsMono Nerd Font Mono", { italic = true, weight = "Bold" }),
		},
		{
			intensity = "Bold",
			font = wezterm.font("JetBrainsMono Nerd Font", { weight = "Bold" }),
		},
	},
}
```

### Anything else?

![image](https://user-images.githubusercontent.com/12585256/139671687-abf6de30-43b5-42dc-bb22-0532e009a404.png)
![image](https://user-images.githubusercontent.com/12585256/139671727-63be35d9-c3b2-48d1-9914-c496176d8d35.png)

**Comment by jubalfh** [comment] 2021-11-06 21:23
this is most likely caused by the fact that wezterm calculates calculates the window size using cell-sized increments (plus padding, scrollers & decorations).

perhaps it would be possible to special-case the tiling wm behaviour – with a caveat, that this would cause the padding values become the _minimal_ padding values?

**Comment by gwww** [comment] 2021-11-09 01:16
This feels like a dup of https://github.com/wez/wezterm/issues/1254

**Comment by jubalfh** [comment] 2021-11-09 12:06
@gwww i think you might have wanted to comment on another issue; this one is not about the rendering things within window boundaries but rather sizing the window itself. (or i have misunderstood the OP very badly, which is also possible.)

**Comment by gwww** [comment] 2021-11-09 14:19
The OP is about not being able to size a window to take the full vertical space on the screen -- showing up as a gap at the bottom of the screen. Seems the same, but its also possible I misunderstand this bug report.

**Comment by wez** [comment] 2021-11-09 15:20
This is a duplicate of #1254

**Closed by wez** 2021-11-09 15:20 UTC
Labels: bug

**Comment by jubalfh** [comment] 2021-11-09 18:17
i stand corrected.

so to finally make a constructive contribution to the thread: i can confirm that the fix is working – see attached screenshot (window on the left, one of the older nightly builds, on the right; window on the right, wezterm built from the commit c47c7c6d1fe9b0282c424e3dafe8d7b58f27c4d6)

configuration: impish running gnome 40.5, gnome-shell, pop-shell in tiling mode with gaps, all running on x.

![impish running gnome-shell with pop-shell in tiling mode](https://user-images.githubusercontent.com/1334590/140981008-7b347610-97c2-46a6-bcae-6b4198ae6b7f.png)

**Comment by rcorre** [comment] 2023-02-03 14:40
I'm encountering this on `wezterm 20221119-145034-49b9839f` using the Yabai window manager on macos 12.6 with this config:

```
local wezterm = require 'wezterm'
return {
    font = wezterm.font 'Hack',
    color_scheme = "Solarized (light) (terminal.sexy)",
    enable_tab_bar = false,
    window_decorations = "NONE",
    use_resize_increments = true,
}
```

If I remove `window_decorations = "NONE"`, it works as expected (but I have that annoying title bar wasting space). This screenshot shows terminals with and without decoration:


<img width="956" alt="Screen Shot 2023-02-03 at 9 39 12 AM" src="https://user-images.githubusercontent.com/2496231/216630722-ba4319e4-6236-4e3e-bace-8e574f914218.png">

**Comment by wez** [comment] 2023-02-03 14:47
You almost always want to include at least `RESIZE` in your window decorations otherwise you will have problems with window sizing. This is mentioned several times in the docs: https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html

**Comment by rcorre** [comment] 2023-02-03 14:58
That did it @wez, thank you! Sorry I missed that 🙇
