### ISSUE TITLE
Wayland: output frozen until user input on non-local domains

### ISSUE THREAD

**Issue by kraf1nix** [wez/wezterm#1814] opened 2022-04-03 16:28 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland (NixOS unstable, SwayWM)

### WezTerm version

20220319-142410-0fcdea07

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using Wezterm with `enable_wayland = true` on a non-local domain, terminal output is frozen until any user input is performed (via a click, or key press).

### To Reproduce

Launch a `unix` or `ssh` domain with `enable_wayland = true`, open `vim` or `neovim` without pressing a key or clicking/moving your mouse, and see that neovim/vim does not show it's full launch page.

#### Issue occurs
```sh
wezterm --config-file /tmp/wezterm-wayland.lua connect unix
```

#### Issue does not occur
```sh
wezterm --config-file /tmp/wezterm-wayland.lua start
wezterm --config-file /tmp/wezterm-x.lua start
wezterm --config-file /tmp/wezterm-x.lua connect unix
```

### Configuration

Config where issue occurs (`/tmp/wezterm-wayland.lua`):
```lua
local wezterm = require "wezterm"
return {
  enable_wayland = true,
  unix_domains = {
    { name = "unix" }
  }
}
```

Config where issue does not occur (`/tmp/wezterm-x.lua`):
```lua
local wezterm = require "wezterm"
return {
  enable_wayland = false,
  unix_domains = {
    { name = "unix" }
  }
}
```

### Expected Behavior

Output should not be frozen until user input occurs when wayland is enabled.

**Comment by loops** [comment] 2022-04-07 12:58
Same issue here.   Can confirm that the issue is not apparent when   enable_wayland = false.

**Comment by wez** [comment] 2022-04-08 17:21
I think this may be due to the same root cause as #1841 which is now fixed in `main`.  That should show up in a nightly build for linux within about 30 minutes from now.

**Comment by gertjanvanzwieten** [comment] 2022-04-08 20:25
I just tested it briefly (wezterm 20220408-101518-b908e2dd) and can confirm that the problem appears to have been fixed, at least on the unix socket. Great work!

**Comment by loops** [comment] 2022-04-08 21:35
Looks great.   Just tested HEAD (b908e2dd8c...) and it works now with an ssh domain.

**Closed** 2022-04-09 01:29 UTC
Labels: bug, Wayland, multiplexer
