### ISSUE TITLE
Letter spacing too small for bitmap font

### ISSUE THREAD

**Issue by ConorHK** [wez/wezterm#1164] opened 2021-09-23 13:37 UTC
The font spacing for the Gohu bitmap font is far too small, and adjusting the kerning harfbuzz value makes no difference.

Example:
![wezterm](https://user-images.githubusercontent.com/43848548/134517070-d04e30a7-e384-488c-ae8f-b839df4d1eff.jpg)

**Comment by wez** [comment] 2021-09-23 14:27
With this config:

```lua
local wezterm = require 'wezterm'
return {
  font_dirs = {"/tmp/gohufont"},
  font = wezterm.font("GohuFont"),
}
```

I see:

![Screenshot from 2021-09-23 07-23-52](https://user-images.githubusercontent.com/117777/134525237-36c8c686-a9ee-4c92-9156-a82200ccb5ac.png)

You didn't include the information that we ask for in the normal bug report flow: https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug.yml so important information about your environment that would help to figure out next steps is missing.

Please add that missing information!

In addition, the output from `wezterm ls-fonts` is often helpful when troubleshooting fonts; please add that also!

**Comment by wez** [comment] 2021-09-24 15:09
Duplicate of #1165

**Closed by wez** 2021-09-24 15:09 UTC
Labels: waiting-on-op
