### ISSUE TITLE
Italian keyboard: Cannot input some chars

### ISSUE THREAD

**Issue by ferama** [wez/wezterm#1080] opened 2021-08-25 07:59 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

latest, built from source too

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I'm on a M1 Mac using Italian Keyboard. It seems there is no way to input chars like ']' on '}'. I can successfully input '[' and '{' instead. The ']' char on Italian keyboard require a combination of Option plus the key containing "+". The '}' instead, requires Shift+Option+ the key containing "+"

I'm absolutely new to rust but I tried to find the source of the issue. I noticed that if in this file https://github.com/wez/wezterm/blob/main/window/src/os/macos/window.rs I comment from line 1817 to line 1829 I can successfully input the chars above.

```rust
            let raw_modifiers = modifiers;
            let mut modifiers = modifiers;

            let (key, raw_key) = if chars.is_empty() || chars == unmod {
                (key, None)
            } else {
                let raw = key_string_to_key_code(unmod);
                match (&key, &raw) {
                    // Avoid eg: \x01 when we can use CTRL-A
                    (KeyCode::Char(c), Some(raw)) if c.is_ascii_control() => (raw.clone(), None),
                    // ==========================================================
                    // Commented the following trying to debug some input not working properly
                    // ==========================================================
                    // (KeyCode::Char(k), Some(KeyCode::Char(r)))
                    //     if k.is_ascii_punctuation() && r.is_ascii_punctuation() =>
                    // {
                    //     // Well, `chars` is supposed to represent the processed and modified
                    //     // interpretation of the keypress, and `unmod` the same, but ignoring
                    //     // any modifier keys.  eg: `ALT-l` has unmod=`l` and chars=`¬`.
                    //     // However, SUPER+SHIFT+[ yields chars=`[` and unmod=`{` which is
                    //     // the opposite of what we want.
                    //     // If both chars and unmod are punctuation then let's take unmod,
                    //     // and filter out the SHIFT state if present.
                    //     modifiers -= Modifiers::SHIFT;
                    //     (KeyCode::Char(*r), None)
                    // }
                    _ => (key, raw),
                }
            };
```

I'm not actually able to contribute with a proper fix to the issue but I hope that the hint can be helpful 

### Configuration

no config

**Comment by wez** [comment] 2021-08-25 16:54
Thanks for digging in!
https://github.com/wez/wezterm/issues/760 and https://github.com/wez/wezterm/issues/601 are related issues.
This is a bit tricky to get right because the IME also makes things complicated! (https://github.com/wez/wezterm/issues/615)

If you have the bandwidth to poke at this a bit further, and since you have and use one of the keyboard layouts that wezterm struggles with, I'd really appreciate it if you could help us find out the path to success!

The goal of the input handling is to capture, in as high-fidelity as possible, the pressed keys and then represent them in a logical and an unambiguous fashion.  The code that you commented out was intended to do that, but it doesn't seem universally good.

What would be super helpful to me is:

* Turn on https://wezfurlong.org/wezterm/config/lua/config/debug_key_events.html
* Try pressing the keys that produce the typical latin and punctuation symbols, especially where those require different modifiers from a US layout, and report any that aren't working, and whether your proposed change makes those keys work. Please include the key event debug output from the keys that aren't working, and if your change makes things better, the key event debug output with that change applied.
* For the things that aren't working, I'd like to try to reproduce that on my M1 mac, which has US keyboard.  I can enable the Italian layout, but I don't know which keys to press, so I'd appreciate you giving me really basic and explicit steps on what to press and what to expect the output to be.

**Comment by nklmilojevic** [comment] 2021-12-08 18:39
I'm going to piggy back on this issue, having the same issue with Serbian input:

<img width="1789" alt="CleanShot 2021-12-08 at 19 38 59@2x" src="https://user-images.githubusercontent.com/9573356/145265030-138eb4f3-bed0-4c2f-a73e-d03f83e66a66.png">

I tried the fix with commenting out the code but it doesn't work. Any ideas?

**Comment by nklmilojevic** [comment] 2021-12-08 18:43
quick update:

works with `send_composed_key_when_left_alt_is_pressed = true` in the config

**Comment by aorith** [comment] 2021-12-09 14:29
I haven't tested ferama's solution, but until someone finds a proper fix for this, remapping the keys that don't work is an option.
For example, this is what I use with an Spanish keyboard layout:

```lua
  use_ime = false,
  send_composed_key_when_left_alt_is_pressed = true, -- my bluetooth keyboard needs "left" even if I want the "right" alt
  send_composed_key_when_right_alt_is_pressed = true,
  enable_csi_u_key_encoding = false,
  use_dead_keys = true,
  keys = {
    {key="+", mods="ALT", action={SendKey={key="]"}}},
    {key="ç", mods="ALT", action={SendKey={key="}"}}},
    {key=" ", mods="ALT", action={SendKey={key=" "}}},
  },
```

**Comment by wez** [comment] 2022-01-03 07:30
I think this is essentially a duplicate of two other issues, but regardless: Thanks to the groundwork laid in https://github.com/wez/wezterm/issues/1483 I just pushed a commit that fixes those other mac issues, and I think it resolves this one too.  It will show up in the nightly downloads within an hour.

**Closed** 2022-01-08 04:19 UTC
Labels: bug, macOS, fixed-in-nightly, keyboard
