### ISSUE TITLE
High CPU usage when almost idle

### ISSUE THREAD

**Issue by usagi-flow** [wez/wezterm#2027] opened 2022-05-24 19:17 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220524-093749-89d78ac4

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I noticed over the last few weeks, since I discovered wezterm, that its CPU usage is high.
E.g. high enough to noticeably drain the battery of my Macbook faster.

But because "high" is highly subjective (ha!), I ran WezTerm next to two other terminals with GPU acceleration on my Linux PC.
I started all three terminals within a second, and ran `tmux a` to attach to a simple tmux session with just an `htop` running, filtering on the three terminals.

As soon as I started them, I could clearly see that WezTerm consumes a bit more than twice as much CPU time compared to Alacritty, and about 3.5x compared to Kitty.

![image](https://user-images.githubusercontent.com/2804556/170109868-b4ca2f76-caa3-434d-8163-6b02848feb87.png)

I also tried running WezTerm with an opaque background and/or with a longer blink time interval as I saw in another issue a while ago, but the result remained very similar.

The previous screenshot is from the test made with 20220408-101518-b908e2dd, but I observe the same behavior in the nightly build:
![image](https://user-images.githubusercontent.com/2804556/170114339-ff243509-24d8-4a8d-95c3-d2ecda7fb0f6.png)

### To Reproduce

Start WezTerm on a mostly idle machine, run `htop` and observe the CPU usage and CPU time.

### Configuration

```lua
local wezterm = require("wezterm");

return {
	font = wezterm.font("SauceCodePro Nerd Font"),
	color_scheme = "SpaceGray",
	default_cursor_style = "BlinkingUnderline",
	enable_tab_bar = false,
	use_resize_increments = true,
	initial_cols = 206,
	initial_rows = 52,
	window_background_opacity = 0.98,
	window_padding = {
		top = 0,
		bottom = 0,
		left = 0,
		right = 0
	},
	window_close_confirmation = "NeverPrompt",
	check_for_updates = false
}
```

### Expected Behavior

The CPU time shouldn't be higher than other GPU-based terminals.

### Logs

[wez.a.log](https://github.com/wez/wezterm/files/8765571/wez.a.log)

### Anything else?

In case it's relevant, in the screenshot, the terminal to the top left is alacritty, to the top right is wezterm, and to the bottom left is kitty.

I used WezTerm and observed this issue on Mac Catalina (MBP 2014) and on Arch Linux.

**Comment by wez** [comment] 2022-05-25 00:40
Can you try setting these to see if it makes a difference?

```lua
  animation_fps = 10,
  cursor_blink_rate = 1000,
```

**Comment by etienne-k** [comment] 2022-05-26 08:34
Thanks for your quick reply, @wez !

Unfortunately, the result remains the same despite the new settings.

![image](https://user-images.githubusercontent.com/2804556/170450346-e3b93aa3-3717-4d63-87dd-8b659a36f0cd.png)

With you suggested config changes, my config is now the following:
```lua
local wezterm = require("wezterm");

return {
	font = wezterm.font("SauceCodePro Nerd Font"),
	color_scheme = "SpaceGray",
	default_cursor_style = "BlinkingUnderline",
	enable_tab_bar = false,
	use_resize_increments = true,
	initial_cols = 206,
	initial_rows = 52,
	window_background_opacity = 0.98,
	window_padding = {
		top = 0,
		bottom = 0,
		left = 0,
		right = 0
	},
	window_close_confirmation = "NeverPrompt",
	check_for_updates = false,
	animation_fps = 10,
	cursor_blink_rate = 1000
}
```

I'm still on 20220524-093749-89d78ac4.

**Comment by wez** [comment] 2022-05-26 13:17
The increased usage when focused is almost certainly due to the blinking/easing cursor. If you want to be more power efficient, you might want to set `animation_fps=1` and/or disable cursor blinking.

The logs you shared don't include information about your GPU: if your linux system has an issue with graphics drivers, wezterm will fall back to CPU/software rendering and the utilization will be higher than it would otherwise.  The issue template explained how to obtain that information when you opened the report; you can find it again in the "Logs" section of the template: https://github.com/wez/wezterm/blob/main/.github/ISSUE_TEMPLATE/bug.yml

**Comment by etienne-k** [comment] 2022-05-26 20:23
Thanks for the tip. Unfortunately, again, `animation_fps=1` doesn't seem to make a difference. The CPU usage is still noticeably higher than the other GPU terminals.

I oversaw the debug overlay trick, my bad. Here it is:
```
22:21:06.867 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX 5700 XT (navi10, LLVM 13.0.1, DRM 3.44, 5.17.7-zen1-1-zen) 4.6 (Compatibility Profile) Mesa 22.0.3 is_context_loss_possible=false wezterm version: 20220524-093749-89d78ac4
```
I don't recall having issues with GPU acceleration in other applications, neither on my PC (which the line over is from), nor on the macbook pro.

**Comment by wez** [comment] 2022-08-24 02:42
I pushed a number of changes this weekend that reduce CPU utilization; I would love for you to try the latest nightly build and let me know what you think.

**Comment by thenewvu** [comment] 2022-08-24 06:11
Thank you so much. I opened both nightly and latest wezterm windows with the same config and the same size; I observed the CPU usage when both open `top` in background, the nightly uses less than ~30% of CPU comparing to the latest.

**Comment by etienne-k** [comment] 2022-09-10 14:39
Thank you very much for the improvements! Despite this issue, I have to praise this otherwise awesome terminal!

On wezterm 20220905-102802-7d4b8249, unfortunately, I still observe the same behavior. It could very well be that the performance has been improved, but looking at the CPU usage of different terminals running next to each other, I still notice a sensibly higher CPU usage with Wezterm.

It's definitely related to the rendering/screen refreshing. Running `htop -d1` (refresh rate of 100ms) makes Wezterm consume around 20%-30% on a macbook pro with a 2.6 GHz Core i5.

**Comment by akriegman** [comment] 2022-09-11 01:01
I am having a similar issue. I generally keep several wezterm windows open for days at a time. At some point wezterm starts using around 20% of a cpu continuously, and I have to restart it to fix the problem. Would love to see a fix for this and I'm happy to provide more information, although I don't know what would be helpful.

wezterm version: 20220807-113146-c2fee766
os: Ubuntu 20.04
wezterm config:
```lua
local wezterm = require 'wezterm'

return {
	-------- key bindings -------- 
	keys = {
		{
			key = 'Backspace',
			mods = 'CTRL',
			action = wezterm.action.SendKey {
				key = 'Backspace',
				mods = 'ALT',
			},
		},
	},

	-------- cosmetics --------
	default_cursor_style = 'BlinkingBar',
	font = wezterm.font 'Go Mono',
	color_scheme = 'Afterglow',

	-------- window --------
	use_fancy_tab_bar = false,
	hide_tab_bar_if_only_one_tab = true,
	window_padding = {
		left = 0,
		right = 0,
		top = 0,
		bottom = 0,
	},
	window_decorations = "RESIZE",
}
```
Thanks for your work on this awesome piece of software :)

**Comment by wez** [comment] 2022-09-11 14:30
I'd definitely recommend trying the latest nightly build: I landed some memory and performance changes this weekend and those are on top of the improvements since the august release.

You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

You can also [build from source](https://wezfurlong.org/wezterm/install/source.html) if you prefer.

**Comment by wez** [comment] 2022-09-11 14:35
> Running `htop -d1` (refresh rate of 100ms)

FWIW, this is most definitely not "almost idle" as mentioned in the title and when I run this, `htop` dominates the CPU, especially when maximized.

However, I haven't seen wezterm use as much CPU as you called out, either on my Linux box or on my mac so I'd recommend trying the nightly.

**Comment by etienne-k** [comment] 2022-09-13 16:40
Thanks again for the improvements! I believe CPU usage got better indeed, but I'd have to test that on my Linux box to compare with what I observed until now.

I installed nightly (thanks for the brew tap!) - wezterm 20220912-062610-fe78b582 - and noticed CPU usage is still about 5x higher than alacritty when running htop at its normal refresh rate:
![image](https://user-images.githubusercontent.com/2804556/189951638-b705072c-42d6-49bb-84d5-673a816bffcd.png)

> FWIW, this is most definitely not "almost idle" as mentioned in the title and when I run this, `htop` dominates the CPU, especially when maximized.

Oh you're absolutely right, this is more like a stress test! Just wanted to emphasize that I believe that the CPU usage seems to be directly related to the frequency of screen refreshes.

> However, I haven't seen wezterm use as much CPU as you called out, either on my Linux box or on my mac so I'd recommend trying the nightly.

CPU usage seems to have dropped lower, I'd say mostly around 15% - 20%, but under stress, Wezterm definitely consumes way more than when almost idle, and also more than its counterparts:
![image](https://user-images.githubusercontent.com/2804556/189956424-adc0969a-8cab-4b65-9054-fb218ae093db.png)

Now while `htop -d1` is probably not a common use case, it seems such stress is comparable to running an application with lots of output (`make` in a medium/large C/C++ project?) or to scrolling in Vim...

---

Here's the debug overlay of my macbook I just ran these tests on:
```
Debug Overlay
wezterm version: 20220912-062610-fe78b582
OpenGL version: Intel Iris OpenGL Engine 4.1 INTEL-14.7.21
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
18:37:39.573 WARN env_bootstrap > setlocale(en_DE.UTF-8) failed, fall back to en_US.UTF-8
>
```

**Comment by etienne-k** [comment] 2023-01-07 21:10
For the record: It seems like when using the new rendering frontend, the CPU/battery drops a lot. A quick look at the numbers shows a usage that is lower than Kitty or Alacritty. I observed this on the macbook (Intel Iris -> Metal backend) pro using nightly, have yet to verify other platforms.

This is the new feature: https://github.com/wez/wezterm/issues/2756 (thanks a lot for that @wez, it's absolutely amazing!!)

**Comment by pragma-** [comment] 2023-02-11 09:32
I'd love to use the WebGpu front end, but it horribly breaks font rendering, at least on Windows 10. It causes the font antialiasing to be grayscale which makes the fonts look bolded/thick. Reverting back to OpenGL restores the dark blue/red antialiasing and makes the fonts look normal/thin again.

**Comment by sandikata** [comment] 2024-04-12 12:31
Hello, this is still a issue. Compared to kitty or alacritty (they don't use CPU like wezterm), what we can do in wezterm to make it better like kitty or alacritty in order of cpu usage? I really like wezterm functionallity.

**Comment by pragma-** [comment] 2024-04-26 22:24
I run weechat, an IRC client, in a fullscreen wezterm on one of my displays. Weechat displays the current time in its statusbar. I had to set this to HH:MM instead of HH:MM:SS to prevent high CPU usage. Updating the "seconds" field once a second -- which apparently causes a full ncurses display refresh -- was enough to increase the CPU to noticeable levels.

Like @sandikata, in their comment above, I did not experience this in kitty or alacritty. Despite this, I do much prefer wezterm and I do hope this can be optimized further.

**Comment by wez** [comment] 2024-05-07 21:18
I'm going to close this since the OP reports that their situation is fine. If other folks are having problems, then I recommend that they each post a well-qualified issue that precisely describes what is happening for them, such that it is reproducible by others.

**Closed by wez** 2024-05-07 21:18 UTC
Labels: bug, render-latency
