### ISSUE TITLE
Undercurl cutoff

### ISSUE THREAD

**Issue by boltlessengineer** [wez/wezterm#3157] opened 2023-02-25 13:02 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230224-171344-c5247d21

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

<img width="94" alt="스크린샷 2023-02-25 오후 9 34 48" src="https://user-images.githubusercontent.com/60088301/221357496-be7f5565-1d54-4a56-a2e2-4d747bd26de9.png">

When using Undercurl, the line below is cut off. This makes undercurl look less squiggly. This makes distinguishing undercurl from normal underline much harder.

### To Reproduce

The picture above is from Neovim, but this can be also reproduced with code from Wezterm's FAQ section.

```bash
printf "\x1b[58:2::255:0:0m\x1b[4:1msingle\x1b[4:2mdouble\x1b[4:3mcurly\x1b[4:4mdotted\x1b[4:5mdashed\x1b[0m\n"
```

### Configuration

```lua
return {
  font = wezterm.font_with_fallback {
    'Fira Code',
  },
  font_size = 16.0,
  underline_position = "800%",
  underline_thickness = "1.5pt",
}
```

### Anything else?

Currently I put my underlines at bottom end of the cells. I can just adjust the underline position more higher to fix cutoff issue, but supporting bottom-most undercurl would be nice.

Also, there was similar issue about 2 years ago. (#734)

**Comment by wez** [comment] 2023-02-25 13:52
If you remove the underline_position from your config, do the underlines not get cut off?

**Comment by boltlessengineer** [comment] 2023-02-25 14:35
They don't get cut off when I remove `underline_position`. The issue only happens when I put underline at the bottom of the cell. I want to set underline's position there because they looks great with [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) Neovim plugin.

Is this intended behavior?

**Comment by wez** [comment] 2023-02-25 15:41
Yeah, this is working as intended: the underline is pre-rendered into a cell sprite and is (very quickly) composited into underlined cells by the GPU. Your configuration makes the underline render outside the bounds of the cell sprite, so the part that is outside the bounds of the cell are clipped away.

**Comment by boltlessengineer** [comment] 2023-02-25 16:06
So there are no way to print undercurl on top of the under cell.

How about modifying undercurl's starting position a bit? I mean like -cosine curve. This should allow us to have a continuous curve and avoid being cut off by cell boundaries.

Having this feature as an additional option would be great :)

**Comment by wez** [comment] 2023-02-25 16:11
https://github.com/wez/wezterm/blob/1f7a34f8b259c58387392e358f5fe54c733e193a/wezterm-gui/src/glyphcache.rs#L751 is the start of the logic in the code. If you can see a way to tweak it, you're welcome to send a PR, but I have no plans to make changes to this myself at this time.

**Comment by wez** [comment] 2023-03-19 20:26
I'm going to close this: it is working as intended, and there is nothing more for me to do at this time.

**Closed by wez** 2023-03-19 20:26 UTC
Labels: bug
