### ISSUE TITLE
Mode for opening links

### ISSUE THREAD

**Issue by amiroslaw** [wez/wezterm#1362] opened 2021-12-04 23:59 UTC
I'm not sure if can I achieve it in existing solutions, but I would like to open a link and not to have clicking it using mouse.

**Describe the solution you'd like**
Mode where you can select link and open it in the default browser like It's possible in copping it from "Quick Select Mode"

**Describe alternatives you've considered**
Window event for "Quick Select Mode" could be a alternative, because I could add xdg-open in that hook.

**Comment by bew** [comment] 2021-12-05 00:04
Maybe even further: have a 'general' hint system accessible from Lua, where you can trigger the hint system and then do the action you want with the one you selected.

**Comment by wez** [comment] 2021-12-05 01:02
Is this a duplicate of https://github.com/wez/wezterm/issues/527 ?
Or is this pairing that with eg: quick select or copy mode?

**Comment by amiroslaw** [comment] 2021-12-05 01:40
I thought more like quick select/copy mode. The main goal is to open a link without mouse.  
I've tied add my code to open-url event but it's only execute after mouse clicking.

**Comment by marulitua** [comment] 2021-12-17 05:32
Maybe we can implement something like [kittys's hints](https://sw.kovidgoyal.net/kitty/kittens/hints/)

**Comment by wez** [comment] 2021-12-23 18:10
I just pushed a commit that extends quick select mode so that you can do this:

```lua
local wezterm = require 'wezterm'

return {
  keys = {
    {key="P", mods="CTRL",
     action=wezterm.action{QuickSelectArgs={
       patterns={
          "https?://\\S+"
       },
       action = wezterm.action_callback(function(window, pane)
          local url = window:get_selection_text_for_pane(pane)
          wezterm.log_info("opening: " .. url)
          wezterm.open_with(url)
       end)
     }}
   },
  },
}
```

From my brief skim of the linked kitty hints doc, this sounds like a similar feature set.

I do want to note that this mechanism doesn't know about implicit or explicit hyperlinks: quick select can only match on the textual content of the display.  If an application is using OSC 8 hyperlinks then the URLs embedded in those are not visible to the quickselect text matcher.  I'm going to ponder whether and how to connect those two together, but in the meantime, let me know what you think of this new feature! (it should show up in the nightly downloads within an hour)

Docs are at: https://wezfurlong.org/wezterm/config/lua/keyassignment/QuickSelectArgs.html
and https://wezfurlong.org/wezterm/config/lua/wezterm/open_with.html

**Closed** 2021-12-26 17:19 UTC
Labels: enhancement, fixed-in-nightly
