### ISSUE TITLE
Not launching when using gnome keyboard shortcuts

### ISSUE THREAD

**Issue by Sir-Photch** [wez/wezterm#2299] opened 2022-07-25 09:21 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Current Archlinux with GDM

### WezTerm version

20220724-225546-4bf89e0c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

So there is an option in gnome-settings, specifically keyboard, that maps a given keyboard shortcut to a command. I have configured one as seen in the image below.

Using this Shortcut elicits some weird behavior though; Wezterm does not start up at all, or, takes 10 seconds.

I can confirm that this feature works with different terminal emulators.
Changing the command to `wezterm -n &` does not help.

### To Reproduce

1. Install wezterm
2. Assign keyboard shortcut in gnome-settings
3. press shortcut

### Configuration

no config, since launching with `-n` has no effect.

### Logs

this seems to be one of the logs showing what got messed up, although I am not exactly sure if this is the right one. Since I just installed wezterm though, it might apply anyways:

```console
10:58:25.648  INFO   wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX 6700 XT (navy_flounder, LLVM 14.0.6, DRM 3.46, 5.18.14-zen1-1-zen) 4.6 (Compatibility Profile) Mesa 22.1.3 is_context_loss_possible=false wezterm version: 20220624-141144-bd1b7c5d
10:58:34.056  INFO   wezterm_gui::termwindow > OpenGL initialized! AMD Radeon RX 6700 XT (navy_flounder, LLVM 14.0.6, DRM 3.46, 5.18.14-zen1-1-zen) 4.6 (Compatibility Profile) Mesa 22.1.3 is_context_loss_possible=false wezterm version: 20220624-141144-bd1b7c5d
10:58:44.733  ERROR  wezterm_gui::termwindow > PaneOutput: wanted mux_window_id=1 from mux, but was not found, cancel mux subscription
10:59:32.843  WARN   wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
10:59:32.845  WARN   mux::localpane              > unknown DeviceControlMode::Enter EnterDeviceControlMode(params: [], intermediates: [], byte: 'z' 0x7a, ignored_extra_intermediates=false)
10:59:32.845  WARN   mux::localpane              > unhandled DeviceControlMode::Data 7a z
10:59:32.845  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: "0%m"
11:01:33.796  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
11:01:33.796  WARN   wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
11:02:08.021  ERROR  wezterm_gui                            > X11 connection is broken: xcb connection error: Connection error, possible I/O error; terminating
```

### Anything else?

![grafik](https://user-images.githubusercontent.com/47949835/180741410-765adbfa-1dcb-4fd3-91c9-33e5c5e6d1d3.png)

**Comment by wez** [comment] 2022-07-25 13:02
I can't reproduce this; it works for me.
Could you share `ls -l` of the log directory?

Mine currently has these files:

```
lrwxrwxrwx. 1 wez wez       39 Jul 25 05:48 x11-:0-org.wezfurlong.wezterm -> /run/user/1000/wezterm/gui-sock-1084241=
-rw-------. 1 wez wez      812 Jul 25 05:57 wezterm-gui-log-1084241.txt
```

The `x11-:0-org.wezfurlong.wezterm` symlink identifies the primary wezterm for that X display. It points to `gui-sock-1084241`.
Its logs are in the file named `wezterm-gui-log-1084241.txt`

The contents of the equivalent file on your system will be interesting to see; I wonder if there is something happening in there that is getting in the way of opening new windows?

Do you have the same problem if you manually launch `wezterm -n` from another terminal?

**Comment by Sir-Photch** [comment] 2022-07-25 13:28
> Could you share `ls -l` of the log directory?

```console
$ ls -l
.rw------- chris chris  12 KB Mon Jul 25 15:13:10 2022  check_update
srwx-----T chris chris   0 B  Mon Jul 25 15:13:00 2022  gui-sock-2609
srwx-----T chris chris   0 B  Mon Jul 25 15:20:46 2022  gui-sock-6737
.rw------- chris chris 261 B  Mon Jul 25 15:13:00 2022  wezterm-gui-log-2609.txt
.rw------- chris chris 261 B  Mon Jul 25 15:20:46 2022  wezterm-gui-log-6737.txt
lrwxrwxrwx chris chris  36 B  Mon Jul 25 15:20:46 2022  x11-:1-org.wezfurlong.wezterm ⇒ /run/user/1000/wezterm/gui-sock-6737
```
> Do you have the same problem if you manually launch wezterm -n from another terminal?

No, that works fine.

> The contents of the equivalent file on your system will be interesting to see; I wonder if there is something happening in there that is getting in the way of opening new windows?

I see... I can't manage to pull it up with the shortcut though right now...

**Comment by wez** [comment] 2022-07-26 14:41
`wezterm-gui-log-6737.txt` would be the log file for the active wezterm instance based on what you shared above; the number portion is the same as in `x11-:1-org.wezfurlong.wezterm ⇒ /run/user/1000/wezterm/gui-sock-6737`

**Comment by wez** [comment] 2022-07-26 15:06
By default wezterm will try to launch a new program via an existing wezterm instance (the one identified by that X11 symlink), so if a window doesn't open then there may be some information in the logs of that existing instance that tells us something.

**Comment by Sir-Photch** [comment] 2022-07-26 15:13
I see. However, there does not seem to be helpful information though. I started `wezterm -n` through `gnome-terminal` and rebound my shortcut to `/usr/bin/wezterm -n &`; Using that shortcut does not open up wezterm at all though.

**Comment by wez** [comment] 2022-07-26 15:27
What if you remove the `&`? It shouldn't be necessary

**Comment by Sir-Photch** [comment] 2022-07-26 15:29
Haha yeah, works now, thanks :)

**Closed** 2022-07-26 15:29 UTC
Labels: bug
