### ISSUE TITLE
Subpixel imperfections in Powerline font

### ISSUE THREAD

**Issue by d-miketa** [wez/wezterm#717] opened 2021-04-22 10:37 UTC
(nightly 21/4/21, Mac OS 11.2.1)

I get sub-pixel rendering errors with Powerline symbols – see vertical bar separating the filled-in arrow and the rest of the prompt. The issue persists even with the most minimal config specifying only the font and doesn't seem to be ameliorated by any of the tips mentioned in [the Powerlevel10k Readme](https://github.com/romkatv/powerlevel10k/blob/master/README.md#sub-pixel-imperfections-around-powerline-symbols).

MesloLGS NF:
<img width="159" alt="image" src="https://user-images.githubusercontent.com/320321/115700304-72033c00-a35e-11eb-9191-f57cfe5328f2.png">

Powerline symbols:
<img width="148" alt="image" src="https://user-images.githubusercontent.com/320321/115700232-61eb5c80-a35e-11eb-85a7-a5a604fe9174.png">

Comparison w/ Kitty:
<img width="104" alt="image" src="https://user-images.githubusercontent.com/320321/115700843-066d9e80-a35f-11eb-8c42-25d72cecdfaf.png">

**Comment by wez** [comment] 2021-04-22 15:40
This is a duplicate of https://github.com/wez/wezterm/issues/584

**Closed by wez** 2021-04-22 15:40 UTC
Labels: bug
