### ISSUE TITLE
Can' compile package wezterm-git on Arch but I cam compile from source

### ISSUE THREAD

**Issue by IvayloHrTonev** [wez/wezterm#4987] opened 2024-02-09 08:34 UTC
## Build Environment (please complete the following information):

 - OS: 
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
 - Linux: Linux user-ms7d54 6.7.4-arch1-1 # 1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux
 - Compiler: gcc (GCC) 13.2.1 20230801
 - Rust version:  Default host: x86_64-unknown-linux-gnu
rustup home:  /home/user/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.76.0 (07dca489a 2024-02-04)

If I'm building from git repo everything is fine.
If I do:
paru -Sy wezterm-git 

build failed with:

 ```
 /usr/bin/ld: /home/user/.cache/paru/clone/wezterm-git/src/wezterm/target/release/deps/librusqlite-0700e57d90d15b4a.rlib(rusqlite-0700e57d90d15b4a.rusqlite.82e52a71e7de8f55-cgu.10.rcgu.o): in function `rusqlite::inner_connection::InnerConnection::prepare':
          /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rusqlite-0.27.0/src/inner_connection.rs:227:(.text._ZN8rusqlite16inner_connection15InnerConnection7prepare17h375810736a43e170E+0x81): undefined reference to `sqlite3_prepare_v2'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `sync-color-schemes` (bin "sync-color-schemes") due to 1 previous error
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by SomeRandoNamedDave** [comment] 2024-02-09 12:18
This is caused by the lastest pacman update changing the default options in /etc/makepkg.conf, lto is now enabled by default in the options array which is what is causing the build to fail.

This can be worked around by updating the pkgbuild adding
```sh
options=(!lto)
```
somewhere before the `prepare()` function.

If you want to build this before the pkgbuild is updated in the AUR (or if Wez knows of a different/better solution) you can edit `~/.cache/paru/clone/wezterm-git/PKGBUILD` making the above change then running
```sh
cd ~/.cache/paru/clone/wezterm-git
git commit -am "temp fix"
paru --rebuild=yes -S wezterm-git
```

**Comment by IvayloHrTonev** [comment] 2024-02-09 14:02
> This is caused by the lastest pacman update changing the default options in /etc/makepkg.conf, lto is now enabled by default in the options array which is what is causing the build to fail.
> 
> This can be worked around by updating the pkgbuild adding
> 
> ```shell
> options=(!lto)
> ```
> 
> somewhere before the `prepare()` function.
> 
> If you want to build this before the pkgbuild is updated in the AUR (or if Wez knows of a different/better solution) you can edit `~/.cache/paru/clone/wezterm-git/PKGBUILD` making the above change then running
> 
> ```shell
> cd ~/.cache/paru/clone/wezterm-git
> git commit -am "temp fix"
> paru --rebuild=yes -S wezterm-git
> ```

Thanks, this fixes the things

**Comment by wez** [comment] 2024-02-11 02:35
If you share the diff for the PKGBUILD and/or .srcinfo, we can get that committed and made available to others

**Comment by SomeRandoNamedDave** [comment] 2024-02-11 04:18
Sorry, probably should have just created a patch in the first place, just `git apply <file>`
(not sure why but I had to change the ext to txt in order for gh to accept the file)

[pacman-6.0.2-9_build_fix.patch.txt](https://github.com/wez/wezterm/files/14231262/pacman-6.0.2-9_build_fix.patch.txt)

**Comment by wez** [comment] 2024-02-11 16:31
Thanks; I pushed an update. Please let me know if it works as I don't run arch and don't have an easy way to verify these changes directly

**Comment by SomeRandoNamedDave** [comment] 2024-02-11 19:08
Just updated, all good.

Sorry I forgot to also increment the pkgrel in that patch, I don't manage any remote packages so that completely slipped my mind.

**Closed** 2024-02-11 21:59 UTC
Labels: bug
