### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KiaraGrouwstra** [wez/wezterm#4470] opened 2023-10-21 01:18 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

gnome + paperwm

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Wezterm Error: `running message loop: error during event_q.read_events protocol_error=None: Broken pipe (os error 32)`

### To Reproduce

occasionally i get this error, altho it appears to function more like a warning

### Configuration

no config

### Expected Behavior

no errors

### Logs

```
01:04:35.036  ERROR  wezterm_mux_server_impl::local > writing pdu data buffer: Broken pipe (os error 32)
01:04:55.308  ERROR  window::os::wayland::frame     > Unable to set cursor to left_ptr: cursor not found
01:04:55.308  ERROR  window::os::wayland::frame     > Unable to set cursor to left_ptr: cursor not found
01:04:55.308  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.310  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.311  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.313  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.315  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.317  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.319  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.321  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.323  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.326  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.327  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.329  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.331  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.333  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.335  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.337  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.339  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.341  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.343  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.345  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.347  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.349  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.351  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.353  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.357  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.359  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.361  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.365  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.367  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.369  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.371  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.377  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.383  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.385  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.387  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.389  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.391  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.393  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.395  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.397  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.399  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.401  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.403  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.405  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.407  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.409  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.411  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.413  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.415  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.417  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.419  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.421  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.423  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.426  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.427  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.429  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.431  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.433  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.435  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.437  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.439  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.441  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:04:55.443  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.954  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.956  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.958  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.960  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.962  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.963  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.965  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.967  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.969  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.971  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.973  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.975  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.977  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.979  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.981  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.983  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.985  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.987  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.989  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.991  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.993  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.995  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:08.998  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.000  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.001  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.003  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.005  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.098  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.104  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.105  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.108  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.110  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.112  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.114  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.116  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.118  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.120  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.122  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.338  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.340  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.342  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.343  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.348  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.349  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.351  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.353  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.355  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.357  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.359  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.361  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.363  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.365  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.367  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.369  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.371  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.373  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.375  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.377  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.379  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.381  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.383  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.386  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.388  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.389  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.391  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.393  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.395  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.397  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.399  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.401  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.403  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.405  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.408  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.409  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.411  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.413  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.415  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.417  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.419  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.421  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.423  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.425  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.427  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.429  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.431  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.433  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.435  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.437  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.439  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.441  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.443  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.445  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.447  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.449  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.451  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.453  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.455  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.457  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.459  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.462  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.463  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.465  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.467  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.470  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to xterm: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.472  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.474  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.475  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.478  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.480  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.481  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.483  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.485  ERROR  window::os::wayland::frame     > Unable to set cursor to left_ptr: cursor not found
01:05:09.485  ERROR  window::os::wayland::frame     > Unable to set cursor to left_ptr: cursor not found
01:05:09.485  ERROR  window::os::wayland::frame     > Unable to set cursor to left_ptr: cursor not found
01:05:09.486  ERROR  window::os::wayland::frame     > Unable to set cursor to left_ptr: cursor not found
01:05:09.486  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
01:05:09.486  ERROR  window::os::wayland::pointer   > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
02:57:24.451  ERROR  wezterm_gui                    > running message loop: error during event_q.read_events protocol_error=None: Broken pipe (os error 32); terminating
```

(cursor issues now reported over at https://github.com/ful1e5/Bibata_Cursor/issues/152 - over here mostly the final line appears relevant)

### Anything else?

(i'm on NixOS, so updating a single package to nightly version appears a bit trickier than it might normally be.)

**Comment by kaddkaka** [comment] 2023-10-21 20:18
Seems like a duplicate of https://github.com/wez/wezterm/issues/3751

People seems to have had some success by setting cursor theme.

**Closed** 2023-10-21 22:24 UTC
Labels: bug
