### ISSUE TITLE
Wezterm window not obeying adwaita theme under gnome wayland

### ISSUE THREAD

**Issue by Sir-Photch** [wez/wezterm#2974] opened 2023-01-18 13:04 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

20230115-214820-a2e027df

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After switching to Gnome Wayland instead of X11 Wezterm does not seem to respect the set adwaita theme; The terminal window now has got it's own window header style.

### To Reproduce

1. Current Gnome desktop with mutter
2. Start wayland session
3. launch wezterm

### Configuration

not sure if this is causing the issue.

```lua
local wezterm = require 'wezterm'

function scheme_for_appearance(appearance)
	if appearance:find 'Dark' then
		return 'Gruvbox dark, hard (base16)'
	else
		return 'Gruvbox light, hard (base16)'
	end
end

-- https://wezfurlong.org/wezterm/config/lua/window/get_appearance.html
wezterm.on('window-config-reloaded', function(window, pane)
	local overrides = window:get_config_overrides() or {}
	local appearance = window:get_appearance()
	local scheme = scheme_for_appearance(appearance)
	if overrides.color_scheme ~= scheme then
		overrides.color_scheme = scheme
		window:set_config_overrides(overrides)
	end
end)

return 
{
	font = wezterm.font_with_fallback 
	{
		{ 
			family = 'FiraCode Nerd Font',
			weight = 'Regular',
			harfbuzz_features = { 'zero' }
		},
		'VL Gothic'
	},

	font_size = 15,
	
	max_fps = 144,

	enable_wayland = true,
	
	check_for_updates = false,
	hide_tab_bar_if_only_one_tab = true,
	tab_bar_at_bottom = true,
	-- window_background_opacity = 0.95,
	-- text_background_opacity = 1.0
}

```

### Expected Behavior

Rounded corners, window header bar adhering to system theme, e.g. light theme when other windows are using light theme, dark theme if other windows are using dark themes.

**Comment by wez** [comment] 2023-01-18 15:07
That's just how wayland works, unfortunately. This is a duplicate of:
* https://github.com/wez/wezterm/issues/1969

**Closed by wez** 2023-01-18 15:07 UTC
Labels: bug
