### ISSUE TITLE
Send typing to multiple panes, ala 'synchronize-panes' in tmux

### ISSUE THREAD

**Issue by fcpg** [wez/wezterm#4066] opened 2023-07-28 14:14 UTC
**Is your feature request related to a problem? Please describe.**
A nice feature in tmux is the `synchronize-panes` window option, that duplicate input to all panes in the current tab. Quite handy when you need to run some commands on several hosts - just open a pane for each host, ssh into it, and turn the option on. All keystrokes are sent to every panes. Turn option off when you're done.

**Describe the solution you'd like**
A toggle option/command similar to `synchronize-panes`.

**Describe alternatives you've considered**
Well, ansible can solve the same kind of problems, but it's far from always available. `synchronize-panes` is more crude but very handy when you need it. 

**Additional context**
N/A

**Comment by wez** [comment] 2023-08-02 14:06
Duplicate of https://github.com/wez/wezterm/issues/2658

**Closed by wez** 2023-08-02 14:06 UTC
Labels: enhancement
