### ISSUE TITLE
Links too easy to click (more generally, mouse action bindings)

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#119] opened 2020-01-16 20:30 UTC
**Is your feature request related to a problem? Please describe.**

I find it too easy to accidentally click link/URL-like things. I'd prefer a ctrl-click kind of interaction.

**Describe the solution you'd like**

I've like to be able to control mouse actions in the same way as keybindings so I can set some Mod-Click combination to visit links.

**Comment by ImportTaste** [comment] 2020-01-20 18:12
Middle click to close tabs would be amazing.

**Comment by wez** [comment] 2020-01-20 19:26
> Middle click to close tabs would be amazing.

@ImportTaste: assuming that you mean middle click on the tab title in the tab bar, rather than in the terminal area of the tab, to close it, I think that could be implemented more easily than the broader request on this issue; would you mind opening a separate issue for that?

**Comment by ImportTaste** [comment] 2020-01-20 23:48
> > Middle click to close tabs would be amazing.
> 
> @ImportTaste: assuming that you mean middle click on the tab title in the tab bar, rather than in the terminal area of the tab, to close it, I think that could be implemented more easily than the broader request on this issue; would you mind opening a separate issue for that?

Sure thing.

**Closed** 2020-05-22 15:09 UTC
Labels: enhancement

**Comment by wez** [comment] 2020-05-22 15:11
master now allows:

```lua
local wezterm = require 'wezterm';

return {
  mouse_bindings = {
    -- Change the default click behavior so that it only selects
    -- text and doesn't open hyperlinks
    {
      event={Up={streak=1, button="Left"}},
      mods="NONE",
      action="CompleteSelection",
    },

    -- and make CTRL-Click open hyperlinks
    {
      event={Up={streak=1, button="Left"}},
      mods="CTRL",
      action="OpenLinkAtMouseCursor",
    },
  },
}
```

**Comment by wez** [comment] 2020-05-22 15:22
docs are even available: https://wezfurlong.org/wezterm/config/keys.html#configuring-mouse-assignments

**Comment by odama626** [comment] 2022-08-05 15:39
just ran into this, this is the new syntax


```lua
local wezterm = require 'wezterm'

return {
  mouse_bindings = {
    -- Change the default click behavior so that it only selects
    -- text and doesn't open hyperlinks
    {
      event={Up={streak=1, button="Left"}},
      mods="NONE",
      action=wezterm.action.CompleteSelection("PrimarySelection"),
    },

    -- and make CTRL-Click open hyperlinks
    {
      event={Up={streak=1, button="Left"}},
      mods="CTRL",
      action=wezterm.action.OpenLinkAtMouseCursor,
    },
  }
}

```

**Comment by bew** [comment] 2022-08-05 16:03
Hello @odama626,

This is a 2 year old issue, a lot of things changed since then!

If you have an issue, I'd suggest to open a brand new issue and fill in all the information (optionally linking to this one if you think the problem is similar).

**Comment by odama626** [comment] 2022-08-05 21:14
Thanks for the recommendation.

The config snippet above was what I was looking for but I noticed that things have changed a bit so I just commented with the updated snippet for the next person that comes along

**Comment by bew** [comment] 2022-08-06 03:38
Oh ok, makes a lot more sense!!

Note that you'll also want to completed disable (with Nop) the down event of Ctrl-click, otherwise apps capturing the mouse (e.g: neovim) would receive the down event but not the up event (since it's mapped to open the link) and this messes up what you usually intended to do.
This is all documented in the official docs at: https://wezfurlong.org/wezterm/config/mouse.html?highlight=Ctrl-click#gotcha-on-binding-an-up-event-only
(just below the example of this issue, in the mouse bindings docs)

**Comment by odama626** [comment] 2022-08-08 15:23
oh sweet! thanks for saving me from that eventual hard to debug issue!  I went ahead and added that to the snippet above as well
