### ISSUE TITLE
[Vulkan] Window only updates when moving the mouse, not when typing

### ISSUE THREAD

**Issue by Flakebi** [wez/wezterm#2770] opened 2022-11-21 16:03 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Sway

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When typing or pressing keys, the window does not update.
Only when moving the mouse, the windows is redrawn and the previously typed text becomes visible.

Also interesting, when pressing `Ctrl+Shift+L` for the first time after starting wezterm, the screen updates a bit, i.e. my shell disappears and I have a black terminal (+ the top bar). After moving the mouse, the debug overlay text appears.
On subsequent `Ctrl+Shift+L` presses, the debug overlay appears right away without needing to move the mouse. (But entering text in the debug overlay still doesn’t appear until the mouse is moved.)

I put a trace log below.
I wrote 'abcdef', then moved the mouse (text appeared), then wrote 'ghij', then moved the mouse.

### Configuration

`wezterm --config 'front_end="WebGpu"'`

### Logs

[log.txt](https://github.com/wez/wezterm/files/10058096/log.txt)

### Anything else?

This only happens with Vulkan. Tested with RADV and AMDVLK on a RX 5700 XT and RX 6700 XT.

**Comment by wez** [comment] 2022-11-22 15:40
Please run `WAYLAND_DEBUG=1 wezterm`, trigger this issue once or twice, and then attach the wayland debug logs to this issue, thanks!

**Comment by Flakebi** [comment] 2022-11-24 11:50
I wrote 'abcd', then moved the mouse (text appeared), then wrote 'efgh', then moved the mouse.
[wl-debug.txt](https://github.com/wez/wezterm/files/10084216/wl-debug.txt)

Some more info in case it’s relevant, I’m using fish, when I press enter to run a command, the terminal updates, and I’m on NixOS.

**Comment by wez** [comment] 2023-04-09 05:46
Duplicate of https://github.com/wez/wezterm/issues/3126 but has follow up happening https://github.com/wez/wezterm/issues/3468

**Closed by wez** 2023-04-09 05:46 UTC
Labels: bug, Wayland
