### ISSUE TITLE
Custom highlighting based on regex

### ISSUE THREAD

**Issue by RAV64** [wez/wezterm#4593] opened 2023-11-18 08:41 UTC
**Is your feature request related to a problem? Please describe.**
I wish to have terminal-wide highlighting for words like todo, fixme, hack, etc.. Additionally I would like to highlight hexcodes with their corresponding colors.

**Describe the solution you'd like**
I was under the impression this would already be implemented because of the similar feature for hyperlinks as they are given custom font attribute (underline) based on regex. ( At least so I assume :) )

These regex matches should accept value (Example: I want "todos" red!) or a function for more intelligent logic (Example: I want to highlight {{matched_hex}} with {{matched_hex}}).

I'm interested in having the same kind of control over them as [formatItem](https://wezfurlong.org/wezterm/config/lua/wezterm/format.html) offers.

**Describe alternatives you've considered**
Alternatively this functionality can be recreated per program. For example with treesitter injections or regex highlighting in (neo)vim. Unfortunately every program doesn't offer this option :( which is why I'd like the terminal to manage this feature.

**Additional context**
Thank you very much :)

**Comment by bew** [comment] 2023-11-18 09:31
Looks like this is a duplicate of #4348

**Comment by RAV64** [comment] 2023-11-18 09:51
If this doesn't bring additional value then feel free to close. Hopefully this is something that can be and is implemented 👍🏻

**Comment by wez** [comment] 2024-01-24 01:25
Duplicate of https://github.com/wez/wezterm/issues/4348

**Closed by wez** 2024-01-24 01:25 UTC
Labels: enhancement
