### ISSUE TITLE
can display   "#की एक छवि",           Notice where the arrow is. It's missing a quotation mark

### ISSUE THREAD

**Issue by xxaier** [wez/wezterm#4071] opened 2023-07-30 03:06 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

macos 13.4.1 (c) (22F770820d)

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

item2
<img width="335" alt="image" src="https://github.com/wez/wezterm/assets/130831741/501fd5e8-f12a-4de7-bd1b-22e5b09349c6">

wezterm
<img width="375" alt="image" src="https://github.com/wez/wezterm/assets/130831741/670b3fbe-26cf-46e0-a4f5-8e0294d18062">

Notice where the arrow is. It's missing a quotation mark

### Configuration

```
local wezterm = require 'wezterm'

return {
  font = wezterm.font_with_fallback {
    {
      family='FiraCode Nerd Font Mono',
      weight="Bold"
    },
    {
      family='Noto Sans CJK SC',
      weight="Bold"
    }
  },
  window_close_confirmation="NeverPrompt",
  font_size = 16,
  selection_word_boundary = '{}[]()"\'=`,;: ❯│',
  hide_tab_bar_if_only_one_tab = true,
  hyperlink_rules = {
    -- Linkify things that look like URLs and the host has a TLD name.
    -- Compiled-in default. Used if you don't specify any hyperlink_rules.
    {
      regex = [[\b\w+://[&a-zA-Z!\$\d_\.\?\-/%\[\]:=+#]*]],
      format = '$0',
    },

    -- linkify email addresses
    -- Compiled-in default. Used if you don't specify any hyperlink_rules.
    {
      regex = [[\b\w+@[\w-]+(\.[\w-]+)+\b]],
      format = 'mailto:$0',
    },

    -- file:// URI
    -- Compiled-in default. Used if you don't specify any hyperlink_rules.
    {
      regex = [[\bfile://\S*\b]],
      format = '$0',
    },

    -- Linkify things that look like URLs with numeric addresses as hosts.
    -- E.g. http://127.0.0.1:8000 for a local development server,
    -- or http://192.168.1.1 for the web interface of many routers.
    {
      regex = [[\b\w+://(?:[\d]{1,3}\.){3}[\d]{1,3}\S*\b]],
      format = '$0',
    },

    -- Make task numbers clickable
    -- The first matched regex group is captured in $1.
    {
      regex = [[\b[tT](\d+)\b]],
      format = 'https://example.com/tasks/?t=$1',
    },

    -- Make username/project paths clickable. This implies paths like the following are for GitHub.
    -- ( "nvim-treesitter/nvim-treesitter" | wbthomason/packer.nvim | wez/wezterm | "wez/wezterm.git" )
    -- As long as a full URL hyperlink regex exists above this it should not match a full URL to
    -- GitHub or GitLab / BitBucket (i.e. https://gitlab.com/user/project.git is still a whole clickable URL)
    -- {
    --   regex = [[["]?([\w\d]{1}[-\w\d]+)(/){1}([-\w\d\.]+)["]?]],
    --   format = 'https://www.github.com/$1/$3',
    -- },
  },
}

```

**Comment by michaelrommel** [comment] 2023-08-06 13:30
Hi, I looked at this because I had similar (easier) issues in the past.

For me it is not clear, how the glyph should actually look. The way it is displayed in the headline of this bug in Chrome or Firefox displays one contracted character based on three unicode (surrogate) points.

The second screenshot of yours show two glyphs side by side, not combined.

When I copy and paste the character from the headline to a terminal/editor/textfile, I get the following:

<img width="1272" alt="image" src="https://github.com/wez/wezterm/assets/919935/85947f34-abf6-415c-af54-9ceeb0c7e705">

- first line shows the copy/pasted character, but it seems that one surrogate pair is incomplete e0 a4 b5 + e0 a4 bf and then another e0 a4 bf. Apple Terminal (upper left portion) shows the incomplete surrogate, kitty (lower left) shows to muddled up surrogates in one cell, the quotes in another) and wezterm shows the first complete pair in separate cells, overlayed by the second incomplete surrogate, overlaid by the quotation mark
- second line shows only the base character e0 a4 b5 (this renders correctly as one glyph plus quotes in the next cell)
- third line shows the pair, where Apple Terminal shows the glyphs in two cells, with the quote in the third, kitty shows the combined glyph in one cell followed by the quote in the next cell, wezterm shows the glyphs in two cells, then overlays the quote with the second cell.

BTW: the quotes are always there, just overlaid.

Have you played around with the settings:

```
config.treat_east_asian_ambiguous_width_as_wide = false
config.unicode_version = 9
-- config.normalize_output_to_unicode_nfc = true
-- config.allow_square_glyphs_to_overflow_width = "Always"
config.allow_square_glyphs_to_overflow_width = "Never"
```

And are you running inside a terminal multiplexer like tmux or so?

**Comment by wez** [comment] 2023-08-06 13:34
See also:
* https://github.com/wez/wezterm/issues/1333

**Comment by xxaier** [comment] 2023-08-15 04:38
![image](https://github.com/wez/wezterm/assets/130831741/b356d7f4-c1b6-4147-a828-b0401a56bf9b)
see the image， i change the config but no effect
the error is I can't edit this string in vim , not just display error

**Comment by wez** [comment] 2023-08-18 18:15
Closing as a duplicate of https://github.com/wez/wezterm/issues/1333

**Closed by wez** 2023-08-18 18:15 UTC
Labels: bug
