### ISSUE TITLE
Including SHIFT in mods when key implies it results in keybinding not working

### ISSUE THREAD

**Issue by EpocSquadron** [wez/wezterm#787] opened 2021-05-12 14:19 UTC
## Describe the bug

I use a mechanical keyboard running QMK. On it I have a key bound to `|`, which is the shifted variant of `\` on an english keyboard. QMK sends the shifted `\` keycodes to the operating system, but I no longer think about it that way as it is just a single keypress for me. I was adding some keybindings for managing splits and wanted to continue in the pattern that CTRL|SHIFT are used for many mux purposes in wezterm (esp since SUPER conflicts with Gnome-wide keybindings all the time), and wanted to use `|` to indicate a horizontal split action. Not thinking, I configured it with the CTRL|SHIFT mods. I then waited for the configuration to reload, and tried the keybinding, and it did nothing. After thinking about it, I removed the SHIFT from the mods and now the keybinding works, even if I press shift in addition on the keyboard (QMK deduplicates it).

## Environment (please complete the following information):

 - OS: Archlinux Gnome 40 Wayland
 - Version: wezterm 20210405-110924-a5bb5be8
 - ENG

## Configuration

```lua
    {key="|", mods="CTRL|SHIFT", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
```

## Expected behavior

Wezterm should swallow the repeated SHIFT specifier and let it work, perhaps with a warning to the user that removing the SHIFT mods will not alter the meaning of the keybinding.

**Comment by wez** [comment] 2021-05-12 15:06
This isn't a bug (the configuration you want to use is technically invalid), and I I don't believe that what you asked for is possible in a portable way: while wezterm does have access to a raw code that corresponds to the non-portable physical key location, the translation of that key location is generally opaque and hidden behind a keyboard layout layer in the OS.  While some OS's expose some of the information about the keyboard layout, there isn't a guaranteed way on all OS's for an application to know that a given layout produces a given symbol.

Without that, it's not possible for wezterm to reason with certainty about whether a SHIFT in mods is redundant with the translated key press.

If such a set of APIs existed on all OS's it would help me clean up the handful of open key assignment/modifier issues that are currently open.

**Comment by EpocSquadron** [comment] 2021-05-12 18:53
I'm not sure I follow. I believe that QMK is sending both `\` and shift keycodes when I press the key I identify as `|`, as it presents as a standard English layout keyboard to the operating system. Thus, when wezterm recieves the keys, it should be looking for the `\` keycode with a shift modifier, even though the literal character `|` is what's specified in the config. This seems to work, but adding shift in the modifiers manually breaks it.

**Comment by EpocSquadron** [comment] 2021-05-12 19:03
Let me take qmk out of it. If I just use my laptop's regular US keyboard, ctrl-shift-`\` works when configured without shift in the mods list, and doesn't work with shift in the mods list.

**Comment by wez** [comment] 2021-05-13 14:15
Is your issue the same thing as https://github.com/wez/wezterm/issues/601 ?

**Comment by EpocSquadron** [comment] 2021-05-13 14:34
@wez I think it may indeed be. I just checked having `"\\"` as the key with CTRL|SHIFT as mods and that doesn't work either, which is very much like the reported issue there.

**Comment by wez** [comment] 2021-05-13 14:44
OK, let's close this one in favor of that!

Duplicate of #601

**Closed by wez** 2021-05-13 14:44 UTC

**Comment by EpocSquadron** [comment] 2022-01-12 20:02
Update for posterity,  #1483 makes it so that we need to use the following for the keybinding to work, and it now will work regardless of if you physically press shift or imply it at the keyboard. So truly resolved now.

```lua
    {key="\\", mods="CTRL|SHIFT", action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
```
