### ISSUE TITLE
Wezterm should print out path of file/directory dropped onto window

### ISSUE THREAD

**Issue by r00ster91** [wez/wezterm#1018] opened 2021-08-14 15:52 UTC
**Is your feature request related to a problem? Please describe.**
The problem is that Wezterm doesn't print out the path of files/directories dropped onto its window. It just ignores it.

**Describe the solution you'd like**
I want Wezterm to print out the path of whatever is dropped onto Wezterm's window.

It would be very helpful for all kinds of applications. The program could detect if it received a path and then do something with that file or directory. And the more terminals support this feature, the easier the lives for terminal developers.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Alacritty, GNOME Terminal and other terminals already do this:
![image](https://user-images.githubusercontent.com/35064754/129451796-a06c2d4f-fae2-4361-81c4-6ff0fa5ecd93.png)
This is another thing that would bring Wezterm more on par with other terminals.

**Comment by wez** [comment] 2021-08-14 15:55
Duplicate of #640

**Closed by wez** 2021-08-14 15:55 UTC
Labels: enhancement
