### ISSUE TITLE
macOS Monterey Python 2 sunset warning

### ISSUE THREAD

**Issue by reportaman** [wez/wezterm#1331] opened 2021-11-21 04:46 UTC
On macOS Monterey I got this message:

<img width="259" alt="Screen Shot 2021-11-20 at 8 43 41 PM" src="https://user-images.githubusercontent.com/71736629/142749945-7004d9b3-2906-4c39-9d16-0a570017e716.png">

Clicking on the ```Learn More...``` took me directly to this page:
https://www.python.org/doc/sunset-python-2/

**Comment by wez** [comment] 2021-11-21 15:00
wezterm doesn't use python2 for anything; what I suspect is happening is that something that you're running from a shell launched by wezterm is using python2 and macOS is attributing that to wezterm.
I suspect that this is another case of https://github.com/wez/wezterm/issues/482

**Comment by wez** [comment] 2021-11-22 14:55
Confirmed that this is a duplicate of #482 by opening wezterm then running python2.

**Closed by wez** 2021-11-22 14:55 UTC
