### ISSUE TITLE
Wired highlight in neovim

### ISSUE THREAD

**Issue by Adnios** [wez/wezterm#1418] opened 2021-12-19 12:29 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20211218-094600-ea46967e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After a recent update, there is a wired highlight when moving the cursor to "==" "--" "<<".

In the following gif, the left one is wezterm and the right one is kitty.

![wired-hightlight](https://user-images.githubusercontent.com/41060790/146674776-b6f0d6a9-967c-42cc-ba45-da05d091eea9.gif)

### To Reproduce

1.  `nvim -u  NONE -N test.txt`
2. insert "==", "--" or "<<"
3. move curosr.

### Configuration

no config

**Comment by bew** [comment] 2021-12-19 12:33
This looks like  #478  ?

**Comment by wez** [comment] 2021-12-19 14:45
Yeah, this is a duplicate of #478

**Closed by wez** 2021-12-19 14:45 UTC
Labels: bug
