### ISSUE TITLE
Apple Silicon macOS: File permission's don't work all time and with all programs run from wezterm

### ISSUE THREAD

**Issue by reportaman** [wez/wezterm#482] opened 2021-02-13 06:18 UTC
## Describe the bug

When someone installs a new application on macOS Big Sur, and the application tries to access files in folders like Desktop/Downloads, macOS asks for a permission from user to grant access to the application program. Once granted, the permissions last forever unless user manually removes the permission given to application to access those folders (System Preferences > Security & Privacy > Privacy > Files and Folders > ApplicationName from list > checkboxes). That doesn't seem to be the case for WezTerm, even though right permissions are set & and in place as per information in (System Preferences > Security & Privacy > Privacy > Files and Folders > ApplicationName from list > checkboxes). The same command line programs do not have any problem accessing those files and folders with other terminal emulators like Alacritty, iTerm2, Terminal.app.

## Environment:
```
>> wezterm --version
wezterm 20210203-095643-70a364eb-26-g9bf419eb
```
```
>> neofetch
                   'c.           reportaman@Mac-mini.local
                 ,xNMM.          ------------------------------
               .OMMMMo           OS: macOS 11.2 20D64 arm64
               OMMM0,            Host: Macmini9,1
     .;loddo:' loolloddol;.      Kernel: 20.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 3840x2160
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: WezTerm
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 1909MiB / 16384MiB
       .cooc,.    .,coo:.
```

## To Reproduce

1. Open WezTerm.app for the first time, and try opening some text files in Desktop & Download folders with applications like ``less`` or ``vim``. When macOS prompts for permission to allow WezTerm to access files in those folders, grant it. 
2. Check the permissions are correctly set: System Preferences > Security & Privacy > Privacy > Files and Folders > WezTerm > checkboxes for Desktop & Downloads folder. The permissions should be set.
3. Quit WezTerm.app, and open it again! Try opening files on Desktop/Download folder again using ``less ~/Desktop/``, etc. For some reason, macOS will again ask for permission! This doesn't happen with other terminal applications I have installed on my system.

>NOTE-1: The reason I mention that file permission's "don't work all the time" is at times I get this prompt for both Desktop & Downloads folder, and at times just for Desktop (and not for Downloads. i.e. am able to access files right away).

>NOTE-2: In my testing I think I saw at times being able to open file from vim using ``:e ~/Desktop/filename.txt`` without prompt, but being prompted while trying to open the same file with a vim plugin like [Startify](https://github.com/mhinz/vim-startify)  or [NERDtree](https://github.com/preservim/nerdtree). Though can't say defintelty as I am not able to recreate behavior in NOTE-2 at the time of writing this. Also, all this while I did not change any permissions to any file, and did not add/remove files from Desktop/Downloads folder.

## Expected behavior
System should not ask for permissions for WezTerm every time it is opened.

## Screenshots

![Screen Shot 2021-02-12 at 9 51 32 PM](https://user-images.githubusercontent.com/71736629/107843465-2477bb00-6d80-11eb-826c-69df1751c56e.png)

![Screen Shot 2021-02-12 at 9 54 17 PM](https://user-images.githubusercontent.com/71736629/107843467-293c6f00-6d80-11eb-91f1-4d5c35a9e302.png)

**Comment by wez** [comment] 2021-02-14 05:26
I suspect that this may have something to do with not being code signed.  Or alternatively: if you regularly update to nightly, each time the executable is changed it wouldn't surprise me if it needed to be re-granted permissions.

**Comment by reportaman** [comment] 2021-02-14 05:39
@wez I have never re-downloaded or updated wezterm, so its not the latter. I have unsigned binaries on my system like Alacritty which came "unsigned" afaik (and seems to be the case from this inflammatory comment from its developer: https://github.com/alacritty/alacritty/issues/1896#issuecomment-690677828), unless I am misunderstanding your reference to "signing".

**Comment by reportaman** [comment] 2021-02-14 08:17
@wez Btw, the problem occurs only when wezterm gui is directly opened by clicking the app icon. Opening ``>>wezterm`` or ``>>wezterm-gui`` doesn't have the same problem (probably because the permissions get chained from the parent terminal emulator).

**Comment by wez** [comment] 2021-02-15 08:49
I can't reproduce this.  I wonder if there's something else that we're missing.
Where is WezTerm.app installed? is it on a removable device, or installed in /Applications, or somewhere else?
How did you install wezterm?

**Comment by reportaman** [comment] 2021-03-19 23:41
@wez I had tried this with both prebuilt macOS app, and homebrew's version. And both had caused same problem. Updating them to latest also didn't help. 

This worked though:

I already had these WezTerm permissions under ``System Preferences > Security & Privacy > Privacy > Files & Folders > Wezterm``  checked, _**I unchecked them and rechecked them & it magically got resolved.**_. Its weird this problem never happened with any other application.

<img width="670" alt="Screen Shot 2021-03-19 at 4 37 19 PM" src="https://user-images.githubusercontent.com/71736629/111851679-67720480-88d1-11eb-85b7-ec4521f5f6ee.png">

**Comment by teenjuna** [comment] 2021-05-08 04:10
I actually encountered the same issue. My environment:
```
>>> wezterm --version
wezterm 20210503-220535-d64b7852
>>> neofetch
                    'c.          user@macbook.local
                 ,xNMM.          --------------------------
               .OMMMMo           OS: macOS 11.2.3 20D91 arm64
               OMMM0,            Host: MacBookPro17,1
     .;loddo:' loolloddol;.      Kernel: 20.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 36 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: fish 3.1.2
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1440x900
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: WezTerm
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Apple M1
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 2190MiB / 16384MiB
       .cooc,.    .,coo:.
```

Not only I were asked to grant the permissions on every new launch, I were also forced to grant the same permissions like 10 times after calling `exa -T` in the home directory. There's definitely something wrong. **But the solution with rechecking the permissions worked for me too.** @reportaman I suggest reopening this.

**Comment by LuarRaNa** [comment] 2021-09-30 09:32
Hi !!!

I have the same problem.
As @reportaman mentioned this happens with external plug-ins. Like LunarVim in my examples.

Running a command right at HOME trigger the access prompt.
```
username in ~
❯ lvim ~/.config/wezterm/wezterm.lua
username in ~ took 9s
❯
```
![image](https://user-images.githubusercontent.com/67846413/135424090-d1cf1e0c-20a5-41c5-b85f-347371e584ea.png)

Moving to the specific directory and running the same command works fine.
```
username in ~/.config/wezterm via 🌙
❯ lvim wezterm.lua
username in ~/.config/wezterm via 🌙 took 6s
❯
```

- wezterm version: 20210814-124438-54e29167 / Downloded and installed in /Applications
- iTerm, kitty, terminal.app works normally.
- Opening wezterm from another terminal emulator works normally.
- The solution with rechecking the permissions doesn't work
- Mac mini - Apple M1, Big Sur 11.6

**Comment by gwww** [comment] 2021-11-06 19:30
The `codesign` works for me too! Thx!!!

**Comment by kyelewis** [comment] 2021-11-17 01:51
This also happens with microphone access when launching the android-emulator from command line, apple will prompt for microphone access for wezterm on a regular basis while the emulator runs, seems like more than one an hour.

**Comment by wez** [comment] 2021-11-21 15:13
I plan to do something to get wezterm codesigned to help with this. Current blockers:

* I need to renew a long-expired Apple developer account
* I just moved to a new state, and Apple needs to verify my new address, which may require additional steps
* I need to set up automation to codesign. Not sure if I trust GH Actions with that.

**Comment by wez** [comment] 2021-11-23 04:53
OK, the latest nightly is now code signed; hopefully this is the last we see of this issue!

**Closed** 2021-12-03 04:33 UTC
Labels: bug, fixed-in-nightly, cant-reproduce
