### ISSUE TITLE
Cannot remove native title bar from window

### ISSUE THREAD

**Issue by kivsiak** [wez/wezterm#5483] opened 2024-05-27 18:31 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Ubuntu 24.04

### WezTerm version

20240520-135708-b8f94c47

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

RESIZE only decoration does not remove native window tile bar. 

### To Reproduce

Install wezterm on latest ubuntu 24.04 in X11 mode. Add config line

![изображение](https://github.com/wez/wezterm/assets/307729/04d2524c-885b-409d-b38a-6af5f7a3ebfa)

### Configuration

config.window_decorations = "INTEGRATED_BUTTONS|RESIZE"

### Expected Behavior

No title bar is shown

### Logs

Debug Overlay
wezterm version: 20240520-135708-b8f94c47 x86_64-unknown-linux-gnu
Window Environment: X11 GNOME Shell
Lua Version: Lua 5.4
OpenGL: NVIDIA GeForce RTX 4080/PCIe/SSE2 4.6.0 NVIDIA 535.171.04
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

**Comment by wez** [comment] 2024-07-13 23:01
Duplicate of https://github.com/wez/wezterm/issues/3936

**Closed by wez** 2024-07-13 23:01 UTC
Labels: bug
