### ISSUE TITLE
The Multiplexing is very slow

### ISSUE THREAD

**Issue by joexue** [wez/wezterm#1872] opened 2022-04-13 18:22 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220101-133340

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

The functionality of TLS multiplexing is very good but a bit slow, if I directly use ssh connect to the host, every thing is fine but if I use the TLS multiplexing, it is very slow, I even can see a double line under the character I typed in. If I use delete the cursor even can go back beyond my prompt to the first column of the terminal. Since it it is connecting to company's server, I cannot capture what it is, sorry about that.

### To Reproduce

configure a tls multiplexing server and connect to it.

### Configuration

no specific

### Expected Behavior

run at least as fast as ssh connection

**Comment by wez** [comment] 2022-04-15 14:59
Can you describe in more detail what you're doing when you notice that it is slow?
What is the ping/round-trip latency between the local and remote hosts?
How large is the terminal (rows and columns)?

Have you tried adjusting the `local_echo_threshold_ms` setting? See bottom of https://wezfurlong.org/wezterm/config/lua/TlsDomainClient.html?highlight=local_echo_threshold_ms#tlsdomainclient for details

**Comment by joexue** [comment] 2022-04-18 20:51
I notice it is slow because when I type, it response not instantly, as I describe in the original post I even can see the double line under the characters I type in in short time.  for example below, if I type in "ls example" I will see the double under line from "l" to "e" in order for short time. and if I try to delete the "ls example" the cursor even can reach 'h".

`
host$ ls example
`

The network is a bit slow I know, ping round-trip time is 226ms.
of course if I connect to a host with fast network, the symptoms not so significant. 
but if I use ssh directly connect to problematic server without multiplexing, the response is much faster. so I think multiplexing contributes more than network speed.

I use local_echo_threshold_ms = 10 and it doesn't help.

**Comment by joexue** [comment] 2022-04-18 21:03
the terminal is not large, I use small terminal. 1920x1280 and font size is 14

**Comment by joexue** [comment] 2022-04-20 13:53
try to use ssh domain instead of tls domain, the result is same.

**Comment by joexue** [comment] 2022-04-20 13:54
to be more clear, the client is windows and the server is Linux

**Comment by joexue** [comment] 2022-04-20 14:51
![IMG_2216_MOV_AdobeCreativeCloudExpress](https://user-images.githubusercontent.com/261642/164258843-4ec5330d-f3d1-4eb2-b92f-3511c5493119.gif)

**Comment by wez** [comment] 2022-04-20 14:53
Try setting `local_echo_threshold_ms = 300` to discourage the local predictive echo?

**Comment by joexue** [comment] 2022-04-20 20:25
looks not helping

**Comment by digitallyserviced** [comment] 2022-04-24 22:29
I actually have had a similar issue. When using the mux unix domain, and navigating while holding down arrows or hjkl in neovim,  the repeat actually gets stuck and I cannot even stop it without spamming opposite keys which then have their own delayed repeat until the cursor finally stops. 

I have since stopped using the unix domain mux just because there is a huge delay sometitmes, while a direct `wezterm-gui` feels immediate and very responsive in comparison.

I can say that this seems to happen after a little while into the server running after it has used up some memory. Killing and restarting the process earns me some more responsiveness for a little while but in the end becomes enough of an issue to have left the feature altogether.

I will work on getting some data,logs,rec of the issue but I had been keeping an eye on this issue because of it mentioning slowness, and now that OP mentions it happening over even unix domain for them too I figured I should chime in as **me too**.

**Comment by digitallyserviced** [comment] 2022-05-11 00:27
Is this something related to the #1814 #1841 that may have been resolved with the recent
[b908e2d](https://github.com/wez/wezterm/commit/b908e2dd8cd27c613c8d76e9e6abc5245e500d7d) commit?

**Comment by joexue** [comment] 2022-12-06 21:59
Used sometime to dig it, the slow looks from proxy more than network transmission somehow.

**Comment by joexue** [comment] 2022-12-07 17:16
Hi @wez, I can provide more specific log if you need. The functionality is really good and useful, I hate I cannot  use RUST to program.

**Comment by cunha** [comment] 2022-12-11 23:15
I have just what looks like the same problem when using a unix socket to connect to a remote host. The slowdown I am experiencing seems related to redrawing operations. Some observations:

* If I keep the terminal at 80x25, then it performs reasonably well
* If I maximize the screen (318x75) then
  * `vim` is extremely slow (0.5s delay when pressing `j`)
  * `nano` still performs reasonably well (nothing changes on the terminal except the cursor)

One difference between the two editors is that `vim` updates the cursor position at the bottom right of the terminal, while `nano` does nothing other than modify the cursor position.

This is with `local_echo_threshold_ms = 50000`, and the latency between me and the server is around 40ms.

**Comment by sirfz** [comment] 2023-01-04 08:50
I experienced the same with both direct ssh and multiplexing. Using ssh from wsl works normally as already reported.

**Comment by cd-a** [comment] 2023-04-03 15:04
Since https://github.com/wez/wezterm/commit/d36ad7ca7f9054a9d2b49ffe8696c3e617623194 was merged I wanted to check again on latest master.

I can't connect to the mux server anymore though. @wez did you change something there since last release that I'm not aware of?

The standard config I used before does not connect to a local unix socket anymore, but works on latest release:
```lua
config.unix_domains = {
  {
    name = 'unix',
  },
}

config.default_gui_startup_args = { 'connect', 'unix' }

```

**Comment by cd-a** [comment] 2023-04-03 15:24
@wez I'd love to, but there are none :)

When I run this config on the release, and there is no socket open yet, on first terminal it briefly shows no socket yet, and creates it, then every terminal afterwards connects to it. So when I close, reopen, it loads the layout again.

On latest master, nothing. No message about missing socket, no attaching to socket. Just behaves as if there is no mux set up.

I tried killing the existing socket from the release version, that maybe master would do it differently, but no. 

Any way I can log this verbosely?

**Comment by wez** [comment] 2023-04-03 15:48
@cd-a please file an issue with complete repro steps and config

**Comment by cd-a** [comment] 2023-04-03 16:21
@wez sure! Here it is: https://github.com/wez/wezterm/issues/3438

**Comment by cd-a** [comment] 2023-04-03 16:45
So after wez helped me figure out how to properly start the mux server on the master build, here are my findings using:

- 4k, full screen wezterm
- neovim latest

It's blazingly fast now, I can hardly notice a difference to non-mux performance now. Maybe a tiny fraction, but only noticeable if I compare them directly against each other... or maybe I'm even hallucinating that one. It just works great!

So I will now switch to the mux version, loving it. Great work wez!

**Comment by joshuarubin** [comment] 2023-04-03 20:09
Can you specify any config and minimum wezterm build dates that are required to get fast mux on a 4k full screen? I'm running `20230326-111934-3666303c` on my server and `20230330-214948-d1c2257b` on my client and those may not be new enough.

**Comment by wez** [comment] 2023-04-03 20:24
@joshuarubin https://github.com/wez/wezterm/commit/d36ad7ca7f9054a9d2b49ffe8696c3e617623194 or later

**Comment by joshuarubin** [comment] 2023-04-03 21:27
> @joshuarubin [d36ad7c](https://github.com/wez/wezterm/commit/d36ad7ca7f9054a9d2b49ffe8696c3e617623194) or later

thanks for the info. is that for both the client and server, or is it ok for one side to be older?

**Comment by wez** [comment] 2023-04-03 21:31
While that change in theory only changed some logic on the server, there were some other multiplexer changes that bumped the CODEC_VERSION over the weekend, and the client will give up talking to a server with a mismatching CODEC VERSION.  So you'll want to upgrade both the client and the server.

**Comment by wez** [comment] 2023-04-04 03:38
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by cd-a** [comment] 2023-04-04 04:22
@joshuarubin for the config, please check https://github.com/wez/wezterm/issues/3438 where it's linked with the description.

**Comment by joshuarubin** [comment] 2023-04-04 04:28
Thanks for your help. I think I've got it working.

New issue, I can make separately, but in case you are already aware, on main when I'm connected to an ssh domain and do `win:perform_action(wezterm.action.SplitHorizontal({ domain = "DefaultDomain" }), pane)` I get this:

```
22:13:19.082 WARN mux::domain > Directory "/home/<USERNAME>" is not readable and will not be used for the command we are spawning: No such file or directory (os error 2)
```

This is on MacOS and my home dir is in /Users, so I'm not sure why that's happening.

**Comment by wez** [comment] 2023-04-04 04:46
@joshuarubin please file a separate issue so that this one can remain focused on the performance aspect

**Comment by calops** [comment] 2023-04-05 17:11
I've tried with an identical `unix_domains` configuration and wezterm version `20230405-084502-37e8a504` and it behaves the exact same way as the normal `ssh_domains` solution: very sluggishly. Big vim windows are unusable.

I don't understand what I'm doing differently.

**Comment by sirfz** [comment] 2023-04-05 18:38
I can confirm the experience is quite smooth with the nightly build. My setup:

OS: Windows 10
domain:
```lua
unix_domains = {
     {
       name = 'wsl-mux',
       serve_command = { 'wsl', 'wezterm-mux-server', '--daemonize' },
     },
},
```
WSL: Ubuntu 20.04 (with nightly `wezterm-mux-server`)

I logon to WSL and just ssh and work on remote servers all day, working great!

**Comment by lrvdijk** [comment] 2023-04-07 14:15
For me the performance has increased a lot too, so much that I can now use it as a daily driver! 🎉 

Still feel it's a little bit slower than iTerm2 + ssh + Tmux, but it's good enough for me.

**Comment by wez** [comment] 2023-04-07 14:21
@calops if you have vim plugins that cause every line to change when moving the cursor up or down (eg: displaying relative line numbers at the start of each line), then wezterm will still need to send a lot of data on each cursor movement.  Perhaps there is something like that in your config that is triggering the worst case performance?

**Comment by calops** [comment] 2023-04-07 14:28
@wez Yes, I do have something like this, but that's irrelevant for a simple use-case like "scrolling through a file" where lines are gonna get redrawn no matter what. And even simple stuff such as selecting text (which shouldn't redraw much) has a noticeable latency, which is made very obvious when doing it with the mouse.

The real problem here is that a plain `ssh` session still handles all this and performs perfectly fine compared to a wezterm mux session. It's faster by at least one or two orders of magnitude.

So it seems obvious to me that wezterm adds a significant overhead to this. Is this a technical limitation for this solution, or is there hope that it could be improved somehow?

**Comment by wez** [comment] 2023-04-07 14:37
Yes, there is more overhead because there obviously is more going on.
I think we all hope for improvement here.

One of my hopes is that enough users are willing to lend support that I can afford to
spend more time on issues like this one.
https://wezfurlong.org/wezterm/sponsor.html has some more information about this.

**Comment by supernomad** [comment] 2023-04-07 20:40
@wez I am still seeing this performance bottle neck as well with MacOS <> Linux and the latest nightly. I am more than happy to help dive into the code, but would need some assistance as to where to start. If you can give me some guidance as to where to start, I can take a whack at what is going on as I have a simple reproduction setup and can dive in over the next few weeks as I should have some spare time. Let me know if that makes sense to you!

**Comment by wez** [comment] 2023-04-07 21:57
@supernomad thanks for the offer, but I think it will likely be more time consuming to bootstrap someone than for me to sit down and do the work.  At a high level the issue is this:

* The mux sync protocol is line-based. So if a line is mutated, it gets flagged as dirty and that line will then either be unilaterally pushed to the client, or listed in a dirty lines set for the client to pull when it needs to render it
* Some terminal update operations are encoded in a few bytes of escape sequence, but can touch every line in the screen, amplifying the data that needs to be sent over the wire and driving up the latency

So the change granularity is `O(changed-lines)` and results in transmitting data that is `O(changed-lines x terminal_width)`.

The end state I have in mind is:

* At the mux layer, tap into the terminal output byte stream and journal it
* Build up a client + cursor concept that enables that journal when a client subscribes to it. It needs to be zero cost if there are no subscribers, and the journal needs to be pruned as soon as all clients (there can be multiple!) have read past it
* When subscribed, if the nature of the update being pushed by the server can be described by an incremental read from that journal, just send those bytes, otherwise send the line data.
* The client would need to be able to apply both the delta line updates and the byte stream updates, which means building a local `wezterm_term::Terminal` and applying both sets of changes to a local copy of the terminal emulation
* Rendering would need to be re-structured to run off of that model

That would bring the data to be processed down closer to `O(output-bytes)` in the best case.

These are pretty significant changes across several layers; it's not a small task.

**Comment by cunha** [comment] 2023-04-07 23:50
I did some additional tests on a 136x566 window and indeed could see some slowdown with `relativenumber` set in Vim (although I'd say the terminal was still useable). On a more comfortable 77x318 window I could not notice any slowdown.

This is over the Internet when connected to a server that is 30ms away; one's mileage will likely vary depending on connection quality.

**Comment by calops** [comment] 2023-04-12 08:37
> Yes, there is more overhead because there obviously is more going on.

That part wasn't obvious to me, actually. What specifically is done in addition to what an SSH/tmux stack is doing?

**Comment by wez** [comment] 2023-04-12 14:53
@calops you can read the code if you're really interested. It's too much to explain here for a casual comment; it will take time I don't have and it will have only cost and no benefit to me to do so to someone that isn't committed to spending some of their time also working on this, and I don't believe that you are that person.

**Closed** 2023-07-12 19:00 UTC
Labels: bug, fixed-in-nightly, multiplexer
