### ISSUE TITLE
WezTerm starts with gibberish (version?) in first line logging into WSL

### ISSUE THREAD

**Issue by thundron** [wez/wezterm#5342] opened 2024-04-26 13:42 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Whenever I try to log into wsl/bash, some characters + the version number appear as first line input

### To Reproduce

Running `wsl.exe` from a `powershell` prompt
![Screenshot 2024-04-26 150933](https://github.com/wez/wezterm/assets/5888446/ef7cc8bb-b276-4e1b-aa7e-3103dd7d0a0a)

Using `bash` as a `default_prog` value
![Screenshot 2024-04-26 153825](https://github.com/wez/wezterm/assets/5888446/b3e0d72a-7f71-4bed-a105-2ca9b94e2b99)

### Configuration

```lua
local wezterm = require("wezterm")

local config = wezterm.config_builder()

config.enable_tab_bar = false
config.default_prog = { "bash" }

return config
```

### Expected Behavior

The terminal opens without input noise

### Logs

Debug Overlay
wezterm version: 20240203-110809-5046fc22 x86_64-pc-windows-msvc
Window Environment: Windows
Lua Version: Lua 5.4
OpenGL: AMD Radeon RX 7900 XTX 4.5.0 Core Profile Context 24.3.1.240312
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>

### Anything else?

EDIT: I forgot to mention I use `tmux` and after a look around, I found https://github.com/wez/wezterm/issues/2060 which looks very similar

**Comment by wez** [comment] 2024-05-05 23:26
Duplicate of https://github.com/wez/wezterm/issues/4509

**Closed by wez** 2024-05-05 23:26 UTC
Labels: bug
