### ISSUE TITLE
Slow, animated text selection

### ISSUE THREAD

**Issue by neculaesei** [wez/wezterm#33] opened 2019-06-12 11:03 UTC
## Is it a build problem?
No

## Did something not work the way you expected?
Selecting text with the mouse seems to have a slow animation applied instead of being instant.
Running on Windows 10 Pro

### What did you expect to happen?
Instant text selection

### What actually happened?

Slow and animated text selection

![wezterm](https://user-images.githubusercontent.com/3195552/59346323-b4976e80-8d1a-11e9-85bc-f9574f1c9d71.gif)

**Comment by neculaesei** [comment] 2019-06-12 11:05
Non-related question: is mouse support on the road?

conhost supports it, but the new microsoft/terminal doesn't.
is it possible to add?

**Comment by wez** [comment] 2019-06-12 13:57
Thanks for reporting this.   I'll take a look: I did some work to improve this reasonably recently in 
https://github.com/wez/wezterm/commit/c207142bcf7915c3a9dd3f2cdd67f052e1ab3d21 but it sounds like something else it going on so I'll dig deeper.

> Non-related question: is mouse support on the road?
> 
> conhost supports it, but the new microsoft/terminal doesn't.
> is it possible to add?

That's an unfortunate limitation in conpty; it affects everything that uses conpty.   Here's the issue I filed with Microsoft:
https://github.com/microsoft/terminal/issues/376

Since it seems like it will have a long time frame to resolve in conpty, what are the interim solutions?
There are two possibilities you can try now, but neither are currently well tested--my main platforms at the moment are posix, so I haven't been forced to polish the windows side.   I would value your feedback on how well these work for you.

## winpty

I just added some very brief info on this to the readme yesterday because I noticed it was missing.  Here's a little more detail:

* Select a flavor (either cygwin or msys, whichever you prefer) of winpty from its release page: https://github.com/rprichard/winpty/releases/tag/0.4.3 and place the corresponding `winpty.dll` either in the same dir as `wezterm.exe` or otherwise ensure that it is in the `PATH`.    You will also need a cygwin or msys installation that matches the `winpty.dll` you chose in your path or in the same dir as the rest of this stuff.
* Set `pty = WinPty` in your `~/.wezterm.toml` configuration file
* quit and restart `wezterm.exe`; it should use either the cygwin or the msys pty subsystem which supports mouse reporting

## wezterm multiplexing

This is very new code and I haven't tested this on windows yet, but the idea is that you can connect to the WSL environment from the win32 gui environment using the multiplexer/terminal server protocol in wezterm.  You will have a wezterm running as a server in your WSL environment and a win32 wezterm running as the native gui.

### In your WSL environment:

* build the master branch of wezterm
* in the `~/.wezterm.toml` set `mux_server_unix_domain_socket_path` to something like `/mnt/c/Users/USERNAME/.wezterm.sock`.  The important thing is that this path be something resolvable from the win32 environment (eg: somewhere on `/mnt/c/`)
* run `wezterm start --front-end muxserver`

### In your win32 environment

* Grab a build from master: https://ci.appveyor.com/project/wez/wezterm/build/artifacts?branch=master
* In your win32 `~/.wezterm.toml`, set `mux_server_unix_domain_socket_path` to the win32 version of the path you set in the WSL environment (`mux_server_unix_domain_socket_path = "c:/Users/USERNAME/.wezterm.sock"`)
* run `wezterm start  --broken-mux-client-as-default-domain`

New windows and tabs will spawn new processes in the WSL environment, but render natively in the gui.   The performance of this is not as good as it could be, and this area is under active development so it should improve reasonably rapidly over the next couple of weeks.

**Comment by wez** [comment] 2019-06-12 14:29
Back to the selection performance: I just tried this and it works very snappy on the system I have handy, which is a pretty powerful work laptop: Razer blade with a good GPU.   Can you share some details about the system you're running on (CPU, GPU, screen resolution, the approximate size of the wezterm window)?  I'd like to understand whether this might be related to the available power in the system or whether something else might be a factor so that I can figure out how to reproduce and then resolve this issue.

You are not the only person to mention the selection performance: @xavierd also brought it up to me the other day.

**Comment by wez** [comment] 2019-06-12 14:49
(I just tested the wezterm multiplexing stuff on win32 and edit my comment with instructions: it works with the mouse but feels a little sluggish when initially opening the window)

**Comment by wez** [comment] 2019-06-12 15:06
Please also tell me whether you are using a build you downloaded from our releases section (if so, which one you downloaded), or whether you built it for yourself (if so, which revision of the repo, and can you confirm that you built with the `--release` flag)?

In addition, do you have any non-default configuration in your `wezterm.toml` file?  The `scrollback_lines` setting can influence the worst case complexity of selection processing so I'm wondering about that value in particular.

**Comment by wez** [comment] 2019-06-12 15:29
The closest I got to reproducing this was with a debug build, which was only occasionally sluggish for large selections.  I did spot and remove what appeared to be some debug code that got left in (74717744ba53a46e37d61645018de95ec37156a4), and with that removed I couldn't get it to feel slow, so maybe this will fix it for you?  I'd suggest waiting for that build to show up on appveyor and trying it out.

**Comment by xavierd** [comment] 2019-06-13 04:43
Rebuilding wezterm on top-of-tree did the trick for me :)

**Comment by neculaesei** [comment] 2019-06-13 16:16
Thank you for the reply!
Just got the latest build (01a8c32b), it's much faster.
I have no `wezterm.toml` (yet).
The capture at the bottom is at ~30fps.

We could close this issue, as the slow selection is fixed, right?

> Can you share some details about the system you're running on (CPU, GPU, screen resolution, the approximate size of the wezterm window)?
CPU: Intel i7-8700K (12) @ 3.696GHz
GPU: NVIDIA GeForce GTX 1070
Resolution: 2560 x 1440 @ 144hz
Window size: 1306 x 640

![wezterm2](https://user-images.githubusercontent.com/3195552/59449194-50a2a200-8e0f-11e9-9997-b71bc10f35e9.gif)

**Comment by wez** [comment] 2019-06-13 17:20
Yep, that looks much better!  I'll close this out, thanks for reporting this!

**Closed by wez** 2019-06-13 17:20 UTC
