### ISSUE TITLE
Can not input Ctrl-\ on Mac ( German keyboard )

### ISSUE THREAD

**Issue by aivanise** [wez/wezterm#1891] opened 2022-04-19 17:04 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220419-084632-92893f2a

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

whenever I try to enter Ctrl-\ to send a SIGQUIT to whatever im running (on my keyboard this is Ctrl-RightOption-Shift-7) I get esc-Ctrl-Space instead of ctrl-\

```
xxd
^[^_
00000000: 1b1f 0a

```
i have tried

```
keys = {
-- make ctrl-\ work (or not)
{ key="phys:7", mods="CTRL|ALT|SHIFT", action="DisableDefaultAssignment" }
}

```
in wezterm.conf, but nope.

### To Reproduce

switch to German keyboard in Macos
hit Ctrl-Shift-RightAlt-7

### Configuration

no config

### Expected Behavior

i expect Ctrl-\ (SIGQUIT) to be sent to the shell, i.e.

bash-5.1$ sleep 10
^\Quit: 3

not

$ sleep 10
^[^_^[^_^[^_^[^_^[^_^[^_^[^_^C

**Comment by wez** [comment] 2022-04-19 21:18
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out.

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them.

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by aivanise** [comment] 2022-04-20 05:59
^\ now works, but backspace stopped working ;) 

```
$ xxd
^[[3~^\Quit (core dumped)

```
wezterm 20220419-211836-6152bc0e

**Comment by wez** [comment] 2022-04-20 06:25
doh!  I think that is fixed in 924b63eb429cd2c1398a25c5735a860045d6a5ca

**Comment by aivanise** [comment] 2022-04-21 20:33
seems like its all working now, cheers

**Comment by aivanise** [comment] 2022-05-09 12:45
upgraded to the latest nightly and the issue with backspace and delete from above (https://github.com/wez/wezterm/issues/1891#issuecomment-1103501418) is back

> wezterm -V
wezterm 20220508-223436-7858f652

**Comment by wez** [comment] 2022-05-10 05:18
I can't reproduce this; here's what I see when logged into a linux box from my mac:

```
; showkey -a

Press any keys - Ctrl-D will terminate this program

^[[3~    27 0033 0x1b
         91 0133 0x5b
         51 0063 0x33
        126 0176 0x7e
^?      127 0177 0x7f

```

**Closed** 2022-06-01 12:39 UTC
Labels: bug, fixed-in-nightly
