### ISSUE TITLE
Windows installer flagged as containing Trojans

### ISSUE THREAD

**Issue by m-o-leary** [wez/wezterm#5776] opened 2024-07-02 08:30 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I downloaded this and when I tried to install it I got a security warning.

The infosec team in my company were alerted and they sent me a link to this analysis https://www.virustotal.com/gui/file/35a6ec0eff7aa65e3987f14223bfb9df831eaab2964eb441ed6cad4356d252ff/details

### To Reproduce

I think this is heavily reliant on my company security setup 

### Configuration

No config to show

**Comment by 0x6675636b796f75676974687562** [comment] 2024-07-02 15:06
Also https://bazaar.abuse.ch/sample/35a6ec0eff7aa65e3987f14223bfb9df831eaab2964eb441ed6cad4356d252ff/

**Comment by wez** [comment] 2024-07-13 21:18
Duplicate of https://github.com/wez/wezterm/issues/5074

**Closed by wez** 2024-07-13 21:18 UTC
Labels: bug
