### ISSUE TITLE
Click to position cursor in bash (shell integration)

### ISSUE THREAD

**Issue by mcarans** [wez/wezterm#2438] opened 2022-08-20 19:32 UTC
**Is your feature request related to a problem? Please describe.**
I am unable to click the left mouse button to position the cursor in bash

**Describe the solution you'd like**
Click left mouse button positions cursor in bash

**Describe alternatives you've considered**
Kitty and DomTerm support this. For example in Kitty, using [shell integration](https://sw.kovidgoyal.net/kitty/shell-integration/#shell-integration), you can "Click with the mouse anywhere in the current command to move the cursor there" in zsh, fish and bash.

This looks like a great terminal emulator and this would be a great feature to add.

**Other information**
I tried sourcing the shell integration file here: https://raw.githubusercontent.com/wez/wezterm/main/assets/shell-integration/wezterm.sh, but it didn't enable click to position in bash.

**Comment by wez** [comment] 2022-08-20 20:57
Duplicate of https://github.com/wez/wezterm/issues/1175

**Closed by wez** 2022-08-20 20:57 UTC
Labels: enhancement
