### ISSUE TITLE
Handling of non-us keyboards

### ISSUE THREAD

**Issue by arnaudlimbourg** [wez/wezterm#1543] opened 2022-01-13 21:21 UTC
**Is your feature request related to a problem? Please describe.**
Using a french keyboard, specifically an ergodox with qmk firmware using layers, is quite frustrating as I cannot type some characters, namely {}[]@\ and probably others.

**Describe the solution you'd like**
On both iterm2 and kitty this works fine and I'm lacking knowledge about keycodes, keymaps, etc. so I'm not sure if I need to configure something. I see there are a couple of issues opened on related subjects but since it works on iterm and kitty there probably has to be a way I'm missing.

Any advice is appreciated.

**Comment by wez** [comment] 2022-01-14 01:46
Are you running on the nightly build of wezterm, where significant changes have been made to keyboard input?
Which OS are you using?
Is this issue essentially a duplicate of https://github.com/wez/wezterm/issues/1542 ?

**Comment by arnaudlimbourg** [comment] 2022-01-14 08:57
I should have mentioned, I'm on macOS.

I was not running nightly so I switched to nightly and it is much better!

Many keys work but weirdly while } works, { doesn't. Running the debug mode I see this but I'm not sure how to interpret

```
 2022-01-14T08:53:44.894Z INFO  wezterm_gui::termwindow::keyevent      > key_event RawKeyEvent { key: Char('\''), modifiers: ALT | RIGHT_ALT, phys_code: Some(K4), raw_code: 21, repeat_count: 1, key_is_down: true, handled: Handled(false) }
 2022-01-14T08:53:44.894Z INFO  wezterm_gui::termwindow::keyevent      > Physical(K4) ALT | RIGHT_ALT -> perform ActivateTab(3)
 2022-01-14T08:53:45.014Z INFO  wezterm_gui::termwindow::keyevent      > key_event RawKeyEvent { key: Char('\''), modifiers: ALT | RIGHT_ALT, phys_code: Some(K4), raw_code: 21, repeat_count: 1, key_is_down: false, handled: Handled(false) }
 2022-01-14T08:53:45.014Z INFO  wezterm_gui::termwindow::keyevent      > key_event KeyEvent { key: Char('{'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('\''), modifiers: ALT | RIGHT_ALT, phys_code: Some(K4), raw_code: 21, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
 2022-01-14T08:53:45.014Z INFO  wezterm_gui::termwindow::keyevent      > send to pane key=Char('{') mods=NONE
 2022-01-14T08:53:45.414Z INFO  wezterm_gui::termwindow::keyevent      > key_event RawKeyEvent { key: Char('='), modifiers: ALT | RIGHT_ALT, phys_code: Some(Equal), raw_code: 24, repeat_count: 1, key_is_down: true, handled: Handled(false) }
 2022-01-14T08:53:45.415Z INFO  wezterm_gui::termwindow::keyevent      > key_event KeyEvent { key: Char('}'), modifiers: NONE, repeat_count: 1, key_is_down: true, raw: None }
 2022-01-14T08:53:45.415Z INFO  wezterm_gui::termwindow::keyevent      > send to pane key=Char('}') mods=NONE
 2022-01-14T08:53:45.415Z INFO  wezterm_term::terminalstate::keyboard  > key_down: sending "}", Char('}') NONE
 2022-01-14T08:53:45.486Z INFO  wezterm_gui::termwindow::keyevent      > key_event RawKeyEvent { key: Char('='), modifiers: ALT | RIGHT_ALT, phys_code: Some(Equal), raw_code: 24, repeat_count: 1, key_is_down: false, handled: Handled(false) }
 2022-01-14T08:53:45.486Z INFO  wezterm_gui::termwindow::keyevent      > key_event KeyEvent { key: Char('}'), modifiers: NONE, repeat_count: 1, key_is_down: false, raw: Some(RawKeyEvent { key: Char('='), modifiers: ALT | RIGHT_ALT, phys_code: Some(Equal), raw_code: 24, repeat_count: 1, key_is_down: false, handled: Handled(false) }) }
 2022-01-14T08:53:45.486Z INFO  wezterm_gui::termwindow::keyevent      > send to pane key=Char('}') mods=NONE
```

Not sure if this is a duplicate, it might well be.

**Comment by wez** [comment] 2022-01-14 15:15
It seems that `{` in your keyboard layout is ALT-4; I would consider this to be the same issue as #1542, which is that the default ALT-<number> assignments are not great for non-US layouts

**Comment by wez** [comment] 2022-01-14 15:41
Duplicate of #1542

**Closed by wez** 2022-01-14 15:41 UTC
Labels: enhancement
