### ISSUE TITLE
Wezterm most of the times can't be resized

### ISSUE THREAD

**Issue by drainpixie** [wez/wezterm#5337] opened 2024-04-25 14:12 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

2bwm (master)

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Most of the times the spawned window can't be resized.

### To Reproduce

Spawn Wezterm (be it through Rofi or a keybinding), try resizing by dragging or keybindings, fail to do so.

### Configuration

```lua
local wezterm = require "wezterm"
local config = wezterm.config_builder()

config.font_size = 10.0
config.window_padding = {
    left = 8,
    right = 8,
    top = 8,
    bottom = 8
}

config.front_end = "OpenGL"
config.color_scheme = "Gruvbox dark, medium (base16)"
config.enable_tab_bar = false

return config
```

### Expected Behavior

Should spawn as a window & be resizeable

### Logs

```
Debug Overlay
wezterm version: 20240203-110809-5046fc22 x86_64-unknown-linux-gnu
Window Environment: X11
Lua Version: Lua 5.4
OpenGL: Mesa Intel(R) UHD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 24.0.3
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
16:11:51.012 ERROR window::os::x11::connection > error fetching window manager name: empty list of windows
16:11:51.027 WARN window::os::x11::connection > Unable to resolve appearance using xdg-desktop-portal: get_appearance.read_setting: Reading xdg-portal org.freedesktop.appearance color-scheme: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```
### Anything else?

https://github.com/wez/wezterm/assets/121581793/2d8f7c9d-26a3-43c5-ad26-3e9bb97d4582

**Comment by wez** [comment] 2024-05-05 23:32
Please try the latest nightly build

**Comment by duganchen** [comment] 2024-05-08 23:34
This is a duplicate of #5332

**Comment by wez** [comment] 2024-05-09 21:54
I don't think this is a duplicate of #5332 because this issue is encountered on X11 whereas the other one is Wayland.

**Closed** 2024-05-20 00:24 UTC
Labels: bug, X11, waiting-on-op
