### ISSUE TITLE
Wezterm doesn't open if it's the first window

### ISSUE THREAD

**Issue by jabuxas** [wez/wezterm#5258] opened 2024-04-02 14:15 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)

### WezTerm version

wezterm 20240325-093507-e5ac32f2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Wezterm doesn't appear on screen if it's the first terminal being opened, but it opens if I for example open kitty first and then wezterm.

### To Reproduce

1. Start hyprland
2. start wezterm
3. wezterm doesn't start.
4. open kitty
5. open wezterm, wezterm now opens

### Configuration

no config

### Expected Behavior

Wezterm opens normally.

### Logs

It doesn't log, the process starts but doesn't log anything

### Anything else?

It might have to do with hyprland, i'm not sure how to diagnose it. It happens both on my desktop with Gentoo and my laptop with Arch.

**Comment by RangHo** [comment] 2024-04-03 07:11
I assume this issue is related to #4708 and #5103.

Affected compositors do not send a window initialization message with (0, 0) as the window size, and this list includes Hyprland v0.37.
Forcing wezterm to use XWayland is a temporary workaround, though.

**Comment by jabuxas** [comment] 2024-04-03 21:52
it definitely is the same problem, though i'd assume its something on hyprland side and not wezterm then, right? 

opening kitty first then wezterm then wezterm works though.. for some odd reason (without the enable_wayland = false)

**Comment by RangHo** [comment] 2024-04-03 22:13
It _is_ on wezterm, as it apparently does not (well, as far as I understand, that is) respond correctly to a window sizing and positioning message. Check out the explanation here: https://github.com/wez/wezterm/issues/5197#issuecomment-2020263016

I don't have much wayland experience to contribute so I'm waiting for a fix as well 😂

**Comment by woojiq** [comment] 2024-04-19 20:26
Duplicate of https://github.com/wez/wezterm/issues/5103

**Comment by wez** [comment] 2024-05-05 14:07
Duplicate of #5103

**Closed by wez** 2024-05-05 14:07 UTC
Labels: bug
