### ISSUE TITLE
Wezterm from Gnome Software Center (Fedora) only installing 867kb - Makes directories

### ISSUE THREAD

**Issue by jkemp814** [wez/wezterm#2937] opened 2023-01-10 07:11 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Fedora Linux 37 Silvewrblue (Wayland)

Install flatpak from Software center ends with incomplete installation. Installing from Flathub completes.

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Incomplete installation.

### To Reproduce

Install from Gnome Software Center. App will not launch. Check folder size. Only 867kb. Software store states it should 105MB. Downloaded from Flathub at 42.9MB. Folder still only shows 816.7kb from Flathub. Will not launch.

### Configuration

no config

### Expected Behavior

Should install complete package.

### Anything else?

Nope.

**Comment by jkemp814** [comment] 2023-01-10 07:14
![image](https://user-images.githubusercontent.com/12059343/211485632-c40f4b61-dc05-4d91-82ec-372279a000c5.png)

**Comment by wez** [comment] 2023-01-10 14:08
Sounds like something went wrong when installing it.  Try uninstalling it and reinstalling it?

**Comment by jkemp814** [comment] 2023-01-10 16:28
I ahve tried many times. From the Software Cneter and from the

commandline: flatpak install flathub org.wezfurlong.wezterm 

Still same results. 'Megasync' package has done this. I had to use their CMD package. Even Firefox's flatpak a couple years back, wouldn't start. I have seen these complaints across the NET for years. Most will, some won't start.

I will try again and logut, restart and see what happens.

**Comment by jkemp814** [comment] 2023-01-10 16:50
I uninstalled, deleted package in .var/app, then logged out. 

Reinstalled from command line and ran: flatpak run org.wezfurlong.wezterm

Got this error message in the console:

[destroyed object]: error 7: failed to import supplied dmabufs: Unsupported buffer format 875713345
09:47:28.643  ERROR  wezterm_gui > running message loop: error during event_q.read_events protocol_error=Some(ProtocolError { code: 7, object_id: 0, object_interface: "<unknown>", message: "" }): Protocol error (os error 71); terminating

**Comment by wez** [comment] 2023-01-11 16:16
Sounds similar to https://github.com/wez/wezterm/issues/2011

**Comment by wez** [comment] 2023-02-07 03:34
I'm closing this out; the original issue sounded like a failed download, and the subsequent issue sounds like a duplicate of a different issue

**Closed by wez** 2023-02-07 03:34 UTC
Labels: bug
