### ISSUE TITLE
Memory footprint compare with Windows Terminal

### ISSUE THREAD

**Issue by lost4git** [wez/wezterm#2172] opened 2022-06-25 10:59 UTC
### 1 tab opened

![屏幕截图 2022-06-25 185206](https://user-images.githubusercontent.com/65008815/175770525-d1017747-c878-416a-a5d9-8a97a80abb0c.png)

### 5 tabs opened
![屏幕截图 2022-06-25 162407](https://user-images.githubusercontent.com/65008815/175770527-ff12f6e7-c6e2-42eb-b684-2908218e3f56.png)

It would be great if the initialization memory footprint could be reduced (for use on low memory devices)

**Comment by wez** [comment] 2022-06-25 12:12
Duplicate of #1626

**Closed by wez** 2022-06-25 12:12 UTC
Labels: enhancement
