### ISSUE TITLE
wezterm forgets that it is maximized

### ISSUE THREAD

**Issue by db48x** [wez/wezterm#5783] opened 2024-07-04 12:56 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Mutter

### WezTerm version

wezterm 20240701_070926_69686f45

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I can maximize the WezTerm window, but as soon as I switch to some other program and then back, WezTerm is no longer maximized.

### To Reproduce

- Start WezTerm
- hold down system key, right click
- choose Maximize
- WezTerm is now maximized
- alt-tab away (or switch windows by any other means)
- alt-tab back
- WezTerm is back to 80×24

### Configuration

```lua
local config = wezterm.config_builder()
return config
```

Yes, an empty config. The problem goes away if I specify
```lua
config.window_decorations = "RESIZE"
```

Weirdly, this enables the titlebar as well as the resizable borders.

### Expected Behavior

Maximized windows should stay that way.

### Logs

Debug Overlay
wezterm version: 20240701_070926_69686f45 x86_64-unknown-linux-gnu
Window Environment: Wayland
Lua Version: Lua 5.4
OpenGL: NVIDIA GeForce GTX 980 Ti/PCIe/SSE2 4.6.0 NVIDIA 550.90.07
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

**Comment by wez** [comment] 2024-09-22 15:34
Duplicate of https://github.com/wez/wezterm/issues/4665

**Closed by wez** 2024-09-22 15:34 UTC
Labels: bug, Wayland
