### ISSUE TITLE
Chrome flagging download as suspicious

### ISSUE THREAD

**Issue by JPHutchins** [wez/wezterm#5542] opened 2024-06-10 20:12 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230203-110809-5046fc

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Chrome flags the installer and refuses to download.

![image](https://github.com/wez/wezterm/assets/34154542/9a693ce1-b288-4f55-a27d-41631b75c87b)

### To Reproduce

Download GitHub releases using Chrome

### Configuration

NA

### Expected Behavior

Chrome downloads the installer without warning.

### Anything else?

I'm not sure that the installer is signed, is it supposed to be and how would I check?

```powshershell
(Get-AuthenticodeSignature -FilePath .\WezTerm-20240203-110809-5046fc22-setup.exe).Status
NotSigned
```

Maybe switching to MSI from EXE would resolve this issue. 

Anyway, can the false positive be reported to Chrome?

**Comment by qgates** [comment] 2024-06-11 00:52
Confirm same issue with the windows zip download as well:

[WezTerm-windows-20240203-110809-5046fc22.zip](https://github.com/wez/wezterm/releases/download/20240203-110809-5046fc22/WezTerm-windows-20240203-110809-5046fc22.zip)

However in this case the download is flagged as 'dangerous' instead of 'suspicious'.

**Comment by JPHutchins** [comment] 2024-06-11 01:12
> 'dangerous' instead of 'suspicious'.

💣 🕵️‍♀️

**Comment by wez** [comment] 2024-07-13 22:17
Duplicate of https://github.com/wez/wezterm/issues/5074

**Closed by wez** 2024-07-13 22:17 UTC
Labels: bug
