### ISSUE TITLE
SHIFT modifier is lost on macOS/ABC

### ISSUE THREAD

**Issue by gaydenko** [wez/wezterm#765] opened 2021-05-06 10:07 UTC
This is a config fragment:
```lua
        { 
            key = "raw:9", -- v
            mods = "CMD|SHIFT",
            action = wezterm.action { PasteFrom = "Clipboard" }
        },
```
This is debug output on the command with ABC keyboard layout and Russian one:
```
 2021-05-06T09:49:18.072Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('v'), modifiers: NONE, raw_key: Some(Char('V')), raw_modifiers: SUPER, raw_code: Some(9), repeat_count: 1, key_is_down: true }
 2021-05-06T09:49:24.604Z INFO  wezterm_gui::termwindow::keyevent > key_event KeyEvent { key: Char('V'), modifiers: NONE, raw_key: Some(Char('М')), raw_modifiers: SHIFT | SUPER, raw_code: Some(9), repeat_count: 1, key_is_down: true }
```
As you can see SHIFT is lost in `raw_modifiers` list at the first (ABC) case. As a result I get typed `v` on the command line input istead of pasting clipboard. With Russian layout all do work. 

The issue takes place for other (not all) keys I have assigned also.

I have tried to replace ABC with British or U.S. layout and got the same issue.

`20210502-154244` version is in use on MBP running Big Sur.

**Comment by gaydenko** [comment] 2021-05-18 20:00
@wez Will you, please, add the macOS tag with a hope somebody will got a curiosity to reproduce the issue?

**Comment by wez** [comment] 2021-05-22 06:13
Likely related to https://github.com/wez/wezterm/issues/601

**Comment by wez** [comment] 2021-06-10 14:45
Duplicate of #601

**Closed by wez** 2021-06-10 14:45 UTC
Labels: bug, macOS
