### ISSUE TITLE
Colors displayed are not same as the colorscheme defined.

### ISSUE THREAD

**Issue by LimbicSys** [wez/wezterm#2287] opened 2022-07-20 07:30 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20220719-194527-badfae7d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I use the colorscheme `Catppuccin Mocha`, the color displayed are not correct.
For example, the background defined by the colorscheme is `#1e1e2e`, but the displayed color is `#232036`.
<img width="661" alt="截屏2022-07-20 15 06 12" src="https://user-images.githubusercontent.com/30319215/179918660-bb7686f9-6094-4a50-9a2c-03a1d7fb40df.png">
The left terminal is wezterm, the right one is kitty. They use the same colorscheme, but the colors are slightly different.
`TERM` is set to be `xterm-256color`.

### To Reproduce

1. Set the colorscheme to be `Catppuccin Mocha`.
2. Launch the terminal.

### Configuration

``` lua
return {
  color_scheme = "Catppuccin Mocha",
}
```

### Expected Behavior

Display the right colors.

### Logs

Debug Overlay
wezterm version: 20220719-194527-badfae7d
OpenGL version: Apple M1 Pro 4.1 Metal - 76.3
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
15:28:37.056 WARN env_bootstrap > setlocale(en_CN.UTF-8) failed, fall back to en_US.UTF-8
>

**Comment by wez** [comment] 2022-07-20 15:40
I can't reproduce on my mac:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/117777/180022019-5da794a3-a168-4d50-82af-8abc1895cd0c.png">

Do you see the same different for all colors on that system?

**Comment by LimbicSys** [comment] 2022-07-21 02:08
I link my mac to a display.
When the display works as the main display, the colors are not correct.
But if I only use mac's display, the colors are correct.

**Comment by LimbicSys** [comment] 2022-07-21 02:29
My display uses sRGB color space.
The color value is got by the `Digital Color Meter` App.
When I set it "Display in sRGB", kitty's color value is correct.
When I set it "Display native values", wezterm's color value is correct.

**Comment by wez** [comment] 2022-07-21 03:18
I'm curious if kitty is color-correct when that display is set to "display native values"?

**Comment by LimbicSys** [comment] 2022-07-21 04:20
> I'm curious if kitty is color-correct when that display is set to "display native values"?

No. The color value is `#1c1c28` in native.

I also test other terminals.
Kitty and Iterm have the same display behaviors.
And Alacritty is same as wezterm.

**Comment by wez** [comment] 2022-07-21 04:58
This is a bit of a tricky area; the opengl implementation may or may not report whether it supports the SRGB colorspace. In addition, it may or may not support automatic conversion from linear to srgb for the result of the shader program.

The strategy used by wezterm is to indicate to the glium crate (which is a safe opengl wrapper) that it outputs srgb and to output srgb in its shaders.

Provided that the opengl implementation correctly reports to glium that srgb is supported, then wezterm will produce color correct output.

If glium doesn't think that the gl implementation supports srgb then the result may be over or under corrected (https://github.com/wez/wezterm/issues/1701 is an example of that).

On recentish versions of macOS, the opengl implementation is layered on top of Metal so there is an additional layer of stuff happening.

What I suspect may be the case is that the opengl implementation may somehow not be seeing the true display format for your monitor and thus the output is over/under gamma corrected.

For Kitty, I suspect that it isn't indicating to opengl that it outputs srgb so it has the opposite issue by default, but then becomes color correct when used on that other display.

I find it interesting that iterm behaves the same way as kitty for you.  Do you have GPU rendering enabled in its settings?
My understanding is that iterm directly targets Metal when using GPU rendering, so I would assume that it would have the highest chance of being color correct in all situations.  Can you try turning GPU rendering on/off and see if that impacts the color accuracy?

If iterm also has incorrect colors in some situations, then I might suspect something about the configuration/color profile associated with the display, however, I don't know enough how that works on macOS to say for sure.

**Comment by kovidgoyal** [comment] 2022-07-21 05:08
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_colorspace

**Comment by LimbicSys** [comment] 2022-07-21 05:28
Things got right when I use the system's `srgb` color profile instead of the display's color profile. And all terminals display the same colors.

**Comment by LimbicSys** [comment] 2022-07-21 05:32
By the way, Iterm's gpu rendering has no impact on colors.

**Comment by wez** [comment] 2022-07-22 02:15
OK, so this sounds like the issue is really in the display color profile and is not something that opengl apps can do anything about, so I'm going to close this!

**Closed by wez** 2022-07-22 02:15 UTC
Labels: bug
