### ISSUE TITLE
Keyboard not responding after resizing window

### ISSUE THREAD

**Issue by junnplus** [wez/wezterm#2024] opened 2022-05-24 13:01 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220509-172420-e5a483ff

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Keyboard not responding after resizing window.

### To Reproduce

1. start wezterm gui
2. input anything is work
3. resize window
4. input anything is not work

### Configuration

no config

### Expected Behavior

input anything is work after resize window

**Comment by junnplus** [comment] 2022-05-24 13:30
> I suspect that this might be the same underlying issue as #1628 where the IME somehow gets stuck

Useful clue, i set `use_ime` to false and it works!

**Comment by wez** [comment] 2022-05-24 13:35
Thanks for confirming!
Closing as duplicate of #1628

**Closed by wez** 2022-05-24 13:35 UTC
Labels: bug, keyboard
