### ISSUE TITLE
Include LuaLS stubs for the Lua api

### ISSUE THREAD

**Issue by koshell** [wez/wezterm#4386] opened 2023-10-02 02:32 UTC
**Is your feature request related to a problem? Please describe.**
I enjoy tweaking my config this way and that. Frequently done similar in neovim. However it can be very frustrating trying to troubleshoot my config files with wezterm because I end up constantly having to cross-reference the online docs. Then I also frequently have to actually check the return values line up with the docs (docs are always more of a suggestion anyway). Having no completeion makes it way too easy to pass a string when you meant to pass a table or recieve a table where you meant to recieve a string.

**Describe the solution you'd like**
The solution would simply be to include some stubs that could be read by LuaLS. That would then allow for auto-completion and type checking. Ideally you would use some kind of workflow that would generate these stubs directly from the rust source so you can avoid having to update them directly as functions are added or removed. However I'm unfamiliar with the rust ecosystem so I can't say if a premade tool already exists for such a use case.

**Describe alternatives you've considered**
Limited information can be documented by interrogating the various endpoints during runtime. It is possible to inspect tables for keys and types and build up a rough idea of the layout. However this doesn't work for functions (can't exactly randomally execute functions to see what happens) and would be unreliable for tables with optional values.

**Additional context**
As a demonstration here is what a stub for `wezterm.battery_info` might look like (written from memory, might be syntax errors):
```lua
---@module wezterm
local wezterm = {}

---@return { state_of_charge : number, vendor : string, model : string, serial : string, time_to_full : number?, time_to_empty : number?, state : "Charging" | "Discharging" | "Empty" | "Full" | "Unknown" }
function wezterm.battery_info() end
```

**Comment by wez** [comment] 2023-10-02 14:49
Duplicate of https://github.com/wez/wezterm/issues/3132

**Closed by wez** 2023-10-02 14:49 UTC
Labels: enhancement
