### ISSUE TITLE
There are always some empty lines in the bottom

### ISSUE THREAD

**Issue by ihaohe** [wez/wezterm#3706] opened 2023-05-11 11:16 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230501-084619-d0e9a034

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

There're always some empty lines in the bottom.  In the following pic, I draw a red box in the empty lines and use "tab_bar_at_bottom = true" for more explicit illustration.
![image](https://github.com/wez/wezterm/assets/41662686/5bc51b2c-ac6b-4b54-a573-4bb9c1c02354)

### Configuration

no config

**Comment by wez** [comment] 2023-05-11 15:03
Duplicate of https://github.com/wez/wezterm/issues/3391

**Closed by wez** 2023-05-11 15:03 UTC
Labels: bug
