### ISSUE TITLE
Unable open wezterm on hyprland

### ISSUE THREAD

**Issue by huwqchn** [wez/wezterm#5299] opened 2024-04-15 12:07 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

hyprland

### WezTerm version

latest nightly

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

ERROR  wezterm_term::terminalstate::performer > kitty_img: data should have been materialized in coalesce_kitty_accumulation: base64 decode: Invalid padding

### Configuration

empty config

### Expected Behavior

can works on hyprland without error

### Logs

20:07:02.920  ERROR  wezterm_term::terminalstate::performer > kitty_img: data should have been materialized in coalesce_kitty_accumulation: base64 decode: Invalid padding

**Comment by ForeverZer0** [comment] 2024-04-18 04:19
Have the same issue, though it does work for me if I disable Wayland support.
```
config.enable_wayland = false
```
It is odd though, as it does work under other Wayland sessions, so it does seem to be something specifically related to Hyprland. I don't seem to get any errors or warning, it simply hangs forever without actually starting.

Here is what I get, not sure if it will help track down the problem:

OS: Arch Linux
Hyprland:  0.39.1-4
wezterm: 20240203.110809.5046fc22-1

Running...
```
WEZTERM_LOG=debug wezterm start --always-new-process
```
[Resulting Log](https://gist.github.com/ForeverZer0/3ddab45b6d46f60bc32d2703df663205)

It doesn't seem to be dependent on configuration, I can completely remove my configuration for the same result, likewise no difference if using hardware/software rendering, OpenGL, Vulkan, etc.

**Comment by woojiq** [comment] 2024-04-19 20:25
Duplicate of https://github.com/wez/wezterm/issues/5103

**Comment by wez** [comment] 2024-05-05 14:07
Duplicate of #5103

**Closed by wez** 2024-05-05 14:07 UTC
Labels: bug
