### ISSUE TITLE
Special glyphs are rendered with visible separator

### ISSUE THREAD

**Issue by vimpostor** [wez/wezterm#826] opened 2021-05-28 16:24 UTC
When using special glyphs such as `\uE0B6`, wezterm inserts a weird visual artifact between the symbols.

Please see the attached screenshot. On the left **wezterm** with weird visible separators, and on the right **KDE konsole** with no visual separators.
<img width="752" alt="Screenshot_20210528_181348" src="https://user-images.githubusercontent.com/21310755/120013291-dca03b00-bfe0-11eb-8cd2-d1ce1764143f.png">

## To Reproduce

Run the following command:
```bash
echo -e "\uE0B6$(tput setab 7)$(tput setaf 0)TEST$(tput setab 0)$(tput setaf 7)\uE0B4"
```

Now you should see a nice continuous ribbon, but instead wezterm renders small separators between the glyphs.

## Environment:

 - OS: Linux X11
 - Version: wezterm 20210502-154244-3f7122cb
 - Font: MesloLGS NF (Nerdfont patch with extra glyphs)

```lua
local wezterm = require 'wezterm';
return {
	color_scheme = "Breeze",
	enable_tab_bar = false,
	font = wezterm.font("MesloLGS NF"),
	font_size = 10.0,
}
```

**Comment by wez** [comment] 2021-05-28 16:31
Duplicate of https://github.com/wez/wezterm/issues/584

**Closed by wez** 2021-05-28 16:31 UTC
Labels: bug
