### ISSUE TITLE
wezterm ls-fonts --list-system|bat will panic

### ISSUE THREAD

**Issue by Freed-Wu** [wez/wezterm#2676] opened 2022-10-29 09:54 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

lxqt

### WezTerm version

20220905.102802.7d4b8249-1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

```sh
❯ wezterm ls-fonts --list-system|bat
17:51:31.114  ERROR  env_bootstrap > panic at library/std/src/io/stdio.rs:1015:9 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: __libc_start_main
  15: <unknown>

thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1015:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### To Reproduce

Install wezterm and bat, then `wezterm ls-fonts --list-system|bat`

### Configuration

Empty

### Expected Behavior

No bug.

### Logs

Empty

### Anything else?

None

**Comment by vimpostor** [comment] 2022-10-29 19:30
Yeah, that's a common Rust problem with `println!()`: https://github.com/rust-lang/rust/issues/24821

You can reproduce it even simpler just by closing the pipe immediately: `wezterm ls-fonts --list-system | false`

The fix could be to use `writeln()` instead of `println()`:

```diff
-    println!("Primary font:");
+    writeln!(std::io::stdout(), "Primary font:")?;
```

But that would be cumbersome to replace. Maybe it's better to wait for upstream Rust to fix this, there seem to be some recent development regarding this issue: https://github.com/rust-lang/rust/issues/97889

**Comment by wez** [comment] 2022-10-29 19:49
This sounds more like a `bat` problem than a wezterm problem; sounds like `bat` is terminating before the output is printed and wezterm, indirectly via the rust runtime, is raising that as an error to let you know that what you're trying to do doesn't make sense.

Note that using `?` to propagate the error doesn't change the fact that the output is closed prematurely by the other process.

**Closed** 2022-11-20 13:23 UTC
Labels: bug

**Comment by Freed-Wu** [comment] 2022-11-20 13:28
> You can reproduce it even simpler just by closing the pipe immediately

I test `wezterm ls-fonts --list-system | false` can result in this bug. So I think it is not bat's bug.

> wait for upstream Rust to fix this

I see. Thanks!

**Comment by wez** [comment] 2022-11-20 13:41
FWIW: this isn't a bug in wezterm or in Rust.  It's telling you that it couldn't write to the pipe. If `bat` closes the pipe before the data is read, that really does feel like a bug in `bat`: what's the point of piping to a pager if the pager closes the input before it read everything?

**Comment by Freed-Wu** [comment] 2022-11-20 13:46
OK, I'll report it to bat.

**Comment by vimpostor** [comment] 2022-11-20 15:52
> If `bat` closes the pipe before the data is read

FWIW: That's not true, bat does not even close the pipe and I don't know where you get that idea from. It just doesn't read everything at once.
In fact this is not a bug but the correct behaviour for any sane pager. If you pipe a 1M-line long essay to a pager, would you rather have it doing `read()` syscalls forever, or have it do a few and then display the data immediately?

The piping to `false` was just a minimum reproducable example, but the bug does not have anything to do with the program closing the pipe. You can also reproduce it with piping to `less`, if you want to test it yourself.

**Comment by sharkdp** [comment] 2022-11-20 21:15
To be clear, this only happens if `bat` uses a pager (`less`, which it does by default) AND if that pager is closed before reading the full output. `bat` works in a fully streaming way, so if the pager does not require more output from `bat`, it will not read more of its input.

This error can *not* be reproduced by piping to `bat --paging=never`/`bat -P` or when piping to `bat` with the pager, then scrolling to the end of the output (`shift+g`), forcing `less` to read all output, and then closing the pager.

As @vimpostor said, this can also be reproduced with `less`. Or when piping to `head` (maybe a bit more realistic then piping to `false`, but that would also work).

So no, this is not a bug in `bat`.

What I typically do is to explicitly handle the broken pipe error in my Rust apps (and ignore it, exit with 0). See e.g. https://github.com/sharkdp/fd/blob/db2590dca56a180d51ec73a3dc41963e454452cc/src/output.rs#L24-L26. A cheaper option is to just use `writeln!(<stdout handle>, …).ok()` but that will keep your process unnecessarily writing to the broken pipe.
