### ISSUE TITLE
Kitty image protocol doesn't work on Windows

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [wez/wezterm#5757] opened 2024-06-26 15:44 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20240623-130118-4daab4dc

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When running a Windows version of _WezTerm_, only an _iTerm2_ image protocol seems supported (Linux version supports **both** _Kitty_ and _iTerm2_). 

### To Reproduce

1. Connect a Windows version of _WezTerm_ to a Linux box, over SSH or WSL.
2. install [`timg`](https://github.com/hzeller/timg/) to be able to display images in your terminal: `apt-get install timg` on Debian/Ubuntu.
3. Run `timg -pi image.png`. The image will get displayed (because _iTerm_ protocol works as expected).
4. Run `timg -pk image.png`. The image will **not** get displayed.

![image](https://github.com/wez/wezterm/assets/73111822/efb838fc-3533-4fdb-a07c-0a11b1966242)

### Configuration

no config

### Logs

No logs, except for `gui-sock-123456` socket file.

**Comment by AnonymouX47** [comment] 2024-06-26 20:38
Duplicate of #1673

**Closed** 2024-07-13 21:26 UTC
Labels: bug
