### ISSUE TITLE
Broken box-drawing character rendering

### ISSUE THREAD

**Issue by tk-nguyen** [wez/wezterm#899] opened 2021-06-23 12:09 UTC
## Describe the bug
I'm running into an issue with the box-drawing characters not rendering correctly: ├ ┤

## Environment (please complete the following information):

 - OS: Linux Wayland (sway)
 - Version: wezterm 20210622-203951-ea95f3f7
 - The active keyboard layout name: en_US

## To Reproduce
I'm using `JuliaMono` as my font in wezterm, downloaded from here: https://github.com/cormullion/juliamono. When i ran `lsblk` or any other utilities that draw boxes, the characters appeared broken, like the screenshots below. When I changed to another terminal (`kitty`), they were rendered as expected.

## Configuration
Here's the relevant config:
```lua
local wezterm = require 'wezterm';

return {
  color_scheme = "Dracula+",
  font = wezterm.font("JuliaMono", {bold=false, italic=false}),
  ...
}
```

## Expected behavior
The box-drawing characters are rendered correctly.

## Screenshots
Here's the output in `wezterm`:
![screenshot_2021-06-23_19-06-17_498805753](https://user-images.githubusercontent.com/39090621/123093569-0caef280-d456-11eb-8131-bd5d013acd28.png)
And here's the output in `kitty`:
![screenshot_2021-06-23_19-06-39_408635096](https://user-images.githubusercontent.com/39090621/123093621-1afd0e80-d456-11eb-94f2-26a08e6af851.png)
Side-by-side: 
![screenshot_2021-06-23_18-52-55_785291420](https://user-images.githubusercontent.com/39090621/123093659-25b7a380-d456-11eb-9715-5afe9289eb2a.png)

## Additional context
Strangely, when I changed my font to `JuliaMono-Regular`, the characters are drawn correctly (a little unaligned):
![screenshot_2021-06-23_18-56-55_917886847](https://user-images.githubusercontent.com/39090621/123093873-69aaa880-d456-11eb-984d-236448f3b5fe.png)
I also have an issue on the font repository: https://github.com/cormullion/juliamono/issues/109, but it appears to be the terminal problem, as it rendered fine in `kitty`.

**Comment by bew** [comment] 2021-06-23 12:39
> I also have an issue on the font repository: [cormullion/juliamono#109](https://github.com/cormullion/juliamono/issues/109), but it appears to be the terminal problem, as it rendered fine in `kitty`.

NOTE that kitty isn't a good comparaison when trying to see if the font or the terminal is at fault, because kitty doesn't use the font for most of these drawing chars, and draws the chars itself, so they are _always_ perfect.

**Comment by wez** [comment] 2021-06-23 16:02
In nightly builds of wezterm, you can run `wezterm ls-fonts --text '├─'` and it will print out something like this to explain which font is used to render a given character; that will help to understand a bit more about whether a mixture of fonts is being picked up and used for that text:

```bash
; wezterm ls-fonts --text '├─'
├    \u{251c}     glyph=915  wezterm.font("Terminus", weight="Bold", stretch="Normal", italic=false)
                             /home/wez/.fonts/terminus-bold.otb, FontDirs
─    \u{2500}     glyph=891  wezterm.font("Terminus", weight="Bold", stretch="Normal", italic=false)
                             /home/wez/.fonts/terminus-bold.otb, FontDirs
```

You can also run `wezterm ls-fonts` with no additional arguments to print out the font resolution "plan".

The block glyphs are generally problematic for two reasons:

* If the glyphs aren't resolved from the base font and are instead found in a fallback font, the font metrics almost never match up correctly, leading to small imperfections relative to the rest of the text
* There is a freetype hinting bug that can cause antialiased gaps or glitches when the font size results in fractional pixels

So there is a growing trend among terminal emulators to override and ignore certain drawing characters that are typically found in fonts and draw their own pixel perfect versions. Kitty has the most complete set of those, and wezterm is slowing growing its own set (#433, #584, #588).

**Comment by tk-nguyen** [comment] 2021-06-25 05:37
So I ran `wezterm ls-fonts` with the problematic characters, and here's the output:
```bash
~ ➜  wezterm ls-fonts --text "├"
├    \u{251c}     glyph=285  wezterm.font("JuliaMono", weight="Regular", stretch="Normal", italic=false)
                             /home/thainguyen/.local/share/fonts/JuliaMono-RegularLatin.ttf, FontConfig

~ ➜  wezterm ls-fonts --text "┤"
┤    \u{2524}     glyph=284  wezterm.font("JuliaMono", weight="Regular", stretch="Normal", italic=false)
                             /home/thainguyen/.local/share/fonts/JuliaMono-RegularLatin.ttf, FontConfig
```
Which coincided with what @cormullion said here: https://github.com/cormullion/juliamono/issues/109#issuecomment-866784166. I'll ask him for more information.

**Comment by wez** [comment] 2021-06-26 21:30
I just pushed a series of commits that completes wezterm's own box drawing glyph range.  If you grab the nightly build you should have a better experience.

I'm going to close this issue as a duplicate of #584

**Closed by wez** 2021-06-26 21:30 UTC
Labels: bug

**Comment by cormullion** [comment] 2021-06-26 21:34
Cool. Is the built-in box drawing  "always on" or a configurable option that can switched on and off?

**Comment by wez** [comment] 2021-06-26 21:36
it's controlled by https://wezfurlong.org/wezterm/config/lua/config/custom_block_glyphs.html which is enabled by default
