### ISSUE TITLE
Using Unix Domains multiplexing makes Wezterm lags

### ISSUE THREAD

**Issue by pengux** [wez/wezterm#2656] opened 2022-10-20 18:44 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Sway

### WezTerm version

20220905-102802-7d4b8249

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When using this configuration:

```
return {
  unix_domains = {
    {
      name = 'unix',
    },
  },
  default_gui_startup_args = { 'connect', 'unix' },
}
```

when typing and holding a key for example, the typing lags behind and for example does not stop immediately when releasing the key. This does not happen if not using the Unix Domains multiplexing.

### To Reproduce

Add the above configuration to use Unix Domain multiplexing, then hold a key and check the printing of characters on screen. Compare with using wezterm without multiplexing.

### Configuration

```
return {
  unix_domains = {
    {
      name = 'unix',
    },
  },
  default_gui_startup_args = { 'connect', 'unix' },
}
```

### Expected Behavior

For wezterm not to lag when using multiplexing

**Comment by wez** [comment] 2022-10-22 04:03
essentially a duplicate of https://github.com/wez/wezterm/issues/2503

**Closed by wez** 2022-10-22 04:03 UTC
Labels: bug, multiplexer
