### ISSUE TITLE
Unix domain interferes with ScrollToPrompt

### ISSUE THREAD

**Issue by brandonchinn178** [wez/wezterm#4120] opened 2023-08-09 04:56 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230806-225328-bf172634

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Adding the following in `wezterm.lua` causes my ScrollToPrompt key binding to stop working:
```lua
return {
  ...

  unix_domains = {
    {
      name = 'unix',
    },
  },
  default_gui_startup_args = { 'connect', 'unix' },
}
```

With this new configuration commented out, I can use the ScrollToPrompt binding to jump to the previous command, but with it enabled, I can't.

### Configuration

```
return {
  unix_domains = {
    {
      name = 'unix',
    },
  },
  default_gui_startup_args = { 'connect', 'unix' },
}
```

**Comment by kaddkaka** [comment] 2023-08-09 11:54
I experience the same behavior on Ubuntu 22.04 (wezterm version: 20230806-225328)

My key binding is `SHIFT + UpArrow`.

**Comment by wez** [comment] 2023-08-09 13:05
Duplicate of https://github.com/wez/wezterm/issues/2880

**Closed by wez** 2023-08-09 13:05 UTC
Labels: bug

**Comment by brandonchinn178** [comment] 2023-08-09 15:00
Weird... I definitely searched for ScrollToPrompt
