### ISSUE TITLE
[BUG] Text weight affects the text color of highlights.

### ISSUE THREAD

**Issue by aarondill** [wez/wezterm#4492] opened 2023-10-26 16:27 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

AwesomeWM w/Picom

### WezTerm version

20231017-091526-fec90ae0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When selecting text, lighter font weights will result in lighter text fg, despite the actual setting.

Thin:
![2023-10-25_17-20_1](https://github.com/wez/wezterm/assets/117116764/e268e1bf-de35-4c6c-a7b5-db619088910f)

ExtraBlack:
![2023-10-25_17-20](https://github.com/wez/wezterm/assets/117116764/2e1b09f1-5122-4c8c-a51a-41ac5c5cb22c)

Note: this affects (anywhere?) the text background is set, including `less`'s messages: (look at the bottom)
![2023-10-25_14-32](https://github.com/wez/wezterm/assets/117116764/6bbe7698-31a1-4388-9b01-225962552bdc)

### To Reproduce

1. Use the below configuration
2. Double click to select a line of text
3. Notice light-grey (impossible to read) text, despite `selection_fg = "black"`
4. Replace `"Thin"` with `"ExtraBlack"`
5. Reload config (close/open or use button in panel)
6. Double click to select a line of text
7. Notice correct black text color.

### Configuration

```lua
local wezterm = require("wezterm")
return {
  font = wezterm.font_with_fallback({
    "JetBrains Mono", -- <built-in>, BuiltIn
  }, { weight = "Thin" }), --- Try ExtraBlack to fix it. Though, the font size is now wrong.
  colors = {
    -- the foreground color of selected text
    selection_fg = "black",
    -- the background color of selected text
    selection_bg = "#fffacd",
  },
}
```

### Expected Behavior

The text color should always be black, as that's what's set.

### Logs

Debug Overlay
wezterm version: 20231017-091526-fec90ae0 x86_64-unknown-linux-gnu
Window Environment: X11 awesome
WebGPU: name=Mesa Intel(R) Xe Graphics (TGL GT2), device_type=IntegratedGpu, backend=Gl, vendor=32902, device=0
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit

### Anything else?

I discovered this problem with @Danielkonge in the comments of #4343

The stable release's `"Regular"` font weight seems to correspond to the nightly's `"Thin"`. Was this an intentional change?

**Comment by aarondill** [comment] 2023-10-26 16:30
Quoting @Danielkonge:

> Yes, this seems to be the problem and an actual bug that you can make an issue for. I also have this effect of making the text thinner when selecting it when using `selection_fg = 'black'`. But it is a weird bug, it doesn't seem to have this behavior with white?
> 
> <img alt="Screenshot 2023-10-26 at 00 26 26" width="197" src="https://user-images.githubusercontent.com/7075380/278163006-0ebc03dd-0a2e-401c-bfc8-e43068fef654.png"> <img alt="Screenshot 2023-10-26 at 00 26 49" width="199" src="https://user-images.githubusercontent.com/7075380/278163066-5db423b0-cc4b-4976-958e-677b77511100.png">

**Comment by aarondill** [comment] 2023-10-26 16:34
More Photos: 
top is "Regular", bottom is "Thin":
![2023-10-25_16-50](https://github.com/wez/wezterm/assets/117116764/05cbb1b9-6687-4ae5-9d6d-8a33572b510c)
Completely unreadable (Thin):
![2023-10-25_16-48](https://github.com/wez/wezterm/assets/117116764/01e685ad-6bc3-46bd-8c05-eb4f89e82fa2)


Left: Thin, Right: Regular:
![2023-10-25_14-18](https://github.com/wez/wezterm/assets/117116764/ed354ab1-80f9-4545-8fa3-f5b421a02d6e)

**Comment by wez** [comment] 2023-11-04 14:19
Perhaps this is really a duplicate of either of:
* https://github.com/wez/wezterm/issues/3774
* https://github.com/wez/wezterm/issues/3032

**Comment by Danielkonge** [comment] 2023-11-04 17:45
Not OP, but I also saw an issue like this. 

I couldn't see a difference with `config.freetype_load_flags = 'NO_HINTING'`, but I can barely see a difference with `config.front_end = "WebGpu"` vs. `config.front_end = "OpenGL"`. The ones including the `s` at the split are `WebGpu` and the ones excluding it are `OpenGL`:

<img width="86" alt="Screenshot 2023-11-04 at 18 39 51" src="https://github.com/wez/wezterm/assets/7075380/99d0211f-4fa6-4354-9b06-080556180125">

<img width="91" alt="Screenshot 2023-11-04 at 18 40 18" src="https://github.com/wez/wezterm/assets/7075380/7d1c4e0b-f97e-4b96-aac1-a0c73582f46a">

<img width="89" alt="Screenshot 2023-11-04 at 18 41 09" src="https://github.com/wez/wezterm/assets/7075380/700695a7-943f-40cd-a10c-2d6ad097e6fd">

<img width="87" alt="Screenshot 2023-11-04 at 18 41 38" src="https://github.com/wez/wezterm/assets/7075380/5462bdf2-71ea-496b-b98d-ad456978f54e">

Though I still think black looks thinner than white. 

On another note: I once in a while get a single character misaligned (happens rarely, so it is hard to reproduce), do you think `config.freetype_load_flags = 'NO_HINTING'` could help with this? (I will try setting it for a little and see if it reoccurs.)

**Comment by wez** [comment] 2023-11-04 23:06
re: `NO_HINTING`, yeah, I think it will help, and that I should probably make that the default

**Comment by aarondill** [comment] 2023-11-05 04:40
It does seem like this might be a duplicate of #3032, however, that implies that `front_end = "OpenGL"` would fix this, while I'm still experiencing this no matter the value of `front_end`.

**Closed** 2024-02-05 05:18 UTC
Labels: bug
