### ISSUE TITLE
Virus in Windows build

### ISSUE THREAD

**Issue by danielfaust** [wez/wezterm#5434] opened 2024-05-17 10:16 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### Which Wayland compositor or X11 Window manager(s) are you using?

When I download the Windows build either from [GitHub directly](https://github.com/wez/wezterm/releases/download/20240203-110809-5046fc22/WezTerm-windows-20240203-110809-5046fc22.zip) [0] or from [wezfurlong.org](https://wezfurlong.org/wezterm/install/windows.html#installing-on-windows) [1] then Chrome hints at "Suspicious download blocked". I proceeded to download it anyway, which then got marked as "Virus found" by Chrome. As soon as it appeared on the filesystem, Windows Defender blocked and deleted the file.

After telling Defender to allow the file and re-downloading it, I uploaded it to VirusTotal, which found that `24/68 security vendors and no sandboxes flagged this file as malicious` [2]

[WezTerm-windows-20240203-110809-5046fc22.zip.sha256](https://github.com/wez/wezterm/releases/download/20240203-110809-5046fc22/WezTerm-windows-20240203-110809-5046fc22.zip.sha256) contains `57e5d03b585303d81e8b8e96d1230362852eb39aca92b3b29c7a42cfb82f9ac4  WezTerm-windows-20240203-110809-5046fc22.zip
` which matches the sha256 on VirusTotal.

I will report this to GitHub.

[0] https://github.com/wez/wezterm/releases/download/20240203-110809-5046fc22/WezTerm-windows-20240203-110809-5046fc22.zip

[1] https://wezfurlong.org/wezterm/install/windows.html#installing-on-windows

[2] https://www.virustotal.com/gui/file/57e5d03b585303d81e8b8e96d1230362852eb39aca92b3b29c7a42cfb82f9ac4

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Contains Virus.

### Configuration

None

**Comment by akthe-at** [comment] 2024-05-17 13:50
This is a duplicate of #5074 related issues. Specifically read @wez  response [here](https://github.com/wez/wezterm/issues/5074#issuecomment-1974922875)

**Comment by wez** [comment] 2024-05-17 14:08
Duplicate of #5074

**Closed by wez** 2024-05-17 14:08 UTC
Labels: bug
