### ISSUE TITLE
Losing selection when text cursor is on the same line

### ISSUE THREAD

**Issue by kappa** [wez/wezterm#644] opened 2021-04-05 08:15 UTC
## Describe the bug

I cannot pinpoint the right set of actions yet. But it is so annoying that I decided to write this down anyway.
When I select some text with my mouse anywhere in the window, the selection is relatively persistent. It may stay there for a long time while I am working in a different part of the window. Sometimes it survives when the text underneath changes, sometimes doesn't.

When I move cursor to one of the lines with selected text, the selection almost instantly disappears. If I select on the same line as my text cursor is on, the selection almost always goes away in a fraction of a second. Sometimes it is removed even before I finish dragging the mouse to select. Sometimes it is removed when I type something on that line. The most frustrating thing is that it does not always happen. The selection can live for one second or for several with the same text and cursor movements.

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210404-112810-b63a949d
 - The active keyboard layout name: ENG

## To Reproduce

Case 1:
1. open an empty buffer in vim; type "foo"
2. select "foo" with the mouse
3. type "bar"
4. the selection over "foo" disappears. (sometimes when I type "b", sometimes a couple of characters later)

Case 2:
1. run "nano ~/.wezterm.lua"
2. select a word in the middle of the screen (not on the first line) with the mouse
3. move the text cursor down line by line
4. when it passes the line with the selection, the selection disappears.

## Configuration

wezterm.lua only has hyperlinking rules.

## Expected behavior

I expect the selection to be persistent unless the text content of it changes in any way. Redrawing the text in a different style should not remove the selection either.

## Screenshots

![Peek 2021-04-05 01-09](https://user-images.githubusercontent.com/47310/113552903-b5faf080-95ab-11eb-84a9-654952fe9867.gif)

**Comment by wez** [comment] 2021-04-05 16:22
The visual indication of the selection is cleared if it intersects a line that is marked dirty; in other words, if the application(s) in the terminal change something on one of the lines that holds the selection, it is cleared.

The visual selection range is maintained in the GUI as simply the start and end range in the scrollback+viewport.  The GUI only looks at the content of the selection when [CompleteSelection](https://wezfurlong.org/wezterm/config/lua/keyassignment/CompleteSelection.html) or [CompleteSelectionOrOpenLinkAtMouseCursor](https://wezfurlong.org/wezterm/config/lua/keyassignment/CompleteSelectionOrOpenLinkAtMouseCursor.html) actions are triggered, and only then to send the selection at that moment to the appropriate clipboard location.

Since there is no historical content for a given line (the only "history" is when a line moves into scrollback and becomes immutable), the GUI cannot diff lines to reason about what exactly changed.  All it knows is that something intersecting it was changed, and rather than show a nonsensical range, wezterm clears the range from the screen.

Note that the clipboard contents are not cleared as part of clearing the range.

Also note that reading data from the clipboard is a complex multi-step IPC operation that cannot complete in the context of the GUI render loop, so it's not a simple case of "just" reading the clipboard to compare things!

What you described sounds like it is working as designed, but you mentioned that sometimes it doesn't clear: I think that may the real bug here.  If you can find a way to reproduce that, I would be grateful!

**Comment by kappa** [comment] 2021-04-07 04:39
Thanks for the explanation. While I am thinking about why I expect a different behavior, I can certainly demonstrate the situation when it doesn't clear.

This is nano:
![Peek 2021-04-06 21-36](https://user-images.githubusercontent.com/47310/113811160-8de0ce00-9720-11eb-8347-2fe106924cef.gif)

**Comment by wez** [comment] 2021-04-10 02:55
The under-invalidation issue is resolved, so I'm going to close this issue.  Thanks for the easy repro!

**Closed by wez** 2021-04-10 02:55 UTC
Labels: bug

**Comment by kappa** [comment] 2021-06-03 06:34
Wez, I was able to root cause my original complain. The culprit is "byobu" which does frequent redraws of the line with the cursor, apparently. I'll attach the video to demonstrate the current behaviour.

https://user-images.githubusercontent.com/47310/120598327-fedbf380-c3fa-11eb-9b61-5551b009b1d3.mp4

**Comment by kappa** [comment] 2021-06-03 06:39
I am only pressing the mouse button once in each line and then dragging slowly side to side. The line with the cursor constantly resets the selection.
I don't know if you are interesting in looking into this since "byobu" isn't really very popular these days. But I do not see this behaviour in other terminal emulators, so fixing/changing this might make wezterm more compatible in general.

You decide if you want to reopen the issue.

**Comment by wez** [comment] 2021-06-03 06:42
I wonder if what you're seeing was resolved by https://github.com/wez/wezterm/commit/2e924c9627fba2178155bdf2177eda84e1daf99a 
Would you mind trying the nightly build to see?

**Comment by wez** [comment] 2021-06-03 06:43
(may not be applicable if that application isn't using mouse reporting)

**Comment by kappa** [comment] 2021-06-03 06:46
I have just tried nightly AppImage and it still reproduces.

**Comment by wez** [comment] 2021-06-17 15:04
From your video, you can see that the selection is cleared whenever the GHz status item changes; I suspect that byobu is repainting the whole screen when it does that and that marks the lines as dirty even though they haven't really changed.

I don't see a simple way to resolve this but will keep it in mind!

**Comment by kappa** [comment] 2021-06-20 21:45
I imagine in that case the selection would clear anywhere on the screen. I tried to demonstrate on video (from 0:23) that it only happens on the line where the cursor is located now.

**Comment by kappa** [comment] 2021-08-17 01:18
@wez This issue seems to be gone in 20210814!

**Comment by wez** [comment] 2021-08-17 01:57
I think 80d261977f9edfff3ffb0b49c0688f5b8e932a83 (and the couple of commits that enabled it, mainly eae327efccc5e8de25c1fdafe438f802af185afe) fixed it, but I forgot to look up this issue and mention it when I wrote up that commit message!
