### ISSUE TITLE
Mouse bindings not working anymore when an app intercepts the mouse

### ISSUE THREAD

**Issue by ipkiss42** [wez/wezterm#2411] opened 2022-08-15 12:24 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20220807-113146-c2fee766

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When a program which intercepts mouse actions is running, all the WezTerm default mouse bindings (with the Shift key held) are inactive. The intercepted mouse actions (without Shift) are working fine, though. The key bindings are also working fine (without Shift) when there is no app intercepting mouse actions.

For example, holding the Shift key and trying to select, paste or open a URL using the mouse do not work anymore in a (remote) tmux session.

I tried various WezTerm versions to find out when the regression happened. It still worked in 20220624-141144-bd1b7c5d, but was broken already in 20220807-105216-608750d5. There was no pre-built Windows binary between the two versions for me to try, so I cannot be more precise than that. Hopefully it will be enough to identify the regression.

### To Reproduce

1. Open WezTerm
2. Ssh to a remote machine
3. Open an app which intercepts the mouse (e.g. vim with mouse support, tmux session, etc) on that machine
4. Try Shift+(LeftClick & Drag) for selecting test, or Shift+MiddleClick for pasting, or Shift+Click for opening a URL

### Configuration

I have a minimal config file, only because middle-click is not easy to do on my laptop (so I used right-click for pasting).
I could reproduce the selection issue with no config file.

```lua
local wezterm = require 'wezterm';

return {
    mouse_bindings = {
        {
            event={Down={streak=1, button="Right"}},
            mods="NONE",
            action="PastePrimarySelection",
        },
    },
}
```

### Expected Behavior

I expect that it works as it used to, e.g. in version 20220624-141144-bd1b7c5d :)

### Logs

After trying some copy-paste in vim:

```
Debug Overlay
wezterm version: 20220807-113146-c2fee766
OpenGL version: Intel(R) UHD Graphics 620 4.5.0 - Build 27.20.100.8190
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
14:05:59.764 WARN wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
14:06:15.511 WARN wezterm_term::terminalstate > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
14:16:37.951 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
14:16:37.994 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: "0%m"
14:16:49.554 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
14:16:49.554 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
14:22:52.516 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
14:22:52.560 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: "0%m"
```

**Comment by wez** [comment] 2022-08-16 14:00
Duplicate of https://github.com/wez/wezterm/issues/2389.
which is already fixed in the nightly download

**Closed by wez** 2022-08-16 14:00 UTC
Labels: bug
