### ISSUE TITLE
Cursor hiding in Wayland

### ISSUE THREAD

**Issue by hgaiser** [wez/wezterm#3334] opened 2023-03-23 09:53 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Gnome

### WezTerm version

wezterm 20230320-124340-559cb7b0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

Moving the cursor after clicking in Wezterm and typing doesn't make it reappear.

### To Reproduce

1. Click with the mouse inside the Wezterm window.
1. Press Shift or some other key, the cursor should be hidden.
1. Move the cursor, it doesn't reappear until it leaves the window.

### Configuration

no config

### Expected Behavior

I expect the cursor to reappear after moving it.

### Anything else?

Related PR: https://github.com/wez/wezterm/pull/2977

[Screencast from 2023-03-23 10-59-43.webm](https://user-images.githubusercontent.com/716138/227168757-3fbfff59-0c92-4871-8880-13b1cf47f321.webm)

**Comment by VarLad** [comment] 2023-03-23 17:54
Hard to reproduce on my side, but can confirm that this often happens with me as well (on Wayland)

**Comment by bagel897** [comment] 2023-03-23 21:43
Can confirm

**Comment by jmbaur** [comment] 2023-03-23 23:02
I cannot reproduce this with a few different wayland compositors (sway and river), but I have not tried out gnome/mutter.

**Comment by jalil-salame** [comment] 2023-04-02 21:10
I can reproduce this issue on NixOS unstable running Sway, by setting the GTK/X11 cursor/cursor theme it fixed itself.

That might cause issues reproducing it: try using a fresh install of a distro with few defaults (Arch/NixOS minimal).

**Comment by Arjun31415** [comment] 2023-04-06 14:49
> I can reproduce this issue on NixOS unstable running Sway, by setting the GTK/X11 cursor/cursor theme it fixed itself.
> 
> That might cause issues reproducing it: try using a fresh install of a distro with few defaults (Arch/NixOS minimal).

I keep getting this error -
````
20:17:40.859  ERROR  window::os::wayland::pointer > Unable to set cursor to arrow: cursor not found
20:17:40.859  ERROR  window::os::wayland::pointer > Unable to set cursor to arrow: cursor not found
````
further, previously i was using a catpuccin cursor theme and now  i changed my cursor theme to Adwaita, yet and it does not resolve itself.

If it might help, I am using Hyprland

**Comment by feathecutie** [comment] 2023-04-16 12:54
This issue also happened to me in conjunction with various error messages mentioning `cursor not found`. Setting the cursor theme, either via the environment variable `XCURSOR_THEME` or via the lua config option `xcursor_theme`, resolved both the cursor hiding issue and the error messages.


The following are just some thoughs and research about possibly fixing this issue on wezterm's side without requiring user action, feel free to disregard:

Since it seems like this bug mainly stems from either no cursor theme being set or the cursor theme being set to a theme that is not currently installed, it might be beneficial for wezterm to query the icon theme via other sources instead of just the config option and the environment variable ([as is currently the case?](https://github.com/wez/wezterm/blob/6ec11393d5ae33c87b4a6ce7fe5f257dffd00021/window/src/os/wayland/pointer.rs#L239
)).
[The Arch wiki mentions different mechanisms that platforms configure the cursor theme with](https://wiki.archlinux.org/title/Cursor_themes#Configuration), but none of these seem cross-platform enough to be useful for all window managers and desktop environments.
On Gnome, the cursor theme could e.g. be queried using [gsettings/dconf](https://wiki.archlinux.org/title/Cursor_themes#GNOME) or [Gtk.Settings:gtk-cursor-theme-name](https://docs.gtk.org/gtk4/property.Settings.gtk-cursor-theme-name.html), but this would not necessarily resolve anything on WMs like Sway or Hyprland.

**Comment by Arjun31415** [comment] 2023-04-16 13:57
My Xcursor theme env variable is set though. 
```
echo $XCURSOR_THEME
Catppuccin-Mocha-Green
```
It does not work with Adwaita also

**Comment by wez** [comment] 2023-04-16 14:12
FWIW, I use this when I run under wayland/gnome:

`~/.config/wezterm/wayland_gnome.lua`:

```lua
local wezterm = require 'wezterm'
local mod = {}

local function gsettings(key)
  return wezterm.run_child_process({"gsettings", "get", "org.gnome.desktop.interface", key})
end

function mod.apply_to_config(config)
  if wezterm.target_triple ~= "x86_64-unknown-linux-gnu" then
    -- skip if not running on linux
    return
  end
  local success, stdout, stderr = gsettings("cursor-theme")
  if success then
    config.xcursor_theme = stdout:gsub("'(.+)'\n", "%1")
  end

  local success, stdout, stderr = gsettings("cursor-size")
  if success then
    config.xcursor_size = tonumber(stdout)
  end

  config.enable_wayland = true

  if config.enable_wayland and os.getenv("WAYLAND_DISPLAY") then
    local success, stdout, stderr = gsettings("text-scaling-factor")
    if success then
      config.font_size = (config.font_size or 10.0) * tonumber(stdout)
    end
  end

end

return mod
```

then in my main config file I pull it in like this: (See: [Making your own lua modules](https://wezfurlong.org/wezterm/config/files.html#making-your-own-lua-modules))

```lua
local wezterm = require 'wezterm'
local config = {}
if wezterm.config_builder then
   config = wezterm.config_builder()
end

local wayland_gnome = require 'wayland_gnome'
wayland_gnome.apply_to_config(config)

return config
```

This obviously assumes gnome, and thus isn't suitable for non-gnome compatible environments.

**Comment by Arjun31415** [comment] 2023-04-19 16:02
Ok, I think i know how to fix my issue. Few cursor themes (read catpuccin) does not have xterm.png or whatever image format [ref](https://github.com/catppuccin/cursors/tree/main/src/Catppuccin-Frappe-Flamingo-Cursors). Whereas [Adwaita](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/tree/master/src/cursors/pngs/32x32) has ( see there is a xterm.png file present).  Instead, catpuccin has a [default.svg](https://github.com/catppuccin/cursors/blob/main/src/Catppuccin-Frappe-Flamingo-Cursors/default.svg)

Now in here it is being set to xterm by default https://github.com/wez/wezterm/blob/db720bd78cad6ccd1d6bcfadf63df05c7ba32313/window/src/os/wayland/window.rs#L1115

So there are two possibilities, 
1. I can take it up with catpuccin repo to include a xterm image file which could be a softlink to the default one
2. The other is fixing it here, because i use kitty too which does not have this issue with the catpuccin cursor

**Comment by wez** [comment] 2023-04-19 17:31
If the issue is really that your chosen theme doesn't have a full set of icons, then 048e8dd1bac2f680b223039e4c916050c52f91ff should help with that.

That should show up in nightly builds within the hour.

**Comment by lnicola** [comment] 2023-04-19 17:40
I'm seeing what's reported in the original comment -- the mouse cursor disappears when I press shift, at least in `htop`. I don't think this is related to the cursor theme. I'm on Adwaita FWIW.

**Comment by wez** [comment] 2023-04-19 17:43
The mouse cursor is supposed to hide when you press a key. It should reappear when you move the mouse; that's the behavior that I see on all the systems that I use.

**Comment by hgaiser** [comment] 2023-04-19 17:45
> The mouse cursor is supposed to hide when you press a key. It should reappear when you move the mouse; that's the behavior that I see on all the systems that I use.

Is there anything I can do to help debug this issue? As per my comment https://github.com/wez/wezterm/issues/3334#issuecomment-1485015434, changing that code helps for me, while without it the cursor does not reappear when I move the mouse.

I'm using that for 3 weeks now and I am happy with how it works, though I have no clue if it is correct or not.

**Comment by wez** [comment] 2023-04-19 17:49
@hgaiser Oh, I missed that. Wayland is a bit picky about the serial, so I would have expected the opposite behavior to be true!

We can try taking out the serial in the nightly and see what people say about it.

**Comment by hgaiser** [comment] 2023-04-19 17:50
Would you like a PR for that change?

**Comment by wez** [comment] 2023-04-19 17:58
Thanks; I've applied the equivalent of that to `main` in e204f8ba494498836014bfeaf3ae94adb5ac5d86

**Comment by hgaiser** [comment] 2023-04-19 17:58
Great, thanks :+1: . Hope it solves other peoples problems too.

**Comment by Arjun31415** [comment] 2023-04-20 09:39
Ok this works for me with Adwaita, sadly not with catppuccin, maybe that is a different issue. Will recheck.

**Comment by chrysos349** [comment] 2023-04-20 10:35
Neither of the commits above (048e8dd1bac2f680b223039e4c916050c52f91ff and e204f8ba494498836014bfeaf3ae94adb5ac5d86) fixed the issue for me.

I still had these errors:
```
ERROR  window::os::wayland::pointer > set_cursor: Unable to set cursor to arrow: cursor not found, Unable to set cursor to 'default': cursor not found
ERROR  window::os::wayland::frame   > Unable to set cursor to left_ptr: cursor not found
```
What fixed my problem of the invisible cursor was https://github.com/wez/wezterm/issues/3334#issuecomment-1510372732. Thanks, @feathecutie!

>  either via the environment variable XCURSOR_THEME or via the lua config option xcursor_theme, resolved both the cursor hiding issue and the error messages.

**Comment by lnicola** [comment] 2023-04-20 12:16
Thanks, this is fixed for me.

> The mouse cursor is supposed to hide when you press a key. It should reappear when you move the mouse

This is less nice than in other terminal emulators. It disappears on `Ctrl-Shift` in WezTerm, but not in GNOME Terminal. The latter also doesn't hide the curson on `Ctrl-Shift-C` or `Ctrl-Shift-V`. I can file a new issue, if you're open to tweaking this.

**Comment by wez** [comment] 2023-04-20 14:14
@lnicola please file a separate issue for that

**Comment by wez** [comment] 2023-04-20 14:15
@chrysos349 what did you set the theme to?

**Comment by chrysos349** [comment] 2023-04-20 14:18
@wez I have `Yaru `and `Adwaita ` installed. Either of them solved the issue.

**Comment by wez** [comment] 2023-04-20 14:24
@chrysos349 the way that wezterm (and other software) works is that if you don't specify a theme, `default` is assumed. Most systems have a symlink or similar that makes `default` point to whatever the main theme is on the system.  It sounds like that might be missing from your system.

**Comment by Arjun31415** [comment] 2023-04-21 07:48
> Ok this works for me with Adwaita, sadly not with catppuccin, maybe that is a different issue. Will recheck.

I have figured out the problem and the solution. 
So, I have set the `XCURSOR_THEME` using gsettings -
```sh
echo $XCURSOR_THEME
Catppuccin-Mocha-Maroon
```
This works in all other GUI applications including browser, kitty, etc.
Now, I tried the same by setting `config.xcursor_theme` in wezterm config, but to no avail.

The issue is that in `/usr/share/icons` the folder is saved as Catppuccin-Mocha-Maroon-**Cursors**.  
I changed my config to reflect that 
```lua
local wezterm = require("wezterm")
return {
-- other setttings
    xcursor_theme="Catppuccin-Mocha-Maroon-Cursors"

}
```
and now it works !
I'm not sure what the exact issue is and why it is unable to detect the cursor theme even though the index file gives the correct name -
```
[Icon Theme]
Name=Catppuccin-Mocha-Maroon
Comment=based on Volantes Cursors
```

**Comment by Arjun31415** [comment] 2023-04-22 03:37
I see, then this issue can be closed, because mine is no longer related to it. Thank you for your help and quick responses

**Comment by snaggen** [comment] 2023-05-16 05:41
Just tested this with the latest nightly: 20230515-073311-76406e84
It still doesnt fix the mouse pointer issue described in #2995 , where the mouse pointer stays hidden when split panes is used. To reproduce that case you just do:

1. Split the terminal to get side by side panes.
1. Move the mouse over the right pane and click.
1. Type in the right pane so the mouse is hidden
1. Move the mouse to make it vissible. Now it should be visible but it is not.

So, this issue is not fully fixed in nightly, and should probably not have the "fixed-in-nightly" label.

**Comment by wez** [comment] 2023-05-16 13:41
@snaggen please open a separate issue!

**Closed** 2023-07-12 19:00 UTC
Labels: bug, Wayland, fixed-in-nightly

**Comment by wez** [comment] 2024-01-04 19:24
For those landing here from search engines: see https://github.com/wez/wezterm/issues/1742#issuecomment-1075333507 for a way to explicitly apply GNOME's settings to your wezterm mouse cursor
