### ISSUE TITLE
default config , http://127.0.0.1:8888/demo/ can't click

### ISSUE THREAD

**Issue by usrtax** [wez/wezterm#3147] opened 2023-02-24 02:38 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20221119-145034-49b9839f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

default config , http://127.0.0.1:8888/demo/ can't click

### Configuration

local wezterm = require 'wezterm'

return {
  font = wezterm.font_with_fallback {
    {
      family='FiraCode Nerd Font Mono',
      weight="Bold"
    },
    {
      family='Noto Sans CJK SC',
      weight="Bold"
    }
  },
  window_close_confirmation="NeverPrompt",
  font_size = 16,
  selection_word_boundary = '{}[]()"\'=`,;: ❯│',
  hide_tab_bar_if_only_one_tab = true
}

**Comment by wez** [comment] 2023-02-24 02:53
Duplicate of https://github.com/wez/wezterm/issues/928

**Closed by wez** 2023-02-24 02:53 UTC
Labels: bug
