### ISSUE TITLE
Nerd-Fonts are rendered incorrectly

### ISSUE THREAD

**Issue by AlexKurisu** [wez/wezterm#1609] opened 2022-02-01 10:34 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20220131-214448-fb135049

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Nerd-Fonts symbols are rendered incorrectly (see screenshot). Fonts look fine in other terminal emulators
![image](https://user-images.githubusercontent.com/60626727/151952485-5ad72590-30f5-450e-8d88-dd715a5a2b36.png)

### To Reproduce

Run vim/neovim with nerd-tree, airline and vim-devicons installed and enabled for each of them.

### Configuration

```lua
local w = require 'wezterm';

-- A helper function for my fallback fonts
function font_with_fallback(name, params)
    local names = {name, "Symbols Nerd Font", "Noto Color Emoji"}
--    local names = {name, "Noto Color Emoji"}
    return w.font_with_fallback(names, params)
end

return {
    freetype_load_target = "HorizontalLcd",
    freetype_render_target = "HorizontalLcd",
    warn_about_missing_glyphs = false,
    use_cap_height_to_scale_fallback_fonts = true,

    font = font_with_fallback("Iosevka Fixed"),
    font_rules = {
        -- Italic
        {
            italic = true,
            font = font_with_fallback({
                family = "Iosevka Fixed", italic = true
            }),
        },
        -- Bold Italic
        {
            italic = true, intensity = "Bold",
            font = font_with_fallback({
                family = "Iosevka Fixed", weight = "Bold", italic = true
            }),
        },
        -- Bold
        {
            intensity = "Bold",
            font = font_with_fallback({
                family = "Iosevka Fixed", weight = "Bold"
            }),
        },
    },
    font_size = 12.0,
    force_reverse_video_cursor = true,
    colors = {
        foreground = "white",
        background = "black",
        cursor_border = "gray90",
        ansi =      { "black",  "red3", "green3", "yellow3", "blue2",   "magenta3", "cyan3", "gray90" },
        brights =   { "gray50", "red",  "green",  "yellow",  "#5c5cff", "magenta",  "cyan",  "white"  },
    },

    check_for_updates = false,
    swallow_mouse_click_on_pane_focus = true,
    exit_behavior = "Close",
    --default_prog = { "zsh", "-" },
    --use_resize_increments = true,
    enable_kitty_graphics = true,
    use_fancy_tab_bar = false,
    tab_max_width = 24,
    window_padding = {
        left = 0,
        right = 0,
        top = 0,
        bottom = 0,
    },

    disable_default_key_bindings = true,
    keys = {
        { key = "c",          mods = "CTRL|SHIFT", action = w.action{ CopyTo = "Clipboard" }},
        { key = "v",          mods = "CTRL|SHIFT", action = w.action{ PasteFrom = "Clipboard" }},
        { key = "Enter",      mods = "ALT",        action = w.action{ SpawnTab = "CurrentPaneDomain" }},
        { key = "LeftArrow",  mods = "ALT",        action = w.action{ ActivateTabRelative=-1 }},
        { key = "LeftArrow",  mods = "CTRL|ALT",   action = w.action{ MoveTabRelative=-1 }},
        { key = "RightArrow", mods = "ALT",        action = w.action{ ActivateTabRelative=1 }},
        { key = "RightArrow", mods = "CTRL|ALT",   action = w.action{ MoveTabRelative=1 }},

        { key = "r",          mods = "CTRL|SHIFT", action = "ReloadConfiguration" },
    }
}
```

**Comment by wez** [comment] 2022-02-01 14:02
Please describe/highlight what is incorrect about it; I can't tell what the issue is from your screenshot!

**Comment by wez** [comment] 2022-02-01 14:49
Could you narrow this down to the characters that are being printed? Consider using https://github.com/wez/wezterm/blob/main/wt-record or `script` to capture the offending behavior at an 80x24 terminal size.  That will allow me to replay what you're seeing without having to replicate your entire setup.

**Comment by abzcoding** [comment] 2022-02-01 15:17
i have the same issue,
this is when i use https://github.com/wez/wezterm/commit/caf504ee819ac395aec8a7d9af131b75af1f9318
<img width="1506" alt="Screen Shot 2022-02-01 at 6 39 44 PM" src="https://user-images.githubusercontent.com/10992695/151994602-79812c08-799d-4856-9d82-6fadd79db3af.png">

and this is the when i use https://github.com/wez/wezterm/commit/a8aafaebf84412357c60b464baf49ba6fe431936
<img width="1620" alt="Screen Shot 2022-02-01 at 6 47 01 PM" src="https://user-images.githubusercontent.com/10992695/151995952-af7521a7-14e2-436f-8b92-da81c2a77e8a.png">

i'll try to run that script that you mentioned

**Comment by abzcoding** [comment] 2022-02-01 15:36
@wez tyvm! https://github.com/wez/wezterm/commit/af92265ffb214878beadb543bd9e4b74e0bb8a99 fixed the issue for me

**Comment by wez** [comment] 2022-02-01 15:45
Duplicate of #1607

**Closed by wez** 2022-02-01 15:45 UTC
Labels: bug, fixed-in-nightly, waiting-on-op

**Comment by abzcoding** [comment] 2022-02-01 16:45
@wez https://github.com/wez/wezterm/commit/5f2c905db86353040c63ee9335cf69ca9fd5e99c seems to break things again
