### ISSUE TITLE
Fonts are too bold on nightly

### ISSUE THREAD

**Issue by adwaymalhotra** [wez/wezterm#3828] opened 2023-06-05 19:28 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Hyprland on HEAD.

### WezTerm version

20230408-112425-69ae8472 (stable) and 20230530-062729-95e44f21(nightly)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Fonts are very bold in nightly. I tried both the deb and the AppImage.

I tried with the freetype enabled and disabled. The font looks less bold with HorizontalLcd disabled but still not equal to the stable version.
![freetype_custom](https://github.com/wez/wezterm/assets/9569615/f09ce9d1-8c66-4ce0-b0c5-ae8baa6a3e5a)

![freetype_default](https://github.com/wez/wezterm/assets/9569615/fc0ac6af-1335-43cf-aa88-4114c14528b2)

### Configuration

local default_font = {
	{ family = "CaskaydiaCoveNF" },
	-- { family = "IosevkaTermSS08 NF", weight = "Medium", stretch = "Expanded", scale = 1.00 },
}

local font_settings = wz.font_with_fallback(default_font)

return {
	font_size = 10,
	line_height = 1.1,
	font = font_settings,
	freetype_load_target = "Light",
	freetype_render_target = "HorizontalLcd",
}

### Expected Behavior

Fonts should look great as always?

### Logs

// I don't think there's anything relevant but here goes. There was nothing in the CTRL+SHIFT+L screen either.

warning: queue 0x557799d60630 destroyed while proxies still attached:
  wl_display@1 still attached
warning: queue 0x557799d433a0 destroyed while proxies still attached:
  zwp_linux_dmabuf_feedback_v1@45 still attached
warning: queue 0x557799fb4cc0 destroyed while proxies still attached:
  wl_display@1 still attached
warning: queue 0x5577999635b0 destroyed while proxies still attached:
  wl_callback@51 still attached
  zwp_primary_selection_offer_v1@4278190090 still attached
  wl_data_offer@4278190086 still attached
  wl_data_offer@4278190087 still attached
  wl_buffer@46 still attached
  wl_shm_pool@49 still attached
  wl_buffer@53 still attached
  wl_shm_pool@55 still attached
  wl_data_offer@4278190083 still attached
  wl_data_offer@4278190080 still attached
  xdg_wm_base@23 still attached
  wl_surface@22 still attached
  wl_data_device@19 still attached
  wl_pointer@17 still attached
  zwp_text_input_v3@16 still attached
  wl_keyboard@15 still attached
  zwp_primary_selection_device_v1@14 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@13 still attached
  wl_output@12 still attached
  wl_output@11 still attached
  zwp_text_input_manager_v3@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

$XDG_RUNTIME_DIR doesn't seem to contain any logs either.

**Comment by wez** [comment] 2023-06-06 15:26
Likely a duplicate of:
* https://github.com/wez/wezterm/issues/3032

**Comment by adwaymalhotra** [comment] 2023-07-13 11:04
Yes, it seems like the same issue, font rendering is fine with front_end = "OpenGL".

Duplicate of #3032

**Closed** 2023-07-13 11:04 UTC
Labels: bug
