### ISSUE TITLE
1f152 codepoint not found in any fonts on Windows

### ISSUE THREAD

**Issue by lentikr** [wez/wezterm#3546] opened 2023-04-17 13:04 UTC
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20230408-112425-69ae8472

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Some characters cannot be displayed properly.
![1681736565792](https://user-images.githubusercontent.com/95539012/232491962-bac5fee8-f4ef-48f1-b0bd-1da77659e38c.png)

### To Reproduce

1. Use conda to create a virtual environment
2. Switch to the environment

### Configuration

config.font = wezterm.font_with_fallback({ "Hack NFM", "Microsoft YaHei" })

### Expected Behavior

In other terminal, the character can be displayed properly.
![1681736542035](https://user-images.githubusercontent.com/95539012/232491880-dbeddc2d-215a-4bc3-81cf-b61579c206a9.png)

### Anything else?

I used starship.

**Comment by wez** [comment] 2023-04-17 14:14
The logs should have a message explaining what glyph that is and perhaps why no font containing it could be found.
You didn't share them here so I don't know what they say.

The https://github.com/wez/wezterm/issues/new?assignees=&labels=bug&template=bug.yml form has some information on locating the logs, please include them here.

**Comment by lentikr** [comment] 2023-04-17 14:46
In addition, the font file is Hack Regular Nerd Font Complete Mono Windows Compatible.ttf, from [https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip).

**Comment by wez** [comment] 2023-04-17 14:59
See also: https://wezfurlong.org/wezterm/troubleshooting.html#debugging-font-display

**Comment by miah0x41** [comment] 2023-04-24 20:46
Apologies, missed off my version: `WezTerm version 20230408-112425-69ae8472` - I installed via `winget`.

**Comment by wez** [comment] 2023-05-29 23:10
Try setting `WEZTERM_LOG=font=trace` in the environment, then running `wezterm.exe ls-fonts --codepoints 1f152` and share the output; that should show more information about the fonts that wezterm is looking at in order to locate that codepoint.

**Comment by miah0x41** [comment] 2023-05-30 10:38
As requested:

```
wezterm.exe ls-fonts --codepoints 1f152
11:36:14.586  WARN   wezterm_font > No fonts contain glyphs for these codepoints
: \u{1f152}.
Placeholder glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about conf
iguring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
LeftToRight
 0 🅒    \u{1f152}    x_adv=10 cells=1  glyph=.notdef ,0    wezterm.font("JetBra
i
nsMono NF", {weight="Regular", stretch="Normal", style="Normal"})
                                      C:\USERS\ROOT\APPDATA\LOCAL\MICROSOFT\WIND
OWS\FONTS\JETBRAINS MONO REGULAR NERD FONT COMPLETE WINDOWS COMPATIBLE.TTF, Dire
ctWrite
```

Screenshot:

![image](https://github.com/wez/wezterm/assets/99686292/191ca287-a43a-4f31-8275-127405c28c14)

**Comment by wez** [comment] 2023-05-31 14:58
Sorry, that should be `WEZTERM_LOG=wezterm_font=trace`

**Comment by miah0x41** [comment] 2023-05-31 17:40
Understood; please see the attached log file with `TRACE` level log for fonts:
[wezterm-gui.exe-log-23256.txt](https://github.com/wez/wezterm/files/11617319/wezterm-gui.exe-log-23256.txt)

**Comment by wez** [comment] 2023-06-01 14:58
`WEZTERM_LOG=wezterm_font=trace` should be set while running `wezterm.exe ls-fonts --codepoints 1f152` rather than when running the gui

**Comment by miah0x41** [comment] 2023-06-01 16:31
I'm sorry - I'm not sure I know how to do that exactly.

Are these the correct steps?

1. Open `cmd.exe`.
2. Enter `set WEZTERM_LOG=wezterm_font=trace`
3. Then run `wezterm.exe ls-fonts --codepoints 1f152`

If so, please see new log.

[wezterm-gui.exe-log-18560.txt](https://github.com/wez/wezterm/files/11627515/wezterm-gui.exe-log-18560.txt)

**Comment by kbrs-miaha** [comment] 2023-06-13 11:49
Hi, was the log file I provided insufficient? It was provided 12 days ago. There wasn't any feedback. 

Is it possible to keep open?

**Comment by wez** [comment] 2023-06-13 14:22
Sorry; looks like GH automation didn't remove the waiting-on-op label after your most recent update

**Comment by wez** [comment] 2023-08-27 16:57
@miah0x41 The log file indicates that none of the fonts discovered by wezterm include that codepoint.
Part of the fallback processing involves asking the DirectWrite layer to suggest fonts with matching codepoints, and it appears that none were suggested by DirectWrite.

What font actually contains that codepoint on your system?

**Comment by wez** [comment] 2023-08-28 16:01
That codepoint is not in `JetBrainsMono NF`, but is present in some other font on your system.

![image](https://github.com/wez/wezterm/assets/117777/c1fe12ca-28dc-471a-8941-0a9ad320d71e)

**Comment by miah0x41** [comment] 2023-08-28 16:17
So clearly this is beyond my understanding.  I've done the following experiment to try and figure out what it could be using _Windows Terminal_ - it is as you say, the symbol is coming from somewhere else:

This is my default profile, it does state `JetBrainsMono NFM` and it does show the correct symbol:

![image](https://github.com/wez/wezterm/assets/99686292/8f7d223a-276c-4af0-9b59-75555e7afeb7)

If I change font to `JetBrainsMono NF`, it appears to work:

![image](https://github.com/wez/wezterm/assets/99686292/ccf710e4-4b27-48fd-b4d6-bcbcd4b1d5a5)

If I change font to `Lucinda Console`, the python symbol is gone but it does appear to work:

![image](https://github.com/wez/wezterm/assets/99686292/ec2f3773-dc69-4f02-a2be-c7f839bedfa1)

So this confirms the symbol is available through some other means.

Is the `hb-view` app from: https://harfbuzz.github.io/utilities.html?

**Comment by miah0x41** [comment] 2023-08-28 16:24
I'm happy to keep digging except I don't quite know where to go next.

**Comment by jdhang** [comment] 2023-10-23 03:57
hey @miah0x41, I don't know if you were able to resolve this. I did some digging and found that the "🅒" symbol is part of the `PingFang` font. I am on MacOS though and cannot confirm that it will work on Windows. I updated my config file to include that font, specifically `PingFang SC`,  and I was able to see the symbol in wezterm. I hope this helps!

**Comment by bezlant** [comment] 2023-10-23 07:36
I highly recommend this tool to fix your nerd fonts, after the update to nerd fonts v3 everything has been messed up for me and this is the saviour https://github.com/loichyan/nerdfix

**Comment by miah0x41** [comment] 2023-10-23 10:16
> hey @miah0x41, I don't know if you were able to resolve this. I did some digging and found that the "🅒" symbol is part of the `PingFang` font. I am on MacOS though and cannot confirm that it will work on Windows. I updated my config file to include that font, specifically `PingFang SC`, and I was able to see the symbol in wezterm. I hope this helps! ![Screenshot 2023-10-23 at 00 23 19](https://user-images.githubusercontent.com/5394681/277229645-e637752d-1417-4467-8f08-305b4881d4ba.png)

Thanks for resolving. I can confirm this works on my Windows setup.

1) Downloaded font (e.g. [Link](https://github.com/zongren/font/blob/master/PingFang-SC-Regular.ttf))
2) Installed (double click on Windows)
3) Updated config `wezterm.lua`:

```lua
-- abbreviated example
return {
  font = wezterm.font_with_fallback {
    'JetBrainsMono NF',
    'Cascadia Code',
    'JetBrains Mono',
    -- added font
    'PingFang SC',
  },
}
```
4) Reload config and test with `conda activate <environment>`.

**Comment by miah0x41** [comment] 2023-10-23 10:37
@wez - I'm happy to close based on @jdhang suggestion. 

For completeness, I downloaded the latest JetBrainsMono NF today to see if that was an issue and the error arises.  For now, it seems we need `PingFang SC`.

**Comment by bezlant** [comment] 2023-10-24 02:43
@miah0x41 yes, i've use the nerdfix to get all the missing symbols in the nerd fonts.

**Comment by miah0x41** [comment] 2023-10-24 09:48
> @miah0x41 yes, i've used the nerdfix to get all the missing symbols in the nerd fonts.

@bezlant - as far as I can tell, `nerdfix` will identify and replace missing symbols from a project.  That could be a directory or a file.  How do I apply this tool in this instance? What should my target be? I'm not sure where the symbol originates from.

Thanks in advance.

**Comment by bezlant** [comment] 2023-10-24 23:15
@miah0x41 
1. Copy in paste the symbol in to a file, use ```nerdfix fix filename```
2. Get or generate a list of the most popular symbols use nerdfix to get all the missing symbols. (option I've used)

**Comment by miah0x41** [comment] 2023-10-25 12:01
Thanks for the advice. I copied across the two symbols, which don't show properly on the terminal into the attached `test.txt` including an example from the docs to make sure the tool is working.  My expectation is that it will identify all three symbols as needing a fix but the output only shows one symbol (the example from the nerdfix docs).

A follow on question is, should it provide a suitable substitute, where do I put it to make `wezterm` work as expected?

```bash
nerdfix check test.txt

 INFO Check input file from 'test.txt'
note: Found obsolete icon U+F752
  ┌─ test.txt:2:2
  │
2 │  
  │  ^ Icon 'mdi-folder_multiple' is marked as obsolete
  │
  = You could replace it with:
        1. 󰉓 U+F0253 md-folder_multiple
        2. 󱏓 U+F13D3 md-folder_star_multiple
        3. 󰉔 U+F0254 md-folder_multiple_image
        4. 󱑾 U+F147E md-folder_multiple_plus
```

Do you get any suggestions for the first and last symbol?

Example file:
[test.txt](https://github.com/wez/wezterm/files/13165550/test.txt)

**Comment by bezlant** [comment] 2023-10-25 13:10
@miah0x41 Exactly, you get the substitute and pick one from the terminal.
In this case you want to type in 1 and press enter, it will proceed searching for all the other missing symbols in that file and replace them. After that all the missing symbols will be working!

**Comment by bezlant** [comment] 2023-10-25 13:12
<img width="466" alt="Screenshot 2023-10-25 at 20 12 01" src="https://github.com/wez/wezterm/assets/89563512/d79bfcfb-a3c9-492a-a4f9-79e989652a39">

**Comment by bezlant** [comment] 2023-10-26 08:24
Seems like it doesn't.

**Comment by wez** [comment] 2023-11-04 17:01
I'm going to close this as it isn't a wezterm issue, but rather an issue with the fonts installed on the system

**Closed by wez** 2023-11-04 17:01 UTC
Labels: bug, Windows
