### ISSUE TITLE
Powerline rendering issues.

### ISSUE THREAD

**Issue by Anomalocaridid** [wez/wezterm#670] opened 2021-04-09 22:10 UTC
## Describe the bug

On Wezterm, some powerline symbols have imperfections like small lines between them and slight misalignment. 

## Environment (please complete the following information):

 - OS: EndeavourOS Linux X11
 - Version: wezterm 20210405-110924-a5bb5be8

## To Reproduce

Steps to reproduce the behavior.

Use the powerlevel10k plugin with zsh.
My configuration files for each are in the following links: [zsh](https://github.com/Anomalocaridid/dotfiles/blob/master/.zshrc), [powerlevel10k](https://github.com/Anomalocaridid/dotfiles/blob/master/.p10k.zsh).

## Configuration
I am not aware of any relevant code in my wezterm.lua file.

## Expected behavior
I expected my wezterm terminal's prompt to look like my kitty terminal's prompt with no breaks or misalignments between characters.

## Screenshots

My wezterm terminal
![wezterm](https://user-images.githubusercontent.com/29845794/114245341-4ba4d000-995e-11eb-9a87-a9f28e7f1b78.png)

My kitty terminal (it is a different size window, but that is unrelated to the issue.)
![kitty](https://user-images.githubusercontent.com/29845794/114245433-7bec6e80-995e-11eb-8062-109147b46f66.png)

## Additional context

A similar thing appears to happen when I use the text editor kakoune, on which I have configured a powerline status bar plugin.

**Comment by wez** [comment] 2021-04-10 02:50
Duplicate of #584

**Closed by wez** 2021-04-10 02:50 UTC
Labels: bug

**Comment by Anomalocaridid** [comment] 2021-04-10 18:37
Oh sorry, I wasn't aware that that issue was related to Powerline.
