### ISSUE TITLE
Wezterm does not run on WebGPU on Linux X11

### ISSUE THREAD

**Issue by uncomfyhalomacro** [wez/wezterm#4965] opened 2024-02-05 14:52 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

GNOME X11

### WezTerm version

wezterm 20230712.072601.f4abf8fd+git390

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Bug is described to this link https://bugzilla.suse.com/show_bug.cgi?id=1219206

### To Reproduce

1. Run wezterm on X11 on default settings.

### Configuration

no config

### Expected Behavior

Runs on default WebGPU.

### Logs

```
wezterm 06:05:19.451  ERROR  wezterm_gui > running message loop: process_queued_xcb: poll_for_queued_event: X(Match(RequestError { response_type: 0, error_code: 8, sequence: 254, bad_value: 17825801, minor_opcode: 4, major_opcode: 149, pad: 1 }), None); t
```

### Anything else?

Reporter uninstalled wezterm. I still can reproduce the issue though on any X11 session e.g. LeftWM.

**Comment by uncomfyhalomacro** [comment] 2024-02-05 14:53
Workaround is set the backend to OpenGL as described on the bug report. Please clarify.

**Comment by wez** [comment] 2024-02-05 17:57
I don't know what `20230712.072601.f4abf8fd+git390` is. What does `wezterm --version` output?
This sounds like a duplicate of https://github.com/wez/wezterm/issues/4290

**Comment by uncomfyhalomacro** [comment] 2024-02-06 04:18
> I don't know what `20230712.072601.f4abf8fd+git390` is. What does `wezterm --version` output? This sounds like a duplicate of #4290

my bad. `+` means number of commits after. the version is specifically commit 600652583594e9f6195a6427d1fabb09068622a7

**Comment by uncomfyhalomacro** [comment] 2024-02-06 04:24
also yes #4290 is what i mean when i think the issue was very familiar. yeah

**Comment by wez** [comment] 2024-02-06 14:41
OK, let's close this as a duplicate of #4290

**Closed by wez** 2024-02-06 14:41 UTC
Labels: bug
