### ISSUE TITLE
Weird input when exiting Vim immediately after opening it.

### ISSUE THREAD

**Issue by iteemhe** [wez/wezterm#1921] opened 2022-04-26 09:01 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm version: 20220425-222826-7f0b5ab0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

![image](https://user-images.githubusercontent.com/31311090/165262274-d0a71d38-6277-4d95-93a2-a7c0188ce538.png)

### To Reproduce

1. Open Vim
2. Exist Vim immediately after opening, using `:q` or other methods;
3. Press some keys, like `d` on keyboard.
4. Now you can see weird input is inserted to the shell. It can be replicated in `bash` and `zsh`.

I have tried other terminal emulators like xfce4 terminal. I could not replicate this behavior in other terminal emulators.

### Configuration

no config

### Logs

```
04:52:33.240 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-12418
04:52:33.414 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) HD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 22.0.2 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2dd
04:52:36.742 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 0
04:52:38.312 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 0
04:56:06.782 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 1
04:56:06.910 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 1
04:56:07.540 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 1
04:56:07.661 INFO wezterm_gui::termwindow > Ding! (this is the bell) in pane 1
04:57:05.427 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
04:57:05.427 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
04:58:13.780 INFO wezterm_gui::termwindow > OpenGL initialized! Mesa Intel(R) HD Graphics 620 (KBL GT2) 4.6 (Compatibility Profile) Mesa 22.0.2 is_context_loss_possible=false wezterm version: 20220408-101518-b908e2dd
04:58:16.530 WARN wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(2)
04:58:16.552 WARN mux::localpane > unknown DeviceControlMode::Enter EnterDeviceControlMode(params: [], intermediates: [], byte: 'z' 0x7a, ignored_extra_intermediates=false)
04:58:16.553 WARN mux::localpane > unhandled DeviceControlMode::Data 7a z
04:58:16.553 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: "0%m"
04:58:17.752 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
04:58:17.752 WARN wezterm_term::terminalstate::performer > unknown unspecified CSI: ">4;m"
```

**Comment by iteemhe** [comment] 2022-04-26 09:11
It seems like this issue has been fixed in the latest version.

```
wezterm version: 20220425-222826-7f0b5ab0
```

**Comment by wez** [comment] 2022-04-26 12:53
Duplicate of #1850

**Closed by wez** 2022-04-26 12:53 UTC
Labels: bug
