### ISSUE TITLE
WezTerm overwriting $SHELL variable

### ISSUE THREAD

**Issue by LordMZTE** [wez/wezterm#4168] opened 2023-08-19 15:00 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

i3

### WezTerm version

wezterm 20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

When the `$SHELL` variable is set in WezTerm's environment, WezTerm will unset it and populate it with the login shell obtained from `/etc/passwd`, clobbering the environment of the shell process running inside WezTerm.

This happens because [this code](https://github.com/wez/wezterm/blob/main/env-bootstrap/src/lib.rs#L240-L244) deletes the variable, which causes `cmdbuilder::get_shell` to look up the login shell. This then ends up getting saved in `$SHELL` for processes running inside WezTerm.

While this behavior is explained by the fact that people often don't relog after updating their login shell, I believe that it not only makes no sense to work around user error, but also that it's rather uncommon for people to have `$SHELL` set in the environment WezTerm runs in. Those who do probably have a good reason for doing so, which WezTerm currently ignores. This situation is made worse by the fact that this is not fixable by adjusting WezTerm's config either, and thus the only way to currently work around this is to configure every shell which WezTerm might run to "undo" this.

I did not use a nightly build as the code causing this is still present on master.

### To Reproduce

1. Set SHELL to something other than your login shell.
2. Start WezTerm.
3. See that WezTerm will have set SHELL to your login shell.

### Configuration

See [here](https://git.mzte.de/LordMZTE/dotfiles/src/branch/master/.config/wezterm/wezterm.lua.cgt). This is not required as this can be reproduced without a config.

### Expected Behavior

The `$SHELL` variable remains unchanged inside WezTerm.

### Logs

Debug Overlay
wezterm version: 20230712-072601-f4abf8fd x86_64-unknown-linux-gnu
Window Environment: X11 i3
OpenGL: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 4.6.0 NVIDIA 535.98
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
>

**Comment by wez** [comment] 2023-08-20 17:43
This is intended behavior. The bug is that you can't override SHELL via https://wezfurlong.org/wezterm/config/lua/config/set_environment_variables.html, which has now been fixed in `main`.

**Closed by wez** 2023-08-20 17:43 UTC
Labels: bug
