### ISSUE TITLE
after echo $'\xe'  everything is so messed up!

### ISSUE THREAD

**Issue by arashatt** [wez/wezterm#4486] opened 2023-10-24 17:14 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

20230712-072601-f4abf8fd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

please try `echo $'\xe'` in your wezterm!

![Screenshot from 2023-10-24 20-41-13](https://github.com/wez/wezterm/assets/55944526/317a6c5a-e698-4381-a5f8-4659b1cfb585)

### Configuration

no config

**Comment by ninjalj** [comment] 2023-10-27 22:01
Duplicate of #3962

**Comment by wez** [comment] 2023-11-04 14:34
Note that you can use CTRL-SHIFT-P to open the command palette and then choose `Reset the terminal emulation state in the current pane` to get out of that state.

**Comment by wez** [comment] 2023-11-04 14:35
Closing as duplicate of #3962

**Closed by wez** 2023-11-04 14:35 UTC
Labels: bug
