### ISSUE TITLE
wayland CSD maximize controls don't fully maximize the window

### ISSUE THREAD

**Issue by ittayd** [wez/wezterm#2136] opened 2022-06-19 05:03 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20220618-195835-2f073a7d

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Compare this from the 04 version
![image](https://user-images.githubusercontent.com/33328/174466565-3f0517a7-dfa8-4fc3-be9d-a14ef2bd0d35.png)

With this:
![image](https://user-images.githubusercontent.com/33328/174466625-066a10dd-f169-4cc5-8f1b-ddb995ad65c5.png)

In particular, clicking the up carret for full screen mode expands the window right and down, but doesn't make it snap to the upper left corner of the screen

I need to use nightly since the stable version has a bug interpreting the copy_mode key bindings (which I've copy-pasted from the site):
callback error
stack traceback:
        [C]: in function 'wezterm.action'
        [string "/home/ittay/.wezterm.lua"]:13: in main chunk
caused by: while processing an enum of type `KeyAssignment` and value
{"CopyMode": "Close"}
which has allowed variants `ActivateCopyMode`, `ActivateKeyTable`,
`ActivateLastTab`, `ActivatePaneByIndex`, `ActivatePaneDirection`,
`ActivateTab`, `ActivateTabRelative`, `ActivateTabRelativeNoWrap`,
`AdjustPaneSize`, `ClearKeyTableStack`, `ClearScrollback`,
`CloseCurrentPane`, `CloseCurrentTab`, `CompleteSelection`,
`CompleteSelectionOrOpenLinkAtMouseCursor`, `Copy`, `CopyTo`,
`DecreaseFontSize`, `DisableDefaultAssignment`, `EmitEvent`,
`ExtendSelectionToMouseCursor`, `Hide`, `HideApplication`, `IncreaseFontSize`,
`MoveTab`, `MoveTabRelative`, `Multiple`, `Nop`, `OpenLinkAtMouseCursor`,
`Paste`, `PasteFrom`, `PastePrimarySelection`, `PopKeyTable`,
`QuickSelect`, `QuickSelectArgs`, `QuitApplication`, `ReloadConfiguration`,
`ResetFontAndWindowSize`, `ResetFontSize`, `ScrollByLine`,
`ScrollByPage`, `ScrollToBottom`, `ScrollToPrompt`, `ScrollToTop`,
`Search`, `SelectTextAtMouseCursor`, `SendKey`, `SendString`, `Show`,
`ShowDebugOverlay`, `ShowLauncher`, `ShowLauncherArgs`, `ShowTabNavigator`,
`SpawnCommandInNewTab`, `SpawnCommandInNewWindow`, `SpawnTab`, `SpawnWindow`,
`SplitHorizontal`, `SplitVertical`, `StartWindowDrag`, `SwitchToWorkspace`,
`SwitchWorkspaceRelative`, `ToggleFullScreen`, `TogglePaneZoomState`
unknown variant `CopyMode`, expected one of `SpawnTab`, `SpawnWindow`,
`ToggleFullScreen`, `Copy`, `CopyTo`, `Paste`, `PastePrimarySelection`,
`PasteFrom`, `ActivateTabRelative`, `ActivateTabRelativeNoWrap`,
`IncreaseFontSize`, `DecreaseFontSize`, `ResetFontSize`,
`ResetFontAndWindowSize`, `ActivateTab`, `ActivateLastTab`, `SendString`,
`SendKey`, `Nop`, `DisableDefaultAssignment`, `Hide`, `Show`,
`CloseCurrentTab`, `ReloadConfiguration`, `MoveTabRelative`, `MoveTab`,
`ScrollByPage`, `ScrollByLine`, `ScrollToPrompt`, `ScrollToTop`,
`ScrollToBottom`, `ShowTabNavigator`, `ShowDebugOverlay`, `HideApplication`,
`QuitApplication`, `SpawnCommandInNewTab`, `SpawnCommandInNewWindow`,
`SplitHorizontal`, `SplitVertical`, `ShowLauncher`, `ShowLauncherArgs`,
`ClearScrollback`, `Search`, `ActivateCopyMode`, `SelectTextAtMouseCursor`,
`ExtendSelectionToMouseCursor`, `OpenLinkAtMouseCursor`, `CompleteSelection`,
`CompleteSelectionOrOpenLinkAtMouseCursor`, `StartWindowDrag`,
`AdjustPaneSize`, `ActivatePaneDirection`, `ActivatePaneByIndex`,
`TogglePaneZoomState`, `CloseCurrentPane`, `EmitEvent`, `QuickSelect`,
`QuickSelectArgs`, `Multiple`, `SwitchToWorkspace`, `SwitchWorkspaceRelative`,
`ActivateKeyTable`, `PopKeyTable`, `ClearKeyTableStack`

### Configuration

none

**Comment by wez** [comment] 2022-06-19 05:36
In the nightly, `enable_wayland=true` is now the default. Because Wayland doesn't mandate server-side-decorations, and your Wayland compositor doesn't implement them, and because wezterm is not a GTK application, you're seeing basic client-side-decorations.

You can either set `enable_wayland=false` to have XWayland draw them in and go back to the X11-style behaviors, adjust [window_decorations](https://wezfurlong.org/wezterm/config/lua/config/window_decorations.html) to remove the titlebar, or just live with it.

**Comment by ittayd** [comment] 2022-06-19 09:44
What are the other side effects of `enable_wayland=false` ? Note that I'm not asking about aesthetics, but the fact I can't maximize the window now.

**Comment by wez** [comment] 2022-06-19 13:23
In theory, `enable_wayland=true` should take better advantage of the wayland environment and have improved latency and better integration with the compositor than it would otherwise.
`enable_wayland=false` ignores wayland and uses XWayland instead.

Personally, I think XWayland generally works a bit better, but the wayland users of wezterm generally want to use native wayland end to end.  There are sometimes some quirks, for instance, this issue with copy and paste:
* https://github.com/wez/wezterm/issues/2110

Again, personally: I think Wayland isn't quite on the same level as X11 yet and I run X11 for my desktop environment here as it has fewer headaches overall.

Please open a separate issue for the maximize problem you mentioned!

**Comment by ittayd** [comment] 2022-06-19 13:47
This issue is primarily for that: 
"In particular, clicking the up carret for full screen mode expands the window right and down, but doesn't make it snap to the upper left corner of the screen"

**Comment by ittayd** [comment] 2022-06-19 13:47
BTW, amazing work on this terminal!

**Comment by wez** [comment] 2022-07-09 17:44
I can't reproduce this on mutter, weston or wayfire. Is it still an issue for you?

**Comment by ittayd** [comment] 2022-07-10 02:25
I moved back to x11, so can't test this now.

**Comment by wez** [comment] 2022-07-10 03:10
Let's close it; can re-open if/when you get a chance to try it and it is still an issue.

**Closed by wez** 2022-07-10 03:10 UTC
Labels: bug, Wayland
