### ISSUE TITLE
Strange rendering issues

### ISSUE THREAD

**Issue by BIKA-C** [wez/wezterm#3452] opened 2023-04-06 03:18 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230326-111934-3666303c

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When rendering the checkmark symbol: ✔ with green foreground colour, it displays the checkmark, but without the colour:

## Wezterm output
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/50717946/230262371-6e24c960-4ad2-41ce-9220-f5afc472ad9d.png">

### Terminal.app output
<img width="978" alt="image" src="https://user-images.githubusercontent.com/50717946/230262437-0463843c-2f2e-4f46-aeca-f58703e12f77.png">

However, what's interesting is that it restores the correct behaviour if do this:
```shell
 print -P "\033[1;31m✘\n" 
```
OR
```shell
print -P "\033[1;31m✘\033[0m"
```

And `✘` here is important, only this symbol can restore the correct behaviour. I tried regular letters, some other symbols and they don't work.

The restored from WezTerm:

<img width="529" alt="image" src="https://user-images.githubusercontent.com/50717946/230263513-8bbf737b-bbd2-4782-8437-7cd72d29b9dd.png">

### Configuration

```
local wez = require("wezterm")

return {
    colors = {
        background = '#282c34',
    },
    color_scheme = 'BlulocoDark',
    font = wez.font 'FiraCode Nerd Font',
    font_size = 22,
    freetype_load_target = "Light",
    window_background_opacity = 0.77,
    window_decorations = "RESIZE | MACOS_FORCE_DISABLE_SHADOW",
    front_end = "WebGpu",
    macos_window_background_blur = 100000,
    enable_tab_bar = true,
    cursor_blink_rate = 570,
    animation_fps = 60,
    cursor_blink_ease_in = "EaseIn",
    cursor_blink_ease_out = "Linear",
    skip_close_confirmation_for_processes_named = {
        'bash',
        'sh',
        'zsh',
    },
    window_padding = {
        left = 30,
        right = 30,
        top = 50,
        bottom = 30,
    },
    initial_cols = 150,
    initial_rows = 45,
    window_close_confirmation = 'NeverPrompt',
    native_macos_fullscreen_mode = true,
    hide_tab_bar_if_only_one_tab = true,
    cursor_thickness = "0.066cell"

}

```

### Expected Behavior

The checkmark symbol's foreground colour should be respected.

**Comment by BIKA-C** [comment] 2023-04-06 04:47
Also, maybe the `bold_brightens_ansi_colors = true` option should be enforced even if the foreground is the default? It really helps as shown on the screenshots above where the Terminal.app highlighted the bolded part but WezTerm did not. I have it turned on, but the bolded parts are not using the bright version because it is using the default.

I am still learning rust, not so sure where to start in this project. Here is the relevant code I found:
https://github.com/wez/wezterm/blob/45db43aa95f837c680da8dbe08f8f8a27b5cc680/wezterm-gui/src/termwindow/render/mod.rs#L884

Or I guess we add something in the previous match?

**Comment by wez** [comment] 2023-04-06 04:51
Duplicate of:
* https://github.com/wez/wezterm/issues/3043

**Closed by wez** 2023-04-06 04:51 UTC
Labels: bug

**Comment by wez** [comment] 2023-04-06 04:53
re: bold, see also: https://github.com/wez/wezterm/issues/3415
and please avoid bundling multiple different issues together, as it makes it difficult to track overall status!

**Comment by BIKA-C** [comment] 2023-04-06 04:55
Ah, thanks for the quick reply! Sorry for adding different issues to the same post. Didn't search hard enough before posting. I will track them instead.
