### ISSUE TITLE
Persistent unix domain connection requires window_close_confirmation be prompted

### ISSUE THREAD

**Issue by junkblocker** [wez/wezterm#1224] opened 2021-10-12 22:54 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

wezterm 20211009-173426-8c613d85

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

If I have

```
window_close_confirmation = "NeverPrompt",
skip_close_confirmation_for_processes_named = {
    "bash",
    "sh",
    "zsh",
    "fish",
    "tmux"
},
...
unix_domains = {
    {
        name = "unix",
        connect_automatically = true
    }

```

and I close the wezterm gui window using the window manager's close button, I seem to lose the session. If I unset `window_close_confirmation` so that it prompts before closing the window no matter which way I close it, the domain recovers just fine.

Seen on Fedora 34/KDE

### To Reproduce

As described in the bug.

### Configuration

As described in the bug.

### Expected Behavior

No matter how I closed the window with NeverPrompt or without, the domain/session should get recovered on next wezterm app launch.

### Logs

Nothing useful as the session gets closed.

**Comment by wez** [comment] 2021-12-19 06:00
I think this might be a duplicate of #848 

However, there is another issue around this area, in that `skip_close_confirmation_for_processes_named` and the newer https://wezfurlong.org/wezterm/config/lua/mux-events/mux-is-process-stateful.html only apply to local panes.  When using a multiplexer client the panes are not local.

I think the appropriate resolution for this is to send an RPC to the remote mux server, however, care needs to be taken because `Pane::can_close_without_prompting` is not async and the RPC can potentially take > 100ms if the network latency isn't good.

Both this and #848 need to be considered together.

**Comment by wez** [comment] 2021-12-23 20:20
With the recent change around window closing, I think this is effectively fixed, so I'm closing this out.

**Closed by wez** 2021-12-23 20:20 UTC
Labels: bug, fixed-in-nightly
