### ISSUE TITLE
osc52 broken for panes spawned in the gui via the mux (`wezterm cli spawn`, `wezterm cli split-pane`)

### ISSUE THREAD

**Issue by pescobar** [wez/wezterm#1790] opened 2022-03-29 08:48 UTC
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20220328-224732-f478672f

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

osc52 doesn't work when starting a tmux session with mouse mode enabled. Whatever I select with my mouse inside the tmux session (yellow color) is not copied to the clipboard. Sometimes it works for a while until it stops working. Restarting wezterm workarounds the problem for a while

I am using `tmux 3.0a` on `Linux Mint 20.3 based on Ubuntu 20.04` with this [tmux.conf](https://gist.github.com/pescobar/005a55d7e350114702f3d4cb3395ee71)

### To Reproduce

Open tmux, enable mouse mode, select something. Selection should be copied to clipboard but it doesn't. Sometimes it works for a while until it stops working. 

### Configuration

no config

### Expected Behavior

osc52 selection is copied to clipboard

### Logs

pablo@esplinter:~/tmp$ ./WezTerm-nightly-Ubuntu18.04.AppImage 
 2022-03-29T08:39:29.324Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-2471306
 2022-03-29T08:39:29.516Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) Iris(R) Pro Graphics 6200 (BDW GT3) 4.6 (Compatibility Profile) Mesa 21.2.6 is_context_loss_possible=false wezterm version: 20220328-224732-f478672f
 2022-03-29T08:39:32.362Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-29T08:39:39.525Z ERROR wezterm_mux_server_impl::local > decoding a PDU: reading PDU length: EOF while reading leb128 encoded value
 2022-03-29T08:39:41.049Z ERROR wezterm_term::terminalstate::performer > failed to set clipboard in response to OSC 52: Closed(..)
 2022-03-29T08:39:47.201Z ERROR wezterm_term::terminalstate::performer > failed to set clipboard in response to OSC 52: Closed(..)
 2022-03-29T08:39:51.792Z ERROR wezterm_term::terminalstate::performer > failed to set clipboard in response to OSC 52: Closed(..)
 2022-03-29T08:39:56.968Z ERROR wezterm_term::terminalstate::performer > failed to set clipboard in response to OSC 52: Closed(..)
 2022-03-29T08:39:59.202Z WARN  wezterm_term::terminalstate            > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))

**Comment by wez** [comment] 2022-03-29 14:58
Can you simplify the reproduction steps so that recreating your tmux installation is not required? Take a look at https://github.com/wez/wezterm/issues/1662 which is a similar sounding issue

**Comment by wez** [comment] 2022-03-29 15:11
From the error message in your logs, it looks like the wezterm's multiplexer is involved, but your report says that no configuration was in use.

**Comment by pescobar** [comment] 2022-03-30 09:44
I did some tests with and without a config file and I guess I copied the wrong log but I can confirm I get the same error without config file. I attach below the log I collected without any config file:

```
~$ ~/tmp/WezTerm-nightly-Ubuntu18.04.AppImage 
 2022-03-30T09:17:11.764Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-2720278
 2022-03-30T09:17:11.995Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) Iris(R) Pro Graphics 6200 (BDW GT3) 4.6 (Compatibility Profile) Mesa 21.2.6 is_context_loss_possible=false wezterm version: 20220328-224732-f478672f
 2022-03-30T09:17:19.031Z INFO  wezterm_gui::termwindow        > Ding! (this is the bell) in pane 0
 2022-03-30T09:17:19.679Z INFO  wezterm_gui::termwindow        > Ding! (this is the bell) in pane 0
 2022-03-30T09:17:22.004Z ERROR wezterm_mux_server_impl::local > decoding a PDU: reading PDU length: EOF while reading leb128 encoded value
 2022-03-30T09:17:27.253Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-30T09:17:31.282Z ERROR wezterm_term::terminalstate::performer > failed to set clipboard in response to OSC 52: Closed(..)
 2022-03-30T09:20:44.696Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:20:44.862Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:20:48.719Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:20:48.756Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:20:49.212Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:20:50.091Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:21:43.319Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:21:44.605Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:21:45.423Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:22:46.357Z WARN  wezterm_term::terminalstate            > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-30T09:23:17.831Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 1
 2022-03-30T09:25:42.863Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 0
 2022-03-30T09:27:16.567Z INFO  wezterm_gui::termwindow                > Ding! (this is the bell) in pane 0
 2022-03-30T09:28:50.413Z ERROR wezterm_term::terminalstate::performer > failed to set clipboard in response to OSC 52: Closed(..)
```

I tried to reproduce the error with this bash oneliner but I cannot. I only get the error when working for a while inside tmux. 
```
$> for i in $(seq -w 001 999);do printf "\033]52;c;$(printf "%s" "$i" | base64)\a"; sleep 0.1; clipboard=$(xsel -b -o); if [ "$clipboard" = "$i" ]; then echo "OK" $clipboard $i; else echo "ERROR" $clipboard $i && break; fi; done
```

This bug is complex to debug because I couldn't identify a straight forward way to reproduce it. It just happens after using tmux for a while. 

I haven't done any recent change in my tmux versions, my desktop coomputer or my tmux config. The only change I did was to upgrade wezterm and if I downgrade wezterm I don't hit the problem.

**Comment by wez** [comment] 2022-03-30 13:17
Please update wezterm to the latest nightly so that https://github.com/wez/wezterm/commit/1a71a0b21616467509a762425a522d822c23f7e7 is included and that has a chance to potentially reveal more about what is happening.

What is puzzling me is that that error should only be possible if you are using wezterm's multiplexer, but from what you've mentioned so far, it doesn't sound like you are.  Can you share more about the situations in which this issue occurs?

**Comment by pescobar** [comment] 2022-03-31 10:21
By wezterm's multiplexer you mean the functionality to do vertical split or horizontal split with wezterm, right? If that's the case I can confirm I never use this functionality. In wezterm I only use tabs.

My workflow is to open wezterm tab in my desktop, connect to a remote server and launch tmux in the remote server. Inside this tmux session running in the remote server I have multiple tmux tabs. After I work for a while inside this tmux and I move around in the tmux tabs the osc52 support in wezterm stops working. Please let me know if you need more details.

I attach the latest log I collected with the latest nightly ( I have removed the log entries like `Ding! (this is the bell) in pane X`). This time it took a while until the osc52 stopped working.

```
$ ~/tmp/WezTerm-nightly-Ubuntu18.04.AppImage
 2022-03-30T13:29:57.406Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-2758021
 2022-03-30T13:29:57.607Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) Iris(R) Pro Graphics 6200 (BDW GT3) 4.6 (Compatibility Profile) Mesa 21.2.6 is_context_loss_possible=false wezterm version: 20220329-092419-6015957c
 2022-03-30T13:32:45.936Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-30T13:37:18.899Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
 2022-03-30T14:56:24.527Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-30T14:59:35.781Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-31T07:06:59.524Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
 2022-03-31T07:07:04.535Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
 2022-03-31T07:19:02.934Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-31T07:30:48.256Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-31T09:17:22.486Z ERROR wezterm_mux_server_impl::local > decoding a PDU: reading PDU length: EOF while reading leb128 encoded value
 2022-03-31T09:23:44.572Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
 2022-03-31T09:23:46.521Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
 2022-03-31T10:06:18.485Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-31T10:06:19.821Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-31T10:06:33.861Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-31T10:11:22.039Z ERROR wezterm_term::terminalstate::performer > failed to set clipboard in response to OSC 52: Error {
    context: "RemoteClipboard::set_contents send failed",
    source: "Closed(..)",
}
 2022-03-31T10:11:28.715Z ERROR wezterm_term::terminalstate::performer > failed to set clipboard in response to OSC 52: Error {
    context: "RemoteClipboard::set_contents send failed",
    source: "Closed(..)",
}
 2022-03-31T10:11:38.144Z WARN  wezterm_term::terminalstate            > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-31T10:11:41.627Z WARN  wezterm_term::terminalstate            > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-31T10:11:44.551Z WARN  wezterm_term::terminalstate            > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
 2022-03-31T10:11:49.076Z WARN  wezterm_term::terminalstate::performer > unknown unspecified CSI: "3;J"
 2022-03-31T10:11:57.386Z WARN  wezterm_term::terminalstate::performer > unknown unspecified CSI: "3;J"
 2022-03-31T10:12:02.229Z WARN  wezterm_term::terminalstate            > unhandled DecPrivateMode ResetDecPrivateMode(Unspecified(1005))
```

**Comment by wez** [comment] 2022-03-31 13:39
Are you sure that you're not running something that uses `wezterm cli spawn`, `wezterm cli split-pane` or something else that runs the wezterm appimage a second time?

The `wezterm_mux_server_impl::local` log line from your output is from the multiplexer server running inside that process and is something it logs when the client disconnects, so something must be talking to it!

**Comment by wez** [comment] 2022-03-31 13:42
OK, I can reproduce this with the following steps:

* Start wezterm
* In that the initial tab run `wezterm cli spawn` to create a new tab
* OSC 52 won't work in that tab and produces that RemoteClipboard error message

**Comment by pescobar** [comment] 2022-03-31 13:47
I confirm I can also reproduce it with nightly build `20220329-092419-6015957c`

**Comment by wez** [comment] 2022-03-31 16:57
I believe this to be fixed now in `main`. It should show up in nightly builds for Linux within about 30 minutes of this comment.

**Comment by bew** [comment] 2022-03-31 19:37
I love your commit messages @wez, very professional, it's very inspiring 👌
🙃

**Comment by pescobar** [comment] 2022-04-01 08:07
I have installed the deb package for latest nightly `20220331-200643-27d7666a` and I am going to use for my daily work. I will report back in some days.

**Closed** 2022-04-05 03:54 UTC
Labels: bug, fixed-in-nightly, multiplexer

**Comment by pescobar** [comment] 2022-04-05 07:56
I have used the nightly for some days and I haven't hit this problem again. Thanks for the fix
