### ISSUE TITLE
Wrapped lines are copied with linebreaks added when using tmux

### ISSUE THREAD

**Issue by rmoff** [wez/wezterm#5016] opened 2024-02-15 10:30 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

n/a

### WezTerm version

20240212-074107-22f9f8d2

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When there is a long line of output that gets wrapped, if I select this and copy it to my clipboard the clipboard contains linebreak characters matching the wrap - even though there are no linebreaks in the source text that was copied.

**This only happens with tmux**. If I'm not using tmux then the text is copied correctly.

### To Reproduce

1. Without tmux, run `printf "%0.sa" {1..255}  && printf "\na" >> file.txt && printf "%0.sb" {1..255}`
2. Resize the window horizontally so that the text is wrapped
3. Copy the text and paste to something like VS Code
4. Note that a single line is (correctly) shown in VS Code

5. Run tmux
6. Do the same as above, and note that the lines now have hard linebreaks where the wezterm window forced a wrap

### Configuration

```
❯ cat ~/.wezterm.lua
-- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
  config = wezterm.config_builder()
end

-- This is where you actually apply your config choices

-- For example, changing the color scheme:
config.color_scheme = '3024 (dark) (terminal.sexy)'

config.hide_tab_bar_if_only_one_tab = true

config.quit_when_all_windows_are_closed = false

config.font =
  wezterm.font('JetBrains Mono', { weight = 'Bold' })

config.font_size=15

local act = wezterm.action

config.keys = {
 { key = '3', mods = 'OPT', action = wezterm.action.SendString '#' },
  -- Rebind OPT-Left, OPT-Right as ALT-b, ALT-f respectively to match Terminal.app behavior
  {
    key = 'LeftArrow',
    mods = 'OPT',
    action = act.SendKey {
      key = 'b',
      mods = 'ALT',
    },
  },
  {
    key = 'RightArrow',
    mods = 'OPT',
    action = act.SendKey { key = 'f', mods = 'ALT' },
  },
}


config.default_cursor_style = 'BlinkingBlock'
config.cursor_blink_rate = 500
--config.default_cursor_style = 'SteadyBlock'
-- config.default_cursor_style = 'BlinkingUnderline'

-- and finally, return the configuration to wezterm
return config
```

### Expected Behavior

There should be no linebreaks in the text unless they existed in the original terminal output.

This is the behaviour of iTerm2, and is the only thing stopping me fully embracing wezterm as the rest of it is wonderful :D

### Logs

Nothing is shown except this:

![CleanShot 2024-02-15 at 10 27 19](https://github.com/wez/wezterm/assets/3671582/63b243d5-360a-42d6-80d1-49bf44fb9191)

### Anything else?

![CleanShot 2024-02-15 at 10 30 50](https://github.com/wez/wezterm/assets/3671582/9c9e4f1a-50c7-4dcb-951f-a4048472a3c3)

**Comment by bew** [comment] 2024-02-15 11:30
Duplicate of other existing issues, see: #4706

**Comment by rmoff** [comment] 2024-02-15 11:36
d'oh… I thought I'd searched well too ;)

It looks like that other issue wasn't resolved though. If iTerm2 can do it, coudln't wezterm too?

**Comment by bew** [comment] 2024-02-15 14:22
Are you using tmux inside iterm2? Or the tmux mode of iterm2 ? (which is very different in how the terminal sees lines)

**Comment by rmoff** [comment] 2024-02-15 14:49
tmux inside iTerm2. Hopefully [this screencast](https://share.cleanshot.com/W0RMRkLj) helps.

**Comment by wez** [comment] 2024-02-15 15:59
Duplicate of #4706 with the same resolution; I'm sorry that you don't like that answer, but that is the answer.

**Closed by wez** 2024-02-15 15:59 UTC
Labels: bug

**Comment by rmoff** [comment] 2024-02-15 16:26
OK. Thanks anyway for a great tool :)
