### ISSUE TITLE
Consistent crash when opening new terminal window (wayland)

### ISSUE THREAD

**Issue by cmvanb** [wez/wezterm#5311] opened 2024-04-17 13:18 UTC
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

river

### WezTerm version

20240203.110809.5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I have a binding to spawn a new terminal in the CWD:
```
        {
            key = 't',
            mods = 'CTRL',
            action = wezterm.action.SpawnWindow,
        },
``` 

This binding consistently crashes wezterm with the following error:

```
Wezterm Error
running message loop: error during event_q.dispatch protocol_error=Some(ProtocolError { code: 2, object_id: 80, object_interface: "wl_surface", message: "" }): Protocol error (os error 71)
```

WezTerm also crashes when spawning a new terminal with an external (compositor) key binding. In this case though, it spawns one additional terminal successfully before crashing. The error is the same.

### Configuration

```
        {
            key = 't',
            mods = 'CTRL',
            action = wezterm.action.SpawnWindow,
        },
``` 

### Logs

15:03:05.513  WARN   wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 52, cols: 226 }) because window_state is MAXIMIZED
15:03:05.786  ERROR  wezterm_mux_server_impl::local  > writing pdu data buffer: Broken pipe (os error 32)
15:03:05.794  WARN   wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 52, cols: 146 }) because window_state is MAXIMIZED
15:03:27.510  ERROR  wezterm_mux_server_impl::local  > writing pdu data buffer: Broken pipe (os error 32)
15:07:19.029  ERROR  wezterm_mux_server_impl::local  > writing pdu data buffer: Broken pipe (os error 32)
15:07:19.038  WARN   wezterm_gui::termwindow::resize > cannot resize window to match Some(RowsAndCols { rows: 52, cols: 226 }) because window_state is MAXIMIZED
15:11:44.819  ERROR  wezterm_mux_server_impl::local  > writing pdu data buffer: Broken pipe (os error 32)

**Comment by jamespharaoh** [comment] 2024-04-18 14:34
I am also getting protocol error 2 when spawning a new window. I am launching with a gnome shell global shortcut. It happens every time if a wezterm window has the focus, but does not happen if a different application's window has focus.

I see the error pop up as a gnome shell notification with title "Wezterm Error" and body "running message loop: Protocol error 2 on object wl_surface@27:". The number is not the same each time. Here's a screenshot:

![Screenshot from 2024-04-18 16-29-53](https://github.com/wez/wezterm/assets/230005/0372f0fb-1a35-4153-8ffd-1e6318d9d250)

This looks like the same issue to me, but perhaps someone else can verify this, or otherwise.

**Comment by woojiq** [comment] 2024-04-19 20:29
Duplicate of https://github.com/wez/wezterm/issues/5103

**Comment by wez** [comment] 2024-05-05 14:07
Duplicate of #5103

**Closed by wez** 2024-05-05 14:07 UTC
Labels: bug
