### ISSUE TITLE
Would love to be able to rename a tab/title.

### ISSUE THREAD

**Issue by jjaimealeman** [wez/wezterm#2674] opened 2022-10-28 19:41 UTC
**Describe the solution you'd like**
I've just learned of `wezterm` from a reddit post and am really liking it! I spent the morning setting up my favorite colors and stuff. **WELL DONE!!!** 👍

How do I rename the tab/titles?

I've come from using `kitty` and one of my favorite features was the ability to rename a tab.

I would love to have this.

Perhaps I overlooked it in the docs? I sure hope not!

**Comment by jtws** [comment] 2022-10-28 23:01
There's a couple of issues open about this. This feature is doable with Lua and shell scripting. People have different techniques but it boils down to modifying an userdata variable from shell via escape codes or wezterm CLI(?). I use a function echoing the escape code to set the variable I look for in Lua.

Note that I think you need nightly to implement this, stable doesn't have the needed APIs. More than half of documented methods are missing from stable when it comes to MuxWindow, MuxTab, Pane/MuxPane.

<details>
  <summary>My tab bar Lua setup which implements persistent tab names.</summary>

This was never meant to be posted and can contain wrong information in comments. Mostly my own ramblings.


```lua
local M = {}

local debug = false
local wezterm = require("wezterm")
local colors = require("colors")

local palette = colors.palette

-- Titles have to be tracked in shared memory, otherwise odd things happen,
-- e.g., when activating tab with user title all tabs show it, and when user
-- title is not set on active tab, it is not shown for inactive tabs.
wezterm.GLOBAL.tab_titles = wezterm.GLOBAL.tab_titles or {}

local tab_color = {
	inactive = { bg = palette.bg_dark4, fg = palette.fg, edge = palette.yellow },
	active = {
		bg = palette.yellow,
		fg = palette.bg_dark0,
		edge = palette.yellow,
	},
	hover = {
		bg = palette.yellow_bright,
		fg = palette.fg_dark0,
		edge = palette.yellow_bright,
	},
	copy_mode = {
		bg = palette.blue,
		fg = palette.bg_dark0,
		edge = palette.blue,
	},
}

local icon = {
	arrow = utf8.char(0xe0b1), -- 
	arrow_solid = utf8.char(0xe0b0), -- 
}

local tab_idx_list = {
	"¹",
	"²",
	"³",
	"⁴",
	"⁵",
	"⁶",
	"⁷",
	"⁸",
	"⁹",
	"¹⁰",
	"¹¹",
	"¹²",
	"¹³",
	"¹⁴",
	"¹⁵",
	"¹⁶",
	"¹⁷",
	"¹⁸",
	"¹⁹",
	"²⁰",
}

-- Equivalent to POSIX basename(3). Supports Windows and Mac/Linux paths.
-- From docs.
-- @tparam string s Filesystem path.
-- @treturns string Right most element in path.
local function basename(s)
	return string.gsub(s, "(.*[/\\])(.*)", "%2")
end

-- Return index of active tab.
-- @param tabs list of TabInformation tables.
-- @treturns int active tab index.
local function get_active_tab_idx(tabs)
	for _, tab in ipairs(tabs) do
		if tab.is_active then
			return tab.tab_index
		end
	end
end

-- Look for tab_name userdata var in all panes in this tab and use the first
-- one found. If not found, use process name instead. If this is an inactive tab
-- use existing value from GLOBAL if present, otherwise format a new title and
-- store in GLOBAL. If no userdata found, use process name as title.
-- @param tab TabInformation  This tab.
-- @param max_width int  The maximum number of cells available to draw this
--                       tab when using the retro tab bar style.
-- @treturn string  Key in wezterm.GLOBAL holding this tab's title without edges.
--         nil  if error.
local function set_title(tab, max_width)
	local title = nil
	local tab_idx = tab.tab_index + 1
	local tab_idx_str = tab_idx_list[tab_idx]
	if not tab_idx_str then
		wezterm.log_error(
			"tab index " .. tab_idx .. "outside of title index range (0-19)"
		)
		tab_idx_str = ""
	end

	-- Key for this tab in GLOBAL, we use individual vars instead of a table
	-- because GLOBAL isn't a real table, you can't assign a table to it and
	-- then insert to that table. Instead you have to copy, modify the copy, and
	-- replace the GLOBAL.var with the copy, risking probably overwriting other
	-- tabs' event handlers.
	local global_key = "tab_" .. tostring(tab_idx) .. "_title"

	-- Handle inactive tab. No point in checking user vars here.
	if not tab.is_active then
		if
			type(wezterm.GLOBAL[global_key]) == "string"
			and #wezterm.GLOBAL[global_key] > 0
		then
			title = wezterm.GLOBAL[global_key]
		end
	else
		-- An active tab, take first user var from our panes.
		local mw = wezterm.mux.get_window(tab.window_id)
		if not mw then
			wezterm.log_error(
				"failed to get MuxWindow with window id "
					.. tostring(tab.window_id)
			)
		else
			for _, mp in pairs(mw:tabs_with_info()[tab_idx].tab:panes()) do
				local uv = mp:get_user_vars()

				if type(uv.tab_title) == "string" and #uv.tab_title > 0 then
					title = uv.tab_title
					title = wezterm.truncate_right(
						" " .. tab_idx_str .. title .. " ",
						max_width
					)
					break
				end
			end
		end
	end

	-- No user vars in our tabs, use process name of active pane.
	if not title then
		local proc_name = basename(tab.active_pane.foreground_process_name)
		title = wezterm.truncate_right(
			" " .. tab_idx_str .. proc_name .. " ",
			max_width
		)
	end

	if not title then
		wezterm.log_error("unable to set tab[" .. tab_idx .. "] title")
		return nil
	end

	wezterm.GLOBAL[global_key] = title

	return global_key
end

-- Main handler.
wezterm.on(
	"format-tab-title",
	-- @param tab  TabInformation for this tab.
	-- @param tabs  List of TabInformation for all tabs.
	-- @param panes  list of PaneInformation for ACTIVE tab. Documentation is
	-- wrong, claims these are all panes for THIS tab (uses word active to refer
	-- to this several times). In an INACTIVE tab this lists the ACTIVE tab's
	-- panes. To access inactive tab panes you need MuxTab which you can get via
	-- `MuxWindow` and its `panes()` but in stable it returns `MuxPane` which
	-- doesn't have almost any of the documented methods and fields.
	--
	-- So in stable there's no way to get panes in an inactive tab AFAIK. Only
	-- nightly seems to have access to the documented methods.
	-- 
	-- MuxWindow can be gotten with wezterm.mux.get_window(tab.window_id)

	-- each pane has get_user_vars().
	-- @param config  Config table for this window.
	-- @param hover  bool  True if the current tab is in the hover state.
	-- @param max_width int  The maximum number of cells available to draw this
	--                       tab when using the retro tab bar style.
	-- @returns  List of wezterm.format objects describing this tab's appearance.
	function(tab, tabs, panes, config, hover, max_width)
		-- Inactive tab colors and icons.
		local bg = tab_color.inactive.bg
		local fg = tab_color.inactive.fg
		local right_edge_fg = tab_color.inactive.edge
		local right_edge_bg = bg
		local left_edge_bg = bg
		local left_edge_fg = bg
		local right_edge = icon.arrow
		local left_edge = ""

		-- We're next to an active tab, remove right edge arrow leaving space.
		local active_tab_idx = get_active_tab_idx(tabs)
		if tab.tab_index + 1 == active_tab_idx then
			right_edge = ""
			right_edge_fg = bg
		end

		-- Active and hover colors and icons and rest of tabs.
		if tab.is_active then
			bg = tab_color.active.bg
			fg = tab_color.active.fg
			right_edge = icon.arrow_solid
			if tab.tab_index > 0 then
				left_edge = icon.arrow_solid
			end
		elseif hover then
			bg = tab_color.hover.bg
			fg = tab_color.hover.bg
			right_edge = icon.arrow_solid
			if tab.tab_index > 0 then
				left_edge = icon.arrow_solid
			end
		end

		if tab.active_pane.title:match("^Copy mode") then
			bg = tab_color.copy_mode.bg
			fg = tab_color.copy_mode.fg
			right_edge_fg = tab_color.copy_mode.edge
		end

		left_edge_bg = bg

		-- Mutates wezterm.GLOBAL[global_key]
		local global_key = set_title(tab, max_width)

		if not global_key then
			return nil
		end

		local title = wezterm.GLOBAL[global_key]
		if type(title) ~= "string" then
			wezterm.log_error(
				"tab[" .. tab.tab_index + 1 .. "] title is a " .. type(title)
			)
			return nil
		elseif #title == 0 then
			wezterm.log_error(
				"tab[" .. tab.tab_index + 1 .. "] title length is 0"
			)
			return nil
		end

		return {
			{ Background = { Color = left_edge_bg } },
			{ Foreground = { Color = left_edge_fg } },
			{ Text = left_edge },
			{ Background = { Color = bg } },
			{ Foreground = { Color = fg } },
			{ Text = title },
			{ Background = { Color = right_edge_bg } },
			{ Foreground = { Color = right_edge_fg } },
			{ Text = right_edge },
		}
	end
)
return M
```
</details>

<details>
  <summary>Shell func for setting the title</summary>

```zsh
function wezterm_title() {
  # Set wezterm tab and window title (for current tab)
  # @param 1  tab title string (preferably singly quoted or single word)
  local title title_b64

  if [[ $# == 0 ]]; then
    title_b64=""
  else
    title="$@"
    title_b64=$(echo -n "${title}" | base64)
  fi
  # OCI 1337 str \007 ITerm escape seq implemented in wezterm which allows all
  # kinds of behaviour from reading files to invoking certain methods, like
  # SetUserVar.
  echo "\x1b]1337;SetUserVar=tab_title=${title_b64}\007"
}
```
</details>

I've been using this for a month or two and seems to work.

**Comment by jjaimealeman** [comment] 2022-10-28 23:07
Thanks for commenting amigo!

So I'm totally new to wezterm and kinda familiar with lua & neovim.

I'm guessing the top code block would be saved in `.wezterm.lua` and the bottom is a shell script? Or where would that be saved? 🤔

**Comment by jtws** [comment] 2022-10-28 23:58
It's just `require`d in the main config to define the event handler, nothing in the file is called directly from main config. This is my `wezterm.lua`, `tabbar` module is the one I posted.

<details>
<summary>wezterm.lua</summary>

```lua
local keys = require("keys")
local fonts = require("fonts")
local colors = require("colors")
local tabbar = require("tabbar")

return {
	debug_key_events = false,
	check_for_updates = false,

	disable_default_key_bindings = true,
	--leader = keys.leader,
	keys = keys.keys,
	key_tables = keys.key_tables,

	font = fonts.with_fallback,
	warn_about_missing_glyphs = false,
	--allow_square_glyphs_to_overflow_width = "Always",

	force_reverse_video_cursor = true,

	scrollback_lines = 10000,

	enable_tab_bar = true,
	use_fancy_tab_bar = false,
	hide_tab_bar_if_only_one_tab = false,
	tab_bar_at_bottom = true,
	switch_to_last_active_tab_when_closing_tab = true,
	--tab_bar_style = tabbar.tab_bar_style,

	window_frame = tabbar.window_frame,
	window_padding = {
		left = 0,
		right = 0,
		top = 0,
		bottom = 0,
	},

	color_schemes = {
		[colors.scheme_name] = colors.scheme,
	},
	color_scheme = colors.scheme_name,

	-- Use wezterm terminfo on localhost, ssh aliased to
	-- `env TERM=xterm-256color ssh` for compatibility.
	term = "wezterm",
}
```
</details>

The shell func is in my `.zshrc` with a `alias wt=wezterm_title` for convenience. It just sets the uservar in the active pane, and the Lua config checks all panes for the userdata var and uses first one it finds. I don't need per-pane tab titles. Calling `wt ""` sets the uservar to an empty string which disables the tab tittle, resuming to showing the process name.

**Comment by wez** [comment] 2022-10-29 19:57
See also: https://github.com/wez/wezterm/issues/1598

**Comment by wez** [comment] 2023-04-02 04:44
Duplicate of #1598

**Closed by wez** 2023-04-02 04:44 UTC
Labels: enhancement
