### ISSUE TITLE
Unlimited scrollback

### ISSUE THREAD

**Issue by cowens** [wez/wezterm#3879] opened 2023-06-19 16:16 UTC
**Is your feature request related to a problem? Please describe.**

Sometimes I need to scroll back more than my current scrollback_lines config allows, but I don't want to waste RAM. 

**Describe the solution you'd like**

Switch the scrollback buffer from a VeqDeque to something like [Yaque](https://docs.rs/yaque/latest/yaque/) and allow scrollback_lines to be set to -1 for unlimited. 

**Describe alternatives you've considered**

Buying more RAM

**Additional context**

iTerm2 has a similar feature.

**Comment by wez** [comment] 2023-06-19 16:46
Essentially a duplicate of https://github.com/wez/wezterm/issues/1342

However, there is more to this than simply storing on disk; https://github.com/microsoft/terminal/issues/1410#issuecomment-504942872 has some information on this topic, and subsequent discussion.

**Comment by wez** [comment] 2023-07-10 20:16
Closing in favor of #1342 which has more discussion

**Closed by wez** 2023-07-10 20:16 UTC
Labels: enhancement
