### ISSUE TITLE
slime like vim plugin

### ISSUE THREAD

**Issue by xiangpeng2008** [wez/wezterm#1232] opened 2021-10-16 10:43 UTC
Hi,

**Is your feature request related to a problem? Please describe.**

Currently https://github.com/jpalardy/vim-slime supports only 

- GNU Screen
- tmux
- dtach
- kitty
- X11
- whimrepl
- ConEmu
- Vim :terminal
- NeoVim :terminal

Is there any existing similar plugin for wezterm ? In other words, do wezterm supports sending text from 1 pane to another pane ?

Thanks,

**Comment by wez** [comment] 2021-10-17 15:04
I think this is the same request as https://github.com/wez/wezterm/issues/888, so I'm closing this as a duplicate of that one!

**Closed by wez** 2021-10-17 15:04 UTC
Labels: enhancement

**Comment by uncomfyhalomacro** [comment] 2022-06-17 03:54
> Hi,
> 
> **Is your feature request related to a problem? Please describe.**
> 
> Currently https://github.com/jpalardy/vim-slime supports only
> 
>     * GNU Screen
> 
>     * tmux
> 
>     * dtach
> 
>     * kitty
> 
>     * X11
> 
>     * whimrepl
> 
>     * ConEmu
> 
>     * Vim :terminal
> 
>     * NeoVim :terminal
> 
> 
> Is there any existing similar plugin for wezterm ? In other words, do wezterm supports sending text from 1 pane to another pane ?
> 
> Thanks,

See https://github.com/jpalardy/vim-slime/pull/333#issue-1274531113
