### ISSUE TITLE
Resizing doesn't complete the screen redraw in vim, clicking on the screen after resize completes the redrawing process

### ISSUE THREAD

**Issue by poetaman** [wez/wezterm#574] opened 2021-03-23 07:30 UTC
## Describe the bug

Resizing the window does not always complete screen redraw in vim, clicking on screen makes it complete drawing. Please play the mp4 video below:

https://user-images.githubusercontent.com/71736629/112109560-f9e30400-8b6e-11eb-8b5f-0145e1bfd8fa.mp4

## Environment (please complete the following information):

 - macOS 
 - wezterm 20210314-114017-04b7cedd-41-ga5f4803
 - Unicode Hex Input

## To Reproduce

1) Make WezTerm window size close to size of screen (I have a 27 inch 5k display), but don't enable full screen mode.
2) Open a file in Vim (mine is a simple wiki file with no highlights, only thing fancy is airline powerline symbols, but that doesn't matter as this happens even without them and with ``--noplugin``)
3) Create 3 splits
4) Increase and decrease size multiple times (on my Mac I use 3-finger drag) till some region is undrawn (mine happens early and often, like once every 4 redraws for the file in GIF) when I start reducing window size. Note: This effect is not seen when WezTerm is not this big.

> Sidenote: This undrawn region can appear in multiple places in window at once, and it's not necessarily at the bottom.

**Comment by reportaman** [comment] 2021-03-23 20:32
Another example (a screenshot from today) shows an important point. Check the progress of line numbers across the blank region. Whenever it happens, it happens like this: the contents are not hidden, they are just separated by spurious blank space. In the example below, the closing quote & bracket ``']`` visible right above line 54 (to the right side) is actually on line 53 (right after ``['│``).

<img width="1346" alt="Screen Shot 2021-03-23 at 1 21 38 PM" src="https://user-images.githubusercontent.com/71736629/112213357-39dfd080-8bdb-11eb-90d3-3d4e001917e9.png">

After clicking on the screen, it completes its drawing correctly (check line 53 & 54 again):

<img width="1286" alt="Screen Shot 2021-03-23 at 1 32 08 PM" src="https://user-images.githubusercontent.com/71736629/112214263-39940500-8bdc-11eb-9830-04611127fb6a.png">

**Comment by reportaman** [comment] 2021-03-23 20:41
**Update** My quote in above comment "Whenever it happens, it happens like this: the contents are not hidden, they are just separated by spurious blank space." is not true it seems. For instance check the following screenshot (some contents are hidden, others are concatenated in wrong place). The left split should look exactly the same as right split (which it does after I click on WezTerm)

<img width="1938" alt="Screen Shot 2021-03-23 at 1 36 53 PM" src="https://user-images.githubusercontent.com/71736629/112215174-4a914600-8bdd-11eb-89b7-d7ae4a7b7480.png">

**Comment by reportaman** [comment] 2021-03-28 19:22
@wez This one is not fully fixed. I encountered the same problem while working today.

**Comment by wez** [comment] 2021-04-16 16:29
Does this still happen with the latest nightly?

**Comment by reportaman** [comment] 2021-04-16 21:56
@wez No, it stopped happening at some point. Closing the issue.

**Comment by reportaman** [comment] 2021-05-26 00:11
@wez In last week+ (don't know the exact start point) this has started happening again, it happens less often but happens. And this is the only terminal emulator on my machine it happens with. Rest of the terminal emulators with same vim/nvim setup & similar editing tasks has never had this behavior. Opening again...

**Comment by maxammann** [comment] 2021-09-24 09:05
I'm having the same problem on wezterm 20210814-124438-54e29167.

I suspect that this is the same problem as already many terminal emulators had: https://bugzilla.xfce.org/show_bug.cgi?id=13521.

I experice this quite a lot when I start vim through a .desktop file which executes: "wezterm start vim file"

**Comment by omar25h** [comment] 2023-08-05 17:17
Not sure whether this is the same issue or not, but I am also experiencing this whenever opening another window  and scrolling down in Neovim. The screen is redrawn after hitting CTRL+L

https://github.com/wez/wezterm/assets/5558211/6c5646cb-1330-4470-aef6-f891627da1c6

**Comment by bew** [comment] 2023-08-06 07:50
@omar25h I suggest you to open a fresh issue (you can reference this one in description) so you can fully describe your environment, version, and reproduction steps

**Comment by Bellavene** [comment] 2023-09-13 10:21
> Not sure whether this is the same issue or not, but I am also experiencing this whenever opening another window and scrolling down in Neovim. The screen is redrawn after hitting CTRL+L
> 
>  Wezterm.neovim.redraw.mov

It started strangely in the same time for me, but I am using iTerm. I believe something must updated and this bug appeared by itself after.

**Comment by wez** [comment] 2023-09-13 16:12
I'm going to close this issue; it is old and things have changed a lot since it was opened.
If you are experiencing an issue like this, please open a new one with all relevant information (eg: don't just say "same as issue 574").

**Closed by wez** 2023-09-13 16:12 UTC
Labels: bug
