### ISSUE TITLE
Restart/shutdown macOS without Wezterm confirmation

### ISSUE THREAD

**Issue by nguyenhoanghipe** [wez/wezterm#4546] opened 2023-11-08 02:48 UTC
Hi Wez
Thank you for all the hard work you put into this awesome tool!

When I restart or shut down my Mac, a Wezterm confirmation window shows up and blocks the process.
I have tried several settings: `window_close_confirmation`, `skip_close_confirmation_for_processes_named`, and `exit_behavior`.
None of them affects this behavior.
I also tried the latest Nightly Build.

I have a shutdown schedule during night time and this behavior has been blocking the schedule.

May I request a setting to turn off this confirmation window? 
Thank you for considering my request!

<img width="260" alt="Screenshot 2023-11-08 at 13 38 23" src="https://github.com/wez/wezterm/assets/13253443/11084c37-515b-4741-aed3-a68f54ae5a2a">

**Comment by devsunb** [comment] 2023-12-05 09:24
This seems to be a duplicate of #4362 (fixed by #4420).

**Closed** 2024-01-27 16:16 UTC
Labels: enhancement
