### ISSUE TITLE
built-in "global summon" feature

### ISSUE THREAD

**Issue by daishengdong** [wez/wezterm#4679] opened 2023-12-14 03:11 UTC
In Tabby, you can set a "global summon" hotkey (such as ctrl + space), which means that no matter which window you are currently in, pressing the hotkey will immediately switch the focus back to Tabby.

It seems that Wezterm does not have this feature, and although I can replicate this functionality on Windows using third-party tools like AutoHotkey, having it as a built-in feature would be more user-friendly.

**Comment by wez** [comment] 2024-02-03 02:23
Essentially a duplicate of https://github.com/wez/wezterm/issues/1751

**Closed by wez** 2024-02-03 02:23 UTC
Labels: enhancement
