### ISSUE TITLE
No visual indication of pane switch after `ActivatePaneDirection`

### ISSUE THREAD

**Issue by rmarganti** [wez/wezterm#3323] opened 2023-03-22 13:44 UTC
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20230320-124340-559cb7b0

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

- When navigating splits via a keybind tied to `ActivatePaneDirection`, there is no visual indication that that new pane has been activated.
- Cursor does not change, `inactive_pane_hsb` is not applied, etc.
- Upon pressing any additional key, the issue immediately resolves. Any text is inserted in the expected pane.

### To Reproduce

1. Split panes via `SplitHorizontal` or `SplitVertical`.
2. Attempt to navigate panes via `ActivatePaneDirection`.

### Configuration

Keybinds:

```lua
    {
        key = '\\',
        mods = 'LEADER',
        action = action.SplitHorizontal({ domain = 'CurrentPaneDomain' }),
    },
    {
        key = '-',
        mods = 'LEADER',
        action = action.SplitVertical({ domain = 'CurrentPaneDomain' }),
    },

    -- Navigate panes.
    {
        key = 'h',
        mods = 'CTRL|SUPER',
        action = action.ActivatePaneDirection('Left'),
    },
    {
        key = 'l',
        mods = 'CTRL|SUPER',
        action = action.ActivatePaneDirection('Right'),
    },
    {
        key = 'k',
        mods = 'CTRL|SUPER',
        action = action.ActivatePaneDirection('Up'),
    },
    {
        key = 'j',
        mods = 'CTRL|SUPER',
        action = action.ActivatePaneDirection('Down'),
    },
```

### Expected Behavior

When invoking `ActivatePaneDirection`, the newly activated pane should immediately indicate that it has been selected.

**Comment by wez** [comment] 2023-03-22 14:05
Duplicate of https://github.com/wez/wezterm/issues/2879

**Closed by wez** 2023-03-22 14:05 UTC
Labels: bug
